navikt/pensjon-etterlatte-saksbehandling

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/gyldigFramsattSoeknad/GyldigFramsattVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/KommerBarnetTilGodeVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/Virkningstidspunkt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/styled.tsx

Fiks små feil i styling for soeknadsoversikt og bruk ferger fra designbibliotek

---

apps/etterlatte-beregning/build.gradle.kts
apps/etterlatte-beregning/src/main/kotlin/BeregningRepository.kt
apps/etterlatte-beregning/src/main/kotlin/model/Beregning.kt
apps/etterlatte-beregning/src/main/kotlin/model/BeregningService.kt
apps/etterlatte-beregning/src/main/resources/db/migration/V1__create_initial_tables.sql
apps/etterlatte-beregning/src/test/kotlin/BeregningRepositoryImplTest.kt

EY-1147 Opprette tester på lagre i beregning

---

README.md

Opplevde litt problemer ved lokal kjøring med ny app (Beregning), så oppdaterte readme med det som fungerte

Oppdaterte README for lokalt oppsett

---

apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/VedtakMottaker.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/oppdrag/OppdragMapper.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/Utbetaling.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingDao.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingMapper.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/Utbetalingsvedtak.kt
apps/etterlatte-utbetaling/src/main/resources/db/migration/V7__adds_sakstype_to_utbetaling.sql
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/TestHelper.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/VedtakHelper.kt
apps/etterlatte-utbetaling/src/test/resources/vedtak.json
libs/common/src/main/kotlin/vedtak/Vedtak.kt

Sakstype er nå tatt hensyn til i utbetalingsappen.

EY-1229: Utvider Utbetaling med sakstype

---

apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/GrensesnittsavstemmingService.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingService.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/avstemmingsdata/KonsistensavstemmingDataMapper.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/common/Utils.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/avstemmingsdata/KonsistensavstemmingDataMapperTest.kt

- Logikk for å oversende en konsistensavstemming til oppdrag
- Teste for konsistensavstemmingsdatamapperen

EY-1224: Sender konsistensavstemming til oppdrag

---

apps/etterlatte-utbetaling/src/main/kotlin/Application.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/GrensesnittsavstemmingJob.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingJob.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/config/ApplicationContext.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingJobTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingServiceKtTest.kt

- Jobb for å kjøre konsistensavstemming. Konsistensavstemmingen kjøres ikke per nå, siden ikke alle detaljer er på plass enda. Denne skal kommenteres inn når dette er på plass.
- Test for KonsistensavstemmingJob
- En test for start av konsistensavstemming i konsistensavstemmingservice

EY-1220: jobb for konsistensavstemming og enda en test for konsistensavstemmingservice

---

apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/AvstemmingDao.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/Grensesnittavstemming.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/GrensesnittsavstemmingJob.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/GrensesnittsavstemmingService.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingService.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/common/Oppgavetrigger.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingDao.kt
apps/etterlatte-utbetaling/src/main/resources/db/migration/V10__add_saktype_to_avstemming.sql
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/AvstemmingDaoIntegrationTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/GrensesnittavstemmingServiceTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/GrensesnittsavstemmingsJobTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/common/OppgavetriggerTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingDaoIntegrationTest.kt

- Utvider grensesnittavstemming og avstemmingDao med saktype

EY-1281: utvide grensesnittavstemming og avstemmingDao med saktype

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/OppgaveKolonner.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/handlinger/HandlingerKnapp.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/handlinger/SaksbehandlerTildelKnapp.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/header/Header.tsx

Små forbedringer. Eventuelt forslag, hvis noen har sterke meninger imot endringene. 
- Bytte til tittel "Doffen"
- Gjøre tittel om til lenke. Gjør det mulig å åpne i ny fane. 
- Gjøre knapp "Start behandling" om til lenke. Gjør det mulig å åpne i ny fane. 
- Fjerne kolonne beskrivelse siden den p.t. bare tar plass. Får legges tilbake hvis det blir aktuelt.

Gjøre header og "start behandling"-knapp om til lenker

---

apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingService.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingDao.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/TestHelper.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingServiceKtTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingDaoIntegrationTest.kt

- Tester for uthenting av utbetalinger fra dao for konsistensavstemming
- Korrigering av hentUtbetalingerForKonsistensavstemming
- Ser ut som ktlint har fikset litt opp i UtbetalingDao

EY-1339: Tester for uthenting av utbetalinger fra dao for konsistensavstemming

---

apps/etterlatte-brev-distribusjon/src/main/kotlin/AppBuilder.kt
apps/etterlatte-brev-distribusjon/src/main/kotlin/DistribuerBrev.kt
apps/etterlatte-brev-distribusjon/src/main/kotlin/journalpost/JournalpostService.kt

Endrer tema fra PEN til EYB for journalføring av utgående brev.

EY-1210 Bytt tema fra PEN til EYB

---

apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingServiceKtTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingsvedtakTest.kt

- Flere tester for konsistensavstemmingService
- Test for UtbetalingsVedtak, for å oppdage endringer i Utbetalingsvedtak-modell

Flere tester for konsistensavstemmingService og UtbetalingsVedtak

---

.github/workflows/app-etterlatte-vilkaarsvurdering.yaml
apps/etterlatte-vilkaarsvurdering/build.gradle.kts

- får avhengigheter av postgres-plugin

Forenkler gradle-oppsett vilkårsvurdering

---

apps/etterlatte-api/src/main/kotlin/behandling/VedtakKlient.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/Beregningsresultat.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/Vedtak.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/database/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
libs/common/src/main/kotlin/beregning/BeregningsResultat.kt

Om en vilkårsvurdering er underkjent, skal man ikke trenge en beregning

Ey 1377 underkjent vilkaarsvurdering

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/config/DataSourceBuilder.kt
libs/etterlatte-database/build.gradle.kts
libs/etterlatte-database/src/main/kotlin/DataSourceBuilder.kt
libs/etterlatte-database/src/main/kotlin/JdbcUtils.kt
settings.gradle.kts

- Opprette datasource
- Kjøre migrering
- Utils for å hente enkelt-resultat og liste-resultat fra resultSet

Felles-lib for database-oppsett

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutes.kt
libs/etterlatte-ktor/src/main/kotlin/RouteUtils.kt

- Legger til ny metode for å hente ut flere UUID-parametere enn bare behandlingId. Bør nok på sikt evaluere denne måten å hente parametere på da det potensielt fanger opp andre exceptions og gir feil melding i response.
- Noen andre mindre forenklinger

Forenkler routes i vilkårsvurdering

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/src/main/kotlin/BeanFactory.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagClient.kt
apps/etterlatte-behandling/src/test/kotlin/TestApp.kt
apps/etterlatte-behandling/src/test/kotlin/itest/IntegrationTest.kt
apps/etterlatte-grunnlag/.nais/dev.yaml

Ikke i bruk enda, men skal brukes for å sjekke om hendelser i PDL faktisk påvirker relevant grunnlag

Setter opp en klient for å hente grunnlag i behandling

---

apps/etterlatte-beregning/src/main/kotlin/BeregningRepository.kt
apps/etterlatte-beregning/src/main/kotlin/model/BeregningService.kt
libs/common/src/main/kotlin/beregning/BeregningsResultat.kt

Midlertidig fiks inntil vi skal behandle saker med mindre enn 40 års trygdetid.

Hardkode inn trygdetid i beregningsperiode (EY-1403)

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/VedtaksvurderingRoute.kt

Post vedtakhendelser sekvensielt ellers får man potensielt en concurrency update feil i behandling

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/filtere/DateColumnFilter.tsx

EY-1452: Legg til label for datovelgere i oppgavebenken

Fiks feil med label på inputfelter

---

libs/etterlatte-regler/build.gradle.kts
libs/etterlatte-regler/src/main/kotlin/regler/Properties.kt
libs/etterlatte-regler/src/main/kotlin/regler/Regelkjoering.kt
libs/etterlatte-regler/src/test/kotlin/regler/RegelkjoeringTest.kt

Kravet er at vi i resultatet som vi lagrer ned skal kunne spore hvilke versjon av regel-rammeverket som har blitt benyttet.
Hvis noen andre har bedre forslag til hvordan vi kan dekke dette kravet så kom gjerne med forslag!

Legger til versjon av rammeverket som har blitt benyttet for eksekvering av regler

---

apps/etterlatte-behandling/src/main/kotlin/behandling/Behandling.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/model/BeregningService.kt
apps/etterlatte-beregning/src/main/kotlin/model/behandling/BehandlingKlient.kt

Man skal ikke kunne gjøre en beregning om man er i feil state.
Gyldige state er derfor `VILKAARSVURDERING` (steget foran), og `BEREGNING` (steget den er på. Her skulle alle steg etter i redigerbar tilstand vært med, men `BEREGNING` er siste før `VEDTAK_FATTET`)

Ey 1506 tilstandsjekk beregning

---

README.md
get-secret.sh

To feil opplevd på oppsett av en ny maksin med mulig løsning

Oppdater readme - feil opplevd på ny maskin og løsning

---

libs/etterlatte-regler/build.gradle.kts
libs/etterlatte-regler/src/main/kotlin/regler/Node.kt
libs/etterlatte-regler/src/main/kotlin/regler/Regler.kt
libs/etterlatte-regler/src/test/kotlin/beregning/BeregnBarnepensjonTest.kt
libs/etterlatte-regler/src/test/kotlin/regler/FinnFaktumIGrunnlagRegelTest.kt
libs/etterlatte-regler/src/test/kotlin/regler/GangSammenRegelTest.kt
libs/etterlatte-regler/src/test/kotlin/regler/RegelkjoeringTest.kt
libs/etterlatte-regler/src/test/kotlin/regler/SlaaSammenToReglerTest.kt
libs/etterlatte-regler/src/test/kotlin/regler/SlaaSammenTreReglerTest.kt
libs/etterlatte-regler/src/test/kotlin/regler/TestHelper.kt
libs/etterlatte-regler/src/test/kotlin/regler/VelgNyesteGyldigeRegelTest.kt

- Fjerner engelske feltnavn i resultat
- Fjerner avhengighet til `common`
EY-1126

Fikser navngivning i regelresultat

---

apps/etterlatte-behandling/src/main/kotlin/BeanFactory.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/pdl/PdlService.kt
apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/pdl/PdlServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
apps/etterlatte-saksbehandling-ui/server/src/mockdata/personsok_23011255000.json
libs/common/src/main/kotlin/behandling/Grunnlagsendringshendelse.kt

Legger også på bedre logging for å avdekke en bug i håndtering av hendelser

Refaktorerer og samler funksjonalitet i GrunnlagsendringshendelseService

---

libs/etterlatte-regler/README.md

Dokumentasjon regelrammeverk

---

libs/etterlatte-regler/src/main/kotlin/regler/RegelDsl.kt
libs/etterlatte-regler/src/main/kotlin/regler/Regler.kt
libs/etterlatte-regler/src/test/kotlin/beregning/BeregnBarnepensjon.kt
libs/etterlatte-regler/src/test/kotlin/beregning/BeregnBarnepensjonTest.kt
libs/etterlatte-regler/src/test/kotlin/beregning/barnepensjon1967/BeregnBarnepensjon1967.kt
libs/etterlatte-regler/src/test/kotlin/beregning/barnepensjon1967/barnekull/Barnekull.kt
libs/etterlatte-regler/src/test/kotlin/beregning/barnepensjon1967/trygdetidsfaktor/Trygdetidsfaktor.kt
libs/etterlatte-regler/src/test/kotlin/beregning/barnepensjon2024/BeregnBarnepensjon2024.kt
libs/etterlatte-regler/src/test/kotlin/regler/SlaaSammenToReglerTest.kt
libs/etterlatte-regler/src/test/kotlin/regler/SlaaSammenTreReglerTest.kt
libs/etterlatte-regler/src/test/kotlin/regler/TransformasjonRegelTest.kt
libs/etterlatte-regler/src/test/kotlin/regler/VisitorTest.kt

Ny regel for å transformere en annen regels resultat

---

apps/etterlatte-api/src/main/kotlin/Server.kt
apps/etterlatte-api/src/main/kotlin/behandling/BehandlingRoute.kt
apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/build.gradle.kts
apps/etterlatte-behandling/src/main/kotlin/BeanFactory.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/DetaljertBehandlingDto.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BeregningKlient.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/GrunnlagKlient.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/VedtakKlient.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/VilkaarsvurderingKlient.kt
apps/etterlatte-behandling/src/main/resources/application.conf
apps/etterlatte-behandling/src/test/kotlin/TestApp.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealGenerellBehandlingServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/itest/IntegrationTest.kt
apps/etterlatte-beregning/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/server/src/index.ts
apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml

Er draft men ville bare kjøre testene i github workflow

EY-1504 Flytt behandlingskall til behandling

---

apps/etterlatte-behandling/src/main/kotlin/behandling/Behandling.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/manueltopphoer/ManueltOpphoerService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingAggregat.kt
apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealGenerellBehandlingServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealManueltOpphoerServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/itest/BehandlingDaoIntegrationTest.kt

Dette kan ikke settes for revurdering per nå, og det settes fast til å være tidligste virkningstidspunkt for manuelt opphør.

EY-1321: Alle behandlinger har et virkningstidspunkt

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutes.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt

Fjern mulighet for å slette/endre vilkår på en vilkårsvurdering som har et utfall satt.

---

.github/workflows/.build.yaml
.github/workflows/app-etterlatte-saksbehandling-ui.yaml

Ref https://nav-it.slack.com/archives/C01PG1JM9D4/p1673968217423659?thread_ts=1673967245.483729&cid=C01PG1JM9D4 og https://nav-it.slack.com/archives/C01PG1JM9D4/p1673966090991019?thread_ts=1673946121.189369&cid=C01PG1JM9D4
Alltids ei vurdering rundt det å ta inn eksterne actions som denne. Tok ein liten titt, og den ser grei ut utan så mykje ræl, og i ganske mykje bruk, men fint om fleire vurderer det.

EY-1475: Vaskar git-greinnamn før vi annoterer imaget med det

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/vilkaar/BarnepensjonVilkaar.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt

Se tråd: https://nav-it.slack.com/archives/C03DABCCR3L/p1673952702611759

Fjerner virkningstidspunkt fra grunnlaget siden vi ikke har kontroll på om virk. har endret seg.

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Resultat.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vurdering.tsx

Det skal være valgfritt å legge til en begrunnelse av utfall

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/saksliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
libs/common/src/main/kotlin/behandling/BehandlingResource.kt

https://jira.adeo.no/browse/EY-1591

EY-1591 Vis resultat for behandling i brukeroversikten

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/grunnlag/GrunnlagKlient.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt

Henger igjen fra vi postet vilkårsvurdering med grunnlag på kafka.

Fjern død kode fra vilkårsvurdering

---

apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/build.gradle.kts
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingService.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt

Henter ut enhet fra secret hvis ikke vedtaket er fattet. Denne enheten brukes kun for preview før sak sendes til attestering.

EY-1574: Hent enhet til brev før vedtak er fattet

---

apps/etterlatte-beregning/src/main/kotlin/beregning/regler/sats/BarnepensjonSats.kt

Ref https://confluence.adeo.no/display/TE/Beregning+lovtolkning+barnepensjon
EY-1609

Regel for antall søsken i søskenkullet

---

apps/etterlatte-testdata/src/main/resources/templates/dolly/dolly.hbs

For enklere å vite om det er flere søsken i familien, så er det lagt til en kolonne som viser antall søsken som barnet har.
Det gjør det lettere å vite om du sender inn en søknad som inneholder søskenjustering.

Legg til antall søsken i testdata

---

apps/etterlatte-fordeler/src/main/kotlin/fordeler/FordelerKriterier.kt
apps/etterlatte-fordeler/src/test/kotlin/fordeler/FordelerKriterierTest.kt

Se hovedforslag her https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/490

EY-1296 Filtrere bort søknader som ikke er på norsk

---

apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManueltOpphoer.kt

Det er på ingen måte krav om å ha en vilkårsvurdering på et manuelt oppør

Fikser feil status-krav for manuelt opphør

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt

Igjen litt etterslep i logikk jeg ikke fikset for vedtak i første omgang 😅

Man kan fatte manuelle opphør uten vilkårsvurdering

---

apps/etterlatte-beregning/src/main/kotlin/beregning/regler/BeregnBarnepensjon1967.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/Konstanter.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/sats/BarnepensjonSats.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRepositoryTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/TestHelper.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/regler/BeregnBarnepensjon1967Test.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/regler/sats/BarnepensjonSatsTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/regler/trygdetidsfaktor/TrygdetidsfaktorTest.kt

Må også se mer på avrunding i egen oppgave (EY-1611)
EY-1544

Tester regler for beregning av barnepensjon

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/SoeknadsVurdering.tsx

Info om trygdetid må komme frem for pilot. For piloten sin del skal vi kun behandle saker med maks opptjent (eller fremtidig opptjent) trygdetid (40 år). Tekstene må mulig revideres, men venter på tilbakemelding fra fag

EY-1426 Info om trygdetid

---

apps/etterlatte-behandling/src/main/kotlin/behandling/DetaljertBehandlingDto.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/DBTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
libs/common/src/main/kotlin/behandling/BehandlingResource.kt

Ser ingen grunn til at disse skal være nullable. I databasen er det heller ingen verdier på disse feltene som er `null`.

Fjerner nullable på behandlingType og behandlingStatus

---

.github/dependabot.yml

Tenkte eigentleg å ta denne og snyk samtidig, men trur det er greiast å ta ein av dei av gongen, og dependabot er enklare å få inn utan å knekke flyten for nokon

EY-1621: Konfigurasjon for dependabot

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/BeregnBarnepensjon1967.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/Beregningstall.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/Konstanter.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/sats/BarnepensjonSats.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/trygdetidsfaktor/Trygdetidsfaktor.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRepositoryTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/TestHelper.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/regler/BeregnBarnepensjon1967Test.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/regler/sats/BarnepensjonSatsTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/regler/trygdetidsfaktor/TrygdetidsfaktorTest.kt

- Det er besluttet at det skal brukes 16 desimaler i mellomberegninger
- Bruker en egen wrapper rundt BigDecimal for å oppnå dette
EY-1611

Bruker 16 desimaler i mellomberegninger

---

apps/etterlatte-saksbehandling-ui/client/package.json
apps/etterlatte-saksbehandling-ui/client/yarn.lock

This reverts commit 3593054caf506593246ffe419a97197365844f81.

Revert "fix: upgrade react-router from 6.4.3 to 6.6.1 (#535)"

---

apps/etterlatte-grunnlag/build.gradle.kts
apps/etterlatte-grunnlag/src/main/kotlin/Application.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagRoutes.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/OpplysningDao.kt
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/BehandlingEndretHendelseTest.kt
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagServiceTest.kt
apps/etterlatte-grunnlag/src/test/kotlin/itest/RapidTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumentoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/person.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/header/Search.tsx
apps/etterlatte-saksbehandling-ui/server/src/config/config.ts
apps/etterlatte-saksbehandling-ui/server/src/index.ts

Personsøk gikk tidligere direkte til etterlatte-pdltjenester. Nå går det mot grunnlag, og dermed kan man kun søke opp de personene som en sak på seg

Ey 1619 person soek

---

apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml
apps/etterlatte-vedtaksvurdering/.nais/dev.yaml

Se https://nav-it.slack.com/archives/C5KUST8N6/p1674818722408459

Legg til reloader konfig reload hvis secret endrer seg

---

apps/etterlatte-oppdater-behandling/src/test/resources/fullMelding.json
libs/common/src/main/kotlin/grunnlag/opplysningstyper/Opplysningstype.kt

Fjernet noen opplysningstyper som uansett ikke er i bruk

EY-1563 Fjerne opplysninger som ikke er i bruk

---

apps/etterlatte-tilbakekreving/build.gradle.kts
apps/etterlatte-utbetaling/build.gradle.kts
buildSrc/src/main/kotlin/Constants.kt
libs/ktor2client-onbehalfof/build.gradle.kts

Trur kanskje ikkje denne tar unna alt, men det er iallfall eit godt steg.

Bugfix/EY-1633: Oppgraderer avhengnadar Snyk klager på

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-tilbakekreving/build.gradle.kts
apps/etterlatte-utbetaling/build.gradle.kts
buildSrc/src/main/kotlin/Constants.kt
libs/ktor2client-onbehalfof/build.gradle.kts

Inntil vi får ting til å funke

Reverser ktor-oppgradering og tilhøyrande herlegheiter

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/styled.tsx

Alignment på infobokser
Obs - annoteringer på bildet for å fremheve hva jeg mener som infoboks er _ikke_ med i selve løsningen ;)

EY-1284 - juster alignment av infobokser

---

apps/etterlatte-saksbehandling-ui/client/src/App.tsx
apps/etterlatte-saksbehandling-ui/client/src/ErrorBoundary.tsx
apps/etterlatte-saksbehandling-ui/client/src/index.tsx

Benyttet muligheten til å mekke en penere feilmeldingsside nå som testmiljøet var suited for det 🤠

Errorwrapper for finere feilmelding når noe tryner unexpected

---

apps/etterlatte-saksbehandling-ui/client/src/components/vurderingsboks/VurderingsboksWrapper.tsx

em basert gir forskjellige størrelse på søknadsoversikt og vilkårsvurdering.
1rem gir resultat av 16px på begge to.

EY-1284 - gjør 'Rediger' lenker konsistent i VuderingsboxWrapper

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/manueltopphoer/ManueltOpphoerService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealManueltOpphoerServiceTest.kt

Du får aldri satt et riktig virkningstidspunkt på opphøret hvis det ikke er satt riktig fra starten av uansett.

EY-1293 Sikrer at det er saker med noe iverksatt som kan opphøres

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Info.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/OversiktKommerBarnetTilgode.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/Virkningstidspunkt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/utils.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/grunnlag.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Grunnlagsopplysning.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts

Vis kilde for søker og foreldreadresse under "Kommer barne til gode".
P.t. har vi bare "FREG" på søker (barn) men kan vise "PDL: Dato" for forelder.

EY 1259 - kilde for adresser / EY 1254 - kilde for dødsdato

---

apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/AdresseService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/AnnetBrevRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/AvslagBrevRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnvilgetBrevRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/navansatt/NavansattKlient.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
libs/common/src/main/kotlin/vedtak/Vedtak.kt

Henter navn til saksbehandler og attestant basert på ident og legger det til i brevrequest.

EY-1612: Hent navn til saksbehandler og attestant

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-grunnlag/.nais/dev.yaml

…  i behandling og grunnlag for å teste om jeg kan kjøre lokalt uten å hente secrets fra vilkaarsvurdering i dev.

Legger til etterlatte-vilkaarsvudering-lokal som inbound

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/SoeknadsoversiktTextArea.tsx

EY-1640 Feilmelding hvis ikke valg oppdrassammen men trykket videre

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/vilkaarsvurdering.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/hooks/useApiCall.ts
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutes.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt

Endepunktet splittes så ikke vilkårsvurdering opprettes som en side-effekt av at det ikke finnes fra før av.
Nytt endepunkt for å opprette en vilkårsvurdering.
EY-1636

Splitt hent og opprett vilkårsvurdering i to endepunkter

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/Virkningstidspunkt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Resultat.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/utils/formattering.ts

Bjørn og jeg lagde logikk slik at man ikke kan gå videre fra vilkårsvurderingen dersom virkningstidspunktet er endret fra da vilkårsvurderingen ble gjort

Ey 1646 navigeringsforbedringer

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingsstatusRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingsstatusRoutesTest.kt

Dette pga problemer når vi går over til Ktor 2.2.2 ved bruk av OBO-klient når vi kun returnerer tekst
EY-1654

Returnere json-payload ved endring av behandlingstatus

---

apps/etterlatte-saksbehandling-ui/client/package.json
apps/etterlatte-saksbehandling-ui/client/vitest.config.ts
apps/etterlatte-saksbehandling-ui/client/yarn.lock
apps/etterlatte-saksbehandling-ui/server/package.json
apps/etterlatte-saksbehandling-ui/server/yarn.lock
apps/etterlatte-saksbehandling-ui/yarn.lock

Bump avhengighetene som Snyk har opprettet
PS: Det opprettes nye PR-er fra Snyk nå mot main, men jeg dro alle inn hit for å se om ting gikk bra. Det gjorde det ikke 😅

Package bumps

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/innvilget.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/underkjent.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Brev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/manueltopphoeroversikt/ManueltOpphoerOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/ManueltOpphoerModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/grunnlagshendelser/Grunnlagsendringshendelser.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/saksliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/saksoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/utils/formattering.ts

Tar gjennomgående å bytter ut formaterEnumTilLesbarString for behandlingtype til en mer spesifikk funksjon. Evt. noe å vurdere for andre plasser der vi hacker det litt til

EY-1652 Fikser opp i litt språk og visning manuelt opphør

---

apps/etterlatte-beregning/src/main/kotlin/Application.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-fordeler/src/main/kotlin/Application.kt
apps/etterlatte-grunnlag/src/main/kotlin/Application.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/config/ApplicationBuilder.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/Application.kt

Ref diskusjon på slack et par dager siden.
Logg oppstart til sikkerhetsLogg - slik at vi kan sjekke:
1) at vi har koblet oss til sikkerhetsLogg
2) at vi logger sikkerhetsLogg til sikkerhetsLogg :)

Logg startup til sikkerhetslogg

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/BeanFactory.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingsstatusRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingAggregat.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/hendelse/RegistrerVedtakHendelseFelles.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/manueltopphoer/ManueltOpphoerService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingAggregat.kt
apps/etterlatte-behandling/src/test/kotlin/itest/IntegrationTest.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/rivers/LagreIverksattVedtak.kt

Måtte gjøres for å kunne logge vedtakshendeler hvis man får lov til å gjøre statusbyttet, ikke ellers.

EY-1648 Skrive om alle vedtakshendelser til å gå til statussjekken

---

buildSrc/src/main/kotlin/Ktor2.kt
libs/common/src/main/kotlin/logging/LogUtils.kt
libs/etterlatte-ktor/build.gradle.kts
libs/etterlatte-ktor/src/main/kotlin/HttpClient.kt
libs/etterlatte-ktor/src/main/kotlin/RestModule.kt

Fikser korrelasjonsider i etterlatte-ktor

---

apps/etterlatte-utbetaling/src/main/kotlin/Application.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/KvitteringMottaker.kt
apps/etterlatte-utbetaling/src/main/resources/logback-secure.xml
apps/etterlatte-utbetaling/src/main/resources/logback.xml

Legger også på sikkerLogg for utbetalings-appen

Logger error for alle utbetalinger som ikke er godkjent

---

apps/etterlatte-beregning/.nais/dev.yaml
apps/etterlatte-beregning/.nais/prod.yaml
apps/etterlatte-pdltjenester/.nais/dev.yaml
apps/etterlatte-pdltjenester/.nais/prod.yaml
apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml
apps/etterlatte-vilkaarsvurdering/.nais/prod.yaml

Fjerner ubrukt kafka-config

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/Oppgavebenken.tsx
apps/etterlatte-saksbehandling-ui/server/src/middleware/logging.ts
apps/etterlatte-saksbehandling-ui/server/src/routers/loggerRouter.ts
apps/etterlatte-saksbehandling-ui/server/src/utils/logger.ts

Ignorere logging til frackend hvis nais cluster mangler

EY-1686 Fikse feil som oppstår når det logges lokalt

---

apps/etterlatte-behandling/.nais/dev.yaml

Må IKKE merges før prosessen er gjort i GCP

Bumpe behandling postgres 12 -> 14

---

apps/etterlatte-opplysninger-fra-soeknad/.nais/dev.yaml
apps/etterlatte-opplysninger-fra-soeknad/.nais/prod.yaml
apps/etterlatte-utbetaling/.nais/dev.yaml
apps/etterlatte-utbetaling/.nais/prod.yaml

Disse appene nåes kun fra kafka, og kaller heller ikke noen eksterne klienter.
EY-1687

Utbetaling og uthenting-fra-soeknad trenger ikke å være azure-apps

---

apps/etterlatte-brev-api/build.gradle.kts
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingService.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/BehandlingTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingServiceTest.kt

Legger til beløp som utbetales og virkningstidpunkt i brev. 
Er avhengig av https://github.com/navikt/pensjon-etterlatte-felles/pull/20

EY-1661: Vis beløp som utbetales i brev

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/config/BeanFactory.kt
apps/etterlatte-behandling/src/test/kotlin/IntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingsstatusRoutesTest.kt
apps/etterlatte-behandling/src/test/resources/application.conf
apps/etterlatte-beregning/src/main/kotlin/Application.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/config/ApplicationContext.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRoutesTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/dokument/DokumentRouteTest.kt
apps/etterlatte-brev-api/src/test/resources/application.conf
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagRoutesKtTest.kt
apps/etterlatte-pdltjenester/src/main/kotlin/Server.kt
apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/TilbakekrevingRoutesTest.kt
apps/etterlatte-tilbakekreving/src/test/resources/application.conf
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/Application.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/config/ApplicationContext.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt
libs/etterlatte-ktor/src/main/kotlin/RestModule.kt
libs/etterlatte-ktor/src/main/kotlin/testsupport/KtorEnvironmentTestConfigOauth.kt
libs/etterlatte-ktor/src/test/kotlin/RestModuleTest.kt
libs/etterlatte-ktor/src/test/resources/application.conf

* Gikk fint hittil siden de kjørte på samme port(bare flaks)

Kjøre uten .conf fil for tester, blir race condition og feil da

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/typer/oppgavebenken.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/Tags.tsx
apps/etterlatte-saksbehandling-ui/server/src/mockdata/oppgaverMockData.json

Slik at de ikke vises som dumme tomme tags når det er hendelser på sak :D

Hendelse -> endring på sak

---

apps/etterlatte-fordeler/src/main/kotlin/fordeler/FordelerKriterier.kt

Retter opp i litt småting siden jeg var inne i fila.
@LarsErikDahl : Ser ikke ut som det skaper noen konflikt mot branchen din, men du får gi en 👍 / 👎 om det er greit å merge inn, eller om du styrer på med noe i fordeler appen så det ikke bør deployes.

Retter opp tvetydige beskrivelser og noen skrivefeil

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseJob.kt

La merke til at correlationId var ulik innad i samme job.
Får ikke lov å wrappe hele funksjonen med en `withLogContext`

Benytt samme correlationId på tvers av context.

---

apps/etterlatte-gyldig-soeknad/.nais/dev.yaml
apps/etterlatte-hendelser-pdl/.nais/dev.yaml
apps/etterlatte-statistikk/.nais/dev.yaml
apps/etterlatte-statistikk/.nais/prod.yaml
apps/etterlatte-testdata/.nais/dev.yaml

Etter oppdatering av prometheus - gikk gjennom. Disse manglet config i .nais yaml.

EY-1711 - add missing prometheus config

---

apps/etterlatte-utbetaling/.nais/prod.yaml

Første kjøring 27. februar.
EY-1628

Skrur på konsistensavstemming i produksjon

---

jobs/start-regulering/src/main/kotlin/Application.kt

Testet tidligere med og det funket i dev. Så endrer til faktiskt verdi.

Endre melding fra TEST-REGULERING til REGULERING for å kick-starte flyten (EY-1763)

---

apps/etterlatte-statistikk/src/main/kotlin/statistikk/database/StoenadRepository.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/MaanedStatistikk.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/StoenadRad.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
apps/etterlatte-statistikk/src/main/resources/db/gcp/V12__grant_read_access_monthly_stats.sql
apps/etterlatte-statistikk/src/main/resources/db/migration/V11__monthly_statistics.sql
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/VedtakhendelserRiverTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/SakRepositoryTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/StoenadRepositoryTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/domain/MaanedStatistikkTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/service/StatistikkServiceTest.kt

Det er ingen lagring ned av denne enda, dette kommer i en påfølgende task som setter opp en jobb for henting og produsering av forrige måneds stønadsstatistikk

EY-1174 Henter ut stønadsrader for en aktuell måned

---

.github/workflows/job-test-fordeler.yaml

Dependabot bumpet versjon på setup-java - ny påkrevd felt - distribution
Legg til temurin og bumpe fra 16 til 17.

Fix job-test-fordeler jobb

---

apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealGenerellBehandlingServiceTest.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/Application.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/AppBuilder.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/OpprettVedtakforespoersel.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/services/VedtakService.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/regulering/OpprettVedtakforespoerselTest.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BeregningKlient.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/VilkaarsvurderingKlient.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/DBTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/StatussjekkTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
libs/common/src/main/kotlin/sak/Saksbehandler.kt
libs/etterlatte-ktor/src/main/kotlin/TokenUtils.kt
libs/etterlatte-token-model/build.gradle.kts
libs/etterlatte-token-model/src/main/kotlin/no/nav/etterlatte/token/AccessTokenWrapper.kt
libs/etterlatte-token-model/src/main/kotlin/no/nav/etterlatte/token/Fagsaksystem.kt
libs/etterlatte-token-model/src/main/kotlin/no/nav/etterlatte/token/SaksbehandlerManglerEnhetException.kt
libs/etterlatte-token-model/src/test/kotlin/no/nav/etterlatte/token/AccessTokenWrapperTest.kt
libs/ktor2client-onbehalfof/src/test/kotlin/DownstreamResourceClientTest.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/EventNames.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/Feilhaandtering.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/StandardKeys.kt
libs/rapidsandrivers-extras/src/test/kotlin/rapidsandrivers/FeilhaandteringKtTest.kt

Trur dette er ein farbar veg for feilhandtering, men kan sikkert trenge litt justering

EY-1823 Fatt vedtak i omregning, pluss første del av feilhandtering

---

apps/etterlatte-saksbehandling-ui/client/package.json
apps/etterlatte-saksbehandling-ui/client/yarn.lock

Bumper alle ds pakkene i samme PR

Bump ds pakkene til 2.4.0

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/OversiktKommerBarnetTilgode.tsx

EY-1838 Egen lenke for paragraf 22-1

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingsHendelser.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Foerstegangsbehandling.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManueltOpphoer.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Regulering.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Revurdering.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/hendelse/HendelseDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/hendelse/RegistrerVedtakHendelseFelles.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/manueltopphoer/ManueltOpphoerService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealFoerstegangsbehandlingServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealGenerellBehandlingServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealManueltOpphoerServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealRevurderingServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/domain/ReguleringTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt

Forarbeid ifm fjerning av persongalleri på behandling.

EY-1820 Legge hele sak-objektet til behandling

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/klienter/BehandlingKlient.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt

Bruker sakType fra behandling i stedet for å hente fra /sak

Forenkler henting av sakType i vilkårsvurdering

---

.github/workflows/job-start-regulering.yaml
apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/OmregningHendelser.kt
apps/etterlatte-beregning-kafka/src/test/resources/omregningshendelse.json
apps/etterlatte-oppdater-behandling/src/main/kotlin/OmregningsHendelser.kt
apps/etterlatte-oppdater-behandling/src/test/kotlin/OmregningsHendelserTest.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/OpprettVedtakforespoersel.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/Vedtak.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/VilkaarsvurderingKlient.kt
jobs/start-regulering/deploy/dev.yml
libs/common/src/main/kotlin/behandling/BehandlingType.kt
libs/ktor2client-onbehalfof/src/main/kotlin/DownstreamResourceClass.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/Feilhaandtering.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/IkkeStandardiserteKeys.kt

Som det var stoppa det opp etter opprett vedtak-meldinga fordi det neste leddet forventa andre nøklar.

EY-1854: Er konsekvent på kva nøklar vi bruker i meldingane for automatisk behandling

---

apps/etterlatte-statistikk/src/main/kotlin/statistikk/database/StoenadRepository.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/StoenadRepositoryTest.kt

La også til en test som manglet som ville avdekket dette :facepalm:

Fjerner lagring til ikkeeksisterende kolonne

---

apps/etterlatte-behandling/src/main/kotlin/behandling/DetaljertBehandlingDto.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt

Usikker på om det *egentlig* er datoAttestert som skal benyttes her, men det er det som har ligget der til nå.
EY-1868

Vedtaksdato mangler i sidemenyen

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V17__remove_vedtakfattet_column.sql

Feltet vedtakstatus gir nå samme informasjon
EY-1876

Fjerner vedtakfattet felt da dette ikke lenger brukes

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
libs/etterlatte-ktor/src/main/kotlin/RestModule.kt
libs/etterlatte-ktor/src/main/kotlin/TokenUtils.kt

Gir samme effekt som https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/811
Men via hooks som man kan definere egne faser via, kun draft . Ikke ferdig.
Så er spørsmålet hvilken løsning vi burde gå for 🤔

Hook med auth context

---

.github/workflows/app-etterlatte-saksbehandling-ui.yaml

Vi har vel mykje som er høgare på prioriteringslista enn å rette opp namn i alle byggejobbane

EY-1885: Konsekvent i namn

---

apps/etterlatte-beregning/src/main/kotlin/beregning/regler/omstillingstoenad/sats/OmstillingsstoenadSats.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnOmstillingsstoenadServiceTest.kt

Mulig det er litt i overkant å betale ut 250k i måneden

Beregnet omstillingsstønad skal deles på antall måneder

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakDao.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakDaoTest.kt
apps/etterlatte-grunnlag/src/main/kotlin/Application.kt
apps/etterlatte-grunnlag/src/main/kotlin/klienter/BehandlingKlient.kt

Compare strings with = and not == and fix url query param

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseDao.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealFoerstegangsbehandlingServiceTest.kt
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/TilbakekrevingDao.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/common/Utils.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingJobTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/common/UtilsTest.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRepository.kt
libs/common/src/main/kotlin/tidspunkt/MidlertidigeKonverteringsfunksjoner.kt
libs/common/src/test/kotlin/tidspunkt/MidlertidigeKonverteringsfunksjonerTest.kt
libs/common/src/test/kotlin/tidspunkt/TidspunktTest.kt

Lurer på om det her er siste PR før vi må starte å sjå på kommunikasjonen med frontend

EY-1795: Revenge of the tidspunkt

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/attesterVedtak.tsx

I dag blir siden bare refreshet.
EY-1883 og EY-1890

Send attestant til saksoversikt etter iverksettelse av vedtak.

---

apps/etterlatte-saksbehandling-ui/client/src/shared/api/vilkaarsvurdering.ts
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/DelvilkaarRepository.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/vilkaar/BarnepensjonVilkaar.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/vilkaar/OmstillingstoenadVilkaar.kt
libs/common/src/main/kotlin/vilkaarsvurdering/Vilkaarsvurdering.kt

- Fjerner nullable lister for grunnlag og unntaksvilkår
- Fjerner typealiaser for Hovedvilkaar og Delvilkaar og erstatter dette med den egentlige typen Delvilkaar - tror aliasene bare gjør det vanskeligere å forstå at dette er samme typene. 
- Tilsvarende i frontend hvor det var definert to helt like typer.

Mindre justeringer vilkaarsvurdering

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/BehandlingKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/DokumentRoute.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/dokument/DokumentRouteTest.kt

Det blir muligens gjort en sjekk av dette hos saf også, men greit å være på den sikre siden.
EY-1887

Sjekk mot behandling for tilgang før man returnerer dokumenter

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/Virkningstidspunkt.tsx

Tekstendring i "Virkningstidspunkt" BP

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx

Regulering skal ikke sende ut vedtaksbrev, så då skal vi ikke heller vise vedtaksbrev i oppsummeringen.

Ikke vis vedtaksbrev for omregning (EY-1873)

---

apps/etterlatte-trygdetid/build.gradle.kts

This reverts commit 84b70eb1d47ede506469304b0aa8b91c78da623c.
Funka ikkje utan vidare. Får bli ny PR på det.

Revert "Bump com.h2database:h2 from 1.3.148 to 2.1.214 (#1001)"

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt

Dersom dette blir logget er vi nødt til å starte en "timer" for når vi må kunne behandle denne saken.
EY-1893

Logger error dersom vi får inn en sak med adressebeskyttelse.

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrev.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/SideMeny/SideMeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/SideMeny/types.ts
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/beslutningsvalg.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/godkjenn.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/underkjenn.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/attesterVedtak.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/underkjennVedtak.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumentoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt

Saksbehandler skal kunne gi en kommentar også ved innvilgelse

---

libs/common/src/main/kotlin/person/Foedselsnummer.kt
libs/common/src/test/kotlin/person/FoedselsnummerTest.kt

oppdatert logikk ihht https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/barn-fodt-i-norge/fodselsnummer/

Foedselsnummer.kt: rettet logikk for å finne årstall og lagt til test

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/attesterVedtak.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/underkjennVedtak.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/modal/modal.tsx

Tydeliggjør at vedtaksbrev blir utsendt automatisk

---

apps/etterlatte-fordeler/src/main/kotlin/fordeler/FordelerKriterier.kt
apps/etterlatte-fordeler/src/test/kotlin/fordeler/FordelerKriterierTest.kt
apps/etterlatte-fordeler/src/test/kotlin/fordeler/FordelerServiceTest.kt

Vi har ikke støtte i brev, og mangler manuell regulering enn så lenge.
EY-1658

Ikke ta inn søknader med dødsdato før juni 2022.

---

apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/JournalfoerVedtaksbrevTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/service/StatistikkServiceTest.kt
apps/etterlatte-statistikk/src/test/resources/melding.json
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/VedtakHelper.kt
apps/etterlatte-utbetaling/src/test/resources/vedtak.json
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/services/VedtakService.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/regulering/LoependeYtelserforespoerselTest.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/regulering/VedtakServiceImplTest.kt
apps/etterlatte-vedtaksvurdering/build.gradle.kts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/Vedtak.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/Vedtakstidslinje.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V18__remove_beregnet_status.sql
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/TestHelper.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtakstidslinjeTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingRouteTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
libs/common/src/main/kotlin/behandling/VedtakStatus.kt
libs/common/src/main/kotlin/vedtak/LoependeYtelseDTO.kt
libs/common/src/main/kotlin/vedtak/VedtakDto.kt

Tester endepunkter i vedtaksvurdering

---

apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/services/VedtakService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingRouteTest.kt

Endret format for å matche de andre routsen i vedtak

Endre routes for tilbakestilling av vedtak

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vurdering.tsx

Radio-valget "Nei, ingen av unntakene er oppfylt" ble valgt som default siden den ikke hadde noen verdi.
EY-1920

Ikke preutfyll "Nei" på unntaksvilkår

---

apps/etterlatte-behandling/src/test/resources/logback.xml
apps/etterlatte-beregning-kafka/src/test/resources/logback.xml
apps/etterlatte-beregning/src/test/resources/logback.xml
apps/etterlatte-brev-api/src/test/resources/logback.xml
apps/etterlatte-egne-ansatte-lytter/src/test/resources/logback.xml
apps/etterlatte-fordeler/src/test/resources/logback.xml
apps/etterlatte-grunnlag/src/test/resources/logback.xml
apps/etterlatte-gyldig-soeknad/src/test/resources/logback.xml
apps/etterlatte-hendelser-pdl/src/test/resources/logback.xml
apps/etterlatte-oppdater-behandling/src/test/resources/logback.xml
apps/etterlatte-opplysninger-fra-pdl/src/test/resources/logback.xml
apps/etterlatte-opplysninger-fra-soeknad/src/test/resources/logback.xml
apps/etterlatte-pdltjenester/src/test/resources/logback.xml
apps/etterlatte-statistikk/src/test/resources/logback.xml
apps/etterlatte-tilbakekreving/src/test/resources/logback.xml
apps/etterlatte-trygdetid/src/main/resources/logback.xml
apps/etterlatte-utbetaling/src/test/resources/logback.xml
apps/etterlatte-vedtaksvurdering-kafka/src/test/resources/logback.xml
apps/etterlatte-vedtaksvurdering/src/test/resources/logback.xml
apps/etterlatte-vilkaarsvurdering-kafka/src/test/resources/logback.xml
apps/etterlatte-vilkaarsvurdering/src/test/resources/logback.xml

Legger til logback.xml for tester siden main logback har formatering tilpasset logstash

legge til logback.xml i alle apper (src/test)

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vurdering.tsx

Når man trykket vurder etter sletting ble state hengende igjen.
EY-1933

Nullstill vilkår i UI ved sletting

---

apps/etterlatte-fordeler/src/main/kotlin/fordeler/Fordeler.kt
apps/etterlatte-gyldig-soeknad/src/main/kotlin/gyldigsoeknad/barnepensjon/FordeltSoeknadRiver.kt
apps/etterlatte-gyldig-soeknad/src/main/kotlin/gyldigsoeknad/omstillingsstoenad/InnsendtSoeknadRiver.kt
apps/etterlatte-gyldig-soeknad/src/test/kotlin/gyldigsoeknad/barnepensjon/FordeltSoeknadRiverTest.kt
apps/etterlatte-opplysninger-fra-soeknad/src/main/kotlin/opplysningerfrasoknad/StartUthentingFraSoeknad.kt
apps/etterlatte-testdata/src/main/kotlin/testdata/features/dolly/DollyFeature.kt
apps/etterlatte-testdata/src/main/kotlin/testdata/features/soeknad/OpprettSoeknad.kt
libs/common/src/main/kotlin/event/SoeknadInnsendt.kt

Dytter også ut "trenger_behandling" som en property på SoeknadInnsendt

Fikser lytting på begge behandlings-eventene

---

apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml

Vi burde se på en bedre måte å fange feil her, defaultingen til dev har brent oss to ganger nå :(

Legger inn manglende scopes og api i env saksbehandling-ui

---

apps/etterlatte-trygdetid/build.gradle.kts
apps/etterlatte-trygdetid/src/main/kotlin/Application.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/config/ApplicationContext.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/BehandlingKlient.kt
apps/etterlatte-trygdetid/src/main/resources/application.conf
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidRoutesTest.kt

Sjekker tilgang mot behandling

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumentliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumentlisteLiten.tsx

Skill mellom avsender og mottaker på journalførte brev

---

apps/etterlatte-saksbehandling-ui/client/src/shared/header/Search.tsx

Saksbehandlere ønsker å unngå å måtte bruke så mange klikk når de søker opp en bruker.
EY-1964

Gå direkte til saksoversikt ved søk på person

---

.github/workflows/.deploy.yaml

Er ikke 100% stødig på syntaksen her, så fint om noen tar en ekstra titt 🤓

Ikke forsøk å deploy apper til prod hvis de mangler prod.yaml

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/AutomatiskRevurdering.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManuellRevurdering.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Revurdering.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingAggregat.kt
apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/domain/RevurderingTest.kt
apps/etterlatte-opplysninger-fra-soeknad/src/test/kotlin/behandlingfrasoknad/OpplysningsuthenterBarnepensjonTest.kt

Dei følgjer to heilt forskjellige flytar. Det er derfor lurt av oss å også modellere det som forskjellige ting. Som ein bonus gir det mindre kompleks kode

EY-1769: Manuell og automatisk revurdering er to forskjellige ting

---

.github/workflows/app-etterlatte-behandling.yaml
apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-behandling/build.gradle.kts
apps/etterlatte-behandling/src/main/kotlin/config/BeanFactory.kt
apps/etterlatte-behandling/src/main/resources/application.conf
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/IntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/TestApp.kt
libs/etterlatte-funksjonsbrytere/src/main/kotlin/no/nav/etterlatte/funksjonsbrytere/FeatureToggleConfig.kt
libs/etterlatte-funksjonsbrytere/src/main/kotlin/no/nav/etterlatte/funksjonsbrytere/FeatureToggleService.kt

Splitter opp EY-1787 i flere mindre PR'er.
Denne skal kun gjøre unleash tilgjengelig i behanding.

EY-1787 - steg 1 - gjør unleash tilgjengelig i behandling

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/resources/logback.xml
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/Application.kt
libs/etterlatte-ktor/src/main/kotlin/RestModule.kt

Lekkasje av data blir tettet her for behandling sin sikkerlogg.

Log sikkerlogg oppstart behandling

---

apps/etterlatte-saksbehandling-ui/server/src/config/config.ts

Trenger dette for å feks kunne kjøre trygdetid-backend lokalt, men teste med resten av tjenestene i dev-gcp

Mulig å override lokal konfigurasjon med env variabler

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidBeregnet.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/styled.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
apps/etterlatte-trygdetid/.nais/azuread-etterlatte-trygdetid-lokal.yaml
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/main/resources/db/migration/V2__legg_til_trygdetid_i_trygdetidgrunnlag.sql
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidRepositoryTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt

* Flyttet trygdetid fra eget steg til å ligge i beregningsgrunnlag.
* Endret trygdtidsgrunnlag til å kun ha en periode og oppdatere den hvis det eksisterer fra før.

Ey 1916 trygdetid grunnlag tilpass

---

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlKlient.kt
apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonRoute.kt
apps/etterlatte-pdltjenester/src/test/kotlin/person/PersonRouteTest.kt

Eneste som feilet ved ruting av sak var at jeg ikke kan stave tilknytning/tilknyttning riktig :P

Remove spelling mistake

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Foerstegangsbehandling.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManuellRevurdering.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingAggregat.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingService.kt
apps/etterlatte-behandling/src/test/kotlin/OmregningIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/RealGenerellBehandlingServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/OpprettRevurderingModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/saksliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/saksoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Revurderingsaarsak.ts
apps/etterlatte-saksbehandling-ui/server/src/index.ts
libs/saksbehandling-common/src/main/kotlin/behandling/Virkningstidspunkt.kt

Enkel inngang for å kunne opprette revurderinger i frontend. Diverse refaktoreringer på virkningstidspunkt/behandling i tillegg.

Ey 1769 revurdering

---

apps/etterlatte-trygdetid/.nais/prod.yaml

Nais-oppsett for trygdetid i produksjon

---

apps/etterlatte-beregning/.nais/dev.yaml
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnOmstillingsstoenadService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/config/ApplicationContext.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/klienter/TrygdetidKlient.kt
apps/etterlatte-beregning/src/main/resources/application.conf
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnOmstillingsstoenadServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Sammendrag.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Beregning.ts
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
libs/saksbehandling-common/src/main/kotlin/trygdetid/Trygdetid.kt

Henter inn trygdetiden beregnet i steget for beregningsgrunnlag, bruker så denne som grunnlag ved beregning av omstillingsstønad.
EY-2009

Bruker trygdetid i beregning for omstillingsstønad

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/AdresseService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/DistribusjonModell.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/DistribusjonService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/AnnetBrevRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/AvslagBrevRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevRequestMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnvilgetBrevRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/DistribuerBrev.kt
apps/etterlatte-brev-api/src/main/resources/db/migration/V4__utvide_mottaker_adresse.sql
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/DistribuerBrevTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/JournalfoerVedtaksbrevTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/distribusjon/DistribusjonModellTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/distribusjon/DistribusjonServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/MottakerRequestTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/db/BrevRepositoryIntegrationTest.kt

Forbedre håndtering av adresse og sikre at det aldri er null.

EY-1999 Forbedre adresse i brev

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/Tilgangsstyring.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilgang/TilgangRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/config/BeanFactory.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakDao.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakDaoAdressebeskyttelse.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakTilgangDao.kt
apps/etterlatte-behandling/src/main/kotlin/sak/TilgangService.kt
apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/TilgangServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingsstatusRoutesTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingRoutesKtTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakDaoTest.kt

Antar her at alle saksbehandlere kan oppgavene.
Men ingenting annet.

EY-1785 Må ha egen ansatt rolle for å søke opp og behandle disse sakene

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt

Er nok andre mulige varianter her, hadde nok vært lettere å forholde oss til beans på tilsvarende måter som det er gjøres i flere av de andre rest-appene slik at man slipper å reinstansere services etc som det gjøres i stor grad i behandling.

Unngå reinstansering av beans ved hver request

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/domain/Oppgave.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/OppgaveKolonner.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/Oppgavebenken.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/typer/oppgavebenken.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts

Venter med fjerning av antallSoesken og persongalleri i behandling-db frem til dette har fått kjøre litt i dev.

EY-1848 Erstatte antallSoesken med merknad frontend

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidBeregnet.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/styled.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
apps/etterlatte-trygdetid/build.gradle.kts
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/BeregnTrygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidBeregningService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/config/ApplicationContext.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/regler/BeregnTrygdetid.kt
apps/etterlatte-trygdetid/src/main/resources/db/migration/V5__legg_til_felter_beregnet_trygdetidgrunnlag.sql
apps/etterlatte-trygdetid/src/main/resources/db/migration/V6__legg_til_felter_trygdetid_total.sql
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidBeregningServiceTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidRepositoryTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
libs/saksbehandling-common/src/main/kotlin/trygdetid/Trygdetid.kt

Regler for å beregne trygdetid innenfor en periode og total trygdetid.
Må regelspesifiseres. Utkast til regler ligger nå her: https://confluence.adeo.no/display/TE/Beregning+av+trygdetid+lovtolkning

Regler for trygdetid

---

apps/etterlatte-fordeler/.nais/dev.yaml
apps/etterlatte-fordeler/.nais/prod.yaml
apps/etterlatte-fordeler/src/main/kotlin/AppBuilder.kt
apps/etterlatte-fordeler/src/main/kotlin/Application.kt
apps/etterlatte-fordeler/src/main/kotlin/fordeler/FordelerKriterier.kt
apps/etterlatte-fordeler/src/main/kotlin/fordeler/FordelerService.kt
apps/etterlatte-fordeler/src/main/kotlin/skjerming/SkjermingKlient.kt
apps/etterlatte-fordeler/src/test/kotlin/fordeler/FordelerServiceTest.kt

Må vente på https://nav-it.slack.com/archives/CTN3BDUQ2/p1681735074654469
Burde denne Featuretoggles?

EY-1894 Hvis barnet er skjermet så sendes saken til PESYS

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/OpprettRevurderingModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/grunnlagshendelser/tekster.ts
apps/etterlatte-saksbehandling-ui/client/src/components/person/saksoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/UhaandterteHendelser.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/utils.ts

Refaktorert frontend til å bruke riktig datatype fra backend

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BarnepensjonSammendrag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BarnepensjonToolTip.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadSammendrag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadToolTip.tsx

Splitter ut i hvert sitt sammendrag siden disse har litt ulike kolonner, tooltips etc

Eget beregningssammendrag for BP og OMS

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/domain/Oppgave.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDTOTest.kt
apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/leesah/PersonHendelseFordeler.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/BehandlingService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/Oppgavebenken.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/typer/oppgavebenken.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/typer/oppgavefelter.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts

Oppretter merknad på oppgaver i oppgavelisten som stammer fra grunnlagsendringer. Mulig vi skal gjøre noe mer elegant her, men dette bør fungere for nå.
Fjerner også beskrivelse som ikke ble brukt til noe.
EY-2030

Oppretter merknad på oppgaver fra Grunnlagsendringsoppgave

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/Virkningstidspunkt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/utils.ts
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Resultat.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx

Tilpasset tekstene og informasjonen på de forskjellige stegen (Søknadsoversikt, vilkårsvurdering, beregning) for å passe med revurdering

Ey 1769 frontend

---

apps/etterlatte-beregning/src/main/kotlin/beregning/AvkortingRepository.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/AvkortingRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/AvkortingService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Avkorting.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/AvkortingInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadSammendrag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/HjemmelLenke.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/SoeknadsVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/avkorting.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts

Komponenter for å Avkorting og AvkortingGrunnlag
Endepunkt for å lagre AvkortingGrunnlag

EY-2052 - oppstart Avkorting og AvkortingGrunnlag

---

apps/etterlatte-fordeler/src/main/kotlin/fordeler/FordelerKriterier.kt
apps/etterlatte-fordeler/src/test/kotlin/fordeler/FordelerKriterierTest.kt

Vi ønsker fremdeles ikke å håndtere barn over 18 år på gammelt regelverk.
Legger inn en ekstra måned for å ha litt buffer ifm. migrering.
EY-1755, EY-1756

Vi kan ta inn søknader så lenge barnet eller søsken ikke fyller 18 før februar 2024

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/utils.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Revurderingsaarsak.ts

Det er forskjellig hjemmel og tekst på virkningstidspunkt alt etter om det er innvilgelse, revurdering eller opphør.
EY-1601

Endre tekst og hjemmel på virkningstidspunkt ved opphør

---

.github/workflows/app-etterlatte-trygdetid-kafka.yaml
apps/etterlatte-trygdetid-kafka/.nais/dev.yaml
apps/etterlatte-trygdetid-kafka/.nais/prod.yaml
apps/etterlatte-trygdetid-kafka/build.gradle.kts
apps/etterlatte-trygdetid-kafka/src/main/kotlin/AppBuilder.kt
apps/etterlatte-trygdetid-kafka/src/main/kotlin/Application.kt
apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelser.kt
apps/etterlatte-trygdetid-kafka/src/main/kotlin/TrygdetidService.kt
apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/prod.yaml
apps/etterlatte-vilkaarsvurdering-kafka/src/main/kotlin/vilkaarsvurdering/Migrering.kt
apps/etterlatte-vilkaarsvurdering-kafka/src/test/kotlin/vilkaarsvurdering/MigreringTest.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/Migreringshendelser.kt
settings.gradle.kts

Har ikkje gjort noko med sjølve trygdetids-beregninga, så det kan hende det i neste runde trengs meir tweaking der.

EY-1978: Enkelt oppsett for trygdetid for migrering

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt

Motivasjon: Ønsker å kunne gjøre rollback på tvers av repository-metoder, og evnt feil mot andre tjenester.
EY-2025

Transaksjon i service for trygdetid for å sikre rollback

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidRepositoryTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt

Ny tilnærming:
- Hent-operasjoner kan ta inn transaksjon, men må ikke
- Skriv-operasjoner må alltid ta inn transaksjoner

Bruker samme transaksjon for opprett og hent

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/Behandling.tsx

Route beregning har denne:
```
if (behandling.vilkårsprøving?.resultat?.utfall === VilkaarsvurderingResultat.OPPFYLT) {
routes.push('beregningsgrunnlag')
routes.push('beregne')
}
```
Hvis ikke de to er i routes så sendes bruker til søknadsoversikt via en catch route:
```
<Route path="*" element={<Navigate to={behandlingRoutes[0].path} replace />} />
```
Så vi må ha vilkårsprøving tilgjengelig fra starten (hvis det finnes) for at stegmeny fungerer for de to.
Denne fikser stegmeny når man først er inn i en behandling (den laster behandling og så fyller den på med vilkårsvurdering)
Den fikser ikke hvis en bruker bokmerke en understeg (av enten beregningsgrunnlag eller beregne) fordi vi har blitt rutet tilbake til søknadsoversikt før denne har klart å laste.
Men - for nå er dette kanskje …

EY-2164 - stegmeny trenger å vite om mulige vilkårsvurdering for å regne ut riktig routes

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Grunnlagopplysninger.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidBeregnet.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx

Fjerner visning av at regelresultat mangler regelspesifikasjon

---

.github/workflows/.deploy.yaml
.github/workflows/app-etterlatte-behandling.yaml
.github/workflows/app-etterlatte-beregning-kafka.yaml
.github/workflows/app-etterlatte-beregning.yaml
.github/workflows/app-etterlatte-brev-api.yaml
.github/workflows/app-etterlatte-egne-ansatte-lytter.yaml
.github/workflows/app-etterlatte-fordeler.yaml
.github/workflows/app-etterlatte-grunnlag.yaml
.github/workflows/app-etterlatte-gyldig-soeknad.yaml
.github/workflows/app-etterlatte-hendelser-pdl.yaml
.github/workflows/app-etterlatte-institusjonsopphold.yaml
.github/workflows/app-etterlatte-migrering.yaml
.github/workflows/app-etterlatte-oppdater-behandling.yaml
.github/workflows/app-etterlatte-opplysninger-fra-pdl.yaml
.github/workflows/app-etterlatte-opplysninger-fra-soeknad.yaml
.github/workflows/app-etterlatte-pdltjenester.yaml
.github/workflows/app-etterlatte-saksbehandling-ui.yaml
.github/workflows/app-etterlatte-statistikk.yaml
.github/workflows/app-etterlatte-testdata.yaml
.github/workflows/app-etterlatte-tilbakekreving.yaml
.github/workflows/app-etterlatte-trygdetid-kafka.yaml
.github/workflows/app-etterlatte-trygdetid.yaml
.github/workflows/app-etterlatte-utbetaling.yaml
.github/workflows/app-etterlatte-vedtaksvurdering-kafka.yaml
.github/workflows/app-etterlatte-vedtaksvurdering.yaml
.github/workflows/app-etterlatte-vilkaarsvurdering-kafka.yaml
.github/workflows/app-etterlatte-vilkaarsvurdering.yaml

Rein refaktorisering og tilrettelegging, faktiske endringar kjem i ny seinare PR.

EY-2208: Tilrettelegging for å eksperimentere med byggejobbar og gå over til Google Artifactory Registry

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/ManueltVilkaar.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/styled.ts

Endre klikkbar lenke til lovdata til å være tilsvarende søknadsoversikt

---

apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/prod.yaml
apps/etterlatte-trygdetid/src/main/kotlin/Application.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/KodeverkRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/KodeverkService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/config/ApplicationContext.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/KodeverkKlient.kt
apps/etterlatte-trygdetid/src/main/resources/application.conf
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/KodeverkServiceTest.kt
apps/etterlatte-trygdetid/src/test/resources/kodeverk/landkoder.json

Skal benyttes til å populere dropdown i trygdetid-skjermbildet.
EY-2214

Ny tjeneste mot kodeverk for å hente alle land.

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidRepositoryTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt

Gjør et forsøk på å fjerne kompleksiteten som kom ved å legge transaksjon inn i service-laget.

Fjerner bruk av transaksjoner i service for trygdetid

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/attestering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/beslutningsvalg.tsx
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt

Vil se slik ut nå dersom saksbehandler går inn på en sak hen har fattet vedtak på.

EY-2220 Forhindre mulighet til å attestere egen sak

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/InntektAvkortingService.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/AvkortetYtelse.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/InntektAvkorting.kt
apps/etterlatte-beregning/src/main/kotlin/regler/Beregningstall.kt
apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/InntektAvkortingServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/regler/AvkortetYtelseTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/regler/InntektAvkortingTest.kt

-  Ta i bruk interface PeriodisertGrunnlag
-  Legge til regelreferanser
-  Endre regel opprundetInntekt til nedrundetInntekt

EY-2127 Endre regelkjøring avkorting

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevRequestMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EndringBrevRequest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingServiceTest.kt

Se korresponderende PR i etterlatte-felles: https://github.com/navikt/pensjon-etterlatte-felles/pull/71

EY-2089: Enkelt brev for revurderinger

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/OpprettNyBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/RelevanteHendelser.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Revurderingsaarsak.ts

Ser ikke lengre bare på om vi har hendelser oppe for revurdering. Tar også og pynter på tekstene til revurderingsårsakene

Gir muligheten for å opprette en revurdering hvis vi støtter revurderinger

---

apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnBarnepensjonServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/ReguleringTest.kt

Trur ikkje denne dekkjer alt som kan gå feil, men eg trur iallfall han avdekkar ein god del feilsituasjonar som kan oppstå. Og at det er lurt at vi lagar ein liknande test når vi introduserer det nye grunnbeløpet.

EY-1956: Test som gir oss indikasjonar på at det utbetalte beløpet aukar riktig når grunnbeløpet endrar seg

---

apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml
apps/etterlatte-saksbehandling-ui/server/package.json
apps/etterlatte-saksbehandling-ui/server/src/config/config.ts
apps/etterlatte-saksbehandling-ui/server/src/index.ts
apps/etterlatte-saksbehandling-ui/server/src/routers/mockRouter.ts
apps/etterlatte-saksbehandling-ui/server/src/utils/unleash.ts
apps/etterlatte-saksbehandling-ui/server/yarn.lock

URI: /api/feature
Method: POST
Request example:
```
{
"features": [
"pensjon-etterlatte.filtrer-saker-med-enhet-id",
"pensjon-etterlatte.filter-oppgaver-enhet",
"pensjon-etterlatte.filtrer-behandlinger-med-enhet-id"
]
}
```
Response example:
```
[
{
"toggle": "pensjon-etterlatte.filtrer-saker-med-enhet-id",
"enabled": true
},
{
"toggle": "pensjon-etterlatte.filter-oppgaver-enhet",
"enabled": true
},
{
"toggle": "pensjon-etterlatte.filtrer-behandlinger-med-enhet-id",
"enabled": true
}
]
```

Add unleash to bff for frontend use

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt

Feilen kræsjer beregning i produksjon

Svelger exception fra trygdetidklient for beregning barnepensjon

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Revurderingsaarsak.ts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/TestHelper.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
libs/saksbehandling-common/src/main/kotlin/behandling/RevurderingAarsak.kt

La også på en sanity-check i attestering av revurderingen som passer på at det må bli opphør for denne revurderingsårsaken.

EY-1551: Åpner for revurdering på grunn av søkers dødsfall

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelser.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/KodeverkService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidBeregningService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/regler/BeregnTrygdetid.kt
apps/etterlatte-trygdetid/src/main/resources/db/migration/V7__endre-type-nasjon-faktisk.sql
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/KodeverkServiceTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidBeregningServiceTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidRepositoryTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
libs/etterlatte-trygdetid-model/src/main/kotlin/TrygdetidType.kt

Kun Norge blir brukt til beregning av trygdetid p.t.

Støtte for ulike land i trygdetid

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRepository.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/TilbakekrevingDao.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingDao.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRepository.kt
libs/etterlatte-database/src/main/kotlin/DataSourceUtils.kt
libs/etterlatte-database/src/main/kotlin/KotliqueryRepository.kt

I eit forsøk på å standardisere korleis vi gjer transaksjonar, trur eg ein del av poenget er at det er enkelt å gjera det rett (dvs på den måten vi vil ha det).
Har gjort eit forsøk på å oppnå det her.

Hjelpemetode for datasource -> transaksjon

---

.github/workflows/job-test-fordeler.yaml
.github/workflows/lib-etterlatte-beregning-model.yaml
.github/workflows/lib-etterlatte-database.yaml
.github/workflows/lib-etterlatte-funksjonsbrytere.yaml
.github/workflows/lib-etterlatte-jobs.yaml
.github/workflows/lib-etterlatte-kafka.yaml
.github/workflows/lib-etterlatte-ktor.yaml
.github/workflows/lib-etterlatte-regler.yaml
.github/workflows/lib-etterlatte-sporingslogg.yaml
.github/workflows/lib-etterlatte-trygdetid-model.yaml
.github/workflows/lib-ktor2client-auth-clientcredentials.yaml
.github/workflows/lib-ktor2client-onbehalfof.yaml
.github/workflows/lib-rapidsandrivers-extras.yaml
.github/workflows/lib-saksbehandling-common.yaml
.github/workflows/lib-testdata.yaml

Når vi mergar inn ei endring som gjer at alle applikasjonane blir bygga på nytt, hender det at ting på GHA trynar, ser ut som det er fordi det er for mykje som skjer. Så da er det nyttig å kunne rekøyre manuelt når ting trynar på grunn av det

Opnar for å køyre alle våre github actions manuelt

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
apps/etterlatte-beregning/src/main/resources/db/migration/V17__legge_til_fratrekkInnUt_avkortingsgrunnlag.sql
apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/AvkortingInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts
libs/saksbehandling-common/src/main/kotlin/beregning/BeregningDTO.kt

- Nytt felt i skjema
- Nytt felt i domene og database
- Feltet brukes ikke til noe enda men vil bli tatt i bruk i EY-2258

EY-2257 Lagt til felt fratrekkInnUt for avkorting

---

apps/etterlatte-trygdetid/src/main/resources/db/migration/V8__legg_til_felt_begrunnelse.sql

Kun flyway delen av https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/1532
Har lyst å få merget denne slik at jeg kan teste endringer i den andre PR med "låne dev litt" - vil bare at migrering går ut litt kontrollert.
Den skal ikke brekke dev/prod - er bare en ny og nullable felt som vil ignoreres frem til de andre endringer er testet og klart.

EY-2166 - kun migrering

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidRepositoryTest.kt
libs/etterlatte-trygdetid-model/src/main/kotlin/Trygdetid.kt

EY-2166 - mulighet å begrunne trygdetidgrunnlag

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts

Frontend endringer for EY-2166
Backend endringer er i PR https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/1532
Ser slik ut:

EY-2166 - mulighet å begrunne trygdetidgrunnlag - frontend

---

apps/etterlatte-behandling/src/test/kotlin/behandling/migrering/MigreringRoutesTest.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelserTest.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/MigreringIntegrationTest.kt
apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelser.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/MigreringRequest.kt

Skjønner ikkje heilt korleis denne kom seg inn i main, men

Begrunnelse på trygdetid må også definerast og handterast for migrering

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx

Fag har bekreftet at begrunnelse også ønskes på fremtidig trygdetid - fjern filter på "FAKTISK".

EY-2166 fremtidig trygdetid må også kunne begrunnes

---

.github/workflows/app-etterlatte-behandling.yaml
.github/workflows/app-etterlatte-beregning-kafka.yaml
.github/workflows/app-etterlatte-beregning.yaml
.github/workflows/app-etterlatte-brev-api.yaml
.github/workflows/app-etterlatte-egne-ansatte-lytter.yaml
.github/workflows/app-etterlatte-fordeler.yaml
.github/workflows/app-etterlatte-grunnlag.yaml
.github/workflows/app-etterlatte-hendelser-pdl.yaml
.github/workflows/app-etterlatte-institusjonsopphold.yaml
.github/workflows/app-etterlatte-oppdater-behandling.yaml
.github/workflows/app-etterlatte-opplysninger-fra-pdl.yaml
.github/workflows/app-etterlatte-pdltjenester.yaml
.github/workflows/app-etterlatte-statistikk.yaml
.github/workflows/app-etterlatte-trygdetid-kafka.yaml
.github/workflows/app-etterlatte-trygdetid.yaml
.github/workflows/app-etterlatte-vedtaksvurdering-kafka.yaml
.github/workflows/app-etterlatte-vedtaksvurdering.yaml
.github/workflows/app-etterlatte-vilkaarsvurdering-kafka.yaml
.github/workflows/app-etterlatte-vilkaarsvurdering.yaml

For å sørge for at relevante bygg blir trigga med endringar

EY-2282: Går gjennom alle appane våre og samanliknar avhengnadane i build.gradle med dei som er sett opp i yaml-filene

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt

For BP som var opprettet før vi åpnet for ekte trygdetid vil revurdering feiler fordi eksisterende trygdetid finnes ikke.
Opprett (på samme måte som førstegangs) hvis det mangler og det _ikke_ er regulering
For regulering - feil slik at det går til manuelt.

EY-2278 oppretter manglende eksisterende trygdetid ved revurdering - men ikke for regulering

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/OpprettRevurderingModal.tsx

* viser revurderingsårsak i oversikten
* viser riktig vilkårsresultat
* videresender til opprettet revurdering

Småfiks for revurderinger

---

buildSrc/src/main/kotlin/etterlatte.common.gradle.kts
buildSrc/src/main/kotlin/etterlatte.libs.gradle.kts
libs/etterlatte-database/build.gradle.kts
libs/etterlatte-kafka/build.gradle.kts
libs/etterlatte-ktor/build.gradle.kts
libs/etterlatte-sporingslogg/build.gradle.kts
libs/rapidsandrivers-extras/build.gradle.kts
libs/saksbehandling-common/build.gradle.kts
libs/testdata/build.gradle.kts

Så vi slepp å måtte gjenta det i byggefil etter byggefil rundt omkring

EY-2290: Samlar oppsettet for å kople oss til libs-repoet i ei fil

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/utils.ts

- Legger til riktig hjemmel og beskrivelse for virkningstidspunkt for OMS
- Gjør ikke avkorting i beregningssteget
EY-2276

Legger til spesifikk beskrivelse og hjemmel i virkingstidspunkt for omstillingsstønad

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/avbryt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/typer.ts

Rydder også bort en custom match som ble brukt for å hente ut behandlingsId i stedet for å bruke det vi har i redux-state

Teksten på avbryt var litt vel aggressiv for revurderinger

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerHelpers.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/AvslagBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EndringBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnvilgetBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/ManueltBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/Slate.kt
apps/etterlatte-brev-api/src/main/resources/db/migration/V6__sakid_og_innhold.sql
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/JournalfoerVedtaksbrevTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/VedtaksbrevUnderkjentTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/db/BrevRepositoryIntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts

Større omskriving av service og datastruktur i brev. Ved å trekke ut PDF (bytea) i egen tabell reduserer vi sjekker på manuell og automatisk.

EY-2283 Opprydding i services, repo, databasestruktur, m.m.

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/PeriodisertBeregningGrunnlagTest.kt
libs/etterlatte-beregning-model/src/main/kotlin/GrunnlagMedPeriode.kt

…der vi bruker konstant grunnlag viss ikkje det fins institusjonsopphold her allereie

EY-2168: Meir gjennomført variant for institusjonsopphold-reglar

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/beregning/BeregningKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnvilgetBrevData.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt

Endringen er avhengig av https://github.com/navikt/pensjonsbrev/pull/168

EY-2079: Hent avkorting og sett opp brevkode for oms auto

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/SideMeny/SideMeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/AnnullerBehanding.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/AvbrytBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/BehandlingHandlingKnapper.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/NesteOgTilbake.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/typer.ts
apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumentoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts

EY-2232 Skille mellom avbryt (gå ut av behandling) og annuller sak

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/InstitusjonsoppholdForside.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts

NB backend er ikke implementert, se slack.
https://nav-it.slack.com/archives/C052ZKZHZHP/p1686323446320449
Dette vises bak en FT så kan merges as-if.

EY-2241 Vurdering institusjonsopphold frontend

---

apps/etterlatte-trygdetid/src/main/resources/db/migration/V9__legg_til_felter_in_ut_aar.sql

Kun DB migrering fra https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/1586 - slik at den kan deployes mens vi tester koden ved å "låne trygdetid" ;)

EY-2319 støtte for poeng inn/ut aar - db migration

---

apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelser.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidRepositoryTest.kt
libs/etterlatte-trygdetid-model/src/main/kotlin/Trygdetid.kt

Plan er å deploye første commit fra eget PR etterpå slik at vi kan lettere teste ved "låner trygdetid"  :)

EY-2319 støtte for poeng inn/ut aar - backend

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/hooks/useApiCall.ts
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidTest.kt

Legger til enkel backend-validering

Skal ikke kunne legge til overlappende perioder

---

apps/etterlatte-utbetaling/.nais/dev.yaml
apps/etterlatte-utbetaling/.nais/prod.yaml
apps/etterlatte-utbetaling/src/main/kotlin/Application.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/GrensesnittsavstemmingJob.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/GrensesnittsavstemmingService.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingJob.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingService.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/avstemmingsdata/GrensesnittavstemmingDataMapper.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/avstemmingsdata/KonsistensavstemmingDataMapper.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/config/ApplicationContext.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/config/ApplicationProperties.kt
apps/etterlatte-utbetaling/src/test/kotlin/ApplicationIntegrationTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/TestHelper.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/AvstemmingDaoIntegrationTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/GrensesnittsavstemmingsJobTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingJobTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/avstemmingsdata/AvstemmingsdataJaxbTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/avstemmingsdata/AvstemmingsdataSenderIntegrationTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/avstemmingsdata/GrensesnittavstemmingDataMapperTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/avstemmingsdata/KonsistensavstemmingDataMapperTest.kt

Implementert konsistens og grensesnittsavstemming for OMS. Mulig tynt på integrasjonstester da jeg ikke får kjørt de på M1. Bør nok testes i miljø før Merge

Implementere avstemming for OMS

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingRoutes.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingRoutesTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/behandlingsliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Revurderingsaarsak.ts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/DetaljertBehandling.kt
libs/etterlatte-behandling-model/src/test/kotlin/no/nav/etterlatte/libs/common/behandling/DetaljertBehandlingTest.kt
libs/etterlatte-ktor/src/main/kotlin/GcpEnv.kt
libs/etterlatte-vedtaksvurdering-model/src/main/kotlin/VedtakDto.kt
libs/saksbehandling-common/src/main/kotlin/NaisUtils.kt
libs/saksbehandling-common/src/main/kotlin/VedtakType.kt
libs/saksbehandling-common/src/main/kotlin/behandling/RevurderingAarsak.kt

Kjenner meg ganske trygg på denne i og med togglinga.
Dekkjer ikkje alt, men trur det er greitt å ta inn for seg. Med det grunnleggjande som dette merga inn trur eg behovet for å låne applikasjonar i test blir lite.

EY-1578: Revurdering opphør omgjøring av farskap - del 1

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/vilkaar/OmstillingstoenadVilkaar.kt
libs/etterlatte-vilkaarsvurdering-model/src/main/kotlin/vilkaarsvurdering/VilkaarType.kt

Legger til vilkår for sivilstand og andre ytelser

---

apps/etterlatte-trygdetid/src/main/kotlin/Application.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/avtale/AvtaleRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/avtale/AvtaleService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/config/ApplicationContext.kt
apps/etterlatte-trygdetid/src/main/resources/trygdetid_avtale_kriterier.json
apps/etterlatte-trygdetid/src/main/resources/trygdetid_avtaler.json
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/avtale/AvtaleRoutesTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/avtale/AvtaleServiceTest.kt
libs/etterlatte-trygdetid-model/src/main/kotlin/Avtale.kt

Dette er bare første delen - den setter opp verdiene i basen (tatt fra pesys) og gjøre dem tilgjengelig slik at frontend kan hente ut for å bruke i selects.
Knytting av valg til lagret trydetid data og frontend kommer i følgende PRer

EY-2332 - trygdetidavtaler - oppslagstabeller

---

apps/etterlatte-migrering/src/test/resources/barnepensjon_uttrekk_sak_pesys.sql

Disse to spørringene dekker p.t. det vi trenger for å migrere en sak. Må justere litt på migreringslogikken i koden vår i en annen oppgave.
Legger det i test resources inntil videre, denne spørringen vil være en WIP frem mot migreringstidspunktet.
EY-1843

Uttrekk av informasjon fra Pesys for en gitt sakId

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/HendelseBeskrivelse.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/utils.ts

Legger til visning av sivilstandshendelse

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx

Går ikke å lagre trygdetid uten å sende med disse feltene.

Setter initial values for valgfrie felter i trygdetid

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/beregning/BeregningKlient.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt

Er avhengig av at denne også blir godkjent: https://github.com/navikt/pensjonsbrev/pull/172

Bruk ytelseMedGrunnlag for uthenting av avkortingsinfo

---

apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutes.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt

Ved opphør skal vi kopiere beregningsgrunnlaget frå forrige behandling
Førebuing til den funksjonelle PR-en som kjem snart på EY-2347.

EY-2347: Har bruk for å kalle dette endepunktet også som saksbehandlar

---

apps/etterlatte-behandling/src/main/kotlin/behandling/DetaljertBehandlingDto.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EndringBrevData.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.test.ts
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/GrunnForSoeskenjustering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/SoeskenjusteringUndertype.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/revurdering.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/RevurderingInfo.ts
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/BehandlingReducer.ts

Legger til valg av brevmal for revurdering søskenjustering

EY-2330 ny brevmal revurdering soeskenjustering frontend

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BarnepensjonSammendrag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadSammendrag.tsx

Endre rekkefølge på beregningsperioder så nyeste kommer øverst

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/vilkaar/BarnepensjonVilkaar.kt

Presiserer at det gjelder på virkningstidspunktet.
EY-2356

Endrer tekst og spørsmål på vilkåret "Formål".

---

apps/etterlatte-vilkaarsvurdering/src/main/resources/db/migration/V14__legg_til_index.sql

basert på stats fra prod samt `explain analyze` med dev-gcp data

EY-2408 Lagt til noen db-indekser i vilkårsvurdering

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Institusjonsopphold.tsx

* kun vise blokka hvis den finnes hvis grunnlaget og den er satt til iverksatt/fattet
* Kunne slette institusjonsopphold

EY-2359 Readmore for beregningsgrunnlag institusjonsopphold

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/GrunnlagForVirkningstidspunkt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx

For revurdering der revurderingsårsaken er dødsfall. Det fungerer ikke helt som det bør siden uthenting av grunnlag er async enn så lenge, men det er en separat jobb :p

EY-2343 Viser dødsdato for mottaker av ytelsen

---

gradle/wrapper/gradle-wrapper.properties

Release notes: https://docs.gradle.org/8.2/release-notes.html

Update gradle to 8.2

---

.github/workflows/alerts.yaml

Nye lenker til query som ikke mangler `AND`
Dev: https://logs.adeo.no/app/r/s/RxEhL
Prod: https://logs.adeo.no/app/r/s/awtWK

Lenke til logs med korrekt query

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/OpphoerBrevData.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/AdoptertAv.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/RevurderingInfo.ts
libs/saksbehandling-common/src/main/kotlin/behandling/RevurderingInfo.kt

Brevendringane: https://github.com/navikt/pensjonsbrev/pull/185

EY-1552: Det kan vera to som adopterer

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx

Det kan fremdeles sendes andre brev av saksbehandler som en del av behandlingen, som tilbakekreving m.m.

Presiserer at ingen vedtaksbrev sendes for behandling

---

apps/etterlatte-saksbehandling-ui/server/src/utils/unleash.ts

Gjøres for å unngå denne feilmeldingen ved hver redeploy: 
```
FetchError: Unleash Repository error: request to https://unleash.nais.io/api/client/features failed, reason: connect ECONNREFUSED 34.120.34.218:443
```

destroy unleash on sigterm

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/OpphoerBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtak/VedtaksvurderingKlient.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/adresse/AdresseServiceTest.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt

Brev-PR: https://github.com/navikt/pensjonsbrev/pull/186

EY-2420: Innvilgelsesdato

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/AvslagBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/Slate.kt
apps/etterlatte-brev-api/src/main/resources/maler/bp-avslag.json

Brev-PR: https://github.com/navikt/pensjonsbrev/pull/190

EY-2427: Mal for avslag

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt

Det blir kanskje ikke helt pent som en enkel fix. Må evt skrive om mer for å få det penere

Fix for å ignorere sivilstandsendringer på søsken

---

apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/MinOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelistafiltre.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/ToggleMinOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/ToggleNyOppgavelist.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaverny.ts

EY-2442 Filtrering på  oppgavelista 

---

apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/RedigerSaksbehandler.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaverny.ts

La saksbehandler fjerne seg fra egne oppgaver og la andre saksbehandlere ta over oppgavene til andre saksbehandlere

EY-2467 Fjern eller endre saksbehandler på alle oppgaver

---

apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelistafiltre.tsx

- Lar saksbehandler filtrere på frist
- Viser frist som er passert med rød tekst
- Sorterer etter tid over fristen hvis man velger å filtrere på "Frist har passert"

EY-2389 Filtrer og sorter basert på frist

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingVedtakRoute.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
apps/etterlatte-behandling/src/test/kotlin/oppgaveny/OppgaveServiceNyTest.kt

For å "late" som at man bruker oppgave, også i produksjon. 
Skal skrive noen tester / logge bedre hvis det feiler når oppgave er av

EY-2491 Setter saksbehandler på oppgave hvis skrudd av

---

apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/RedigerSaksbehandler.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/FristHandlinger.tsx

- Flytter frist kolonnen
- Bytter knappetype for endre frist
- Legger til mellomrom i frist og saksbehandler cellen
- Fikser en mindre feil ved sjekk om frist er passert. Antar frist kan passeres i inneværende år.

Mindre endringer på frist og saksbehandler i ny oppgaveliste

---

apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/GosysOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/HandlingerForOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelistafiltre.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Tags.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaverny.ts

Setter opp Gosys som oppgavetype og lager modal for visning av informasjon om oppgaven.

EY-2494 Opprett modal for visning av gosys informasjon

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkorting.tsx

- Fjerne tekst om uføretrygd
- Sortere tabeller nyligst først og bakover i tid
- Vise kun siste angitte inntekt og vise historikk med en toggle for tabell grunnlag

EY-2462 små utbedringer inntektsavkorting

---

apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/ToggleMinOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/MinOppgaveliste.tsx

Endre kolonnerekkefølge og vis antall oppgaver ved pagination

---

apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/RedigerSaksbehandler.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/FristHandlinger.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/MinOppgaveliste.tsx

- Setter hele frist som knapp hvis den kan endres
- Setter hele saksbehandler som knapp hvis den kan endres

Sett hele frist/saksbehandler som knapp i oppgavelista

---

apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/FristHandlinger.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/MinOppgaveliste.tsx

- Bytter ut monthpicker med datepicker
- Viser ny frist i tabellen
- Viser lukk istedenfor avbryt hvis frist er blitt endret

Bytt til å bruke datepicker og vis ny dato i tabellen

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakRoutesTest.kt

For bruk på saksoversikt-siden

EY-2380 Legger til endepunkt for å hente oppgaver for bruker

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt

Før så ble det bare sjekket, så vi fikk ikke gjort ferdig oppgaven, og heller ikke oppdatert statusen til behandlingen.

EY-2509 Tar å faktisk attesterer vedtak mot behandling

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
apps/etterlatte-statistikk/build.gradle.kts
apps/etterlatte-statistikk/src/main/kotlin/statistikk/clients/BeregningKlient.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/database/SakRepository.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/database/StoenadRepository.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/Beregning.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/MaanedStatistikk.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/Sak.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/StoenadRad.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
apps/etterlatte-statistikk/src/main/resources/db/migration/V21__add_avkorting_to_stoenad_and_sak.sql
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/SakRepositoryTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/StoenadRepositoryTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/domain/MaanedStatistikkTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/river/VedtakhendelserRiverTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/service/StatistikkServiceTest.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt

- Lagt til avkorting for stønad
- Lagt til avkorting for sak
- Lagt til avkortingsbeløp og årsinntekt (avkortingsgrunnlag) for månedsstatistikk
- Tatt i bruk kotest for unittester

EY-2505 Statistikk for Omstillingsstønad

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Trygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/YrkesskadeTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/api/vilkaarsvurdering.ts

Hjemmel er nok riktig - men tekst må sjekkes av fag.

EY-2369 Yrkesskade trygdetid - frontend

---

apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/HandlingerForOppgave.tsx

Skal være "Gå til behandling", samme som for førstegangsbehandling

EY-2521: Viser handling for underkjente oppgaver også

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlagListe.tsx

Et par liten oppfølgingsendringer
* Gjør display i liste samme som skjema ("Ikke med i prorata")
* Default prorata skal være true

EY-2440 - heading og default verdi

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V50__rydder_opp_feil_i_oppgaver.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgaveny/OppgaveServiceNyTest.kt

Rydder også opp litt rot knyttet til oppgaver i databasen

EY-2525 Avbryter oppgaver under arbeid knyttet  til behandlinger vi avbryter

---

apps/etterlatte-saksbehandling-ui/client/vite.config.ts

Trengs for modal visning av gosys-oppgaver

Lagt til gosys-url i vite

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkortingDetaljer.tsx

- Fikse tallformatering i avkortingdetaljer
- Fikse bugs med inntektsavkortingform etter endret rekkefølge på liste

EY-2523 - Avkorting fikse småfeil

---

apps/etterlatte-behandling/.nais/prod.yaml

Må også skru på toggle'en pensjon-etterlatte.vis-ny-oppgaveliste for prod

Skrur på ny oppgaveliste i prod

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/YrkesskadeTrygdetidBP.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/YrkesskadeTrygdetidOMS.tsx

Håndterer full trygdetid ved YS for OMS

EY-2516-fyll trygdetid ved YS

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadSammendrag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadToolTip.tsx

- Slår sammen kolonne årsinntekt og fratrekk inn år til forventet inntekt i periode med tooltip
- Legger til kolonne for gjenværende måneder
- Oppdatert beskrivelse

EY-2462 Oppdatere inntektsavkorting frontend

---

apps/etterlatte-testdata/src/main/kotlin/Application.kt
apps/etterlatte-testdata/src/main/kotlin/dolly/DollyClient.kt
apps/etterlatte-testdata/src/main/kotlin/dolly/Model.kt

https://dolly-backend.intern.dev.nav.no/swagger-ui/index.html#/bruker-controller/getAllBrukere

Fiks response dolly camelåså

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/GosysOppgaveKlient.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/GosysOppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/GosysOppgaveServiceImplTest.kt

Kodeverk er in-flight EY-2443, har testet med det i Q2. Oppgave-api bruken er uansett featuretogglet (avskrudd i prod)

EY-2379 Benytte faktiske EY*-tema i oppgave-api

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
libs/saksbehandling-common/src/main/kotlin/behandling/RevurderingAarsak.kt

Legger også på en advarsel om å ikke opphøre hvis det medfører tilbakekreving.

Skrur på opphør søkers dødsfall i produksjon

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseJob.kt
apps/etterlatte-beregning/src/main/kotlin/Application.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-grunnlag/src/main/kotlin/Application.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/Application.kt
apps/etterlatte-pdltjenester/src/main/kotlin/Application.kt
apps/etterlatte-statistikk/src/main/kotlin/Application.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/jobs/MaanedligStatistikkJob.kt
apps/etterlatte-trygdetid/src/main/kotlin/Application.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/GrensesnittsavstemmingJob.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingJob.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/config/ApplicationBuilder.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/Application.kt
libs/etterlatte-jobs/src/main/kotlin/jobs/TimerUtils.kt
libs/saksbehandling-common/src/main/kotlin/logging/LogUtils.kt

Ikkje 100%, men eit skritt eller to i rett retning.

EY-2538: Betre stopping av jobbar når applikasjonen stoppar

---

apps/etterlatte-migrering/.nais/dev.yaml
apps/etterlatte-migrering/src/main/kotlin/migrering/Application.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/ApplicationContext.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/ApplicationProperties.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/MigrerSpesifikkSak.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/Migrering.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/Sakmigrerer.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/pen/PenKlient.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/pen/PenModell.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/pen/PenModellTilVaarModell.kt
apps/etterlatte-migrering/src/main/resources/application.conf
apps/etterlatte-migrering/src/test/kotlin/migrering/MigreringIntegrationTest.kt
apps/etterlatte-migrering/src/test/resources/penrespons.json
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/Migreringshendelser.kt

Testa mot PEN i Q2 med sakene frå Andreas i PEN-teamet på Slack.

EY-2558: Hent sak frå PEN

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnvilgetBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/Slate.kt
apps/etterlatte-brev-api/src/main/resources/db/migration/V7__payload_vedlegg.sql
apps/etterlatte-brev-api/src/main/resources/maler/vedlegg/oms_foerstegangsvedtak_innvilgelse.json
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevRouteTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/db/BrevRepositoryIntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/RedigerbartBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/SlateEditor.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts

- Lar saksbehandler redigere deler av 1 til flere vedlegg
- Får kun opp rediger vedlegg hvis det er et vedlegg å redigere
Er avhengig av https://github.com/navikt/pensjonsbrev/pull/225

Lar saksbehandler redigere tekst i vedlegg

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagRepository.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRepositoryIntegrationTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt

https://logs.adeo.no/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(message,envclass,level,application,host,x_correlation_id),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,field:namespace,index:'96e648c0-980a-11e9-830a-e17bbd64b4db',key:namespace,negate:!f,params:(query:etterlatte),type:phrase),query:(match_phrase:(namespace:etterlatte))),('$state':(store:appState),meta:(alias:!n,disabled:!f,field:envclass,index:'96e648c0-980a-11e9-830a-e17bbd64b4db',key:envclass,negate:!f,params:(query:q),type:phrase),query:(match_phrase:(envclass:q))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96e648c0-980a-11e9-830a-e17bbd64b4db',key:x_correlation_id,negate:!f,params:(query:'5d0ea6fd-41f9-43f9-ba9b-e7854e3e6 …

Fikse opphør tryner for oms

---

apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveRoutesNy.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/attestering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/beslutningsvalg.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaverny.ts
libs/etterlatte-ktor/src/main/kotlin/RouteUtils.kt

Hent oppgave for å avgjøre om man kan fatte/attester/ underkjenne hvis oppgaven er under behandling og innlogget bruker er den samme som står på den oppgaven.
* nitpick fix routes for gosys + param.

EY-2596 Beskrivende feilmelding vedtak hvis ikke oppgave ikke stemmer

---

apps/etterlatte-samordning-vedtak/README.md
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt

EY-2529 Noen oppdateringer på grensesnitt

---

apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/MigreringHendelser.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/VedtakService.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/OpprettVedtakforespoersel.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/MigreringHendelserTest.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/regulering/OpprettVedtakforespoerselTest.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/AutomatiskBehandlingRoutes.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/config/ApplicationBuilder.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/migrering/AutomatiskBehandlingRoutesKtTest.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/EventNames.kt

Gjer det no likt som migrering med at vi opprettar, fattar og attesterer vedtak i eitt kall.

EY-2619: Tilpasse flyten også for regulering

---

apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/HandlingerForOppgave.tsx

Funksjonalitet ble fjernet ifm. implementasjon av oppgavebenken. Legger det tilbake.

Gjøre det mulig å åpne behandling/oppgave i ny fane

---

apps/etterlatte-saksbehandling-ui/server/src/index.ts

Manglet en redirect til klageroutes 😅

Ruter klage til behandling-appen

---

apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt

Fix for feil med ikke eksisterende "forrige grunnlag"

Fix for feil i beregningsgrunnlag

---

apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/FilterRad.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelistafiltre.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Tags.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/OpprettKlage.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaverny.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/hooks/useFeatureToggle.ts

Fjerner klage fra filter-menyen hvis det ikke er togglet på :D

Typer for klage-oppgaver i frontend

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRegelkjoring.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/InntektAvkorting.kt
apps/etterlatte-beregning/src/main/resources/db/migration/V24__inntektavkorting_utland.sql
apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/regler/InntektAvkortingTest.kt
apps/etterlatte-beregning/src/test/kotlin/ytelseMedGrunnlag/YtelseMedGrunnlagServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkorting.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts
libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt

- Nye felter backend for inntekt utland inntektsavkorting
- Innekt utland for inntektsavkorting frontend

Ey 2654 inntekt utland inntektsavkorting

---

apps/etterlatte-grunnlag/.nais/dev.yaml
apps/etterlatte-grunnlag/.nais/prod.yaml
apps/etterlatte-grunnlag/.run/etterlatte-grunnlag.dev-gcp.run.xml
apps/etterlatte-grunnlag/src/main/kotlin/Application.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagRoutes.kt
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagRoutesKtTest.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/grunnlag/NyeSaksopplysninger.kt

Prøver å stykke opp generisk behandling i mindre deler

EY-2531 Støtte synkron lagring av nye saksopplysninger

---

apps/etterlatte-brev-api/docker-compose.yml
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/DokumentRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/journalpost/Journalpost.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokument/DokumentRouteTest.kt

Deler opp mega-branch i mindre biter. Dette blir koblet på i en annen branch.

EY-2531 Endepunkt for å ferdigstille journalpost

---

apps/etterlatte-egne-ansatte-lytter/build.gradle.kts
apps/etterlatte-egne-ansatte-lytter/src/main/kotlin/Application.kt
apps/etterlatte-egne-ansatte-lytter/src/main/kotlin/kafka/KafkaConsumerEgneAnsatte.kt
apps/etterlatte-egne-ansatte-lytter/src/test/kotlin/SkjermingslesingTest.kt
apps/etterlatte-hendelser-pdl/src/main/kotlin/Application.kt
apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/common/KafkaKonsument.kt
apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/common/PersonhendelseKonsument.kt
apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/config/ApplicationContext.kt
apps/etterlatte-hendelser-pdl/src/test/kotlin/hendelserpdl/IntegrationTest.kt
apps/etterlatte-institusjonsopphold/build.gradle.kts
apps/etterlatte-institusjonsopphold/src/main/kotlin/Application.kt
apps/etterlatte-institusjonsopphold/src/main/kotlin/kafka/KafkaConsumerInstitusjonsopphold.kt
libs/etterlatte-kafka/src/main/kotlin/kafka/Kafkakonsument.kt

Ser ingen grunn til at det skal vera veldig forskjellig.
Med denne endringa prøver eg å gjera det enkelt å i neste steg lage ein ny kafka-lyttar, som er den funksjonelle endringa vi treng for å lytte på kabal.

EY-2594: Samkøyre korleis vi gjer kafkakonsumering, del 1

---

apps/etterlatte-samordning-vedtak/README.md
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt

Som det er et klart behov for, jfr forespørsel og diskusjon

EY-2529 Lagt til endepunkt for oppslag ikke trigget av køhendelse

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/RevurderingAnnen.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx

- Legger på felt for begrunnelse for hvorfor annen revurdering er valgt
- Gjør også årsak redigerbar i revurderingsoversikt

EY-2656 Legger på begrunnelsefelt for annen revurdering

---

apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
apps/etterlatte-vedtaksvurdering/.nais/prod.yaml

Tar dette i forkant slik at jeg kan jobbe videre med sikkerhetsconfig i `samordning-vedtak`

EY-2414 Tillate inbound fra samordning-vedtak gitt riktig rolle

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageDaoImplTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/klage/formkrav/KlageFormkrav.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/klage.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/api/vedtaksvurdering.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Klage.ts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt
libs/etterlatte-behandling-model/src/test/kotlin/no/nav/etterlatte/libs/common/behandling/KlageTest.kt

EY-2590 Vurdering av formkrav til en klage

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/config/ApplicationBuilder.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/TestHelper.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingRouteTest.kt

trenger oppslag på både 
- vedtakId
- kombo fnr + fomdato

EY-2414 Nye vedtakstjenester for samordning

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnOmstillingsstoenadService.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnBarnepensjonServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnOmstillingsstoenadServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidBeregnet.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
apps/etterlatte-trygdetid-kafka/src/test/kotlin/MigreringHendelserTest.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidBeregningService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/regler/BeregnTrygdetid.kt
apps/etterlatte-trygdetid/src/main/resources/db/migration/V12__detaljert_trygdetid.sql
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidBeregningServiceTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/regler/BeregnTrygdetidTest.kt
libs/etterlatte-trygdetid-model/src/main/kotlin/Trygdetid.kt

To tester er kommentert vekk - men er lenket til et nytt jira. Vi ønsker å få dette synlig i test for å lette fagdiskusjoner.
Har oppdatert feature toggle (bruk faktisk trygdetid) for å sperre alt av dette fra produksjon.

EY-2121 - trygdetid utlandet

---

apps/etterlatte-migrering/build.gradle.kts
apps/etterlatte-migrering/src/main/kotlin/migrering/LyttPaaIverksattVedtak.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/pen/PenKlient.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/LyttPaaIverksattVedtakTest.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/MigreringIntegrationTest.kt
libs/etterlatte-database/build.gradle.kts
libs/etterlatte-database/src/testFixtures/kotlin/no/nav/etterlatte/InMemoryDatabase.kt

[PEN-endepunktet](https://github.com/navikt/pesys/blob/8af8f42fc31731992e725bcc2b44a31949826658/pen-app/src/main/java/no/nav/pensjon/pen_app/domain/barnepensjon/migrering/BarnepensjonMigreringController.kt)

EY-2615: Opphøre sak i PEN

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt

Oppdaget under utv av uthentingstjenesten til samordning

Korrigert uthenting av avkorting til lagring i vedtaksvurderingen

---

.github/workflows/app-etterlatte-samordning-vedtak.yaml
apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/prod.yaml
apps/etterlatte-samordning-vedtak/.run/etterlatte-samordning-vedtak.dev-gcp.run.xml
apps/etterlatte-samordning-vedtak/build.gradle.kts
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/Application.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/ApplicationContext.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakService.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/VedtaksvurderingKlient.kt
apps/etterlatte-samordning-vedtak/src/main/resources/application.conf
apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRouteTest.kt

Noen todos her, pga et par felter ikke er helt landet ennå - må nok ha info fra avkorting her mtp brutto/netto (se bugfix #2163 ✅ ). Men integrasjon/sikkerhet er med dette (og #2160) på plass

EY-2414 Hente data fra vedtaksvurdering fra samordning-vedtak

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/SamordningsvedtakRouteTest.kt
libs/etterlatte-ktor/src/main/kotlin/AuthorizationPlugin.kt

Kan nok fremstå som litt overflødig, enn så lenge appen har masser av APIer hvor det ikke er angitt at noe spesiell rolle trengs - men det burde antageligvis rettes på.... 😬

EY-2414 Verifisere rolle i token (samordning)

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx

- Ikke implementert i første runde pga uklarhet om hva som faktisk skulle/skal være her
- endring av beskrivelse jfr QA EY-2372

EY-2372 Lenke til Gosys for oppgave til lokalkontor

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/AnnullerBehanding.tsx

EY-2690 Tydeligere skille på avbryt og annuller behandling

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/RedigerbartBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/hooks/useApiCall.ts

EY-2674: La saksbehandler hente ut data til brevet på nytt

---

apps/etterlatte-behandling/src/main/kotlin/Contekst.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt
apps/etterlatte-testdata/src/main/kotlin/Application.kt
libs/etterlatte-ktor/src/main/kotlin/AuthorizationPlugin.kt
libs/etterlatte-ktor/src/main/kotlin/JWTTokenClaimsUtils.kt
libs/etterlatte-ktor/src/main/kotlin/RouteUtils.kt
libs/etterlatte-ktor/src/main/kotlin/TokenUtils.kt

Ikkje perfekt, men kjens som eit steg i rett retning.

JWTTokenClaims-uthenting samla

---

apps/etterlatte-behandling/build.gradle.kts
apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
apps/etterlatte-tilbakekreving/.nais/dev.yaml
apps/etterlatte-tilbakekreving/.run/etterlatte-tilbakekreving.dev-gcp.run.xml
apps/etterlatte-tilbakekreving/build.gradle.kts
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/config/ApplicationContext.kt
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/config/ApplicationProperties.kt
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/klienter/BehandlingKlient.kt
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagMapper.kt
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagService.kt
libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt
libs/etterlatte-oppgave-model/src/main/kotlin/OppgaveNy/OppgaveNy.kt
libs/etterlatte-tilbakekreving-model/build.gradle.kts
libs/etterlatte-tilbakekreving-model/src/main/kotlin/Kravgrunnlag.kt
settings.gradle.kts

- Endepunkt for å opprette behandling tilbakekreving i behandlingsapp
- Service som per nå kun oppretter oppgave
- Behandlingsklient i tilbakekrevingsapp som kaller nytt endepunkt
- Dratt domeneklasser for kravgrunnlag ut i ny lib for tilbakekreving

EY-2661 - Opprette behandling for tilbakekreving

---

apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveRoutesNy.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
apps/etterlatte-behandling/src/test/kotlin/VerdikjedeTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgaveny/OppgaveServiceNyTest.kt
libs/etterlatte-oppgave-model/src/main/kotlin/OppgaveNy/OppgaveNy.kt

+ Litt forbedringer av testene for oppgaveserviceNy

EY-2692 Riktig rolle kan tildele seg attesterings oppgave

---

apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelser.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidBeregningService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/regler/BeregnTrygdetid.kt
apps/etterlatte-trygdetid/src/main/resources/db/migration/V13__legg_til_overstyrt_flagg_for_detaljert_trygdetid.sql
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/regler/BeregnTrygdetidTest.kt
libs/etterlatte-trygdetid-model/src/main/kotlin/Trygdetid.kt

Setter også en flagg om at det er overstyrt slik at vi kan nevne det i frontend.

EY-2868 migrering må kunne overstyre beregnet trygdetid

---

apps/etterlatte-saksbehandling-ui/client/src/App.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/Tilbakekrevingsbehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/brev/TilbakekrevingBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oversikt/TilbakekrevingOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/sidemeny/TilbakekrevingSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/stegmeny/TilbakekrevingNavLenke.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/stegmeny/TilbakekrevingStegmeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/useTilbakekreving.ts
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vedtak/TilbakekrevingVedtak.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/api/tilbakekreving.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Tilbakekreving.ts
apps/etterlatte-saksbehandling-ui/client/src/store/Store.tsx
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/TilbakekrevingReducer.ts

- Setter opp enkel flyt som det kan jobbes videre utifra (basert på tilsvarende i klage)
- Legger inn noen mockede data inntil videre

EY-2683 Setter opp steg for tilbakekreving frontend

---

apps/etterlatte-behandling/src/main/kotlin/common/klienter/SkjermingKlient.kt
apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/BeregningService.kt
apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/OmregningHendelser.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/OmregningsHendelserTest.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/MigreringHendelser.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/FeilendeMigreringLytter.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/LagreKopling.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/FeilendeMigreringLytterTest.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/MigreringIntegrationTest.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/MigrerEnEnkeltSak.kt
libs/etterlatte-jobs/src/main/kotlin/jobs/LeaderElection.kt
libs/etterlatte-jobs/src/test/kotlin/jobs/LeaderElectionTest.kt
libs/etterlatte-regler/src/main/kotlin/regler/RegelDsl.kt
libs/etterlatte-regler/src/main/kotlin/regler/Regler.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/PesysKeys.kt

Ubrukte variablar, input-parameter til LeaderElection som kan misbrukast, metodenamn som er forskjellige kun i casing, extends final class

EY-2537: Ryddar unna ein del av det CodeQL klagar på

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BrevApiKlient.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/resources/application.conf
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageDaoImplTest.kt
apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/prod.yaml
apps/etterlatte-hendelser-pdl/src/test/kotlin/hendelserpdl/IntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/klage/Klagebehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/brev/KlageBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/stegmeny/KlageNavLenke.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/stegmeny/KlageStegmeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/sidemeny/TilbakekrevingSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Brev.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Klage.ts
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt

som kan manuelt fylles ut. Det er litt barebones designmessig og mangler litt oppkobling mot riktig mal etc., men det kan komme senere.

EY-2672 Oppretter innstillingsbrev til kabal

---

apps/etterlatte-behandling/src/main/kotlin/behandling/hendelse/HendelseDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/Tilbakekreving.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V59__tabell_for_tilbakekreving.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingDaoTest.kt
apps/etterlatte-tilbakekreving/.run/etterlatte-tilbakekreving.dev-gcp.run.xml
apps/etterlatte-tilbakekreving/src/main/kotlin/Application.kt
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/config/ApplicationContext.kt
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/config/ApplicationProperties.kt
libs/etterlatte-ktor/src/main/kotlin/RouteUtils.kt

- Ny tabell og dao
- Opprettelse av tilbakekreving med behandlingshendelser
- Erstattet mock i get endepunkt med persistert tilbakekreving
- Trukket ut port for tilbakekrevingsapp i property for lokal kjøring

Ey 2661 persistere behandling for tilbakekreving

---

apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelser.kt
apps/etterlatte-trygdetid-kafka/src/main/kotlin/TrygdetidService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt

Trenger flere felter for utland osv - dette tas under EY-2602

EY-2686 - overstyr trygdetid ved feil

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt

https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-002826?id=22Ziy4oBnML16sgHTq25

Gjenbruk transaction

---

apps/etterlatte-behandling/src/main/kotlin/common/DatabaseContext.kt

Reverts navikt/pensjon-etterlatte-saksbehandling#2230
Er bare ekstra spam

Revert "Logg db rollback as error"

---

apps/etterlatte-migrering/src/main/kotlin/migrering/FeilendeMigreringLytter.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/FeilendeMigreringLytterTest.kt
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagConsumer.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/avstemmingsdata/AvstemmingsdataSender.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/StandardKeys.kt
libs/saksbehandling-common/src/main/kotlin/tidspunkt/Tidspunkt.kt

Tar unna alle desse, med unntak av LeaderElection: https://github.com/navikt/pensjon-etterlatte-saksbehandling/security/code-scanning?query=is%3Aopen+branch%3Amain+language%3Akotlin

Rettar ein del feil CodeQL har oppdaga

---

apps/etterlatte-testdata/src/main/kotlin/testdata/features/dolly/BestillingUtil.kt

Vi har ikke noen identer av type igjen

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingVedtakRoute.kt

Hvem som har fattet vedtak i merknad for attesteringsoppgaven, slik at man kan se hvilke oppgaver man _ikke_ kan ta (sine egne)

Hvem har fattet vedtak i merknad

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt

https://logs.adeo.no/app/discover#/?_g=(time:(from:now-24h%2Fh,to:now))&_a=(query:(language:lucene,query:'x_correlation_id:3fcfb09d-c458-4eef-bc3f-8041f3947706'))

Fikser feil med nøstede transaksjoner ifbm klage

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnvilgetBrevData.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/adresse/AdresseServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/BehandlingTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingServiceTest.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Etterbetaling.kt
libs/etterlatte-behandling-model/src/test/kotlin/no/nav/etterlatte/libs/common/behandling/EtterbetalingTest.kt

Obs: biten om etterbetaling skal få ein runde til.

EY-2646: Oppdatert innvilgelsesbrev

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/vilkaar/OmstillingstoenadVilkaar.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt

EY-2372 Lagt vilkår om aktivitet etter 6 mnd tilbake

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkorting.tsx

- Inputfelter som er obligatorisk backend valideres i frontend
- Formatering av måneder vis første og siste dag i måned

EY-2737 - Feilfikser avkorting

---

apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakService.kt
apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakServiceTest.kt

Tenker dette er det siste som implementeres av mapping inntil videre.

EY-2414 samordning, tentativ mapping av årsak

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/sendTilAttesteringModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/vilkaarsvurderingKnapper.tsx

https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-002830?id=VkgU1ooBxUCXV6sgXD7m

Oppdater eller opprett vedtak før brev ved vilkårsvurdering avslag

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/statistikk/StatistikkRoute.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettVedtaksbrevForMigrering.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/VedtaksbrevUnderkjent.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettVedtaksbrevForMigreringTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/VedtaksbrevUnderkjentTest.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/clients/BehandlingKlient.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/VedtakhendelserRiver.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/SakRepositoryTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/service/StatistikkServiceTest.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/VedtakMottaker.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/VedtakHelper.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
libs/etterlatte-vedtaksvurdering-model/src/main/kotlin/VedtakKafkaHendelseType.kt

Måtte gi opp drømmen om data i kafkamelding da det ville krevd ekstra av vedtak som er dumt evt egen kafka app for behandling som er for mye overhead imo, og siden statistikk allerede har klienten gikk jeg for det...

Kun bruke statistikkbehandling

---

libs/saksbehandling-common/src/main/kotlin/behandling/RevurderingAarsak.kt

Liten endring for å kunne teste og rulle ut revurdering for yrkesskade og institusjonsopphold for OMS

Forberede utrulling av revurdering for yrk og Inst for oms

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/vilkaar/OmstillingstoenadVilkaar.kt

Etter tilbakemeldinger fra jurister

EY-2620 Oppdaterer vilkåret for forutgående medlemskap

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/vilkaar/OmstillingstoenadVilkaar.kt

Basert på tilbakemeldinger fra jurister.
Merge https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/2274 først og rebase slik at db-scriptene blir i riktig rekkefølge.

EY-2621 Oppdaterer tekst i Øvrige vilkåar for ytelse

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/ManueltVilkaar.tsx

Benytt korrekt symbol for å sjekke paragraf type.

---

apps/etterlatte-saksbehandling-ui/server/src/routers/loggerRouter.ts

Se https://logs.adeo.no/app/discover#/doc/c9e3a6ff-cb62-43ce-b6a8-50162229a607/logstash-apps-test-002833?id=TUvC24oBxUCXV6sg9_LJ
Implementert lik validering som i https://github.com/mozilla/source-map

Håndter dårlig lineno column som gir dårlig feil

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnvilgetBrevData.kt

Sjå også på https://github.com/navikt/pensjonsbrev/pull/258

EY-2646: Rettar parameternamn mot brevbakeren

---

apps/etterlatte-saksbehandling-ui/client/src/App.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidVisning.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/FilterRad.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/GosysOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/OpprettKlage.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/SakOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/hooks/useFeatureToggle.ts

Betyr at frontend ikke går ned hvis toggle ikke finnes, den får bare defaultverdien. La ikke på noe ekstra logging her siden det vil være ganske spammy og vi ser det allerede i frackend

Feature-toggles med default-verdier

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingVedtakRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt
apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Etterbetaling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/generellbehandling/Utland.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/kontroll/KontrollerOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/DatoVelger.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/generellbehandling.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Generellbehandling.ts
apps/etterlatte-saksbehandling-ui/docker-compose.yml
apps/etterlatte-saksbehandling-ui/server/src/config/config.ts
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/generellbehandling/GenerellBehandling.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/generellbehandling/Innhold.kt

+ litt validering for send til attesteringsflyt og tester

Rina lenker,  dato for dokumenter og validering for sendtilattestering

---

apps/etterlatte-saksbehandling-ui/server/src/routers/loggerRouter.ts

Passar godt med at vi i resten av denne metoden bruker JSON.stringify mykje.
Løyser https://github.com/navikt/pensjon-etterlatte-saksbehandling/security/code-scanning/88

Bruker JSON.stringify også mot loginjection-risiko. 

---

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/sendTilAttesteringModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/Tilbakekrevingsbehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/brev/TilbakekrevingBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/stegmeny/TilbakekrevingNavLenke.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/stegmeny/TilbakekrevingStegmeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vedtak/TilbakerevingsOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/tilbakekreving.ts

- Nytt endepunkt og request i frontend
- Tilpasser sendTilAttesteringModal til å håndtere ulike behandlinger
- Endret navn på steg og div rydding

EY-2767 - Nytt endepunkt for å fatte vedtak tilbakekreving

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etterbetaling/EtterbetalingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/Tilbakekreving.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakDao.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoIntegrationTest.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnOmstillingsstoenadService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/AppBuilder.kt

motivasjon https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-002842?id=B2c89YoBxUCXV6sgLV-9

Forbedre feilmeldinger og extension function for brevid id

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/GrunnlagKlient.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/klienter/GrunnlagKlient.kt
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/klienter/GrunnlagKlientOboTest.kt
apps/etterlatte-beregning/src/main/kotlin/klienter/GrunnlagKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/grunnlag/GrunnlagKlient.kt
apps/etterlatte-grunnlag/src/main/kotlin/Application.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagRoutes.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/PersonRoutes.kt
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagRoutesKtTest.kt
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagServiceTest.kt
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/PersonRoutesTest.kt
apps/etterlatte-saksbehandling-ui/client/src/shared/api/grunnlag.ts
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/GrunnlagKlient.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/klienter/GrunnlagKlient.kt

Litt forarbeid for versjonering av grunnlag. 
- Dele grunnlag i `grunnlag/person` og `grunnlag/sak`. 
- Prefix `/grunnlag/sak/` på alt grunnlag tilknyttet sak. 
- Flytte `oppdater-grunnlag` fra person til sak.

EY-2567 Oppdeling av routes i grunnlag

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etterbetaling/EtterbetalingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etterbetaling/EtterbetalingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etterbetaling/EtterbetalingService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/etterbetaling/EtterbetalingTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Etterbetaling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/MaanedVelger.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Etterbetaling.kt

- Det er månad som er relevant her, ikkje akkurat dagen i månaden
- Validerer at det ikkje er før virkningsdato, etter dagens dato og den slags

EY-2646: Rettar feil og manglar ved etterbetalingsregistreringa

---

apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelser.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelserTest.kt
apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelser.kt

Vi må verifisere at en beregnet ytelse i Gjenny etter nytt regelverk er bedre enn beregningen på gammelt regelverk.
Legger samtidig på noen sjekker på at vi har benyttet samme grunnlag som Pesys i beregningen.
EY-2838

Lønnsomhetsvurdering ved migrering av saker.

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BehandlingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/VilkaarsvurderingKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/AvslagBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EndringBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnvilgetBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/OpphoerBrevData.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BehandlingServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Resultat.tsx

Gjør utbetalingsinfo optional hvis vilkårsvurdering er ikke oppfylt

---

apps/etterlatte-pdltjenester/.nais/dev.yaml
apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt
apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonService.kt

Feilet på feil nivå i uthentingen

Fikse mapping historisk foreldreansvar

---

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/Tilbakekreving.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingDao.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V67__tilbakekreving_vurdering_flere_felter.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingDaoTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingOverordnet.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Tilbakekreving.ts

- Nytt felt for hjemmel
- Nye felter for vurdering av aktsomhet - strafferettsligVurdering, reduseringAvKrav, rentevurdering

EY-2769 - Nye felter vurdering tilbakekreving

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BrevApiKlient.kt
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt
libs/saksbehandling-common/src/main/kotlin/brev/BrevDto.kt

Som vi kan mappe i downstreamresourceclient

Brev-api returnerer meningsfulle objekter

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt

Nyttar høvet til å flytte heile inTransaction-en til route-kallet

EY-2786: Må køyre også hent-kallet for avbryt i ein transaksjon

---

apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/migrering/MigreringRoutesTest.kt

... og ikke utifra vedtaket i Pesys.
EY-2894

Vi må sette virkningstidspunktet til å matche reformtidspunktet

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRequestLogger.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/egenansatt/EgenAnsattRoute.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakRoutesTest.kt

https://sikkerhet.nav.no/docs/sikker-utvikling/auditlogging seier at 
> Hva er auditlogg?
En logg over brukere av NAV IT systemer (primært ansatte) sine handlinger på borgers informasjon og annen viktig informasjon. Handlinger er primært å se på informasjon. All visning av informasjon skal logges, i tillegg til endringer av informasjon.
Formål: Auditloggene skal kunne bevise, eller motbevise, om de ansatte har misbrukt sine tilganger. ( Dette betyr i praksis at vi ikke har behov for system\service brukere )
[...]
> Det er primært handlingene som bruker utfører i GUI som er loggverdig. Søk opp en person er loggverdig, ikke de titalls tjenestekallene som er nødvendig for å svare på handlingen. Logger fra system og\eller service brukere er derfor ikke nødvendig da disse ikke kan spores …

EY-2825: Sporingslogging litt fleire stadar

---

apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/prod.yaml

d'oh!
```
[  2878.200189s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connect timed out after 1s client.addr=10.6.82.56:51882`
```

EY-2616 Lagt til manglende egress for TP

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakTilgangDao.kt
apps/etterlatte-behandling/src/main/kotlin/sak/TilgangService.kt
apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V69__tilgangstyring_basert_paa_view_med_flere_behandlingstyper.sql
apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/TilgangServiceTest.kt
libs/etterlatte-ktor/src/main/kotlin/RouteUtils.kt

- Nytt view og endre tilgangstyring på behandling til å bruke det
- Fjernet egen tilgangstyring på tilbakekrevingstabell

EY-2767 - View for å samle ulike varianter av behandling for å tilgangstyre felles

---

apps/etterlatte-behandling/src/main/kotlin/metrics/OppgaveMetrics.kt

Metrikkene pushet ~17k logmeldinger i døgnet.

Fjerne logspam fra gauge metrikker

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/config/ApplicationBuilder.kt

Jobben startet ~30 sek for tidlig. Legger til 60 sek ekstra venting.

Oppstart av rapid tar lengre tid i prod :(

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/InnvilgetBrevDataBP.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/InntektsendringRevurderingOMS.kt

Det er ikkje gitt at vi har etterbetaling eller (for BP) avkorting

Nokre av sjekkane er i overkant kritiske på nullsjekkinga

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/utils.ts

Endre valg i vilkårsvurdering fra "Ikke vurdert" til "Ikke aktuelt"

---

apps/etterlatte-samordning-vedtak/.nais/prod.yaml
apps/etterlatte-samordning-vedtak/README.md

Ingress basert på https://doc.nais.io/clusters/gcp/

Eksponere samordning-vedtak i prod

---

apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/prod.yaml
apps/etterlatte-trygdetid/build.gradle.kts
apps/etterlatte-trygdetid/src/main/kotlin/Application.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/PatchIdentAlleTrygdetider.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/config/ApplicationContext.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/config/ApplicationProperties.kt

Gjøres av en enkel jobb som spør grunnlag på behandlingen hva identen til avdød er

Patcher alle trygdetider med ident

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/VedtaksvurderingKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/OpphoerBrevData.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt

Dette åpner opp for å hente vedtak som ikke er "vanlig" behandling

EY-2806 - Ta i bruk ny dto for vedtak i brev api

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevProsessTypeFactory.kt
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/brev/TilbakekrevingBrev.tsx

Vedtakstype tilbakekreving opprettes brev med tom mal.
Brevkode for tilbakekreving og innhold kommer senere.

EY-2806 - Tomt brev tilbakekreving

---

apps/etterlatte-trygdetid/.run/etterlatte-trygdetid.dev-gcp.run.xml
apps/etterlatte-trygdetid/src/main/kotlin/Application.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/NyTrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
libs/etterlatte-trygdetid-model/src/main/kotlin/Trygdetid.kt

Gjør det mulig å hente og endre trygdetid riktig når vi har flere per behandling

Trygdetidroutes for nytt api

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRepository.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutes.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingRepositoryTest.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt

- Legger til støtte for å kunne slette eksisterende vilkårsvurdering
- Legger til støtte for å kunne opprette ny vilkårvurdering når man revurderer uten å kopiere fra forrige.
EY-2826

Legger til støtte i backend for å støtte nye vilkår

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/VedtakKlientImpl.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/brev/TilbakekrevingBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/tilbakekreving.ts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakTilbakekrevingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/TestHelper.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtakTilbakekrevingServiceTest.kt
libs/etterlatte-vedtaksvurdering-model/src/main/kotlin/VedtakDto.kt

- Nytt steg i behandling og vedtak for å opprette vedtak tilbakekreving før det fattes
- Vedtak sjekker at status er riktig før den gjøre ulike operasjoner

EY-2806 - oppretter vedtak uten å fatte i eget steg for å kunne bruke det til brevvisning

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx

Forenkler og restrukturerer noe av oppsettet for å unngå duplisering

EY-2951 Forenkler og fjerner dupliserte routes

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/VedtakKlientImpl.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/Tilbakekreving.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingDaoTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/attesterTilbakekreving.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/underkjennTilbakekreving.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/Tilbakekrevingsbehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/brev/TilbakekrevingBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/useTilbakekreving.ts
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingOverordnet.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingPerioder.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/tilbakekreving.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Tilbakekreving.ts
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/TilbakekrevingReducer.ts
libs/etterlatte-tilbakekreving-model/src/main/kotlin/Tilbakekreving.kt

- Tilbakekreving behandling renames til TilbakekrevingBehandling
- Ny klasse for alt tilbakekreving "innhold"

EY-2806 - Omstrukturere tilbakekreving backend

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRepository.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingRepositoryTest.kt

Sletting cascader ikke her som i de andre tabellene.
EY-2826

Slett innslag i vilkaarsvurdering_kilde for kopierte vilkårsvurderinger

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/OverstyrtTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidVisning.tsx

* Fiks tekst (med sjekk på virk)
* Fiks at man ikke kan fjerne når det først er utfylt

EY-2912 fiks poengår tekst

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/SakOversikt.tsx

Det er kun Barnepensjon som skal være mulig å annulere og sende til Pesys. Omstillingsstønad har ikke den muligheten.

EY-2746 Fjerner knapp annulering av omstillingsstønad-sak

---

apps/etterlatte-behandling/src/main/kotlin/behandling/sjekkliste/Sjekkliste.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/sjekkliste/SjekklisteIntegrationTest.kt

Ønske fra Mari før vi skrur sjekklista på i prod

EY-2452 Fjernet sjekklisteelement for BP

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt

ref https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-002876?id=Du_dbIsB-jU5QMHzNsfH

Fix intransaction feil

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/EndringBrevDataBP.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/InnvilgetBrevDataBP.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/InntektsendringRevurderingOMS.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/InnvilgetBrevDataOMS.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/bp/InnvilgetHovedmalBrevDataTest.kt

Ref kommentarane på EY-2646
Sjå også pensjonsbrev-PR: https://github.com/navikt/pensjonsbrev/pull/290

EY-2834: Utbetalingstabell for etterbetaling

---

.github/workflows/app-etterlatte-hendelser-joark.yaml
apps/etterlatte-hendelser-joark/.nais/dev.yaml
apps/etterlatte-hendelser-joark/README.md
apps/etterlatte-hendelser-joark/build.gradle.kts
apps/etterlatte-hendelser-joark/src/main/kotlin/Application.kt
apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/JoarkHendelseHandler.kt
apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/behandling/BehandlingKlient.kt
apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/common/JoarkhendelseKonsument.kt
apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/common/JournalfoeringHendelse.kt
apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/config/ApplicationContext.kt
apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/config/KafkaEnvironment.kt
apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/joark/SafClient.kt
apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/joark/SafGraphql.kt
apps/etterlatte-hendelser-joark/src/main/resources/application.conf
apps/etterlatte-hendelser-joark/src/main/resources/graphql/journalpost.id.graphql
apps/etterlatte-hendelser-joark/src/main/resources/logback-secure.xml
apps/etterlatte-hendelser-joark/src/main/resources/logback.xml
apps/etterlatte-hendelser-joark/src/test/resources/logback.xml
settings.gradle.kts

Appen gjør ingenting _enda_ annet enn å lytte og logge litt. Vil kjøre den ut og se om ting fungerer før jeg legger til masse logikk.

EY-2989 Ny kafka-app som leser hendelser fra joark

---

.github/workflows/app-etterlatte-samordning-vedtak.yaml
apps/etterlatte-samordning-vedtak/.nais/apiendpoints.yaml
apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/prod.yaml
apps/etterlatte-samordning-vedtak/README.md

https://nav-it.slack.com/archives/C02C9GJP17D/p1697806246535379

EY-2987 Deploye API gateway config etter app

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx

For å kunne gå videre med en revurdering der grunnlaget er feil.

EY-2948: Oppdater grunnlag også på Revurderingsoversikt, inntil videre

---

apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/sluttbehandlingUtland/SluttbehandlingUtland.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/generellbehandling/KravpakkeUtland.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Generellbehandling.ts
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/generellbehandling/Innhold.kt

* omskrivning til frie dokumenttype felt og visning av de med dato for sluttbehandlign

EY-2966 Feilmelding attestering genbehandling kravpakke

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/gyldigFramsattSoeknad/omstillingsstoenad/GyldigFramsattOmstillingsstoenad.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/gyldigFramsattSoeknad/omstillingsstoenad/GyldigFramsattVurdering.tsx

Endrer tekst under gyldig fremsatt for OMS for å være mer lik tilsvarende i Barnepensjon

EY-2937 Endret tekst under gyldig fremsatt for OMS

---

.github/workflows/app-etterlatte-vedtaksvurdering-kafka.yaml
apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
apps/etterlatte-vedtaksvurdering/.nais/prod.yaml
apps/etterlatte-vedtaksvurdering/.run/etterlatte-vedtaksvurdering.dev-gcp.run.xml
apps/etterlatte-vedtaksvurdering/build.gradle.kts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/config/ApplicationBuilder.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/SamKlient.kt
apps/etterlatte-vedtaksvurdering/src/main/resources/application.conf
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/TestHelper.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtakBehandlingServiceTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/klienter/SamKlientTest.kt

target: https://github.com/navikt/sam/blob/master/provider/nav-provider-stotte-sam-app/src/main/java/no/nav/provider/stotte/sam/app/SamordneVedtakController.java

EY-2764 Kalle SAM:samordne vedtak

---

.github/workflows/app-etterlatte-samordning-vedtak.yaml

Jobben tar normalt rundt 10 sek.
Setter en timeout pga https://github.com/navikt/pensjon-etterlatte-saksbehandling/actions/runs/6703606263/attempts/1

Kort timeout ved deploy av samordning-vedtak gateway config

---

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt
apps/etterlatte-pdltjenester/src/main/resources/pdl/hentPerson.graphql
apps/etterlatte-pdltjenester/src/main/resources/pdl/hentPersonBolk.graphql
apps/etterlatte-pdltjenester/src/main/resources/pdl/hentPersonHistorikkForeldreansvar.graphql

Og for å kunne gjøre det må vi be om informasjonsfeltet :D

EY-2986 Vi trenger potensielt å mappe folk uten identer

---

apps/etterlatte-hendelser-pdl/src/main/avro/no/nav/person/endre/v1/PersonendringRequested.avdl
apps/etterlatte-hendelser-pdl/src/main/avro/no/nav/person/identhendelse/Identhendelse.avdl
apps/etterlatte-hendelser-pdl/src/main/avro/no/nav/person/identhendelse/v1/foedested/Foedested.avdl
apps/etterlatte-hendelser-pdl/src/main/avro/no/nav/person/identhendelse/v1/foedselsdato/Foedselsdato.avdl
apps/etterlatte-hendelser-pdl/src/main/avro/no/nav/person/identhendelse/v1/sivilstand/Sivilstand.avdl
apps/etterlatte-hendelser-pdl/src/main/avro/no/nav/person/identhendelse/v1/vergemaalellerfremtidsfullmakt/VergemaalEllerFremtidsfullmakt.avdl
apps/etterlatte-hendelser-pdl/src/main/avro/no/nav/person/pdl/leesah/verge/VergemaalEllerFremtidsfullmakt.avdl

Dette er nok ikke en bærekraftig måte å håndtere endringer på sikt, men fikser forhåpentligvis feilene vi ser på lesing i prod.

Oppdaterer med nyeste avro-definisjoner fra PDL master

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/OppdaterGrunnlagModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx

Etter samtale med Mari ble følgende vedtatt:

Flytt utlandstilsnitt overst og la oppdater grunnlag gå til høyre

---

.github/workflows/app-etterlatte-hendelser-samordning.yaml
apps/etterlatte-hendelser-samordning/.nais/dev.yaml
apps/etterlatte-hendelser-samordning/.nais/prod.yaml
apps/etterlatte-hendelser-samordning/README.md
apps/etterlatte-hendelser-samordning/build.gradle.kts
apps/etterlatte-hendelser-samordning/src/main/kotlin/Application.kt
apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/ApplicationContext.kt
apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/KafkaEnvironment.kt
apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningHendelseHandler.kt
apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningHendelseKonsument.kt
apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningVedtakHendelse.kt
apps/etterlatte-hendelser-samordning/src/main/resources/logback-secure.xml
apps/etterlatte-hendelser-samordning/src/main/resources/logback.xml
apps/etterlatte-hendelser-samordning/src/test/kotlin/no/nav/etterlatte/samordning/SamordningHendelseIntegrationTest.kt
apps/etterlatte-hendelser-samordning/src/test/resources/logback-test.xml
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/Application.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/VedtakService.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/AttestertVedtakRiver.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/SamordningMottattRiver.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/AttestertVedtakRiverTest.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/SamordningMottattRiverTest.kt
apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
apps/etterlatte-vedtaksvurdering/.nais/prod.yaml
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
settings.gradle.kts

Dytte ut på river, for å tas hånd om av **vedtaksvurdering-kafka** -> **vedtaksvurdering** `/api/samordnet`
**Skisse som beskriver flyten:**
https://app.mural.co/t/navdesign3580/m/navdesign3580/1694415932692/091ebf09dee71d04c6afd13548767416f0ccdfa8?sender=uab3575b81367246e376e8871

EY-2765 Motta melding fra SAM om ferdig samordnet vedtak

---

apps/etterlatte-hendelser-samordning/.nais/dev.yaml
apps/etterlatte-hendelser-samordning/.nais/prod.yaml
apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/Application.kt

Er forventet av gradle common manifest-config.
Personlig mening: Synes dette er litt så der til opplegg.

EY-2765 Korrigerte pakke for ApplicationKt

---

apps/etterlatte-behandling/src/test/kotlin/behandling/migrering/MigreringRoutesTest.kt
apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelserRiver.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelserRiverTest.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/pen/PenModellTilVaarModell.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/FeilendeMigreringLytterRiverTestRiver.kt
apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelserRiver.kt
apps/etterlatte-trygdetid-kafka/src/test/kotlin/MigreringHendelserRiverTest.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/MigreringRequest.kt

Trygdetidstall og netto-/bruttobeløp fra Pesys er uten desimaler

---

gradle/libs.versions.toml

This reverts commit b39f32d030546b029a73a2a3be9cfd561ef7bc85.

Revert "Bump the avro-og-kafka group with 3 updates (#2597)"

---

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/vedtak/TilbakekrevingKlient.kt
apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/vedtak/TilbakekrevingKlientTest.kt

- Endrer til BigDecimal for å sende riktig format på beløper
- Endrer innhold i ytelse og feilkonto
- Setter N på renterBeregnes
- Fjerner timestamp før sending til etterlatte-proxy da dette ville blitt med pga xmlgregoriancalendar

EY-2996 Endrer vedtaksrequest mot tilbakekrevingskomponenten

---

apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/prod.yaml
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/Application.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/CallerContext.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtak.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakService.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/Tjenestepensjon.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/TjenestepensjonKlient.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/VedtaksvurderingKlient.kt
apps/etterlatte-samordning-vedtak/src/main/resources/application.conf
apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRouteTest.kt
apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakServiceTest.kt
apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/TjenestepensjonKlientTest.kt
apps/etterlatte-samordning-vedtak/src/test/resources/logback-test.xml
libs/etterlatte-ktor/src/main/kotlin/AuthorizationPlugin.kt
libs/etterlatte-ktor/src/main/kotlin/MaskinportenScopeAuthorizationPlugin.kt

Vedr feilhåndteringen, så kan man da få slik output:
```
{
"status": 400,
"detail": "fnr ikke angitt",
"code": "002-FNR-MANGLER",
"meta": {
"correlation-id": "7d2c0d74-8774-4260-ab15-c5b44943ce6a",
"tidspunkt": "2023-11-02T11:40:03.029465Z"
}
}
```

EY-2981 Pesys skal hente omstillingsstønadsvedtaksinfo

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/Behandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx

litt feil i stegmenya da den får hentet behandling og ikke redux behandling, men nå får den det. Var opprinnelig for å slippe alle nullsjekkene så kjører en as i stedet for.

Behandlinggarra

---

apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/migrering/MigreringRoutesTest.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/barnepensjon/Konstanter.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnBarnepensjonServiceTest.kt

Vi bør kunne iverksette mot oppdrag nå på nytt regelverk.
EY-3054

Setter korrekt reformtidspunkt i beregning og for migrering.

---

.github/workflows/app-etterlatte-hendelser-samordning.yaml

SAM er oppdatert og deployet, https://github.com/navikt/sam/actions/runs/6768464335

EY-2765 Re-enable deploy samordninghendelse

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt

Logg diff mellom enhet vi får fra Pesys og den vi ville fått av norg

---

apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelserRiver.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelserRiverTest.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRoutes.kt

Oppdaterer samtidig beregning med flere sjekker for å verifisere at resultatet blir rett.
EY-3058

Legger til beregningsmetode for migrering.

---

libs/saksbehandling-common/src/main/kotlin/person/Folkeregisteridentifikator.kt

For å håndteres bedre av StatusPages.

Endret InvalidFoedselsnummerException til å arve UgyldigForespoerselException

---

apps/etterlatte-saksbehandling-ui/client/src/App.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx

- Kun barnepensjon enn så lenge
GUI:

EY-3056 - Egen side for å opprette førstegangsbehandling manuelt uten oppgave i gosys

---

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt

Har hørt med Oppgave-teamet, og må håndteres hos oss. Kan ikke spesifiseres i søket (med mindre man spør på en spesifikk aktøerID)

Filtrere vekk Gosys-oppgaver som ikke har persontilknytning

---

gradle/libs.versions.toml

For å retrigge alt som #2643 skulle, som feilet fordi dependabot har ikke samme rettigheter som vi på teamet

Dummy commit for å trigge full deploy

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BehandlingKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/tilbakekreving/TilbakekrevingInnholdBrevDataTest.kt

For å kunne plukke opp at vi har en migrert sak i brev

EY-3060 generell brevdata plukker opp kilde

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/detaljer/MottakerPanel.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx

- `div` innenfor `p` er ikke innafor 
- `textarea` kan ikke ha null-verdi

Fjerner et par irriterende frontend-warnings

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnOverstyrBeregningService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/overstyr/BeregnOverstyr.kt
apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnOverstyrServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningServiceTest.kt
libs/etterlatte-beregning-model/src/main/kotlin/OverstyrBeregningsGrunnlag.kt

Draft - venter på EY-3006 og må skrive tester

EY-3007 - overstyr beregning grunnlag - beregning

---

apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/AttestertVedtakRiver.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/resources/attestertVedtakOms.json

Feiler pga https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/2683/files#diff-7ccabc37c9217702a0370ce91e4444815db9c20114b0aa91538e24f32b13c74c
https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-002895?id=A9mmyIsBP0AwnweKaEuH

Korrigert dto-type som parses av Attestert vedtak-river

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/soeskenjustering/SoeskenjusteringPeriode.tsx

ref https://nav-it.slack.com/archives/C043C5ZGW5T/p1699689319979349

Ikke vis frem soesken som ikke ligger på avdødes barn levende barn

---

apps/etterlatte-samordning-vedtak/.nais/dev.yaml

Tilgang for PEN Q0 å kalle samordningsappen

---

apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/logger.tsx

Vi ønsker ikke å få errors ved feks 404 - eller når bruker skriver inn noe som ikke validerer.

Logger 4xx og 3xx feil som info fra frontend

---

libs/etterlatte-vilkaarsvurdering-model/src/main/kotlin/vilkaarsvurdering/VilkaarType.kt

Yrkesskade skal gi 40 års trygdetid på nytt regelverk også

---

apps/etterlatte-migrering/.nais/dev.yaml
apps/etterlatte-migrering/src/main/kotlin/migrering/Application.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/ApplicationContext.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/MigrerSpesifikkSakRiver.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/krr/KrrKlient.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/krr/KrrResponse.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/pen/PenModellTilVaarModell.kt
apps/etterlatte-migrering/src/main/resources/application.conf
apps/etterlatte-migrering/src/test/kotlin/migrering/MigreringRiverIntegrationTest.kt

Ventar på KRR-endring for å kunne teste

EY-3110: Hent språk frå KRR ved migrering

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/VurderHendelseModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/HendelseBeskrivelse.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/utils.ts

Gjenstår gjennomgang med Fag for endelig design, men ønsker å ta den ut så de kan se på det.

Lagt til visning av adressehendelser på saksoversikten

---

apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelserRiver.kt
apps/etterlatte-trygdetid-kafka/src/main/kotlin/TrygdetidService.kt
apps/etterlatte-trygdetid-kafka/src/test/kotlin/MigreringHendelserRiverTest.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt

Yrkesskade del 2: Opprett eget trygdetidsgrunnlag ved yrkesskade

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManuellRevurdering.kt
libs/etterlatte-funksjonsbrytere/build.gradle.kts
libs/etterlatte-funksjonsbrytere/src/main/kotlin/no/nav/etterlatte/funksjonsbrytere/FeatureToggleService.kt
libs/testdata/src/main/kotlin/DummyFeatureToggleService.kt

Togglet i første omgang, spesifikt mtp behov for å opprette ymse testdata for test av samordning

Tillate statusovergang vilkårsvurdert -> fattet vedtak (kontekst er opphør)

---

apps/etterlatte-saksbehandling-ui/server/src/middleware/proxy.ts

Plukkes opp av CallId-pluginen i RestModule.

Generer korrelasjonsID så tidlig som mulig. 

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiver.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/Ryddejobb.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/config/ApplicationBuilder.kt

Gjenbruker løysinga Øyvind laga sist, berre med oppdateringar til det som er endra i main i mellomtida

Rydd journalfoering

---

apps/etterlatte-migrering/src/main/kotlin/migrering/PesysRepository.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/PesysRepositoryTest.kt

Oppdatere pesyskobling til ny behandlingsid etter ny migreringskjøring

Åpne for å inserte flere koblinger mellom en pesysid og flere behandlingsid

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt

Trygdetidsgrunnlag får feil kilde ved migrering

---

apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Utenlandstilknytning.kt

- NASJONAL hardkodes inntil det kan utredes fra pesyssak

Legger til utenlandstilknytning under migrering

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/hendelse/HendelseDao.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/generellbehandling/GenerellBehandling.kt

Legger til hendelser for OPPRETTET, FATTET, ATTESTERT og UNDERKJENT

EY-2693 Behandlingshendelser for generelle behandlinger

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/BehandleJournalfoeringOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/VelgJournalpost.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/endretema/EndreJournalpostTema.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/ferdigstilljournalpost/FerdigstillJournalpost.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/handling/StartOppgavebehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/FullfoerOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/OpprettNyBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Journalpost.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/formattering.ts

Opprydding og forbedringer i brukergrensesnittet. 
Stopper også sb fra å gå videre dersom journalposten ikke har lastet inn.

EY-3040 Opprydding i grensesnitt + feilmelding

---

apps/etterlatte-brev-api/src/main/resources/graphql/dokumentoversiktBruker.graphql

Legge til `tema: [EYO, EYB]` for å kun hente våre journalposter.

EY-3150 Kun hente journalposter med tema EYO og EYB

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/bosattUtland/MottatteSeder.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/Virkningstidspunkt.tsx

- Legger på infoboks i stedet for kun ikon
- Stor forbokstav på Kravdato

Fikser infoboks krav utland

---

apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/beregning.ts

- Sjekkboks for å kunne velge å overstyre beregning ved opprettelse av manuell behandling

EY-3056 - Manuell migrering bruker manuell beregning

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Etterbetaling.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/BehandlingReducer.ts

Designet burde hatt en liten overhaling også, men det får bli en annen PR.

Fikser sletting og visning etterbetaling

---

libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/ListenerMedLogging.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/ListenerMedLoggingOgFeilhaandtering.kt

Mest nyttig for nettopp debug, ofte er det jo akkurat som forventa, men det er fint å kunne sjekke det ved behov

At riveren ikkje plukka opp ei melding pga valideringa er i grunn mest debug

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BeregningKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/EndringBrevDataBP.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt

Tilhøyrande PR i brevbakeren, som må inn samtidig: https://github.com/navikt/pensjonsbrev/pull/323

EY-3122: Mal for revurdering barnepensjon

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/VedtaksvurderingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/OmregnetBPNyttRegelverk.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/BrevEventTypes.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/migrering/FiksEnkeltbrevRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/migrering/OpprettVedtaksbrevForMigreringRiver.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/Migreringshendelser.kt

Brevet feila i genererPDF-steget, så vedtaksbrevet er allereie oppretta.

Fiks enkeltbrevet som feila under migrering

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/SamKlient.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtakBehandlingServiceTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/klienter/SamKlientTest.kt

~~Oppretter denne i draft da selve SAM-endepunktet ikke er endret ennå, så ikke garantert at navngivningen er riktig ennå.~~
Testet lokalt i Gjenny med lokal vedtaksvurdering -> behandling i GCP, med spørring både med og uten etterbetaling (hooket inn på hent vedtakssammendrag)

EY-3155 Sender flagg om etterbetaling ved samordning

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiver.kt

Migreringsrelatert, vi handterer

Hoppar midlertidig over brev 298

---

apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt

Forenkler sjekken så uthentingen ikke gjøres dersom grunnlaget ikke har noen søsken.

Enkelte saker fra migrering krasjer når man leser ut avdødes barn fra grunnlag

---

libs/etterlatte-ktor/build.gradle.kts
libs/etterlatte-ktor/src/main/kotlin/ClientCallLogging.kt
libs/etterlatte-ktor/src/main/kotlin/HttpCallLogging.kt
libs/etterlatte-ktor/src/main/kotlin/HttpClient.kt
libs/etterlatte-ktor/src/main/kotlin/RestModule.kt

Mer spisset enn hva som tilbys av CallLogging fra ktor-bibliotekene, samt entries som kibana kan indeksere

Spisset logging av utgående kall for sporing

---

apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/config/ApplicationContext.kt

Legger inn kjøreplan mottatt på Slack

Legger inn kjøreplan for konsistensavstemming for 2024

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/avtaler/TrygdeAvtale.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/avtaler/TrygdeavtaleVisning.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/detaljer/BeregnetFremtidigTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/avtale/AvtaleRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/avtale/AvtaleRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/avtale/TrygdeavtaleRequest.kt
apps/etterlatte-trygdetid/src/main/resources/db/migration/V17__legg_til_felter_trygdeavtale.sql
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/avtale/AvtaleRepositoryTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/avtale/AvtaleRoutesTest.kt
libs/etterlatte-trygdetid-model/build.gradle.kts
libs/etterlatte-trygdetid-model/src/main/kotlin/Trygdeavtale.kt

Gjenstår litt på test og testing, samt å utvide visnings av "ikke-redigerbar visning" med de nye feltene

Utvidelse av trygdeavtale for avdød

---

apps/etterlatte-migrering/src/main/kotlin/migrering/start/MigrerSpesifikkSakRiver.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/PDLKlient.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt

Patcher inn manglende gjenlevende (hvis avdød ellers stemmer)

POC: Henter persongalleri fra PDL hvis vi mangler gjenlevende i migrering

---

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/BehandlingKlient.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/klienter/BehandlingKlient.kt
libs/ktor2client-onbehalfof/src/main/kotlin/DownstreamResourceClass.kt
libs/ktor2client-onbehalfof/src/main/kotlin/Models.kt

Tilefellene hvor man får en respons burde nok ikke vært exception, men ønsker ikke å gjøre for store endringer på dette nå under migrering.

Tilgjengeliggjør response når downstreamResourceClient returnerer uforventet status

---

apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonService.kt

… og ikke ansvarlige foreldre.
Ved sjekk på ansvarligeForeldre så får vi ingen avdød.
Basert på https://nav-it.slack.com/archives/C01KJ597UAU/p1700213607255259

Lurer på om persongalleriet skal baseres på (biologiske) foreldre 

---

apps/etterlatte-grunnlag/.nais/dev.yaml
apps/etterlatte-grunnlag/.run/etterlatte-grunnlag.dev-gcp.run.xml
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/BehandlingGrunnlagRoutes.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
apps/etterlatte-saksbehandling-ui/client/src/shared/api/grunnlag.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/grunnlag.ts

Veeeldig wip. Kommenter i vei
Holder på med å bruke dette i `Familieforhold.tsx` og underliggende

EY-3116 Hent grunnlag fra grunnlag

---

apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/VedtakService.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/SamordningMottattRiver.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/LagreIverksattVedtakRiverTest.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/AttestertVedtakRiverTest.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/SamordningMottattRiverTest.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt

Oppdaget i test av samordning, rart at ikke iverksett-biten har trigget noen tidligere?
https://logs.adeo.no/app/r/s/r0Osv

Korrigert type DTO som benyttes vedtaksvurdering -> vv-kafka

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/BehandleJournalfoeringOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/ferdigstilljournalpost/FerdigstillJournalpost.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/ferdigstilljournalpost/FerdigstillJournalpostModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/FullfoerOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/OpprettNyBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/OppsummeringOppgavebehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/PersongalleriBarnepensjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/PersongalleriOmstillingsstoenad.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/validator.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Brev.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/JournalfoeringOppgaveReducer.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/formattering.ts

Fikse noen bugs + oppdatere tekster iht. forslag fra fag/design

EY-3186 Opprydding i tekster, m.m. på journalføringsoppgaver

---

apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt

Ingen støtte for disse sakene i brev enda.

Ikke migrer saker som ikke har folketrygd-beregning, eller har proratabrøk

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/soeskenjustering/Soeskenjustering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/soeskenjustering/SoeskenjusteringPeriode.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/Barn.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/Soesken.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts

EY-3198 Endre datakilde for søskenkomponenter

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx

Dette var egentlig på en annen branch, men ble av en eller annen grunn aldri med når jeg merget 😬

Ikke vise melding om utdatert brev etter at vedtak er fattet

---

apps/etterlatte-migrering/src/main/kotlin/Application.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/start/StartMigrering.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/start/StartMigreringTest.kt

For å få køyrd raskare,  ikkje grunn til å vente for dry-run

Ikkje vent før dry-run

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx

For revurderinger er det når behandlingen ble opprettet som ligger i feltet `soeknadMottattDato`, ref. `Behandling.kt:58`

Vis kun søknad mottatt dato hvis den finnes.

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/GrunnlagForVirkningstidspunkt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts

PR nummer 3 i EY-3198
Bygger på/inneholder #2917 ✅

EY-3198 Fjerne resterende bruk av DetaljertBehandlingDto.familieforhold.gjenlevende

---

apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/BoddEllerArbeidetUtlandet.kt
libs/etterlatte-migrering-model/src/main/kotlin/no/nav/etterlatte/rapidsandrivers/migrering/MigreringRequest.kt

Oppretter behandling med utlandsopphold i migrering.

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/SamsvarPersongalleri.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/barnepensjon/FamilieforholdBarnepensjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/omstillingsstoenad/FamilieforholdOmstillingsstoenad.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/grunnlag.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/grunnlag.ts

Ikke akkurat det vakreste, men vi får i alle fall frem at det er personer uten identer i saken

Viser personer med manglende identer i persongalleriet

---

apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/BehandlingSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/sidemeny/TilbakekrevingSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/user.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/saksbehandler.ts
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/InnloggetSaksbehandlerReducer.ts
apps/etterlatte-saksbehandling-ui/server/src/index.ts
apps/etterlatte-saksbehandling-ui/server/src/routers/innloggetBrukerRouter.ts
apps/etterlatte-saksbehandling-ui/server/src/routers/mockRouter.ts
apps/etterlatte-saksbehandling-ui/server/src/utils/enhet.ts
apps/etterlatte-saksbehandling-ui/server/src/utils/parsejwt.ts

- Sjekker om saksbehandler har gruppeID tilknyttet attestant-rollen og returnerer `kanAttestere`. 
- Opprydding i navngiving (`modia` -> `innloggetBruker`)

EY-3207 Sjekke om bruker faktisk er attestant (AD groups)

---

apps/etterlatte-statistikk/src/main/resources/db/migration/V28__patch_kilde_historisk.sql

Sakene ble behandlet i løsningen før vi la til feltet

Setter kilde for saker som var behandlet i Gjenny

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BarnepensjonSammendrag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/soeskenjustering/Soeskenjustering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/Familieforhold.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/Virkningstidspunkt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/usePersonopplysninger.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/PersonopplysningerReducer.ts

EY-3198 Fjerne avdoed/familieforhold fra IDetaljertBehandling

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Grunnlagmapper.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagHenter.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/adresse/PersondataAdresse.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/adresse/RegoppslagResponseDTO.kt
apps/etterlatte-grunnlag/src/main/kotlin/klienter/PersondataKlient.kt
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagHenterTest.kt
libs/saksbehandling-common/src/main/kotlin/person/Person.kt

…s den ikke gir oss verges adresse gitt søkers fnr, for da må vi hente adressen gitt verges fnr i PDL.

EY-3206: Hent verges adresse gitt verges fnr hvis Persondata ikke gir oss den gitt søkers fnr

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/DetaljertBehandlingDto.kt

Backend-delen av #2938
Merges etter ☝️ og utenfor arbeidstid.

EY-3198 Fjernet avdoede/familieforhold fra DetaljertBehandlingDto

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx

Korrigert bug med at logikk for sjekklistestatus var reversert

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/barnepensjon/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/omstillingsstoenad/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/personinfo/UtvandringInnvandring.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts

Viser inn/utflytting i oversikten i familieforhold

---

apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts

Prøver å stoppe uendelig loggeloop

---

apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/logger.tsx

Legger på et ekstra parameter for om vi skal logge feil mot backend, og loggFeil sier at den ikke vil logge feil i sine kall

Sikrer ingen logg loops

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/DetaljertBehandlingDto.kt

Merges først en dag eller 2 etter #2975

EY-3198 Fjernet søker fra DetaljertBehandlingDto

---

apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/prod.yaml

https://nav-it.slack.com/archives/C01KJ597UAU/p1701767828338399

EY-3222 Åpnet vedtaksendepunkt for pensjon-selvbetjening-soknad-alder

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/Verger.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/RedigerMottakerModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts

og... EY-3210: Fikser visning av fødselsnummer i brevmottaker.

EY-3199: Skal forvente data i response når status er 201

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BarnepensjonSammendrag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Barnepensjonberegningssammendrag.tsx

Nytt beregningssammendrag på nytt regelverk BP

---

apps/etterlatte-saksbehandling-ui/client/src/utils/logger.tsx
apps/etterlatte-saksbehandling-ui/server/src/routers/loggerRouter.ts

https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-prod-006742?id=FuM9P4wBKARV67QUlV9u
fnr snek seg med i loggingen

Ikk logg fnr

---

apps/etterlatte-migrering/src/main/kotlin/migrering/infra/ApplicationContext.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/GjenlevendeForelderPatcher.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/PersonHenter.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/start/MigreringRiverIntegrationTest.kt

Dekker punkt to: https://nav-it.slack.com/archives/C05MGJ6MZRN/p1701858713919119?thread_ts=1701851946.674799&cid=C05MGJ6MZRN

Takle manglande relasjon barn avdoed

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt

Bør nok sees på når vi skal implementere støtte for to avdøde.

Opprett konstant grunnlag dersom avdød ikke er registrert med dødsdato

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnOmstillingsstoenadService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnOverstyrBeregningService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt
apps/etterlatte-beregning/src/main/kotlin/ytelseMedGrunnlag/YtelseMedGrunnlagService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakBehandlingService.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/DetaljertBehandling.kt

- Spesifiserte exceptions for avkorting
- Gjenbruk av detaljertBehandling.virkningstidspunkt med require og feilmelding

Enkel rydding avkorting pluss litt mer

---

apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
apps/etterlatte-behandling/src/test/kotlin/VerdikjedeTest.kt
apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtakBehandlingServiceTest.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/DetaljertBehandling.kt
libs/etterlatte-behandling-model/src/test/kotlin/no/nav/etterlatte/libs/common/behandling/DetaljertBehandlingTest.kt

Felter var tidligere brukt av statistikk men nå erstattet av StatistikkBehandling

Fjerner felter fra DetaljertBehandling som er ubrukt

---

apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/prod.yaml
apps/etterlatte-samordning-vedtak/src/main/resources/application.conf
get-secret.sh

Oppfølger til behovet fra pensjon selvbetjening.

EY-3222 Skrudd på tokenX

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/EnhetService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/egenansatt/EgenAnsattService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/TilgangServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/EnhetServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/egenansatt/EgenAnsattServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt

Ref https://nav-it.slack.com/archives/C05MGJ6MZRN/p1701940379493129?thread_ts=1701877619.896839&cid=C05MGJ6MZRN

Takle manglande enhetstilknytning for migrering

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnBarnepensjonServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/ReguleringTest.kt

…av ytelene til nytt regelverk

Benytter nytt regelverk for beregning ved omregning 

---

apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/LoggingPlugins.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SelvbetjeningAuthorizationPlugin.kt

- identifisert med fnr (claims.sub og claims.pid har fnr). 
- Kan ikke bruke `permissions.roles` i nais-manifestet for tokenx
- Sjekke at en bruker kun spør etter _egne_ data
- Tilpasninger til rolle-autorisasjonen slik at flere plugins ikke går i beina på hverandre.
- Dersom ingen principal i pluginene så returnerer umiddelbart (`return@on`), slik at man ikke overskriver gjeldende årsak til at man ikke autoriseres.
https://docs.nais.io/security/auth/tokenx/#example-token-exchanged-from-id-porten
🥵

EY-3222 Ny autoriseringsmekanisme når bruker er borger

---

apps/etterlatte-oppdater-behandling/src/main/kotlin/BehandlingService.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/LoependeYtelserforespoerselRiver.kt

Klargjør regulering av 3 saker med full kjøring

---

libs/etterlatte-ktor/src/main/kotlin/feilhaandtering/StatusPagesKonfigurasjon.kt
libs/saksbehandling-common/src/main/kotlin/person/Folkeregisteridentifikator.kt

Vi får nå kun "failed requirement" i loggene ref https://logs.adeo.no/app/r?l=DISCOVER_SINGLE_DOC_LOCATOR&v=8.11.2&lz=N4IglgdgJgpgHiAXCAnANhmgLADgMYAMAtCjgQIZECMVMKROAzBUTFQOwBGnU2nWUTiAA0IAE4B7AO4BJaPCQgANhIDmAZwAu5dQAsi5AA6H1RQ5KhECBNOwCsAJhHjpMqIogAvTwCUAalhSAEIA0uoA8kp24VQAmlAAVgAKABLOYjAAZjBiGWKKAPRGhgVQYOp4EgBuOQDEBQD8APqqALwAFJlgSpo56ogAhO0AlMKaYAC2MIidkhOIAOQOBA6M1A7UVAAqBOyIjCiIWAQAdA4OVABaC2MSi8ur65s7e3ZYR6fnVwvDwwBkTXIHUqSgArhMIP0hkoYDUlMIpup1ORVDBhMUlGA8ORxhIIMItOQ8ABrJqaMREtFwJqVXIwJQ4sB4ppgKCjLo9PqDdrtBYAEkJvQWMy0EgyiGKAGVtL1RlNtDNyJidIN8WVkZwYVBBplhF16dqIOREYZKcJILA4IsDvwcHa7ERMtiYERjmgqEROLQHW9yNw7JkcFgYA5ODdiTAAJ6II0ms0QGCqHHTAa600Uib9doAR1BOWjME0vTEDKLMFGmkjhmmhl0FPU5eEufzMwmOLwuiatfr03asZg6lNeGmheLpdlv2EvIFMpgwvaovFUtncsL5EVyqhavKfq1Or1YANiBgECqeAZSPN8itCxtuHtjudrpsHq9MB …

Bedre feilmelding folkeregisterident

---

apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml

Server-delen er vel en forholdsvis lett app

Justert requested resources litt ned for frontend

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-beregning/.nais/dev.yaml
apps/etterlatte-beregning/.nais/prod.yaml
apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/prod.yaml
apps/etterlatte-fordeler/.nais/dev.yaml
apps/etterlatte-fordeler/.nais/prod.yaml
apps/etterlatte-grunnlag/.nais/dev.yaml
apps/etterlatte-grunnlag/.nais/prod.yaml
apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
apps/etterlatte-vedtaksvurdering/.nais/prod.yaml
apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml
apps/etterlatte-vilkaarsvurdering/.nais/prod.yaml

Starta på https://console.nav.cloud.nais.io/team/etterlatte/applications og kikka på dei første med gul varseltrekant. Det kjem fleire PR-ar i samme gate.

Rydde iht naiskonsollet - første runde

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx

Ser ut til at refaktoreringen i #2969 endret oppførselen

Sjekklista skal ikke valideres for annet enn førstegangsbehandlinger

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/barnepensjon/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/omstillingsstoenad/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/personinfo/Statsborgerskap.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/personinfo/StatsborgerskapVisning.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts

En vakker dag henter vi landlista og mapper ut noe bedre enn de 3bokstavkodene. men det er ikke i dag :P 
med mindre jeg har lyst og gidder nå da

Viser statsborgerskapet til personer i familieoversikt

---

apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/prod.yaml
apps/etterlatte-hendelser-samordning/.nais/prod.yaml
apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml
apps/etterlatte-vilkaarsvurdering/.nais/prod.yaml

Ryddar opp i det som blir rapportert på https://console.nav.cloud.nais.io/team/etterlatte/applications

Rydde iht naiskonsollet del2

---

apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveRoutesTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelistafiltre.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Tags.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts
libs/etterlatte-oppgave-model/src/main/kotlin/Oppgave/OppgaveIntern.kt

Har manuelt slettet alle oppgaver av denne typen i `dev-gcp`. 
Det var ingen innslag av typen i `prod-gcp`.

EY-3225 Fjerne siste rest av MANUELL_JOURNALFOERING

---

gradle/libs.versions.toml

Trur det å oppgradere særleg r&r og logback tar bort veldig mange åtvaringar frå dependency-track

Oppgraderer nokre avhengnadar, inkl r&r og logback

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/OverstyrBeregningGrunnlag.tsx

Ser noen innslag av dette problemet i produksjon

Fjerner whitespace fra utbetalt beløp før innsending

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreSak.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Journalpost.ts

EY-3179 Støtte endring av sak på journalpost

---

apps/etterlatte-beregning/.nais/dev.yaml
apps/etterlatte-beregning/.nais/prod.yaml
apps/etterlatte-grunnlag/.nais/dev.yaml
apps/etterlatte-grunnlag/.nais/prod.yaml
apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/prod.yaml

Basert på nais console. Alle 3 ligger hovedsaklig på/over allokert minne så booster litt der.
Default cpu er `200m`, https://docs.nais.io/nais-application/application/#resourcesrequestscpu.
Default memory er `256Mi`.

Redusert cpu for 3 apper

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakDao.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakDaoTest.kt

Spesielt viktig for migrerte saker hvor det er anvendt flyktningfordel med 40 års trygdetid.

Rute for å vise informasjon om flyktning i frontend.

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/SakOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/sak.ts

Viser informasjon om flyktningstatus for migrerte saker på saksoversikt

---

apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/KafkaEnvironment.kt
apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningHendelseKonsument.kt

Oppfølger til #3171, som ikke ga så veldig mye

Logger meldinger til sikkerlogg, flyttet til pre-deserialisering

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/AnnullerBehanding.tsx

Er vel ikke første gang denne endres 😛 
Merger ikke denne før folk er enig om hva som bør stå her.

EY-3260 Legger til annuler behandling i OMS og fikser tekster

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Grunnlagmapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Personer.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/GrunnlagKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/OmregnetBPNyttRegelverk.kt
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/itest/GrunnlagDaoIntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/BehandlingsBehov.kt
libs/saksbehandling-common/src/main/kotlin/grunnlag/Grunnlagsdata.kt
libs/saksbehandling-common/src/main/kotlin/grunnlag/opplysningstyper/Opplysningstype.kt

- Lagre opplysning om to avdøde for manuell migrering i grunnlag
- Bruke opplysning til å vise riktig brevmal for foreldreløs

Manuell migrering - Opplysning om foreldreloes i grunnlag

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/jobs/BehandleVedtaksbrevJobb.kt
apps/etterlatte-saksbehandling-ui/client/src/ErrorBoundary.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/logger.tsx
apps/etterlatte-saksbehandling-ui/server/src/index.ts
apps/etterlatte-saksbehandling-ui/server/src/monitoring/logger.ts
apps/etterlatte-saksbehandling-ui/server/src/routers/loggerRouter.ts
apps/etterlatte-saksbehandling-ui/server/src/routers/unleashRouter.ts
apps/etterlatte-saksbehandling-ui/server/src/utils/sanitize.ts

- Flytte unleash/feature til egen router. 
- Endre fra string til objekt i frontend-logging og bruke feilmelding fra front i stedet for "ukjent/generell feil har oppstått".

Opprydding node server

---

.github/workflows/.build-job.yaml
.github/workflows/.build.yaml
.github/workflows/.lib-test.yaml
.github/workflows/.test-job.yaml
.github/workflows/.test.yaml
.github/workflows/codeql.yml
.github/workflows/job-start-grunnlagsversjonering.yaml
buildSrc/build.gradle.kts
docker/Dockerfile

Vil påvirke utvikleroppsett:
Set projekt i idea til å bruke JDK 21 (temurin)
Set JAVA_HOME for terminal til JDK 21

Bump JDK til 21.x

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml

Ligger et godt stykke over requested (default 256Mi) hele tida.

Økt minne for behandling

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sjekkliste/Sjekkliste.tsx

`Cannot read properties of undefined (reading 'foedselsnummer')`
https://nav-it.slack.com/archives/C043C5ZGW5T/p1703064685557629

Utvidet nullsjekk mot søker

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/TrygdetidService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BeregningsinfoBP.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/InnvilgetBrevDataBP.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/BehandlingTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/bp/InnvilgetHovedmalBrevDataTest.kt

Legger på nye felter som trengs for ny innvilgelsesmal på Barnepensjon.

Legger på nye felter ifm endring bp innvilgelsesmal

---

apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/KafkaEnvironment.kt
apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningHendelseHandler.kt
apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningHendelseKonsument.kt

Ikke nødvendig lengre, ymse feil rettet (hos oss og i SAM) og hele løypa er verifisert

EY-2765 Fjernet ekstralogging

---

apps/etterlatte-saksbehandling-ui/server/src/middleware/logging.ts
apps/etterlatte-saksbehandling-ui/server/src/routers/loggerRouter.ts

Ref https://github.com/navikt/pensjon-etterlatte-saksbehandling/security

Rettar moglege loginjection-risikoar. Kanskje ikkje veldig store, men greitt å ta det unna

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Grunnlagmapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/SoekerService.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/BehandlingTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/GrunnlagmapperTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt
libs/saksbehandling-common/src/main/kotlin/person/Person.kt

Det må diskuteres med fag om dette er en rimelig håndtering

EY-3273 Mer forsiktig mapping av verge for BP

---

apps/etterlatte-saksbehandling-ui/Dockerfile
apps/etterlatte-saksbehandling-ui/server/Dockerfile.dev

Ref https://github.com/navikt/pensjon-etterlatte/pull/985

Byttar over til node-bookworm-slim også her, for å vera konsekvent på tvers

---

apps/etterlatte-hendelser-samordning/.nais/dev.yaml
apps/etterlatte-hendelser-samordning/.nais/prod.yaml
apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/Application.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/Application.kt

+ litt nedjustert cpu for hendelse

Skrudd på flere metrics for samordning-apps

---

apps/etterlatte-pdltjenester/.nais/dev.yaml
apps/etterlatte-pdltjenester/.nais/prod.yaml
apps/etterlatte-statistikk/.nais/dev.yaml
apps/etterlatte-statistikk/.nais/prod.yaml
apps/etterlatte-tilbakekreving/.nais/dev.yaml
apps/etterlatte-tilbakekreving/.nais/prod.yaml
apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/prod.yaml
apps/etterlatte-utbetaling/.nais/dev.yaml
apps/etterlatte-utbetaling/.nais/prod.yaml
apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml
apps/etterlatte-vilkaarsvurdering/.nais/prod.yaml

Ikke noe veldig spennende, stort sett samme leia som det som er gjort i desember. Mulig litt tuning etter oppdatering til Java 21, kotlin 1.9 osv.

Justert requested resources på en del apps

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/prod.yaml
apps/etterlatte-hendelser-pdl/.nais/dev.yaml
apps/etterlatte-hendelser-pdl/.nais/prod.yaml
apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml
apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
apps/etterlatte-vedtaksvurdering/.nais/prod.yaml

Noen har fått bumpet memory litt

Justert requested resources på flere apper

---

apps/etterlatte-behandling/src/main/kotlin/metrics/BehandlingMetrics.kt
apps/etterlatte-behandling/src/main/kotlin/metrics/BehandlingMetrikkerDao.kt
apps/etterlatte-behandling/src/test/kotlin/metrics/BehandlingMetricsTest.kt

Labels for saktype, behandlingstype og revurderingsaarsak

Metrikker behandling flere labels

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/SakOversikt.tsx

Vi henter ikke person samtidig som sak da man ikke vet om sb har tilgang enda. 
Henter derfor personinfo fra grunnlag kun om sak finnes.

Bare hente person hvis sak er success

---

apps/etterlatte-utbetaling/.nais/dev.yaml
apps/etterlatte-utbetaling/.nais/prod.yaml

...ettersom diverse tiltak er både merget og in-flight. Det med å få på plass en dry run-mulighet bør sees på.

Justerer utbetaling-ressurser ned igjen

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagHelper.kt

Rettar https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-002970?id=bCj_2YwBNoemB7ykYKHO

Takle at gjenlevande kan mangle

---

apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/GrensesnittsavstemmingJob.kt
apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/config/ApplicationContext.kt
apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/GrensesnittsavstemmingsJobTest.kt

- Endringene rulles tilbake når jobben er kjørt

Kjør grensesnittavstemming på nytt for 5. januar pga feil hos økonomi

---

libs/saksbehandling-common/src/main/kotlin/behandling/Revurderingaarsak.kt

Vedlagt bilde er fra en sak som viser årsaker som er synlig i prod.
Flere av dem er KunIDev saker.
Litt midlertidig logging for å se hva som faktisk skjer når vi sjekker mot miljø.

Revurderingsaarsak - ser ut som sbh ser KunIDev varianter i prod. Litt midlertidig logging

---

apps/etterlatte-migrering/src/main/kotlin/migrering/PesysRepository.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/Pesyssak.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/start/MigrerSpesifikkSakRiver.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt
apps/etterlatte-migrering/src/main/resources/db/migration/V11__tabell_for_dryrun.sql
libs/etterlatte-migrering-model/src/main/kotlin/no/nav/etterlatte/rapidsandrivers/migrering/MigreringRequest.kt

Tabell for å lagre gyldige dry runs
Tilpasser verifisering til å verifisere ulikt basert på om det er over eller under 18
Hvis over 18:
- Sjekker om har bodd utlands
- Sjekker om har flere avdøde
- Dropper verifisering på om under 18

Migrering dry run over 18

---

apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/CallerContext.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt

Rakk bare ikke å ha den med i oppdatering før jul

Småfiks som skulle vært med i oppdatering til kotlin 1.9

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningServiceTest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/DokumentRoute.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokument/DokumentRouteTest.kt

Følgeoppfølging fra https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/3356 sine ubrukte routes

Fjern ubrukte routes med tilbehør backend

---

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt

Eneste konsekvens er strengt tatt litt annen info i kibana/slack, da `StatusPages` slår inn og logger error uansett. Men tenker det er et steg på veien.

Ved konflikt/optimistisk lås-feil i gosys, håndter som 409 hele veien

---

apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt
apps/etterlatte-migrering/src/test/kotlin/migrering/start/MigreringRiverIntegrationTest.kt
libs/saksbehandling-common/src/main/kotlin/person/Person.kt

- Sjekker for inn/utvandring er kun relevant etter fylte 18
- Sjekker på gradering mot PDL også

Mer presise sjekker på gjenopptatte saker i migrering.

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx

[EY-3295 Valgfritt felt i trydetid er satt til å være obligatorisk](https://jira.adeo.no/browse/EY-3295)

EY-3295 Fjern required regel for trydgetid begrunnelse

---

apps/etterlatte-vedtaksvurdering/build.gradle.kts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/config/ApplicationBuilder.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/metrics/VedtakMetrics.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/metrics/VedtakMetrikkerDao.kt
apps/etterlatte-vedtaksvurdering/src/test/java/no/nav/etterlatte/vedtaksvurdering/metrics/VedtakMetricsTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/TestHelper.kt

- Tatt i bruk jobs i vedtaksvurdering
- Ny gauge for løpende vedtak/ytelser

Metrikker til Grafana for løpende vedtak

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt

Trenger for å feilsøke [FAGSYSTEM-312620](https://jira.adeo.no/browse/FAGSYSTEM-312620)

Logge nyBehandlingRequest i sikkerlogg for debugging

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgaveGosys/GosysOppgaveServiceImplTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/ToggleMinOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/MinOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/tildeling/ByttSaksbehandler.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/tildeling/FjernSaksbehandler.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/tildeling/RedigerSaksbehandler.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/tildeling/TildelSaksbehandler.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts

Mer "riktig" implementasjon enn forutgående #3392

Gosys-oppgaver og optimistisk låsing, sette oppdatert versjon

---

apps/etterlatte-saksbehandling-ui/client/package.json
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/Brevutfall.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/hjelpeTekster/AldersgruppeHjelpeTekst.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/hjelpeTekster/EtterbetalingHjelpeTekst.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/Virkningstidspunkt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/components/hjelpeTekst/HjelpeTekst.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/components/maanedVelger/ControlledMaanedVelger.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/components/radioGruppe/ControlledRadioGruppe.tsx

[EY-2585](https://jira.adeo.no/browse/EY-2585)

Error meldinger i valiedering av brevutfall skjema

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/RedigerbartBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/TilbakestillOgLagreRad.tsx

[EY-3298 Knapper i brev er er posisjonert feil](https://jira.adeo.no/browse/EY-3298)

EY-3298 - forbedring av knapper i redigerbart brev

---

apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/SaksbehandlerMedRoller.kt
gradle/libs.versions.toml
libs/etterlatte-kafka/src/test/kotlin/IntegrationTest.kt
libs/etterlatte-ktor/src/main/kotlin/AuthorizationPlugin.kt
libs/etterlatte-ktor/src/main/kotlin/JWTTokenClaimsUtils.kt
libs/etterlatte-ktor/src/main/kotlin/RestModule.kt
libs/etterlatte-ktor/src/main/kotlin/no/nav/etterlatte/libs/ktorobo/AzureAdClient.kt
libs/etterlatte-ktor/src/main/kotlin/no/nav/etterlatte/security/ktor/ClientCredentialAuthProvider.kt
libs/etterlatte-ktor/src/main/kotlin/no/nav/etterlatte/security/ktor/DefaultOAuth2HttpClient.kt

Har testet et par apper lokalt

Bump nav-token-support 3.2.0 -> 4.1.0

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagHenter.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/OppsummeringOppgavebehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/validator.ts
libs/saksbehandling-common/src/main/kotlin/grunnlag/Grunnlagsopplysning.kt

[FAGSYSTEM-313388](https://jira.adeo.no/browse/FAGSYSTEM-313388)

Opprette behandling uten gjenlevende og/eller innsender

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
libs/etterlatte-regler/src/main/kotlin/regler/PeriodisertGrunnlag.kt

Beregning krever et periodisertgrunnlag visstnok...
Se bakgrunn: https://jira.adeo.no/browse/EY-2399

Fjern tomt søskengrunnlag

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/Familieforhold.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/omstillingsstoenad/FamilieforholdOmstillingsstoenad.tsx

Man trenger informasjon om ut-/innvandring for avdød for å vurdere blant annet utenlandstilknytning.

Viser persongalleriet uansett for omstillingsstønad

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/StartInformasjonsbrevgenereringRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/migrering/FiksEnkeltbrevRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/migrering/OpprettVedtaksbrevForMigreringRiver.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/InformasjonsbrevTest.kt
apps/etterlatte-migrering/src/main/kotlin/migrering/pen/PenKlient.kt
apps/etterlatte-oppdater-behandling/build.gradle.kts
apps/etterlatte-oppdater-behandling/src/main/kotlin/Application.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/OpprettBrevRiver.kt
apps/etterlatte-oppdater-behandling/src/test/java/OpprettBrevRiverTest.kt
libs/etterlatte-ktor/src/main/kotlin/no/nav/etterlatte/token/BrukerTokenInfo.kt

Avhengig av https://github.com/navikt/pensjonsbrev/pull/441

Brev utsatt klagefrist

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/vilkaar/OmstillingstoenadVilkaar.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt

Ble tatt bort ved en feil ved fjerning av feature toggles.

Legg til vilkår for avdødes medlemskap i EØS.

---

apps/etterlatte-behandling/src/main/resources/db/migration/V84__oppgavetype_index.sql

Pga denne: https://console.cloud.google.com/sql/instances/etterlatte-sakogbehandlinger/insights;database=sakogbehandlinger;duration=P7D;trace=61700cd8fe8fd1d8051528bdc6de63c2;span=a372844e9e9e06ef;query_hash=17798812228167138430;sort_by=TOTAL_EXEC_TIME/executed?project=etterlatte-prod-207c
Avg execution time: 80.54 ms
Times called: 1,687
Avg rows returned: 21,907.909
```
SELECT
o.id,
o.status,
o.enhet,
o.sak_id,
o.type,
o.saksbehandler,
o.referanse,
o.merknad,
o.opprettet,
o.saktype,
o.fnr,
o.frist,
o.kilde
FROM
oppgave o
INNER JOIN
sak s
ON
o.sak_id = s.id
WHERE
o.type = ANY($1)
AND s.adressebeskyttelse IS NULL
OR (s.adressebeskyttelse IS NOT NULL
AND (s.adressebeskyttelse != $2
AND s.adressebeskyttelse != $3))
```
Plan som kjøres:
```
Nested Loop  (cost=0.28..229.30 rows=1 width=169) …
```

Lagt til index på Oppgave.type

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevoppretter.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/StartInformasjonsbrevgenereringRiver.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/InformasjonsbrevTest.kt

Sjå brev 1255 for eksempel på korleis brevet ser ut no: 
https://gjenny.intern.dev.nav.no/person/02111266762?fane=BREV

Rette informasjonsbrev til å bruke spesifisert mal frå river

---

apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-klage/.nais/dev.yaml
apps/etterlatte-klage/.nais/prod.yaml

Rydder også litt bort fra dev-konfigen

Produksjonsoppsett for etterlatte-klage

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt

slik at typesjekken (dvs første klausulen) ikke ignoreres

Korrigert hentOppgaver-query AND/OR-klausul 

---

apps/etterlatte-klage/.nais/prod.yaml

Gikk litt for raskt i svingene 😅

Fikser manglende external i klage-prod-config

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/ferdigstilloppgave/FerdigstillOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/handling/StartOppgavebehandling.tsx

Tillate lukking av oppgave hvor journalpost ikke tilhører gjenny

---

apps/etterlatte-vedtaksvurdering/src/test/java/no/nav/etterlatte/vedtaksvurdering/metrics/VedtakMetricsTest.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt
gradle/libs.versions.toml
libs/etterlatte-ktor/src/test/kotlin/RestModuleTest.kt

fikset en deprecation + et par linjer som ikke ble brukt videre

Bumped io.mockk

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt

Slik har vi historikk på kabal-hendelser

Registrerer behandlingshendelse for kabalsvar

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiUtils.ts
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt

Ref. feil som har dukket opp i loggen ganske mange ganger den siste uken. 
https://logs.adeo.no/app/r/s/zOo82

Forbedre feilmelding til sb ved feil mot trygdetid grunnlag

---

apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/prod.yaml

Legger kun til ny ingress, scope, og outbound for å kunne teste lokalt først.

Legge til ny ingress for regoppslag

---

apps/etterlatte-behandling/src/main/resources/db/migration/V86__avslutt_duplikate_hendelser.sql

Tar også bort oppgavene. Scriptet er testet i dev med manuelle transaksjoner.

Lukker hendelser som er duplikate

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/Behandlingsliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/Samordning.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/vedtak/typer.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/vedtaksvurdering.ts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/Samordningsdata.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/SamKlient.kt

- Lenke i oversikt:
- Ved klikk:

EY-3293 UI for samordningsinfo

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/components/datoVelger/ControlledDatoVelger.tsx

Liten quick fiks på at man ikke får opp eksisterende verdier når man skal redigere trygdetid [EY-3311](https://jira.adeo.no/browse/EY-3311)

EY-3311 Legge til mulighet for default value for controlled datovelger

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafClient.kt
apps/etterlatte-brev-api/src/main/resources/graphql/dokumentoversiktBruker.graphql
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/VelgJournalpost.tsx
apps/etterlatte-saksbehandling-ui/client/src/utils/formattering.ts

Fjerne filtrering av type siden vi ønsker å vise _alle_ typer: 
- Inngående
- Utgående
- Notat

Hotfix: Sikre uthenting av ALLE journalposttyper

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt

De er allerede lagret og oppdatert i databasen, så nyttig å ha de på dto'en også

Henter ut feltene journalpostid/bestillingsid for brev

---

apps/etterlatte-samordning-vedtak/src/main/resources/logback.xml

Ref masse debug i kibana, validering av tokens.
https://logback.qos.ch/manual/configuration.html#defaultValuesForVariables

Korrigert fallback loglevel for samordning

---

apps/etterlatte-institusjonsopphold/.nais/dev.yaml
apps/etterlatte-institusjonsopphold/.nais/prod.yaml
apps/etterlatte-institusjonsopphold/src/main/kotlin/Application.kt
apps/etterlatte-institusjonsopphold/src/main/kotlin/InstitusjonsoppholdKlient.kt
apps/etterlatte-institusjonsopphold/src/main/resources/application.conf
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgavelistafiltre.ts

Testet OK i dev. Dette gjør at vi kan fjerne enda mer kode fra vår egen proxy.

Koble oss på institusjon sin egen proxy i stedet for å bruke vår egen

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BrevApiKlient.kt
apps/etterlatte-saksbehandling-ui/client/src/components/klage/brev/KlageBrev.tsx

Gir også saksbehandler muligheten til å redigere tittel i frontend

Setter tittel for innstillingsbrev til KA

---

apps/etterlatte-behandling/src/test/kotlin/VerdikjedeTest.kt
apps/etterlatte-fordeler/src/test/kotlin/fordeler/FordelerRiverTest.kt
apps/etterlatte-grunnlag/src/main/kotlin/Application.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagHendelserRiver.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/rivers/GrunnlagHendelserRiver.kt
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/itest/RapidTest.kt
apps/etterlatte-gyldig-soeknad/src/test/kotlin/no/nav/etterlatte/gyldigsoeknad/omstillingsstoenad/InnsendtSoeknadRiverTest.kt
apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/PersonHendelseFordeler.kt
apps/etterlatte-hendelser-pdl/src/test/kotlin/hendelserpdl/IntegrationTest.kt
apps/etterlatte-hendelser-pdl/src/test/kotlin/hendelserpdl/PersonHendelseFordelerTest.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/PdlHendelserRiver.kt
apps/etterlatte-oppdater-behandling/src/test/kotlin/regulering/ReguleringFeiletRiverTest.kt
apps/etterlatte-opplysninger-fra-soeknad/src/main/kotlin/no/nav/etterlatte/opplysningerfrasoknad/StartUthentingFraSoeknadRiver.kt
apps/etterlatte-opplysninger-fra-soeknad/src/test/kotlin/no/nav/etterlatte/opplysningerfrasoknad/OpplysningsuthenterOmstillingsstoenadTest.kt
apps/etterlatte-opplysninger-fra-soeknad/src/test/kotlin/no/nav/etterlatte/opplysningerfrasoknad/StartUthentingFraSoeknadRiverTest.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/BehandlinghendelseRiver.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/KlagehendelseRiver.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/common/UtbetalingEventDto.kt
apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/VedtakHelper.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/AttestertVedtakRiver.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/SamordningMottattRiverTest.kt
apps/etterlatte-vilkaarsvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/MigreringRiverTest.kt
apps/etterlatte-vilkaarsvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRiverTest.kt
libs/etterlatte-pdl-model/src/main/kotlin/pdlhendelse/PdlHendelser.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/IkkeStandardiserteKeys.kt

Kjens mykje tryggare å bruke konstantar enn inline strings

Bruker mest mogleg samme konstantar for r&r-bruken vår

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/SamKlient.kt

Korrigert manglende queryparams i request mot SAM

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BrevApiKlient.kt
apps/etterlatte-saksbehandling-ui/client/src/components/klage/brev/KlageBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/formkrav/KlageFormkravRedigering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/formkrav/KlageFormkravVisning.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurderingFelles.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurderingRedigering.tsx

Etter en rask gjennomgang med fag var det noen klagetekster som skal justeres

EY-3323 Justerer klagetekster

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/BrevEventTypes.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/DistribuerBrevRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/migrering/FiksEnkeltbrevRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/migrering/OpprettVedtaksbrevForMigreringRiver.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/DistribuerBrevRiverTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiverTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerTest.kt

Bruke egen metode for eventname

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelseDTO.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/EtterbetalingBrevTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/bp/InnvilgetHovedmalBrevDataTest.kt

Dersom vi har løpende utbetaling, skal denne lukkes ved bruk av datoTom fra etterbetaling i etterbetalingstabellen i brev.

Lukker perioder for etterbetaling i brev

---

apps/etterlatte-institusjonsopphold/src/main/kotlin/BehandlingKlient.kt
apps/etterlatte-institusjonsopphold/src/main/kotlin/InstitusjonsoppholdKlient.kt
apps/etterlatte-institusjonsopphold/src/main/kotlin/kafka/KafkaConsumerInstitusjonsopphold.kt

Sikre at kun én og én hendelse blir kjørt, og at appen ikke hopper over en hendelse dersom den feiler.

Forbedre feilhåndtering på institusjonshendelser

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/Samordning.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/vedtak/typer.tsx
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/Samordningsdata.kt

avhengig av https://github.com/navikt/sam/pull/148

Vise info om TP-ordning i samordningsbildet i stedet for tssID

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/Familieforhold.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/RedigerFamilieforhold.tsx

[FAGSYSTEM-315044 Familiebildet i Gjenny](https://jira.adeo.no/browse/FAGSYSTEM-315044)

Endre label i rediger familieforhold basert på BP eller OMS

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/Slate.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/EndringHovedmalBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/VedleggBP.kt

Vise riktig vedlegg på Barnepensjon revurdering.

Fix barnepensjon revurdering vedlegg

---

apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningHendelseHandler.kt

https://nav-it.slack.com/archives/C01PG1JM9D4/p1706599488679579

Skip samordningsmelding i prod, vedtak (fom 1.1.2024) er iverksatt og er ikke etterbetaling

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx

[EY-3333 Spinner hvis man har en bruker med grunnlag men ikke sak](https://jira.adeo.no/browse/EY-3333)

Fikse at søk loader i det uenderlige

---

apps/etterlatte-statistikk/src/main/kotlin/statistikk/database/SakRepository.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/Sak.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
apps/etterlatte-statistikk/src/main/resources/db/migration/V32__add_relatert_til_column.sql
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/SakRepositoryTest.kt

For å kunne se hvilke vedtak som er klaget på må vi mappe ut behandlingsid'en til vedtaket klagen gjelder

EY-3376: Mapper ut behandlingsId for vedtaket klagen gjelder

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/MigreringBrevDataService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/PDFGenerator.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/EndringHovedmalBrevData.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/InnvilgetBrevDataBP.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/OmregnetBPNyttRegelverk.kt

Ref https://nav-it.slack.com/archives/C05F6TP0HJM/p1706272473892989
Heng saman med https://github.com/navikt/pensjonsbrev/pull/490

Oppdater migreringsbrev

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt

Kaste feilmeldinger som gir litt mer mening for saksbehandler.

Forbedre feilmeldinger for manglende brøk/trygdetid i brev

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt

Svare NoContent ved skip av sam-melding

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt

```
io.ktor.client.call.NoTransformationFoundException: Expected response body of the type 'class no.nav.etterlatte.libs.common.vedtak.VedtakDto' but was 'class io.ktor.utils.io.ByteBufferChannel'
In response from `http://etterlatte-vedtaksvurdering/vedtak/samordnet/11574`
Response status `200 OK`
Response header `ContentType: null` 
Request header `Accept: application/json`
You can read how to resolve NoTransformationFoundException at FAQ: 
https://ktor.io/docs/faq.html#no-transformation-found-exception
at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:94)
at no.nav.etterlatte.VedtakServiceImpl$samordnetVedtak$1.invokeSuspend(VedtakService.kt:108)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at …
```

Send ved dto i respons selv ved skip av sam-melding

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/ToggleMinOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgavelistafiltre.ts
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaverTable/OppgaverTable.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaverTable/OppgaverTableHeader.tsx

Ikke 100% ferdig, men slenger den ut slik at jeg husker det før jeg stikker på samling. Inføring av sortering på frist og fnr i oppgaveliste på gjenny

Ey 3282 sortering av oppgaveliste

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstilling.kt

Hadde gjort en litt feil antagelse i forenklingen av brevdatamapperen.

Kan ikke legge BrevDataFetcher på toppnivå siden ikke alle brev er på behandling

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/vilkaar/OmstillingstoenadVilkaar.kt

Oppdaterer lenker for vilkår som vises for omstillingsstønad. Også lagt på flere lovreferanser.

Oppdaterer vilkaar-lenker

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivService.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt

Opprydding og sikre at navn er satt

Hotfix: AvsenderMottaker krever navn

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/VergeFeilhaandtering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottaker.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottakerModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/VergeadressePanel.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/grunnlag.ts

Henter den alltid fra PDL for søkers fnr, uavhenging av grunnlaget for eventuell behandling.

Fikser manglende visning av verges adresse uten behandling.

---

apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/Tjenestepensjon.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/TjenestepensjonKlient.kt

Pga mange error-meldinger i prod i dag, ref https://nav-it.slack.com/archives/C043C5ZGW5T/p1706856364435849

Refaktorert logging av 404 ved kall til TP-registeret

---

apps/etterlatte-samordning-vedtak/.nais/dev.yaml

Kun i dev enn så lenge, ref https://nav-it.slack.com/archives/C01KJ597UAU/p1706872834881189

Tilgang til å lese vedtak for ny app i selvbetjening pensjon

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/Brevkoder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/EtterlatteBrevKode.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Varselbrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts

Moglegheit for å hoppe over steget gjenstår, men er ikkje sikker på at vi treng det per no. Kan i så fall bli separat jiramelding.

EY-3405: Introduserer eit varselbrev-steg i behandlingsflyten

---

apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BrevutfallException.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoRoutesTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/BehandlingTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgetDTOTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/Brevutfall.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallVisning.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/hjelpeTekster/FeilutbetalingHjelpeTekst.tsx
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/BrevutfallDto.kt
libs/saksbehandling-common/src/main/kotlin/behandling/Brevutfall.kt

Gjelder ved revurdering av omstillingsstønad.
ToDo:
___
EY-3359

Saksbehandler må velge utfall for tilbakekreving for brev

---

apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageRoutesIntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageAvvisningRedigering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurderingForms.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurderingRedigering.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Klage.ts

Felleskode flyttet til KlageVurderingForms.tsx

EY-3424: Utkast til "velg utfall" når klagen skal avvises. 

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/HandlingerForOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/PersongalleriBarnepensjon.tsx
apps/etterlatte-trygdetid-kafka/src/main/kotlin/no/nav/etterlatte/trygdetid/kafka/MigreringTrygdetidHendelserRiver.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/migrering/MigreringService.kt
libs/etterlatte-migrering-model/src/main/kotlin/no/nav/etterlatte/rapidsandrivers/migrering/MigreringRequest.kt

- Oppgave som lages av gjenopprettelse peker til manuell behandling frontend
- Oppgave fra gjenopprettelse lukkes når manuell behandling blir opprettet
- Manuell opprettelse har betingelser for GJENOPPRETTET slik som for PESYS
- Oppgave inneholder pesysid i merknad som senere parset ut for å preutfylle manuell behandling
- Fnr finnes på oppgave allerede og brukes også til manuell behandling
Rydding:
- Endrer ident fra GJENOPPRETTA til EY rundt omkring

Manuell oppgave til behandling

---

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt
apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/oppgave/OppgaveKlient.kt
apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filter/oppgavelistafiltre.ts
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgavemodal/GosysOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaverTable/OppgaverTableRow.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/BehandleJournalfoeringOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/VelgJournalpost.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/fnr.ts
libs/etterlatte-oppgave-model/src/main/kotlin/Oppgave/OppgaveIntern.kt

Henger sammen med #3679 
Noen av de nullable feltene kan gjøres non-nullable så fort de siste oppgavene i prod blir behandlet.

EY-3166 Oppdatere GosysOppgave iht. manuell journalføring

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/PersongalleriBarnepensjon.tsx

- Utledes til Vedtektsloesning/kilde (Gjenny,Pesys,Gjenopprettet)
- Har også gjort små utbedringer på feilhåndtering og backendfiks på bruk av inTransaction

Manuell behandling - Spørsmål om er migrering pesys endres til om det er løpende eller opphørt i Pesys

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/klage/AvvistKlageFerdigData.kt

Se PR i pensjonsbrev for selve malene https://github.com/navikt/pensjonsbrev/pull/521

Mapper ferdigstilling av avvist klagebrev

---

apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/Application.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/AppContext.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseDao.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelsePoller.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelsePublisher.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiver.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiverTest.kt
apps/etterlatte-vedtaksvurdering-kafka/.run/etterlatte-vedtaksvurdering-kafka.dev-gcp.run.xml
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/Application.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/rivers/AldersovergangRiver.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/resources/logback.xml
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/rivers/AldersovergangRiverTest.kt
libs/etterlatte-vedtaksvurdering-model/src/main/kotlin/VedtakAldersovergangStepEvents.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/AldersovergangerKeys.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/IkkeStandardiserteKeys.kt

fortsettelse av #3692, mindre størrelse på PR

EY-3355 Lytte på hva som skjer med utsendte hendelser

---

apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseDao.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiver.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiverTest.kt

Har sjekket at dersom man kjører oppdateringen x2 så blir det et korrekt array av meldinger i kolonnen

EY-3355 Lagre behandlede meldinger i hendelsen sin rad

---

apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseDao.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelsePoller.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiver.kt

EY-3355 Ferdigstille hendelse

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/underkjent.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/barnepensjon/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/utils/formattering.ts

Fikser også html-error som har vært i `Person.tsx` altfor lenge.

Bruke date-fns for å ta med 'kl.' i datovisning

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-oppdater-behandling/build.gradle.kts
apps/etterlatte-oppdater-behandling/src/main/kotlin/Application.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/BehandlingService.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseRiver.kt
apps/etterlatte-oppdater-behandling/src/test/kotlin/TidshendelseRiverTest.kt

Skal purre om detaljer på hva som skal inn i oppgaven. Må utvide DTOen / opprette ny da, overraskende hvor få felter den har, men kanskje noen detaljer er mer ment for `behandling` å vite/avgjøre?

EY-3355 Lytte på hendelse for å opprette oppgave

---

apps/etterlatte-oppdater-behandling/src/main/kotlin/BehandlingService.kt

```
io.ktor.client.plugins.ClientRequestException: Client request(POST http://etterlatte-behandling/oppgaver/1153/opprett) invalid: 404 Not Found. Text: "{"status":404,"detail":"Kunne ikke finne ønsket ressurs","code":"NOT_FOUND","meta":null}"
at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:54)
at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
at io.ktor.client.plugins.HttpCallValidator.validateResponse(HttpCallValidator.kt:51)
at io.ktor.client.plugins.HttpCallValidator.access$validateResponse(HttpCallValidator.kt …
```

EY-3355 Korrigert api-path

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/OverstyrtTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx

OverstyrtTrygdetid - tekster oppdateres etter ønske fra fag - og flyttes til etter fremtidig.

EY-3408 - flytt/endre poengår i norge

---

apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/bosattUtland/EessiPensjonLenke.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/bosattUtland/MottatteSeder.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/bosattUtland/SkalViseBosattUtland.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/Behandlingsliste.tsx
apps/etterlatte-saksbehandling-ui/docker-compose.yml
apps/etterlatte-saksbehandling-ui/server/src/config/config.ts

EY-3461 Legge til globus-lenke til EP-Gjenny

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/job/SaksbehandlerNavnJob.kt

Blokkerer ikke main + rest kall

Saksbehandler jobb, frigi ressurser etter bruk

---

apps/etterlatte-behandling/src/main/kotlin/behandling/sjekkliste/Sjekkliste.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/bosattUtland/BosattUtland.tsx

Liten fix for å forbedre håndteringen av SED'er

EY-3467 - Nytt punkt til sjekklisten og starte med tom liste for utgående SED

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/RedigerbartVedleggHenter.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/EtterlatteBrevKode.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperRedigerbartUtfallVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/FeilutbetalingUtils.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonOpphoer.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadOpphoer.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadRevurdering.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt

Legger til redigerbart forhåndsvarsel for opphør av barnepensjon og omstillingsstønad.

EY-3474: Legger på forhåndsvarsel for opphør av BP og OMS

---

apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoRoutesTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/Brevutfall.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallVisning.tsx

Viser brevutfallsskjemaet dersom det er et opphør med brev

EY-3474: Vise brevutfall ved opphør /m brev

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-behandling/src/main/kotlin/common/klienter/PesysKlient.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/resources/application.conf
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
libs/etterlatte-ktor/src/main/kotlin/no/nav/etterlatte/token/BrukerTokenInfo.kt

Skal benyttes ifm. vurdering om informasjonsbrev ved dødsfall.
EY-3383

Ny klient for å hente ut løpende ytelser fra Pesys.

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaverTable/OppgaverTable.tsx

Gjøre oppgavelista mer kompakt (mindre)

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx

Dette skal jo ikkje leve så lengje.

Rekkjefølgja som var ga teknisk feil

---

apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/AttestertVedtakRiver.kt

Dette er knyttet til en sak i prod (ikke meldt, men observert av @henrikg) nå hvor et vedtak har stått til samordning i over en uke, og det skyldes at prosessen stoppet opp som følge av timeout i kallet til SAM.
- https://logs.adeo.no/app/r?l=DISCOVER_SINGLE_DOC_LOCATOR&v=8.11.4&lz=N4IglgdgJgpgHiAXCAnANhmgLADgMYAMAtCjgQIZECMVMKROAzBUTFQOwBGnU2nWUTiAA0IAE4B7AO4BJaPCQgANhIDmAZwAu5dQAsi5AA6H1RQ5KhECBNDnQjx0mVEUBBdjDAAzLAQBCACIAMgAqAK5gAGpQAEoAokEkDmIwXjBiKWKKAPRGhtlQYOp4EgBu6QDE2QD8APqqALwAFF5gSprp6ogAhE0AlMKaYAC2MIgtksOIENJEzFAApABMAGJQgxLT0n19AGS15M0lSmHDEF29o%2Brq5KowwjAQpXhKOurCSjDlSsJ5SmB4chDCQQYS6CRaYQlCDaSDpAatdqdHpNJoAcgAJFogTA0eMtBIUog8gBlbQdAajbTjcj%2FHQ9UGFG6cT5QHpeYSQWBwRBo9CYXCEEhkSg0OgMZiUNhcHh8AScNHCADWMAAnogXmEtOlhBAYKocezhIZyGJyMMuk0AI5hdLq8wSSyqPCGAaaVWGMaGXRm9QwAY2u3jYZAvC6 …

Ikke svelg eventuell feil ved oppdatering av vedtak til samordning

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/RedigerbartVedleggHenter.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperRedigerbartUtfallVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonOpphoer.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadOpphoer.kt

- Legger på virkningstidspunkt til barnepensjon opphørsbrev
- Flytter virkningstidspunkt til ferdigstillingsdel for oms opphør
- Fikser feil vedlegg

EY-3488: Endrer litt på virkningstidspunkt og vedlegg for brev

---

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt

Lagt til håndtering av `SocketTimeoutException` som vi får ganske ofte. Gir sb litt mer fornuftig tilbakemelding.

EY-3511 Forbedre håndtering av feil fra Gosys

---

apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/Application.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/VedtakService.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/samordning/KorrigerVedtak.kt

Relatert til #3815, se logglenker der
Koden fjernes umiddelbart etter at prod er ok

Korrigere status på vedtak i prod som følge av timeout

---

apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/VedtakService.kt

Korrigert verb

---

apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/aldersovergang/AldersovergangDao.kt

Oppdaget under testkjøring i dev på bruker som har hatt én fødselsdato-oppdatering

EY-3355 Fjerne mulige duplikater i uttrekk
