navikt/pensjon-etterlatte-saksbehandling

- apps/etterlatte-behandling/src/main/kotlin/behandling/Behandling.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingService.kt
- apps/etterlatte-behandling/src/test/kotlin/itest/BehandlingDaoIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/itest/IntegrationTest.kt
- libs/common/src/main/kotlin/behandling/BehandlingStatus.kt
Per idag så har man mulighet å endre 'Kommer soeker til gode' i alla mulige tilstander, f.eks når den er sendt til attestering eller når den er iverksatt o.s.v. 
Denne PR:en ser til att man kan kun endre den verdien hvis behandlinger er i statusen 'under behandling'
> Kan ikke endre 'kommer barnet til gode' hvis behandlingen ikke er under behandling

- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt
Basert på logger fra produksjon feiler pdltjenester i henting av enkelte personer, med json-feil i deserialiseringen på feltet "relatertPersonsIdent" som kreves i vår modell, men ikke er til stede i PDL-responsen.
Setter dermed feltet som optional i vår modell, så det ikke skal feile i mappingen.
Issue: EY-1074
> Relatert persons ident er ikke nødvendigvis satt

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/EndreVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/Virkningstidspunkt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/utils.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/vilkaar/AlderBarn.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/vilkaarsvurdering.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/kilde.ts
- apps/etterlatte-saksbehandling-ui/client/src/store/reducers/BehandlingReducer.ts
Tidligere så vistes ikke spinners eller feilmeldinger når man vurderte 'kommer barnet til gode' på søknadsoversikten.
Har fikset sån att det gjøres det nå og i tillegg gjort noen mindre refaktoreringer. Har begynt å trekke ut domene-typer fra reducer:sen våres, og hellre istedet ha det en annan plass. Synes ikke det hører helt hjemme där. 😊
> Vis feedback til bruker for kommerbarnettilgode på søknadsoversikten

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
Skaper krøll for beregningen dersom noen saker ikke går gjennom beregningsgrunnlagssiden, i tillegg er hypotesen at alle saker skal gjennom når trygdetid kommer på plass. Gjør derfor denne enkle fiksen nå
> EY-1231 fjern filtrering av beregningsgrunnlagssiden i front

- apps/etterlatte-saksbehandling-ui/client/src/store/Store.tsx
Finnes det noen gode grunner til å ikke alltid ha dette på?
> Skru på redux devtools alltid

- apps/etterlatte-saksbehandling-ui/client/src/shared/hooks/useInnloggetSaksbehandler.tsx
Attesteringsløypen fungerte ikke fordi parsing av saksbehandler fra `/modiacontextholder/decorator'` ikke ble rett. Dette er en rask hack for å få parset responsen til ISaksbehandler slik at flyten fortsatt funker
> EY-1347 Hack for å parse saksbehandler fra apikall

- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingJob.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingService.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/config/ApplicationContext.kt
- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingJobTest.kt
- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingServiceKtTest.kt
- Konsistensavstemming er satt opp til å kjøre hver time. Dersom konsistensavstemming allerede er kjørt en dag, gjøres det ikke på nytt. Dette er i testøyemed, og vil endres så snart vi har fått bekreftet fra Oppdrag at konsistensavstemmingen som sendes over ser ok ut.
- Funksjonalitet for å sjekke om konsistensavstemming er kjørt på en gitt dag
> EY-1226: Kjoerer konsistensavstemming hver time

- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
Vi har en (eller flere?) hendelser som ikke har gode data, og dette blokkerer jobben som sjekker alle hendelser å fullføre.
Tar en enkel fiks ut her, så sitter vi kun igjen med de som feiler.
> Fanger feil per hendelse i GrunnlagsendringshendelseJob

- apps/etterlatte-vilkaarsvurdering/build.gradle.kts
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
- Gjør det enklere å se flyten ved henting / opprettelse av vilkårsvurdering
- Eksluderer `slf4j-api` fra `MockOauth2Server` som gjør at det ikke logges under testkjøring
> Legger på mer logging i vilkårsvurdering

- apps/etterlatte-behandling/src/main/kotlin/behandling/Behandling.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/typer.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/vilkaarsvurderingKnapper.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/Soeknadsoversikt.tsx
Nå skal stegmenyn vise de steg man skal gå igenom, og den endrer seg basert på om vilkårsvurderingen er til avslag eller oppfylt.
F.eks ved avslag så trenger man ikke å gå gjennom beregningsgrunnlag og beregningen:
> Flyt i frontend for førstegångsbehandling (EY-1268)

- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
- libs/common/src/main/kotlin/behandling/Grunnlagsendringshendelse.kt
- libs/common/src/main/kotlin/pdlhendelse/PdlHendelser.kt
Sjekker om en grunnlagsendringshendelse eksisterer i databasen fra før når den mottas. Lagrer ikke en ny hendelse dersom det er tilfelle
> EY-1424: lagrer ikke ned dupliserte gr.lag.endringshendelser

- apps/etterlatte-behandling/build.gradle.kts
- apps/etterlatte-behandling/src/main/kotlin/BeanFactory.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagClient.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagHelper.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseDao.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/SamsvarHelper.kt
- apps/etterlatte-behandling/src/main/kotlin/pdl/PdlService.kt
- apps/etterlatte-behandling/src/main/resources/db/migration/V15__add_samsvarmellompdloggrunnlag_remove_korrektipdl.sql
- apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagClientImplTest.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagHelperKtTest.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/SamsvarHelperKtTest.kt
- apps/etterlatte-behandling/src/test/kotlin/itest/BehandlingDaoIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/pdl/PdlServiceTest.kt
- libs/common/src/main/kotlin/behandling/Grunnlagsendringshendelse.kt
- libs/common/src/main/kotlin/grunnlag/Grunnlag.kt
- libs/common/src/main/kotlin/pdlhendelse/PdlHendelser.kt
- libs/testdata/build.gradle.kts
Ved en grunnlagsendringshendelse, kontrolleres det nå at informasjonen i pdl og grunnlaget til saken er ulikt. Dersom grunnlaget er ulikt, lagres dette ned i databasen, og grunnlagsendringshendelsen er klar for uthenting.
> EY-1425: Sammenligner grunnlag mellom pdl og grunnlag

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/GjelderToolTip.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Sammendrag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/Familieforhold.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/Barn.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/Foreldre.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/Soesken.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/OversiktElement.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/gyldigFramsattSoeknad/GyldigFramsattVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/gyldigFramsattSoeknad/OversiktGyldigFramsatt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/EndreVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/KommerBarnetTilGodeVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/OversiktKommerBarnetTilgode.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/Virkningstidspunkt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/styled.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vedtaksbrev/Vedtaksbrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/ManueltVilkaar.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Resultat.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/styled.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/vilkaar/AlderBarn.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/vilkaar/VilkaarGrunnlagsStoette.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/filtere/DropdownColumnFilter.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/header/Search.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/icons/statusIcon.tsx
- Endret til kun 1 H1 på hver side og endret level på de fleste Heading for å gi bedre forståelse av sidestrukteren. 
(EY-1464, EY-1465, EY-1470)
- Fikset feil med popover som gjorde at den ikke lukket seg. (EY-1469)
- Endret layout slik at alle har lik margin og tittel størrelse
- Mindre endringer som aria-hidden på svg og autocomplete off
- Endre Label til p tags. Beholder stilen. (EY-1462)
> Fiks av H-tags og layout

- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/person/grunnlagshendelser/Grunnlagsendringshendelser.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/grunnlagshendelser/styled.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/person/grunnlagshendelser/tekster.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
- apps/etterlatte-saksbehandling-ui/server/src/index.ts
- apps/etterlatte-saksbehandling-ui/server/src/mockdata/personsok_23011255000.json
- libs/common/src/main/kotlin/behandling/Grunnlagsendringshendelse.kt
Nå som grunnlagsendringshendelser baserer seg på en sjekk om det er en forskjell mellom det vi har i grunnlag og det som ligger i PDL må dette også vises fram i frontend. Utseende er veldig WIP utviklerdesign, det trengs litt avklaringer her med fag og designere
> Viser grunnlagsendringshendelser basert på samsvar

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingAggregat.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/hendelse/HendelseType.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/hendelse/RegistrerVedtakHendelseFelles.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/manueltopphoer/ManueltOpphoerService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingAggregat.kt
- apps/etterlatte-behandling/src/test/kotlin/itest/IntegrationTest.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/BehandlinghendelseRiver.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/VedtaksvurderingRoute.kt
Fjernet lagring av følgende hendelser: 
`VILKAARSVURDERT`
`BEREGNET`
Og når `IVERKSATT`-hendelsen lagres så oppdaterer vi behandlingsstatusen og.
> Fjern unødvendige behandlingshendelser og endre status for IVERKSATT (EY-1334)

- apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningServiceTest.kt
Manuelle opphør har ingen vilkår i saken som skal vurderes, og trenger en opphørsberegning for å opphøre stønaden riktig mot økonomi slik at den kan behandles i pesys.
> Manuelt opphør hopper over vilkårsvurdering før beregning

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/grunnlag.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Grunnlagsopplysning.ts
- apps/etterlatte-saksbehandling-ui/server/src/index.ts
Ren frontend-endring som henter søskenjusteringsvalgene direkte fra kilden (grunnlag) og ikke metadata i beregning. Saksbehandler må også _faktisk_ ta et bevisst valg, da ingen radiobuttons er valgt på forhånd. Kan ikke gå videre om noen søsken ikke er blitt tatt stilling til. 
Ingen visuelle endringer, så legger ikke ved screenshots
> EY-1565 Forenkle søskenjustering i front og hente fra rett kilde

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/vurderingsboks/VurderingsboksWrapper.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/Spinner.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/vilkaarsvurdering.ts
- apps/etterlatte-saksbehandling-ui/client/src/utils/formattering.ts
Et steg på veien for å kunne legge til kommentar til søskenjustering:
Skal gjenbruke samme "vilkårsboks" som i vilkårsvurdering, så gjorde det om til et gjenbrukbart komponent. Ryddet samtidig opp litt i koden i Vurdering.tsx
Også et steg i riktig retning for EY-1284
> EY-1565 VurderingsboksWrapper som eget component

- apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/VedtakKlient.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/Beregning.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRepository.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
- apps/etterlatte-beregning/src/main/resources/db/migration/V4__legger_til_type.sql
- apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRepositoryTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRoutesTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningServiceTest.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/Beregningsresultat.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/DBTest.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
- libs/common/src/main/kotlin/beregning/BeregningsResultat.kt
Forenkler litt rundt dette med Beregningstyper og DelytelsesId. 
- Fjerner delytelseId - det mappes til denne direkte i Utbetaling
- Flytter `type` til `Beregning` - Lar `GP` bli liggende for å unngå at vedtak brekker. Må gjøre en liten migrering av data der.
- Fjerner `Endringskode`. Denne brukes tilsynelatende ikke til noe fornuftig.
> Bruker beregningstype BP for barnepensjon

- libs/common/src/main/kotlin/beregning/BeregningsResultat.kt
Dataene i vedtak er også migrert til å bruke BP der de tidligere brukte GP
EY-1615
> Fjerner beregningstype GP

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/manueltopphoeroversikt/ManueltOpphoerOversikt.tsx
Hvis ikke får man ikke beregnet riktig. Poster tom søskenflokk, siden det ikke er relevant hvem som er med i opphøret
> EY-1321 Må poste beregningsgrunnlag for manuelt opphør

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/attestering.tsx
Ser på om vi er på `lastPage` i stedet for spesifikt `brev`, som virker mer robust uansett
> EY-1321 Attestering gjøres på siste steg alltid

- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRepository.kt
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
- apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingRepositoryTest.kt
Datoen kan ha blitt endret i ettertid, og vi må derfor spørre behandling hva som er gjeldende før vi lagrer totalresultatet. 
Forenklet løsning ifm. pilot.
Som skjermbildene under viser var det ikke mulig å få rett dato på **Barnepensjon innvilget fom. xx.xx.xxxx**. 
Dette er en midlertidig løsning for pilot, ettersom vi egentlig burde slettet/ugyldiggjort hele den opprinnelige vilkårsvurderingen dersom virk. endrer seg.
EY-1629
> Virkningstidspunkt må oppdateres når man setter nytt utfall

- apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingAggregat.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingService.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/BehandlinghendelseRiver.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/Utils.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/VedtakhendelserRiver.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
- apps/etterlatte-statistikk/src/test/kotlin/statistikk/VedtakhendelserRiverTest.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/StandardKeys.kt
Setter teknisk tid på Kafka-meldingen slik at den ikke blir tidspunktet statistikk leser den, men tidspunktet hendelsen har inntruffet
> EY-1549 Fikser opp i teknisk tid og tar med underkjenn-statistikk

- apps/etterlatte-behandling/src/main/kotlin/Application.kt
- buildSrc/src/main/kotlin/Constants.kt
Oppgraderte med det samme token-valideringsbiblioteka våre.
Opphavleg feila etterlatte-behandling-deploy med denne ktor-versjonen. Det viste seg (etter ein del graving) å vera at vi har hatt feil initaliseringsrekkjefølgje, der vi initialiserer Authentication etter vi har kalt authenticate. Trur eldre ktor må vera meir tolerant mot denslags, for eg kan ikkje sjå at det burde ha funka sånn det er i dagens main.
> Oppgraderer til nyaste Ktor

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/OversiktKommerBarnetTilgode.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/utils.tsx
Fiks for kommentar på jira: "Endre statusikon til Error når en vurdering er vurdert “nei”"
Vi trenger det ikke for Virkningspunkt - det har ikke en "nei" status.
Gyldig fremsatt er ikke implementert enda - så den må gjøres som en del av den.
> EY-1284 - sett ikon for kommer barnet til gode.

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/KommerBarnetTilGodeVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/Virkningstidspunkt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Resultat.tsx
- apps/etterlatte-saksbehandling-ui/client/src/store/reducers/BehandlingReducer.ts
- apps/etterlatte-saksbehandling-ui/client/src/tests/behandling-felles-utils.test.tsx
Beregning hentes (fortsatt) først i Beregningssteget. Lagres i redux, ettersom man ikke kan kan endre beregningsgrunnlag uten å lage en ny beregning. Når beregningsgrunnlaget endres, så slettes også beregningen i redux
I tillegg er stegmenyen nå knyttet opp til behandling.status, og for å unngå å fetche behandlingen på nytt _hele_ tiden, så blir også denne statusen oppdatert i redux på de forskjellige actionsa
> EY-1631 Fjern beregning fra hentBehandling og bruk riktig status i stepper

- .github/workflows/app-etterlatte-behandling.yaml
- .github/workflows/app-etterlatte-beregning.yaml
- .github/workflows/app-etterlatte-brev-api.yaml
- .github/workflows/app-etterlatte-brreg.yaml
- .github/workflows/app-etterlatte-fordeler.yaml
- .github/workflows/app-etterlatte-grunnlag.yaml
- .github/workflows/app-etterlatte-gyldig-soeknad.yaml
- .github/workflows/app-etterlatte-hendelser-pdl.yaml
- .github/workflows/app-etterlatte-medl.yaml
- .github/workflows/app-etterlatte-oppdater-behandling.yaml
- .github/workflows/app-etterlatte-opplysninger-fra-inntektskomponenten.yaml
- .github/workflows/app-etterlatte-opplysninger-fra-pdl.yaml
- .github/workflows/app-etterlatte-opplysninger-fra-soeknad.yaml
- .github/workflows/app-etterlatte-pdltjenester.yaml
- .github/workflows/app-etterlatte-statistikk.yaml
- .github/workflows/app-etterlatte-testdata.yaml
- .github/workflows/app-etterlatte-utbetaling.yaml
- .github/workflows/app-etterlatte-vedtaksvurdering.yaml
- apps/etterlatte-brreg/build.gradle.kts
- apps/etterlatte-fordeler/build.gradle.kts
- apps/etterlatte-gyldig-soeknad/build.gradle.kts
- apps/etterlatte-hendelser-pdl/build.gradle.kts
- apps/etterlatte-medl-proxy/build.gradle.kts
- apps/etterlatte-oppdater-behandling/build.gradle.kts
- apps/etterlatte-opplysninger-fra-inntektskomponenten/build.gradle.kts
- apps/etterlatte-opplysninger-fra-pdl/build.gradle.kts
- apps/etterlatte-tilbakekreving/build.gradle.kts
- apps/etterlatte-utbetaling/build.gradle.kts
- buildSrc/src/main/kotlin/Constants.kt
Dersom man oppdaterer libs som andre tjenester har avhengigheter til skal dette bygges i pr. Tilsvarende skal en merge til main trigge en redeploy av tjenesten.
EY-1644
> Fikser avhengigheter for tjenester under path i workflows basert på build.gradle

- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
@simejo Det er rett og slett fordi ingen vet om det brukes. Så da antar jeg at det er lagt inn uten et reelt behov og kan slettes.
> EY-1645 Fjerne oppdatering av behandlingshendelser i vedtak

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingsstatusRoutes.kt
Tidligere så trynte de bara når statussjekken feilet og vi returnerte en 500 internal server error.
I denne PR:en så fanger vi opp når det tryner og returnerer en `409` istedet med en kort feilmelding.
> EY-1650 - Returnere 409 istedet for 500 fra statusroutes på behandling

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
Beregningsgrunnlag viste ingen feilmeldinger dersom apikallet feilet. La inn ApiErrorAlert
> EY-1646 La til errormelding på beregningsgrunnlag ved api errors

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
Bjørn og jeg fikset så Vilkårsvurdering blir hentet fra Redux-state dersom den finnes. Vi dobbeltsjekket at den alltid er up to date, slik at vi ikke ender med en divergert state fra db
> EY-1646 Vilkårsvurdering henter fra redux state om den finnes

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Resultat.tsx
Statusen oppdateres ikke når vi sletter totalvurderingen på vilkårsvurdering. Konsekvensen er at Stepper:n ikke oppdaterer seg og da ser det ut som man kan gjøre ting som man ikke har lov til egentligen.
> Oppdater behandlingsstatus når man sletter totalvurdering

- apps/etterlatte-saksbehandling-ui/client/package.json
- apps/etterlatte-saksbehandling-ui/client/yarn.lock
Fjernet `react-router` ettersom vi har `react-router-dom`
> Fjerne unødvendig packet

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/Virkningstidspunkt.tsx
Oppdaget at virkningstidspunkt ikke ble oppdatert når man oppdaterte begrunnelsen.
En uheldig bieffekt er at man må gå igjennom behandlingen på nytt, men tenker det likevel bør være sånn, @simejo?
> Endring av begrunnelse bør føre til lagring av virkningstidspunkt

- apps/etterlatte-brreg/src/main/kotlin/no/nav/etterlatte/enhetsregister/EnhetsregisterRoute.kt
- apps/etterlatte-brreg/src/test/kotlin/no/nav/etterlatte/enhetsregister/EnhetsregisterRouteKtTest.kt
- apps/etterlatte-brreg/src/test/kotlin/no/nav/etterlatte/enhetsregister/EnhetsregisterRouteTest.kt
Verksemder kan jo heite så mykje forskjellig, så feks ktor sin innebygde escapeIfNeeded tar tak i for mykje. Det å fjerne :// og protokollen før kjens som noko som bør ha veldig låg risiko for falske positive, og samtidig noko som bør ta unna det meste av det problematiske.
Denne rettar dei to snyk reknar som _high severity_ i vår kode: https://app.snyk.io/org/etterlatte/project/5df56718-a6a0-41ac-9342-0024e0568922
> EY-1633: Enkel vasking av input som vi sender direkte vidare

- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagRoutes.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/Oppgavebenken.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/grunnlag.ts
Enkel PR for å unngå 404 ved henting av søskenjustering på en helt ny sak. Dersom søskenjustering ikke er gjort av en saksbehandler _enda_ så er det mer rett å returnere 204 Success enn en failure. Per nå sjekkes det om det er søskenjustering man forsøker å hente ut fra grunnlag for å returnere 204 bare for å unngå å fucke opp evt andre integrasjoner mot endepunktet. Tanken er uansett å flytte ut Søskenjustering fra Grunnlag-db til Beregning-db (https://jira.adeo.no/browse/EY-1618)
To:
> EY-1667 204 på soeskenjustering dersom den ikke finnes (i steden for 404)

- apps/etterlatte-fordeler/src/main/kotlin/Application.kt
For å unngå at fordeler leser alle historiske kafka-meldinger og feiler på disse da de har gått ut på tid, må vi fjerne `seekToBeginning`. Dette ble lagt inn i forbindelse med statistikk-innhenting tidligere.
EY-1677
> Fjerner seekToBeginning når rapids starter opp i fordeler

- apps/etterlatte-beregning/.nais/dev.yaml
- apps/etterlatte-beregning/.nais/prod.yaml
- apps/etterlatte-statistikk/.nais/dev.yaml
- apps/etterlatte-statistikk/.nais/prod.yaml
- apps/etterlatte-statistikk/build.gradle.kts
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/clients/BehandlingKlient.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/clients/BeregningClient.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/clients/BeregningKlient.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/config/ApplicationContext.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/database/SakRepository.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/database/StoenadRepository.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/Beregning.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/Sak.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/StoenadRad.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
- apps/etterlatte-statistikk/src/main/resources/db/migration/V10__add_beregning_column.sql
- apps/etterlatte-statistikk/src/test/kotlin/DBTest.kt
- apps/etterlatte-statistikk/src/test/kotlin/statistikk/VedtakhendelserRiverTest.kt
- apps/etterlatte-statistikk/src/test/kotlin/statistikk/service/StatistikkServiceTest.kt
Dette er nødvendig for stønadsstatistikken for å kunne produsere data på alle aktive ytelser i systemet riktig, og lagres også for saksstatistikk i tilfelle det er nødvendig senere
Setter også opp noen enkle tester for å sjekke at mapping av statistikk er riktig. Sikter på bedre testdekning her etter hvert!
> EY-1174 Lagrer ned beregning for stønad og saksstatistikk

- .github/workflows/app-etterlatte-behandling.yaml
- .github/workflows/app-etterlatte-beregning.yaml
- .github/workflows/app-etterlatte-brev-api.yaml
- .github/workflows/app-etterlatte-grunnlag.yaml
- .github/workflows/app-etterlatte-vedtaksvurdering.yaml
- .github/workflows/app-etterlatte-vilkaarsvurdering.yaml
- apps/etterlatte-behandling/.nais/dev.yaml
- apps/etterlatte-behandling/.nais/prod.yaml
- apps/etterlatte-beregning/.nais/dev.yaml
- apps/etterlatte-beregning/.nais/prod.yaml
- apps/etterlatte-brev-api/.nais/dev.yaml
- apps/etterlatte-brev-api/.nais/prod.yaml
- apps/etterlatte-grunnlag/.nais/dev.yaml
- apps/etterlatte-grunnlag/.nais/prod.yaml
- apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
- apps/etterlatte-vedtaksvurdering/.nais/prod.yaml
- buildSrc/src/main/kotlin/Prometheus.kt
- libs/etterlatte-ktor/build.gradle.kts
- libs/etterlatte-ktor/src/main/kotlin/MetricsRoute.kt
- libs/etterlatte-ktor/src/main/kotlin/RestModule.kt
- libs/etterlatte-ktor/src/test/kotlin/RestModuleTest.kt
Må støtte alle apps som bruker etterlatte-ktor sin restModule()
vi har flere prometheus simple client biblioteker på versjon 0.16 fra transitive - men - må dra inn prometheus client hotspot for å få tak i DefaultExports
VI har 6 apps som bruker restModule. En hadde allerede spec klausul fra før av selv om det ikke var i bruk - så dette legge til i de andre
* etterlatte-behandling
* etterlatte-beregning
* etterlatte-brev-api
* etterlatte-grunnlag
* etterlatte-vedtaksvurdering
* etterlatte-vilkaarsvurdering (hadde det i .nais yaml allerede)
Gjort i Route.metrics() slik at vi kan teste det separat
> EY-1666 - legg til metrics på rest apiene

- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/OppgaveKolonner.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/typer/oppgavebenken.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/typer/oppgavefelter.ts
Rekkefølgen i recorden er også rekkefølgen i nedtrekksmenyen. 
Renamer også "Behandlingtype" -> "Oppgavetype" i UI og i variabelnavn.
> Vis velg øverst for filter på oppgavetype

- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingJob.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/common/Utils.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/config/ApplicationContext.kt
- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingJobTest.kt
- Starter konsistensavstemming kun på dager oppgitt i kjøreplan vi får en gang i året fra økonomi
EY-1718
> Støtte for kjøreplan i konsistensavstemming

- apps/etterlatte-oppdater-behandling/src/main/kotlin/Application.kt
- apps/etterlatte-oppdater-behandling/src/main/kotlin/BehandlingsService.kt
- apps/etterlatte-oppdater-behandling/src/main/kotlin/OmberegningsHendelser.kt
- apps/etterlatte-oppdater-behandling/src/main/kotlin/Reguleringsforespoersel.kt
- apps/etterlatte-oppdater-behandling/src/test/kotlin/ReguleringsforespoerselTest.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/Application.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/LoependeYtelserforespoersel.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/regulering/LoependeYtelserforespoerselTest.kt
- libs/common/src/main/kotlin/behandling/Omberegningshendelse.kt
- libs/common/src/main/kotlin/sak/Sak.kt
- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/EventNames.kt
- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/StandardKeys.kt
App som tar i mot en g-reguleringsmelding og henter ut alle saker for å sende videre til vedtaks-kafka-appen
> EY-1766 Lag hent alle saker-hendelse i kafka-flyten for regulering

- apps/etterlatte-behandling/.nais/dev.yaml
- apps/etterlatte-behandling/.nais/prod.yaml
- apps/etterlatte-beregning/.nais/dev.yaml
- apps/etterlatte-beregning/.nais/prod.yaml
- apps/etterlatte-grunnlag/.nais/dev.yaml
- apps/etterlatte-grunnlag/.nais/prod.yaml
- apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
- apps/etterlatte-saksbehandling-ui/.nais/prod.yaml
- apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml
- apps/etterlatte-vilkaarsvurdering/.nais/prod.yaml
https://docs.nais.io/nais-application/good-practices/?h=shutdown#exposes-relevant-application-metrics
```
If your application only has a single replica, then your users will experience downtime whenever your pod is restarted or moved.
If you wish to avoid unnecessary downtime, your application should run at least 2 replicas.
```
Vedtak er ikke med siden den har en lytter på en rapid..
Godt mulig Vedtak og de andre async appene skal alle ha en leaderElection impl som kun kjører hvis leader slik at man har en backup app der. Men for now tenker jeg dette holder ref nedetiden vi har hatt i dev.
Det er kun vedtak som burde virkelig kanskje trenger denne ekstra implementasjonen slik jeg ser det siden det er en hybrid app.
> Minimum two pods in dev and prod, max 4 in prod 2 in dev

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingsstatusRoutes.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoReguleringTest.kt
- apps/etterlatte-oppdater-behandling/src/main/kotlin/BehandlingsService.kt
- apps/etterlatte-oppdater-behandling/src/main/kotlin/Reguleringsforespoersel.kt
- apps/etterlatte-oppdater-behandling/src/test/kotlin/ReguleringsforespoerselTest.kt
- libs/common/src/main/kotlin/behandling/BehandlingStatus.kt
I Reguleringsflyten oppstår det et problem med de behandlingene som har gjort en beregning (men som fortsatt er under behandling) når grunnbeløpet endres. De vil da ha en beregning med feil grunnbeløp.
For å sørge for at en slik behandling ikke blir iverksatt med feil G, setter vi statusen på behandlinger tilbake til VILKAARSVURDERT for å tvinge saksbehandler til å gjøre en ny beregning med ny G
> Ey 1762 haandtere ikke iverksatt regulering

- apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRoutes.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/klienter/BehandlingKlient.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/klienter/GrunnlagKlient.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/klienter/VilkaarsvurderingKlient.kt
- apps/etterlatte-testdata/src/main/kotlin/Application.kt
- jobs/start-regulering/deploy/dev.yml
- libs/etterlatte-ktor/build.gradle.kts
- libs/etterlatte-ktor/src/main/kotlin/TokenUtils.kt
- libs/etterlatte-token-model/build.gradle.kts
- libs/etterlatte-token-model/src/main/kotlin/no/nav/etterlatte/token/AccessTokenWrapper.kt
- libs/ktor2client-auth-clientcredentials/build.gradle.kts
- libs/ktor2client-onbehalfof/build.gradle.kts
- libs/ktor2client-onbehalfof/src/main/kotlin/AzureAdClient.kt
- libs/ktor2client-onbehalfof/src/main/kotlin/DownstreamResourceClass.kt
- libs/ktor2client-onbehalfof/src/main/kotlin/Tokens.kt
- libs/ktor2client-onbehalfof/src/test/kotlin/AzureAdClientTest.kt
- libs/ktor2client-onbehalfof/src/test/kotlin/DownstreamResourceClientTest.kt
- settings.gradle.kts
Hovudpoenget i denne PR-en er å bruke JWT-en som kjem inn for å sjå om det er ein saksbehandlar eller ei maskin i den andre enden. Gjer det ved å sjekke om oid = sub. (@LarsErikDahl er betre på detaljane på korfor akkurat desse)
Har løyst det ved å pakke inn dagens accessToken-string i eit objekt, som i tillegg tar med seg også sub og oid vidare. Denne wrappinga gjer det også lettare å gjera endringar av denne typen seinare utan å endre ein gasillion signaturar (og er ein liten shoutout til prinsippet om at alle problem i systemutvikling kan løysast ved eit ekstra lag indireksjon)
> EY-1768: Handterer tokens for app-til-app-kommunikasjon annleis enn viss det fins ein saksbehandlar

- .github/dependabot.yml
Det bør halde greitt at vi oppdaterer med minor-versjonane
Frå [dokumentasjonen](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore):
update-types—use to ignore types of updates, such as semver major, minor, or patch updates on version updates (for example: version-update:semver-patch will ignore patch updates). You can combine this with dependency-name: "*" to ignore particular update-types for all dependencies. Currently, version-update:semver-major, version-update:semver-minor, and version-update:semver-patch are the only supported options. **Security updates are unaffected by this setting.**
> EY-1837: Ignorerer patch-versjonar av frontend-avhengnadar

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingsHendelser.kt
- apps/etterlatte-behandling/src/main/kotlin/config/BeanFactory.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/BehandlinghendelseRiver.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
- apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/service/StatistikkServiceTest.kt
bugfiks fra https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/859
SE log:
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `long` from Object value (token `JsonToken.START_OBJECT`)
at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: no.nav.etterlatte.statistikk.river.Behandling["sak"])
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1520)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:14 …
> Send ut behandling som detaljertbehandling for å få riktig objekt ut og

- apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/VedtakKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtak/VedtaksvurderingKlient.kt
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/vedtak.ts
- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/services/VedtakService.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
Legger de fleste endepunktene under /api/vedtak/{behandlingId}/{operasjon} fremfor å ha mange ulike varianter
> Forenkler endepunkter i vedtak slik at de har lik struktur

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseDao.kt
- apps/etterlatte-behandling/src/test/kotlin/IntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/RealFoerstegangsbehandlingServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/RealManueltOpphoerServiceTest.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
- apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/TilbakekrevingDao.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/AvstemmingDao.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingDao.kt
- libs/testdata/src/main/kotlin/behandling/VirkningstidspunktTestData.kt
- For å gå frå Tidspunkt til Timestamp går vi no kun via hjelpemetoden `.toTimestamp()`. Da sikrar vi at det gjerast likt, og gjer at vi slepp å eksponere ut den underliggjande implementasjonen ut frå pakka
- For å opprette `Grunnlagsopplysning.Saksbehandler` går vi no via factory-metoden som allereie fans der. Med det blir det lettare å endre type til Tidspunkt i neste omgang
> EY-1795: Innkapsling av tidspunkt

- apps/etterlatte-behandling/src/main/kotlin/behandling/DetaljertBehandlingDto.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/hendelse/HendelseDao.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/RealFoerstegangsbehandlingServiceTest.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/MaanedStatistikk.kt
- apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/SakRepositoryTest.kt
- apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/StoenadRepositoryTest.kt
- apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/service/StatistikkServiceTest.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/Grensesnittavstemming.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingService.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/avstemmingsdata/GrensesnittavstemmingDataMapper.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingMapper.kt
- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingJobTest.kt
- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/common/UtilsTest.kt
- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingDaoIntegrationTest.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/Vedtakstidslinje.kt
- libs/common/src/main/kotlin/grunnlag/Grunnlagsopplysning.kt
- libs/common/src/main/kotlin/tidspunkt/Klokke.kt
- libs/common/src/main/kotlin/tidspunkt/Tidspunkt.kt
At den underliggjande implementasjonen er `Instant` er ein implementasjonsdetalj som ikkje bør lekke ut av `Tidspunkt`.
Må ta nokre kompromiss for å komme dit i denne PR-en, inkludert å gå tilbake til `Instant.now()` eit par plassar, men eg synes det er verdt det. Det er uansett berre midlertidige tilbakesteg, planen er jo å komme heilt bort frå Instant-bruk.
> EY-1795: Skjul implementasjonsdetalj tidspunkt

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vedtaksbrev/Vedtaksbrev.tsx
Hvis man går inn på en behandling for å attestere, og går direkte til brev, så vises status "Uavklart" i stedet for innvilget, ettersom man ikke har vært innom vilkårsvurdering og populert state.
Før:
Etter:
EY-1865
> Vilkårsvurdering må ligge i state for at sidemenyen skal vises korrekt

- apps/etterlatte-egne-ansatte-lytter/src/main/kotlin/kafka/KafkaConsumerConfiguration.kt
- apps/etterlatte-egne-ansatte-lytter/src/test/kotlin/SkjermingslesingTest.kt
- apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/leesah/KafkaConsumerConfiguration.kt
Siden kafka heartbeat skjer i `.poll()` og vi poller med 8 sek timeout økes den til 20 sek her da prosessering av meldingene kan ta tid.
> Fix test og sett timeout session på pdl

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Sammendrag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Trygdetid.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Beregning.ts
Splitter opp beregningsgrunnlaget slik at den viser søskenjustering kun for barnepensjon. Viser i tillegg riktig ytelse på beregningssammendraget.
EY-1888
> Fjerner søskenjustering i beregningsgrunnlaget for omstillingsstønad

- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/OpprettVedtakforespoersel.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/regulering/OpprettVedtakforespoerselTest.kt
Fant en bug der man gikk videre i flyten trots att ting feilet tidligere. F.eks hvis opprettelse av vedtaket feilet så prøvde man likevel å fatte + attestere det etterpå.
> Ikke gå videre i flyten hvis noe tidligere feiler (EY-1872)

- .github/dependabot.yml
Det held med sikkerheitspatchar pluss minor- og major-versjonar
> Skrur av dependabot-pushinga av patch-versjonar også for gradle-avhengnadar

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/SideMeny/SideMeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumentlisteLiten.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumentoversikt.tsx
Dokumenter åpnes i ny fane. Primærbehovet er at saksbehandler skal ha enkel tilgang til søknaden uten å måtte gå ut av behandlingen. Og de ønsker å ha den oppe på egen skjerm (ny fane).
EY-1891
> Legger til visning av dokumenter i sidemenyen for behandling

- apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/SoeknadStatistikkRiver.kt
- apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/river/SoeknadStatistikkRiverTest.kt
feilende kriterier ble konsevkvent lest ut som null, så det ble feil i integritetssjekken for pakker med feilende kriterier
> Fikser utmapping av liste fra kafka

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/klienter/GrunnlagKlient.kt
- apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/IntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagRoutes.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/OpplysningDao.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagServiceTest.kt
- apps/etterlatte-grunnlag/src/test/kotlin/itest/GrunnlagDaoIntegrationTest.kt
- libs/common/src/main/kotlin/behandling/Grunnlagsendringshendelse.kt
Henter nå ut alle fnr med tilknyttet sak og rolle fra grunnlag i stedet for behandling.
> EY-1820 Flytte grunnlagsrelatert logikk til grunnlagsappen

- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/OpplysningsgrunnlagMapper.kt
- libs/common/src/main/kotlin/grunnlag/Grunnlagsopplysning.kt
- libs/common/src/main/kotlin/grunnlag/Opplysning.kt
Dette gjelder for en adresse på en sak i produksjon.
> EY-1948: Fallbacker til en periode fra 1900-01 hvis periode mangler

- .github/dependabot.yml
Litt hacky og rotete siden dependabot ikke har noen god støtte for å kjøre vanlige oppdateringer uavhengig av sikkerhetsoppdateringer. Derfor en del dobbelt opp...
- **Limit 0** med **daily** tvinger sikkerhetsoppdateringer, siden den har en [låst limit på 5](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit).
- **Limit 10** med **monthly** sikrer månedlig oppdateringer av andre avhegigheter. Satt til søndag slik at vi slipper spam midt i arbeidsdagen.
> Redusere spam fra dependabot

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivService.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt
Det skal også alltid sendes ut på papir, så det ser ikke ut til at det vi har definert under har fungert:
`kanal = "S", // https://confluence.adeo.no/display/BOA/Utsendingskanal`
Det er likevel ingen krise for nå siden barn under 15 år ikke kan ha kodebrikke.
EY-1955
> Vedtaksbrev skal sendes til barnet, ikke gjenlevende forelder.

- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Revurdering.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/domain/RevurderingTest.kt
Manuell revurdering må følge prosessflyten som er definiert idag.
Automatisk behandling skal kunne gjøre alle statusendringer.
> Fiks flyt for manuell/automatisk revurdering

- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlKlient.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/GeografiskTilknytningMapper.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonRoute.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonService.kt
- apps/etterlatte-pdltjenester/src/main/resources/pdl/hentGeografiskTilknytning.graphql
- apps/etterlatte-pdltjenester/src/test/kotlin/TestHelper.kt
- apps/etterlatte-pdltjenester/src/test/kotlin/pdl/PdlKlientTest.kt
- apps/etterlatte-pdltjenester/src/test/kotlin/pdl/mapper/GeografiskTilknytningMapperTest.kt
- apps/etterlatte-pdltjenester/src/test/kotlin/person/PersonRouteTest.kt
- apps/etterlatte-pdltjenester/src/test/kotlin/person/PersonServiceTest.kt
- apps/etterlatte-pdltjenester/src/test/resources/pdl/geografisk_tilknytning.json
- libs/common/src/main/kotlin/person/HentGeografiskTilknytningRequest.kt
- libs/common/src/main/kotlin/person/Person.kt
Splitter opp EY-1787 i flere mindre PR'er.
Denne skal kun gi etterlatte-pdltjenester mulighet å hente geografisk tilknytning
> EY-1787 - steg 2 - PDL tjeneste kan hente geografisk tilknytning

- apps/etterlatte-behandling/.nais/dev.yaml
- apps/etterlatte-behandling/.nais/prod.yaml
- apps/etterlatte-behandling/build.gradle.kts
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ArbeidsFordeling.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/Norg2Klient.kt
- apps/etterlatte-behandling/src/main/kotlin/config/BeanFactory.kt
- apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/TestApp.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/klienter/Norg2KlientTest.kt
Splitter opp EY-1787 i flere mindre PR'er.
Denne skal kun gi etterlatte-behandling mulighet å hente enhet fra Norg2
> EY-1787 - steg 3 - behandling kan hente norg2 enhet info

- apps/etterlatte-saksbehandling-ui/client/src/components/person/saksliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
Vel i denne omgang å vise teksten som automatisk regulering for alle reguleringar, ut frå den hypotesa vi har per no om at vi kun regulerer automatisk.
> EY-1972: Vise regulering som revurderingsårsak til brukaren

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/DokumentRoute.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/Model.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafClient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafService.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/dokument/DokumentRouteTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Brev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/types.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumentoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/dokument.ts
Bare en kjapp fiks for å fjerne 403 error fra loggene. Skal justeres litt mer, men må se hva vi får i respons først siden objektet vi har i dag tydeligvis ikke håndterer 403 error.
> EY-1973 Sikre annen respons ved 403 Forbidden på journalposter

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/config/ApplicationContext.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/BehandlingKlient.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
Sjekker nå at en behandling er i en tilstand hvor den kan beregnes. Det betyr også at det vil være mulig å legge til trygdetid.
Må se litt videre på hvordan vi skal løse eventuelle problemer som oppstår når man har gjort en beregning, men går tilbake og endrer trygdetid. Da må vi tvinge en ny runde gjennom beregning (altså sette status tilbake til VILKAARSVURDERT). Egen oppgave for dette: https://jira.adeo.no/browse/EY-1997
> Tilstandssjekk trygdetid

- apps/etterlatte-behandling/src/main/kotlin/Application.kt
- apps/etterlatte-behandling/src/main/kotlin/Contekst.kt
- apps/etterlatte-behandling/src/main/kotlin/config/BeanFactory.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveServiceImpl.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/domain/Oppgave.kt
- apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/TestApp.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
EnhetService skal gi enheter til en saksbehandler cachet med 15 min.
Den gjøres tilgjengelig på saksbehandler men med en slags lazy (hentes først når den trengs).
I første omgang prøver vi å filtrere oppgaverlisten.
- Er det ikke BehandlingOppgave - så er det ikke filtrert bort.
- Er det BehandlingOppgave med null enhet - så er det ikke filtrert bort (eksisterende data fra før sak ruting)
- Ellers skal det filtreres etter enheter saksbehandleren har.
> EY-1876 - filtrere oppgaveliste utifra enhet til saksbehandler

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/Norg2Klient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/RegoppslagKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafClient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/navansatt/NavansattKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/pdf/PdfGeneratorKlient.kt
- Noen steder brukte brev litt forskjellige strenger for header navn. Bytt til konstant
- Legg til correlation på Norg2Klient
- Bruk getXCorrelationId() istedenfor MDC.get/generate
> etterlatte-brev - bruk X_CORRELATION_ID og getXCorrelationId()

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/OversiktKommerBarnetTilgode.tsx
Tydeliggjør også at det er gjenlevendes adresse som vises.
Grunnen til `props.adresse.poststed || ''` er at poststed tydeligvis ikke finnes i dev, og vil ikke vise `null`
EY-1967
> Vis postnummer og sted i søknadsoversikt

- apps/etterlatte-saksbehandling-ui/client/vite.config.ts
Node 17+ foretrekker IPv6 og skaper trøbbel med mindre man spesifiserer annet i vite config. 
Ref. https://github.com/vitejs/vite/discussions/7620
> endre host for at lokal kjøring skal fungere med node 17+

- apps/etterlatte-behandling/src/main/kotlin/behandling/DetaljertBehandlingDto.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingRoutesKtTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/attesterVedtak.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.test.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/start.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
TLDR:: 
* Mulighet for å manuelt revurdere (til å begynne med, kun regulering)
* Revurdering skal ikke vise brev-siden og skal ikke sende brev hvis `årsaken` er regulering
> EY-1769 Støtt manuell flyt for revurdering (regulering skal ikke sende brev)

- apps/etterlatte-brev-api/build.gradle.kts
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/DistribusjonService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/distribusjon/DistribusjonServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/db/BrevRepositoryIntegrationTest.kt
Brev har flere tabeller med mange felter. Spørringer mot disse tabellene blir mildt sagt vanskelig å lese uten named parameters. I tillegg er det flere steder hvor det burde kjøres rollback dersom en spørring feiler. Drar derfor inn Kotliquery siden mye av dette er støttet ut av boksen, og det brukes nå i flere av prosjektets apper.
> EY-2015 Legge til Kotliquery og forbedre funksjoner

- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/OpplysningsgrunnlagMapper.kt
- apps/etterlatte-grunnlag/src/main/resources/db/migration/V15__setter_alle_fragmenterte_opplysninger_til_aa_vaere_nyeste_fra_pdl.sql
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagServiceTest.kt
- apps/etterlatte-opplysninger-fra-pdl/src/main/kotlin/opplysninger/kilde/pdl/OpplysningsBygger.kt
- libs/saksbehandling-common/src/main/kotlin/grunnlag/Grunnlagsdata.kt
- libs/saksbehandling-common/src/main/kotlin/grunnlag/Opplysning.kt
- libs/testdata/src/main/kotlin/grunnlag/TestDataMaps.kt
- libs/testdata/src/main/kotlin/pdl/PersonTestData.kt
Fragmenteringen av opplysningene skaper problemer når vi henter flere ganger fra PDL, siden gamle opplysninger vi har hentet og brukt i en behandling kan være korrigert i en senere behandling. I stedet for å fragmentere opplysningene fra PDL i separate er de nå lagret som lister, slik at vi kan hente nyeste opplysning (evt. <= en hendelsesid som gir oss historisk grunnlag).
Siden vi allerede har lagret disse opplysningene fra PDL fragmentert (også for saker i produksjon) må vi migrere dataene vi har fra før. Dette blir gjort ved å hente siste grunnlag lagret fra PDL, og populere feltene med verdiene derifra i stedet. Dette betyr at vi vil få duplisert informasjon på alle periodiserte opplysninger, men det ser jeg på som et ikke-problem. I produksjon er det til nå bare gjort uthenting av …
> EY-1968 Lagrer periodiserte opplysninger fra PDL som lister

- apps/etterlatte-testdata/src/main/kotlin/dolly/DollyClient.kt
- apps/etterlatte-testdata/src/main/kotlin/dolly/DollyService.kt
- apps/etterlatte-testdata/src/main/kotlin/dolly/Model.kt
- apps/etterlatte-testdata/src/main/kotlin/testdata/features/dolly/DollyFeature.kt
- apps/etterlatte-testdata/src/main/kotlin/testdata/features/soeknad/SoeknadMapper.kt
- apps/etterlatte-testdata/src/main/resources/templates/dolly/dolly.hbs
- Legge til egen knapp for å sende OMS-søknad. 
- Tilpasse barn/søsken for å gi mening for begge søknader. 
- Markere avdød som brukt (i Dolly) dersom søknad sendes.
> EY-2046 Oppdatere testdata for å støtte OMS

- apps/etterlatte-saksbehandling-ui/client/src/components/person/grunnlagshendelser/tekster.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/person/saksoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/utils.ts
* Vis kun hendelser for når regulering feilet, dette er for att inte påverka produksjon
* Bytt navn på typen for reguleringsamsvar (ref: https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/1279)
> Vis kun grunnbeloeps-hendelser i saksoversikt

- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveServiceImpl.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/domain/Oppgave.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
Saksbehandler må kunne se enhet på oppgave - spesielt hvis de har tilgang til mer enn en enhet.
Dette er kun backend (eksponere enhet på OppgaveDTO).
Tok og fikset det interne Oppgave sealed class tre til å ha hele sak i lik linje til hvordan vi har gjort det med behandlinger.
Frontend fiks tar litt lengre tid - men er lettere å teste når denne er i miljøet :)
> EY-2043 - saksbehandler må kunne se enhet på oppgave

- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/OppgaveKolonner.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/Oppgavebenken.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/typer/oppgavebenken.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenken/typer/oppgavefelter.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts
Vis enhets ID i oppgavelisten (ikke full navn - for å spare plass).
La saksbehandler filtrerer listen.
Siden disse er statisk så er denne første runden altid med - og dropdown har alle mulige kjente verdier.
Senere - hadde det vært veldig fint hvis vi kan bare vise de hvis det er flere enn en i resultatsliste og bare har de som er med i dropdown - men - for nå - så er ikke det så lett uten mye omskriving (tror jeg).
> EY-2043 - saksbehandler må kunne se enhet på oppgave - frontend

- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/common/OppdragDefaults.kt
- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/avstemmingsdata/AvstemmingsdataJaxbTest.kt
Dette for å beregne saker tilbake i tid tidligere enn ved neste månedskjøring.
EY-2057
> Endrer bruk kjøreplan fra J til N i utbetaling

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/ManglerRegelspesifikasjon.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Grunnlagopplysninger.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidBeregnet.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
Mindre pen sak for å markere at en verdi er beregnet i en regel som ikke er spesifisert. Bruker dette for å synliggjøre hvor vi har manglende regelspesifikasjon på OMS.
> Komponent for å synliggjøre manglende regelspesifikasjon i frontend

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
Når vi oppretter vilkårsvurdering for revurdering så er den kopiert fra forrige behandling, d.v.s den er allerede ferdig etter opprettelse.
> Oppdater status til vilkaarsvurdert for revurdering fordi den er kopiert

- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/iverksetting/oppdrag/OppdragJaxbTest.kt
Utvider test for å verifisere bruk av våre egne tjenestespesifikasjoner ikke brekker noe på generering av xml for oppdrag. Grensesnittavstemming og konsistensavstemming har allerede slike tester.
> Sjekker at xml er riktig i test av opprettelse av oppdrag

- get-secret.sh
- Sjekker at .gitignore inneholder .env
- Sjekker at context er **dev-gcp**
- Forenkle input (kan nå skrive _kun_ appnavn, eks: etterlatte-brev-api)
- Scriptet kan kjøres hvor som helst i prosjektet. 
- Støtter uthenting av secrets som ikke er av typen "lokal". Gjør det mulig å kjøre `lokal front -> lokal backend -> dev backend`.
> Liten forbedring av get-secret.sh

- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidBeregningService.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/regler/BeregnTrygdetid.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidBeregningServiceTest.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/regler/BeregnTrygdetidTest.kt
- Justerer opp måneder ved å regne hver 30. dag som en måned i tilfeller hvor total trygdetid består av mange "løse" dager.
- Justerer tilsvarende opp år dersom antall måneder er flere enn 12. 
- Runder av til nærmereste år (ikke alltid opp slik det var tidligere)
EY-2154
> Oppdaterer regler for beregning av trygdetid og avrunding

- apps/etterlatte-beregning/README.md
- apps/etterlatte-beregning/src/main/kotlin/beregning/regler/Beregningstall.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/regler/avkorting/AvkortetYtelse.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/regler/avkorting/InntektAvkorting.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/regler/avkorting/AvkortetYtelseTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/regler/avkorting/InntektAvkortingTest.kt
Fikser også et tilsvarende problem ved beregning av avkortet beløp dersom inntekt er mindre enn 0.5 * grunnbeløp
EY-1961
> Ytelse blir aldri mindre enn 0 ved avkorting

- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BarnepensjonBeregningsGrunnlag.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlag.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagRepository.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/Institusjonsopphold.kt
- apps/etterlatte-beregning/src/main/resources/db/migration/V11__legg_til_institusjons_opphold.sql
- apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnBarnepensjonServiceTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRepositoryIntegrationTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/manueltopphoeroversikt/ManueltOpphoerOversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/beregning.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Beregning.ts
Legger til støtte for institusjonsopphold i beregningsgrunnlag.
Initielt - kun en boolean - kan uvtides senere.
Frontend - oppdatere APIet - men sender bare default verdier opp - frontend skal oppdateres i EY-2170.
> EY-2169 - legg til støtte for beregningsgrunnlag for institusjonsopphold

- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveServiceImpl.kt
Tilgangssjekk var skrevet før vi mappet enhet på endringer - så vi sjekket bare BehandlingOppgave.
Nå er de mappet på samme måte - kjøre samme tilgangssjekk for begge to.
> EY-2201 - sjekk enhet for begge type oppgave

- apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
- apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt
Den skal altid være på fremover - så trenger ikke en bryter lenger.
Denne setter ikke enhet til "not null" - har laget jira EY-2205 for det.
> EY-2204 - fjern sjekk mot SakServiceFeatureToggle.OpprettMedEnhetId

- apps/etterlatte-beregning/src/main/resources/db/migration/V13__temp_migrering_periodisert_soesken_i_beregning.sql
Denne er tenkt til bruk i testing uten at vi trenger en endelig migrering som går til prod og endrer datastrukturen fundamentalt.
Midlertidig med det at denne kolonnen blir fjernet når periodisering av søskenjustering merges inn til main
> Lager en egen kolonne for periodisert søskenjustering (midlertidig)

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingResource.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/person/behandlingsliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/saksoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
Endrer tittel fra `Barnepensjon` til `Saksoversikt` og legger `Sakstype` som en del av behandlingstabellen.
EY-2209
> Saksoversikt tilpasset begge ytelser

- apps/etterlatte-brev-api/docker-compose.yml
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/attestering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/attesterVedtak.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/modal/modal.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Brev.ts
Verifiserer at vedtaksbrev er ferdigstilt _før_ attestering for å sikre at brev-api ikke havner i CrashLoopBackoff.
Viser nå dette dersom brev har ugyldig status:
> EY-2178 Sikre at brev er ferdigstilt før attestering

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingResource.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/RealGenerellBehandlingServiceTest.kt
- libs/saksbehandling-common/src/main/kotlin/behandling/Utenlandstilsnitt.kt
Fag har kommet med ny sett av verdier for Utenlandstilsnitt enum samt bedt om at det er synlig i saksoversikt for person som bruker behandling sammendrag - så må settes der og.
> EY-2189 - endring i enum verdier samt ekspoenere i behandling sammendrag

- apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/InntektAvkortingService.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
- apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt
- apps/etterlatte-beregning/src/main/resources/db/migration/V15__rename_beregnet_avkortinggrunnlag.sql
- apps/etterlatte-beregning/src/main/resources/db/migration/V16__rydde_avkortinggrunnlag.sql
- apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRepositoryTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/InntektAvkortingServiceTest.kt
- Endret navn på BeregnetAvkortingGrunnlag til Avkortingsperiode og flyttet den ut av AvkortingGrunnlag
- Forbedret transaksjonshåndtering ved å lagre hele Avkorting i en public metode og la repo stå for transaksjonen
- Renamet tabeller til å passe ny domenenavn og fjernet ubrukte kolonner
> Ey 2127 rydde avkorting navngivning

- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/regulering/services/VedtakService.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingRouteTest.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
- libs/saksbehandling-common/src/main/kotlin/vedtak/VedtakDto.kt
Quickfix, det er kanskje bedre med et eget endepunkt for systembruker som tillater overstyring
> Migrerte saker skal ikke sende brev

- apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnOmstillingsstoenadService.kt
- apps/etterlatte-beregning/src/main/kotlin/klienter/TrygdetidKlient.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnOmstillingsstoenadServiceTest.kt
Med eksisterende klient - så ender vi opp å returnere en TrygdetidDto men med verdi null.
Denne endring gjør at vi sier det ved å endre fra TrygdetidDto til TrygdetidDto?
> TrygdetidKlient kan få null hvis response er 204

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
Tok litt tid før jeg så at `verdi.toString()` returnerte strengen "null", som krasjet mappingen.
> Fiks visning og mapping av perioder uten beregning

- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
Det er litt missbruk av REST spesifikasjonen å sende med det oppdaterte objektet tilbake ved `delete`, men følger "etablert" praksis fra vilkårsvurdering for nå.
EY-2250
> Nytt endepunkt for å slette trygdetidsgrunnlag

- .github/workflows/app-etterlatte-beregning-kafka.yaml
- .github/workflows/app-etterlatte-trygdetid-kafka.yaml
- .github/workflows/lib-etterlatte-institusjonsopphold-model.yaml
- .github/workflows/lib-etterlatte-token-model.yaml
- .github/workflows/lib-etterlatte-vilkaarsvurdering-model.yaml
For beregning-kafka og trygdetid-kafka hadde vi visst ikkje fått med at byggejobben må køyre når koden i sjølve modulen blir endra.
Fiksar med det samme byggejobbar for eit par ganske nye libs
> EY-2263: Fiks byggejobbar som ikkje lyttar på eigen kode

- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingRoutes.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingRoutesKtTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingRoutesTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/person/saksoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
- libs/saksbehandling-common/src/main/kotlin/behandling/RevurderingAarsak.kt
- Oppdaterer dropdown-liste med gyldige revurderingsårsaker basert på sakstype
- Validerer at en ny revurdering ikke kan opprettes for en revurderingsårsak som ikke er støttet for sakstypen
EY-2262
> Viser liste med revurderingsårsaker basert på sakstype

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlagListe.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/styled.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
Lagt til støtte for å vise en liste av perioder, legge til, endre og slette trygdetidsperioder.
Det er nok et par UX-forbedringer man kan gjøre her, men tenkte å la Mari/Julie for teste litt før jeg gjør for mange finjusteringer.
Hvis man trykker "Legg til periode" får man den gamle komponenten opp
> Støtte for flere trygdetidsperioder

- apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
- apps/etterlatte-saksbehandling-ui/.nais/prod.yaml
Frontend har sluttet å deploye, og klager på at host ikke passerer regex-sjekk.
https://github.com/navikt/pensjon-etterlatte-saksbehandling/actions/runs/5185458336/jobs/9345428892
```
Error: Status: failure: nais.io/v1alpha1, Kind=Application, Namespace=etterlatte, Name=etterlatte-saksbehandling-ui: Application.nais.io "etterlatte-saksbehandling-ui" is invalid: spec.accessPolicy.outbound.external[1].host: Invalid value: "https://login.microsoftonline.com/": spec.accessPolicy.outbound.external[1].host in body should match '^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$' (total of 1 errors)
Error: fatal: deployment failed
```
Verifisert OK i DEV: https://github.com/navikt/pensjon-etterlatte-saksbehandling/actions/runs/518 …
> Fiks outbound for saksbehandling-ui

- apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnBarnepensjonServiceTest.kt
- libs/etterlatte-regler/src/main/kotlin/regler/TomtGrunnlag.kt
Feilen som kjem:
`no.nav.etterlatte.beregning.grunnlag.PeriodiseringAvGrunnlagFeil$IngenPerioder: Ingen perioder for grunnlaget ble gitt for periodisering at no.nav.etterlatte.beregning.grunnlag.PeriodisertBeregningGrunnlag$Grunnlag.<init>(GrunnlagMedPeriode.kt:45) at no.nav.etterlatte.beregning.grunnlag.PeriodisertBeregningGrunnlag.lagGrunnlagMedDefaultUtenforPerioder(GrunnlagMedPeriode.kt:86) at no.nav.etterlatte.beregning.BeregnBarnepensjonService.opprettBeregningsgrunnlag(BeregnBarnepensjonService.kt:257) at no.nav.etterlatte.beregning.BeregnBarnepensjonService.beregn(BeregnBarnepensjonService.kt:79) at no.nav.etterlatte.beregning.BeregnBarnepensjonService$beregn$1.invokeSuspend(BeregnBarnepensjonService.kt)`
> EY-2168: Handterer at grunnlag kan vera tomt

- apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/InntektAvkortingService.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/InntektAvkorting.kt
- apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRepositoryTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/InntektAvkortingServiceTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts
- libs/saksbehandling-common/src/main/kotlin/beregning/BeregningDTO.kt
- Regelberegning for avkorting endret til å bruke virknignstidspunkt og periodisert grunnlag slik at revurdering kun beregner sende inn flere grunnlag men kun beregne fra virkningstidspunkt og fremover
- Lagt til domenelogikk for å sjekke om mottat grunnlag finnes fra før og oppdatere eller legge til hvis ikke finnes fra før
- I frontend legge til ny inntekt hvis det ikke finnes fra før fra nytt virkningstidspunkt redigere hvis det finnes fra før
- Forbedre opprettelse av ny avkorting ved revurdering
> EY-2256 Lagre og oppdatere flere enn et avkortingsgrunnlag

- apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/omregning/OmregningService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
- apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseDao.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/RealGenerellBehandlingServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseDaoTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/person/OpprettRevurderingModal.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
Det betyr at når du oppretter en revurdering på grunn av en hendelse kobler vi hendelsen på behandlingen, slik at den forsvinner fra oppgavelisten.
Hvis behandlingen avbrytes kobles hendelsen i fra igjen, slik at den dukker opp i oppgavelisten / saksoversikten igjen.
Mangler fiksing av tester på flyten når man avbryter en behandling som har hendelse(r) koblet opp
> Kobler revurderinger på grunn av hendelser sammen

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/boddEllerArbeidetUtlandet/BoddEllerArbeidetUtlandetVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/UtenlandstilsnittVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/vurderingsboks/VurderingsboksWrapper.tsx
Vi setter defaultRediger til true hvis data mangler. Men det burde ikke kunne overskrive redigerbart som settes fra status.
Så - for de to nye - hvor vi har lagt til kolonner etter saker var fattet så skriv ut "Ikke vurdert" hvis vi er i denne situasjon
> EY-2295 - ikke åpne for redigering hvis ikke status tillate det - søknadsoversikt

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlagListe.tsx
Backend har tilstandssjekker for å unngå at det redigeres etter at et vedtak har blitt fattet, men trygdetid og avkorting har tillatt og legge til mer grunnlag i frontend. Fjerner knapper for dette.
EY-2203
> Fjerner mulighet for redigering av trygdetid og inntekt fom status fattet

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/AnnullerBehanding.tsx
Unngår at den dukker opp i ferdigbehandlede saker som under:
> Skjuler avbryt-dialogen hvis behandlingen ikke er under arbeid

- apps/etterlatte-gyldig-soeknad/src/main/kotlin/gyldigsoeknad/barnepensjon/FordeltSoeknadRiver.kt
- apps/etterlatte-gyldig-soeknad/src/main/kotlin/gyldigsoeknad/omstillingsstoenad/InnsendtSoeknadRiver.kt
Dersom vi sender inn en søknad og en av oppslagene mot feks behandling feiler, vil det logges en feil, men søknaden må sendes inn på nytt. Burde ikke appen prøve å håndtere meldingen på nytt ved å restarte?
> Forsøker på nytt hvis gyldighetsvurdering feiler

- apps/etterlatte-fordeler/src/main/kotlin/fordeler/FordelerKriterier.kt
- apps/etterlatte-fordeler/src/main/kotlin/fordeler/FordelerService.kt
- apps/etterlatte-fordeler/src/test/kotlin/fordeler/FordelerKriterierTest.kt
Det var gjort en antagelse om at det alltid fantes en gjenlevende forelder som kunne slåes opp i pdl. Dette er ikke tilfellet. Det gjøres nå en sjekk på om det finnes gjenlevende foreldre før det gjøres sjekk mot pdl. Videre vil en slik søknad ikke passere da det vil være en annen innsender enn foreldre i slike tilfeller.
> Fikser at barn som ikke har gjenlevende foreldre kan håndteres i fordeler

- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/regler/barnepensjon/BeregnBarnepensjon1967.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/regler/barnepensjon/Institusjonsoppholdregler.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/regler/BeregnBarnepensjon1967Test.kt
Se [confluence](https://confluence.adeo.no/pages/viewpage.action?pageId=512001934#id-%C2%A7188.Barnepensjonunderoppholdiinstitusjon-Beslutningstre) for illustrasjon av beregningstreet for institusjonsopphold
> EY-2297 Justerer beregningsregel for institusjonsopphold

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/Behandling.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/AnnullerBehanding.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/AvbrytBehandling.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/useBehandling.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/useVedtaksResultat.ts
Viser nå knappen "Tilbake til oppgavelisten" uten modal dersom behandling er ferdigstilt.
EY-2363
> Endrer flyt for avbryt-knappen for ferdige behandlinger.

- apps/etterlatte-beregning/.run/etterlatte-beregning.dev-gcp.run.xml
- apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRegelkjoring.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
- apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt
- apps/etterlatte-beregning/src/main/resources/db/migration/V20__legge_til_restanse_avkortet_ytelse.sql
- apps/etterlatte-beregning/src/main/resources/db/migration/V21__legge_til_restanse_avkortet_ytelse.sql
- apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRegelkjoringTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRepositoryTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTest.kt
- apps/etterlatte-beregning/src/test/kotlin/ytelseMedGrunnlag/YtelseMedGrunnlagServiceTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkorting.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
- libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt
- Ny tabell i db for å lagre årsoppgjør for avkorting og restanse
- Metode for beregne årsoppgjøret og månedlig restanse (uten regelkjøring enn så lenge)
- flyttet domenelogikk fra AvkortingService til Avkorting
- Div rydding og renaming
- Fikset bug i AvkortingIntekst.tsx etter renaming av relevanteMaanederInnAar og fratrekkInnAar
> Ey 2314 restanse første utkast

- alerts.yaml
Ref https://nav-it.slack.com/archives/C01DE3M9YBV/p1684235321138999
Vi har siden 24.05 ikke fått varsler fra logger for saksbehandling i dev eller prod. Denne endringen skal få det til å fungere igjen.
> Endrer expression i alerts.yaml til å bruke gyldige verdier

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/AdoptertAv.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/GrunnForSoeskenjustering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/OmgjoeringAvFarskap.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/RevurderingInfo.ts
Fikk ikke kranglet meg vekk fra å måtte angi typen med en streng, men typescript snevrer ned til aktuell type i alle fall, så `hentUndertypeFraBehandling<AdopsjonInfo>("SOESKENJUSTERING", behandling)` gir typefeil på at "SOESKENJUSTERING" ikke er "ADOPSJON"
> Samler til en funksjon for henting av revurderinginfo

- apps/etterlatte-hendelser-pdl/src/main/kotlin/Application.kt
- apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/PersonHendelseFordeler.kt
- apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/config/ApplicationContext.kt
- apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/pdl/PdlKlient.kt
Vi får ofte "feil" fra **etterlatte-hendelser-pdl** som følge av timeout e.l. mot PDL. 
Legger derfor til `Retry` og skiller exceptions slik at vi ikke fanger ident-error og hendelsesobjekter vi ikke kan håndtere i én og samme try-catch.
> EY-2431 Ikke fange flere exceptions i én + retry

- apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt
- apps/etterlatte-beregning/src/main/kotlin/klienter/BehandlingKlient.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/BehandlingKlient.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/klienter/BehandlingKlient.kt
- apps/etterlatte-vilkaarsvurdering/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt
Siden _kun_ IDen til forrige iverksatte behandling brukes, er det litt unødvendig å sende et detaljert behandlingsobjekt. 
Dersom det skulle vise seg å være behov for andre felter får man heller _lage en DTO med det man trenger..._
> EY-2431 Kun sende behandlingId siden kun det brukes

- apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRegelkjoring.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/AvkortetYtelse.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/Restanse.kt
- apps/etterlatte-beregning/src/main/resources/db/migration/V22__endre_restanse_avkortet_ytelse.sql
- apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRegelkjoringTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRepositoryTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/regler/AvkortetYtelseTest.kt
Regler
- Implementert regler for å beregne restanse
- Oppdatert regel for avkortetYtelse til å legge til restanse
Skrevet om avkortingsdomene
- Fjerner klasse AarsoppgjoerMaaned
- Lager ny klasse Aarsoppgjoer som holder på alt som behøves for å beregne avkorting og restanse innenfor gjeldende år
> Ey 2368 Regler for restanse og avkorting

- apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkorting.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkortingDetaljer.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingServiceTest.kt
- libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt
- Ny komponent for ytelse etter avkorting detaljer for å beskrive hva avkorting og restanse
- Oppdatere tekst under inntektsavkorting
Bugfiks:
- Fikser feil under kopiering av avkorting ved revurdering må generere nye id'er til tidligereAvkortetYtelse for å ikke få duplicate key
> Ey 2374 restanse detaljer frontend

- apps/etterlatte-behandling/src/main/kotlin/Application.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/GyldighetsproevingService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
- apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
- apps/etterlatte-behandling/src/test/kotlin/OmregningIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/FoerstegangsbehandlingServiceImplTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/GyldighetsproevingServiceImplTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingIntegrationTest.kt
- Oppretting av behandling er mykje logikk, og malplassert der han ligg i dag. Synes denne fortener sin eigen factory no
- Mykje i `FoerstegangsbehandlingService` var ubrukt. Det som endte opp med å vera der etter alt ubrukt var sletta og oppretting var trekt ut, var gyldighetsprøving-konseptet, så reindyrka den klassa for det formålet
Denne PR-en skal ikkje ha nokre funksjonelle endringar/konsekvensar, det er kun refaktorisering
> EY-2346: Ryddar i service-laget i behandling

- apps/etterlatte-behandling/src/main/kotlin/Application.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseJob.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseJobTest.kt
- apps/etterlatte-statistikk/src/main/kotlin/Application.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/config/ApplicationContext.kt
- apps/etterlatte-statistikk/src/main/kotlin/statistikk/jobs/MaanedligStatistikkJob.kt
- apps/etterlatte-utbetaling/src/main/kotlin/Application.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/GrensesnittsavstemmingJob.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingJob.kt
- libs/etterlatte-jobs/src/main/kotlin/jobs/TimerUtils.kt
Ved å lytte på shutdown-flagg i det vi plukkar opp feilmeldinga.
Samlar med det samme logikken og sentraliserer dette i etterlatte-jobs-modulen, kjens naturleg at det er der
> Unngår feil i jobbkøyring ved deploy av applikasjon 

- apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/NavAnsattKlient.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/Norg2Klient.kt
- apps/etterlatte-behandling/src/main/kotlin/common/klienter/SkjermingKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/Norg2Klient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/RegoppslagKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/DistribusjonKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafClient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/navansatt/NavansattKlient.kt
- apps/etterlatte-fordeler/src/main/kotlin/behandling/BehandlingKlient.kt
- apps/etterlatte-institusjonsopphold/src/main/kotlin/InstitusjonsoppholdKlient.kt
- apps/etterlatte-testdata/src/main/kotlin/Application.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/KodeverkKlient.kt
- libs/etterlatte-ktor/src/main/kotlin/HttpClient.kt
- libs/etterlatte-ktor/src/main/kotlin/Ping.kt
- libs/saksbehandling-common/src/main/kotlin/logging/LogUtils.kt
Ser ingen grunn til at dette skal variere overalt, så standardiserer
> EY-2484: Forenklar og samkøyrer bruken vår at HttpClient, headers og konfig

- apps/etterlatte-testdata/src/main/kotlin/dolly/DollyClient.kt
For å teste om dette fikser feilen i etterlatte-testdata når du bestiller ny familie
> Setter eksplisitt contenttype på opprettbestilling

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/MaanedVelger.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/soeskenjustering/SoeskenjusteringPeriode.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/virkningstidspunkt/Virkningstidspunkt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/DatoVelger.tsx
- Bytter ut Datepicker i Maanedvelger og bruker MonthPicker fra komponentbiblioteket istedenfor
- Bytter ut react-datepicker for virkningstidspunkt. Dette tillater at saksbehandler skriver inn dato
- Bytter ut react-datepicker for trygdetid og fikser bug der alle datoer blir -1 dag
React datepicker er ikke fjernet fra repoet siden det fortsatt bruker på gammel oppgaveliste. 
Kan fjernes når det byttes til ny oppgaveliste.
> Bytter ut react datepicker med Nav Datepicker 

- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/RedigerSaksbehandler.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/MinOppgaveliste.tsx
- Oppgavestatus hentes nå fra filter istedenfor å være enum
- Endret ordlyd for endring av saksbehandler
> OppgaveStatus som ord og ordlyd for endring av saksbehandler

- apps/etterlatte-behandling/src/main/kotlin/Application.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveDaoMedEndringssporing.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveDaoNy.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveRoutesNy.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
- apps/etterlatte-behandling/src/main/kotlin/sak/SakTilgangDao.kt
- apps/etterlatte-behandling/src/main/kotlin/sak/TilgangService.kt
- apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt
- apps/etterlatte-behandling/src/test/kotlin/IntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgaveny/OppgaveDaoNyTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgaveny/OppgaveServiceNyTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/RedigerSaksbehandler.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/TildelSaksbehandler.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/FristHandlinger.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/MinOppgaveliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaverny.ts
- apps/etterlatte-saksbehandling-ui/server/src/index.ts
- libs/etterlatte-ktor/src/main/kotlin/RouteUtils.kt
- libs/etterlatte-oppgave-model/src/main/kotlin/OppgaveNy/OppgaveNy.kt
Bruken av sakId i parameter gjorde at man kunne lyve til API'et: Saksbehandler A har tilgang til enhet 1234, men ikke enhet 6767 som behandler skjermede saker. Hvis det ligger en oppgave O på enhet 6767 kan saksbehandler da endre på den uten tilgang, ved å sende requests av typen "/api/nyeoppgaver/tildel-saksbehandler/1234" med en referanse til oppgave O i request-body.
Sjekken på tilgang går på sakId som sendes med i parameteret, men det ble ikke validert mot den faktiske saken oppgaven ligger på.
I stedet for å legge på en slik sjekk er dette en omskrivning av oppgaveApi'et til å heller basere seg på id'er sendt i call params, og legge på en tilgangssjekk mot oppgaveId'en i stedet. Brukte også anledningen til å skrive det litt mer REST-aktig
> EY-2500 Legger til tilgangssjekk for oppgaveId, refactor oppgaveApi

- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveDaoMedEndringssporing.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveDaoNy.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgaveny/OppgaveServiceNyTest.kt
Endrer enhet på oppgaver når det kommer inn en endringshendelse på adressebeskyttelse
Det gjenstår fortsatt noen caser for enhetsendring som ikke er håndtert av denne PR'en
> EY-2482-Endre-enhet-oppgave

- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/FilterRad.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelista.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelistafiltre.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/RedigerSaksbehandler.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/TildelSaksbehandler.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/ToggleMinOppgaveliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/FristHandlinger.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/MinOppgaveliste.tsx
- Henter alle oppgaver på nytt hvis man endrer på frist eller saksbehandler
- Flytter filter ut av oppgavelista for å spare filtervalg ved ny henting av oppgaver. Dette vil også gjøre det lettere å bruke filter på min oppgaveliste hvis det trengs senere.
Burde nok lages en egen alert komponent for å bedre vise frem at saksbehandler er endret.
> EY-2504: Hent oppgaver på nytt ved endring i frist eller saksbehandler

- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/ToggleMinOppgaveliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/MinOppgaveliste.tsx
Viser antall oppgaver saksbehandler har under mine oppgaver. 
Gjør det enklere å se at en oppgave legges til under mine oppgaver.
_PS. Skrivefeilen som er i videoen er fikset_
> Legg til antall oppgaver som saksbehandler har

- libs/etterlatte-ktor/src/main/kotlin/HttpClient.kt
Etter opprydding i EY-2484 så ble vår httpKlient konsistent med bruk av "Nav_Call_Id".
Men det viser seg - noen tjenester forventer "Nav_Call_Id" og noen "Nav-Call-Id".
Det er bare en til header med x-correlation-id - så sender begge varianter.
> NAV call id - forskjellige formater

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
Beholder prorata som verdi i backend - men saksbehandlere er mer vant til valget "Ikke med i prorata" i grensesnittet - så reverser logikken der.
> EY-2440 - reverser logikk i frontend for prorata

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
(ikkje alle med brevprosesstype automatisk skal vera readonly lenger). Gjekk derfor for å forenkle med det samme, så vi har betre kontroll framover
> Logikken for om vi skulle la brukar redigere brev eller ikkje var både kompleks og feil 

- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidBeregningService.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/regler/BeregnTrygdetid.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/regler/BeregnTrygdetidTest.kt
* Forenkle til en faktum node - alt kommer fra samme kilde
* Ta hensyn til poeng inn/ut år når vi regner ut hvor lenge en trygdetids periode er for et grunnlag
> EY-2527 - poeng inn  eller ut år - trygdetidsperioder

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
No når vi har brevprosesstypen for redigbart brev, kan vi bruke den direkte heller enn å styre masse med logikk i frontend.
Tanken med `erReadOnly`-metoden var å skilje ut dei breva som kunne redigerast frå dei som ikkje kunne det. No har vi (i den andre EY-2526-PRen) introdusert ein ny brevprosesstype _redigerbar_ for å dekkje dette formålet. Dermed er det berre dei fullautomatiske breva som har typen automatisk, og da kan vi rute kun dei automatiske som read only.
> EY-2526: Forenklar ved å bruke brevprosesstype

- apps/etterlatte-behandling/build.gradle.kts
- apps/etterlatte-beregning-kafka/build.gradle.kts
- apps/etterlatte-beregning/build.gradle.kts
- apps/etterlatte-brev-api/build.gradle.kts
- apps/etterlatte-egne-ansatte-lytter/build.gradle.kts
- apps/etterlatte-fordeler/build.gradle.kts
- apps/etterlatte-grunnlag/build.gradle.kts
- apps/etterlatte-gyldig-soeknad/build.gradle.kts
- apps/etterlatte-hendelser-pdl/build.gradle.kts
- apps/etterlatte-institusjonsopphold/build.gradle.kts
- apps/etterlatte-migrering/build.gradle.kts
- apps/etterlatte-oppdater-behandling/build.gradle.kts
- apps/etterlatte-opplysninger-fra-soeknad/build.gradle.kts
- apps/etterlatte-pdltjenester/build.gradle.kts
- apps/etterlatte-statistikk/build.gradle.kts
- apps/etterlatte-testdata/build.gradle.kts
- apps/etterlatte-tilbakekreving/build.gradle.kts
- apps/etterlatte-trygdetid-kafka/build.gradle.kts
- apps/etterlatte-trygdetid/build.gradle.kts
- apps/etterlatte-utbetaling/build.gradle.kts
- apps/etterlatte-vedtaksvurdering-kafka/build.gradle.kts
- apps/etterlatte-vedtaksvurdering/build.gradle.kts
- apps/etterlatte-vilkaarsvurdering-kafka/build.gradle.kts
- apps/etterlatte-vilkaarsvurdering/build.gradle.kts
- buildSrc/src/main/kotlin/etterlatte.common.gradle.kts
- buildSrc/src/main/kotlin/etterlatte.kafka.gradle.kts
- buildSrc/src/main/kotlin/etterlatte.postgres.gradle.kts
- buildSrc/src/main/kotlin/etterlatte.rapids-and-rivers-ktor2.gradle.kts
- jobs/start-regulering/build.gradle.kts
- jobs/test-fordeler/build.gradle.kts
- Fjernet `etterlatte.kafka` siden det kun pekte på `:libs:etterlatte-kafka`. 
- Fjernet `etterlatte.common` fra `rapids` og `postgres` plugins/buildSrc. 
- Flyttet div avhengigheter til `etterlatte.common`
> Opprydding avhengigheter

- apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgaveny/OppgaveServiceNyTest.kt
- libs/etterlatte-oppgave-model/src/main/kotlin/OppgaveNy/OppgaveNy.kt
Gjør `hentSaksbehandlerForBehandling` mindre streng og sjekker kun på oppgavetype førstegangsbehandling. Hvis ikke vil det feile hvis førstegangsoppgaven er ferdigstilt.
> Bugfix hent saksbehandler for behandling fra oppgave

- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseJob.kt
Setter også debug-nivå på logging av at jobben ikke kjører - det er ikke spesielt interessant å vite at den ikke kjører eksplisitt
> Logger kun "setter opp" når vi faktisk setter opp Grunnlagsendringshendelsejobben

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnvilgetBrevData.kt
requireNotNull på innholdVedlegg gjer at det trynar for BP, kor vi ennoo ikkje har innført redigerbar-vedlegg-logikken. Bruker derfor metode for det på tilsvarande vis som for sjølve innhaldet inntil vidare.
> Fiks innvilgelsesmal ved å gjera også vedlegg til eit funksjonskall

- apps/etterlatte-brev-api/src/test/resources/db.migration/automatisk-til-redigerbart-brev.sql
Usikker på om vi bør køyre denne SQL-en direkte som han er, men trur det skal vera trygt. select-en kan vi uansett bruke for å sjekke ståa.
> EY-2583: SQL for overgangen frå gamal til ny innvilgelsesmal

- apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringRepository.kt
- apps/etterlatte-behandling/src/main/resources/db/migration/V51__pesysid_som_long.sql
- apps/etterlatte-behandling/src/test/kotlin/behandling/migrering/MigreringRoutesTest.kt
- apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelserTest.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/pen/PenModellTilVaarModell.kt
- apps/etterlatte-migrering/src/test/kotlin/migrering/MigreringIntegrationTest.kt
- apps/etterlatte-trygdetid-kafka/src/test/kotlin/MigreringHendelserTest.kt
- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/MigreringRequest.kt
Prøver å stykke opp endringane i migrering i så små og isolerte bitar som mogleg, denne går kun på å endre datatypen for sakid som vi får frå pesys
Ref https://github.com/navikt/pesys/blob/4e37118c3addd920308691f5d2b0329380d8a583/pen-app/src/main/java/no/nav/pensjon/pen_app/domain/barnepensjon/response/BarnepensjonGrunnlagResponse.kt#L9C1-L9C1
> EY-2595: Verkar som sakid i pesys er long, så endrar til det i kva vi får frå dei

- apps/etterlatte-migrering/src/main/kotlin/migrering/Application.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/Migrering.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/pen/PenKlient.kt
- apps/etterlatte-migrering/src/test/kotlin/migrering/MigreringIntegrationTest.kt
Bruker tilsvarande konsept som for migrering (sjå `Reguleringsforespørsel`) - migrér alle hentar først oversikt over alle saker som skal migrerast, og køyrer så ut separat migrering per sak.
> EY-2595: Samkøyre logikken for å migrere ei sak og den for å migrere alle

- get-secret.sh
- Kun spørre bruker om "lokal" secret skal brukes _dersom den finnes_.
- Legge til unleash secret automatisk der det er aktuelt.
- Bruke `fzf` for smudere kjøring. 
- Opprette symlink for bruker slik at scriptet kan kjøres som en vanlig kommando uten å peke på lokasjon.
> Oppgradere secret script

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/SideMeny/SideMeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/AnnullerBehanding.tsx
Legger til avbryt-knapp for revurderinger på Omstillingsstønad. Avbryte førstegangsbehandling her gir ikke mening slik det gjør for barnepensjon da vi ikke har pesys som fallback.
> EY-2643 Legger til avbryt-knapp på omstillingsstønad-behandlinger

- apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveRoutesNy.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
- apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/MigreringHendelser.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/VedtakService.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/MigreringHendelserTest.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/config/ApplicationBuilder.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/migrering/MigreringRoute.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/migrering/MigreringRouteKtTest.kt
- libs/etterlatte-oppgave-model/src/main/kotlin/OppgaveNy/OppgaveNy.kt
Innsåg med det samme at det byrja å bli veldig mange kall mellom vedtaksvurdering-kafka og vedtaksvurdering, så slo dei saman til eit nytt migrerings-endepunkt.
Tildeler der attesteringsoppgåva til systembrukar.
_Eigentleg_ synes eg det ville vore betre om vi returnerte id-en til den nyoppretta oppgåva heile vegen frå _fattVedtak_, men det vart mykje knot, og eg kjenner meg ganske trygg på at det her blir rett også.
Og så har eg gjort eit bevisst val (som eg innser no at eg burde ha diskutert med nokon _før_ eg gjorde det) om at automatisk behandling i størst mogleg grad skal gjera det samme som ved manuell, sånn at vi opprettar oppgåve, tildeler til systemet og ferdigstiller som om det skulle vore gjort manuelt. Trur det er lurt for ettersporing.
> EY-2619: Tilpassar migrering til ny oppgåveflyt

- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/OpprettNyBehandling.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/VurderHendelseModal.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/behandlingsliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/RevurderingInfo.ts
- libs/saksbehandling-common/src/main/kotlin/behandling/RevurderingInfo.kt
Legger på fritekst-årsaken i revurderingsoversikten slik at saksbehandlere som åpner den i ettertid kan se hva som ble spesifisert.
> EY-2401 Viser spesifisert årsak i revurderingsoversikt ved annen revurderingsårsak

- apps/etterlatte-saksbehandling-ui/client/src/components/person/OpprettNyBehandling.tsx
Var ikke mulig å lukke modalen (med avbryt-knappen) dersom det hadde oppstått en feil.
> Fikse liten bug i opprett behandling modalen

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/AnnullerBehanding.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
Redirecte SB til saksoversikten i stedet for oppgavelisten. 
Litt pynting på tekster, men her må det gjøres mer arbeid. Avventer nye tekster fra design. Kommer i egen sak.
> EY-2651 Fikse redirect til saksoversikt + tekster

- apps/etterlatte-saksbehandling-ui/client/src/shared/styled.tsx
Gjør at knapp for å avbryte behandling ikke forsvinner dersom dokumentlisten er svært lang
Eksempel:
> EY-2650 Litt spacing i bunn av sidebar

- .github/workflows/lib-saksbehandling-common.yaml
Der definerer vi Kotlin-versjon. Det kan vera endringar i nye versjonar der som er inkompatible med ein plugin eller eit eller anna, så lurt at vi byggjar iallfall noko automatisk ved endringar der for å sjå at det funkar
> Køyre bygg ved endringar i settings.gradle.kts

- apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/klage/formkrav/KlageFormkrav.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/klage/stegmeny/KlageStegmeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/klage/styled.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/klage.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Klage.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/util.ts
- libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt
Håndteringen av brev i backend kommer i en annen PR, skilte det ut siden det har litt ekstra kompleksitet som er uavklart. Dette betyr at kun ren omgjøring er det utfallet som støttes i denne koden :) 
Noen screenshots fra frontend:
> EY-2671 Ta stilling til en klage som er omgjøring

- apps/etterlatte-saksbehandling-ui/client/src/components/klage/formkrav/KlageFormkrav.tsx
Tar ikke med det overflødige feltet vedtaketKlagenGjelder, som skaper problemer. Har også en mer stabil sjekk på om skjemafyltene er ferdig utfylt.
> Fikser innlesning av eksisterende formkrav

- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRepositoryIntegrationTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/InstitusjonsoppholdOMS.tsx
Rettet en feil på visning av Institusjonsopphold når man navigerer tilbake til Beregningsgrunnlag for OMS.
Rettelsen gjelder kun endringene i InstitusjonsoppholdOMS.tsx.
Endret i tillegg litt på BeregningsgrunnlagOmstillinsstoenad for å få en likere implementasjon som for BP + la til 2 tester
> Rettet en feil på visning av Institusjonsopphold 

- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
Ved kopiering av trygdetid når det er opphør, så skal ikke status settes til TRYGDETID_OPPDATERT
> Setter ikke behandlingsstatus trygdetid ved opphoer

- apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageDao.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
- apps/etterlatte-klage/src/main/kotlin/no/nav/etterlatte/klage/BehandlingKlient.kt
Legger også inn /api/ i request-url'en, og samler endepunktene. Setter også oppdatering av kabalstatus bak sjekk på at det kun er systembrukere som kan oppdatere
> Endrer referansen vi oppdaterer til å være på klageID

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
OMS revurdering annen er helt ytelsesagnostisk frem til brev.
I brev har de brukt TOM_MAL og OMS_REVURDERING_ENDRING, manuelt og redigerbart
Setter opp BP med TOM_MAL og BARNEPENSJON_REVURDERING_ENDRING, manuelt og redigerbart.
> EY-2421 - sett opp brev for BP revurdering annen

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
Slik sjekken var ville et ikke-lastet brev vise advarselen "Dette er et manuelt opprettet brev. Kontroller innholdet nøye før attestering" / "Kan ikke generere brev automatisk. Du må selv redigere innholdet" (avhengig av behandlingsstatus), selv om brevet er automatisk
løser FAGSYSTEM-295518
> viser alert _kun_ for manuelle / redigerbare brev

- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
Når vi har en klage som er omgjøring vil vi opprette en revurdering for de -- så revurdering må støtte nøstede transaksjoner :)
> Fikser nøstet transaksjon + navn i call-parameter

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnvilgetBrevData.kt
Denne datoen blir jo først satt på vedtaket i det saksbehandlar klikkar send til attestering.
> EY-2646: Viss vedtaksdato manglar for brev, bruk dagens dato

- apps/etterlatte-tilbakekreving/.nais/dev.yaml
- apps/etterlatte-tilbakekreving/.run/etterlatte-tilbakekreving.dev-gcp.run.xml
- apps/etterlatte-tilbakekreving/build.gradle.kts
- apps/etterlatte-tilbakekreving/src/main/kotlin/Application.kt
- apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/config/ApplicationContext.kt
- apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/config/ApplicationProperties.kt
- apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagConsumer.kt
- apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/vedtak/TestVedtakRoutes.kt
- apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/vedtak/TilbakekrevingKlient.kt
- apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/kravgrunnlag/KravgunnlagJaxbTest.kt
- apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/vedtak/TilbakekrevingKlientTest.kt
Sender tilbakekrevingsvedtak via `etterlatte-proxy` til soap-tjenesten for tilbakekreving som ligger on-prem.
> EY-2660 Kobler mot etterlatte-proxy for sending av tilbakekrevingsvedtak

- apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
- apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
- apps/etterlatte-behandling/src/test/kotlin/VerdikjedeTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelistafiltre.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Tags.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/Tags.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaverny.ts
- libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt
- libs/etterlatte-oppgave-model/src/main/kotlin/Oppgave/OppgaveIntern.kt
Siden det ikke bare er standard behandlinger vi skal omgjøre, men også tilbakekrevinger og generelle behandlinger, er det ikke bare å rett frem opprette en revurdering for klagen med en gang. Foreløpig lages bare en oppgave, selve omgjøringen blir håndtert i EY-2739, EY-2740 og EY-2741
> EY-2592 Omgjøringer av klager lager en omgjøringsoppgave

- docker/Dockerfile
Dockerfila vi bruker i dag inneheld mykje vi ikkje treng. [baseimages-repoet](https://github.com/navikt/baseimages) er veldig generisk og har mykje, men vi treng nesten ingenting av det. Trur det meste der er mest relevant for on-prem-hosting.
Repoet har også ei åtvaring om 
> 
> Important
> NAIS baseimages are not actively maintained and should be considered deprecated.
> 
> Consider using official images or preferably distroless alternatives.
> 
> Read more in the security playbook: [HERE](https://sikkerhet.nav.no/docs/sikker-utvikling/containere)
Følgjer oppfordringa frå https://sikkerhet.nav.no/docs/sikker-utvikling/containere om å bruke distroless.
> Minimal dockerfile

- apps/etterlatte-tilbakekreving/build.gradle.kts
- apps/etterlatte-utbetaling/build.gradle.kts
- gradle/libs.versions.toml
Når no noko gjer at CodeQL-skanninga feilar på å hente avhengnadane her, så er det på tide å rydde opp. Det verkar heller ikkje som vi bruker han til noko bevisst no. Noterer på blokka å sjå på alternativ
> Denne pluginen er markert som deprecated, og github-repoet er arkivert

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevRoute.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/SakOgBehandlingService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettVedtaksbrevForMigrering.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/db/BrevRepositoryIntegrationTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettVedtaksbrevForMigreringTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/attesterVedtak.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts
Henger sammen med [FAGSYSTEM-295685](https://jira.adeo.no/browse/FAGSYSTEM-295685). 
Sikrer at PDF ikke er låst _før_ vedtaket attesteres. 
Nå lagres PDF dersom status er FATTET_VEDTAK, men brevet får ikke status ferdigstilt før behandling er attestert/godkjent.
> EY-2784 Ikke låse signatur til første person som åpner brev

- apps/etterlatte-behandling/src/test/kotlin/behandling/migrering/MigreringRoutesTest.kt
- apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelserTest.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/MigreringHendelser.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/Application.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/FeilendeMigreringLytter.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/LyttPaaIverksattVedtak.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/MigrerSpesifikkSak.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/PesysRepository.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/Pesyssak.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/pen/PenModellTilVaarModell.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt
- apps/etterlatte-migrering/src/test/kotlin/migrering/FeilendeMigreringLytterTest.kt
- apps/etterlatte-migrering/src/test/resources/attesteringsfeil.json
- apps/etterlatte-trygdetid-kafka/src/test/kotlin/MigreringHendelserTest.kt
- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/MigreringRequest.kt
- libs/saksbehandling-common/src/main/kotlin/Spraak.kt
- Tar høgde for at det kan feile i stega etter fattet vedtak, kor vi manglar data frå den originale pakka
- Tar med språk i requesten, sia dette trengs når vi skal lage brev
- Opnar for å migrere sak fleire gongar, for å forenkle testing
> EY-2786: Meir robust migrering

- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/FristHandlinger.tsx
`onClose` kjører tydeligvis etter at state er oppdatert, så du får en elegant 
```
setOpen(false)
// open er nå false
setOpen(open => !open)
// !open er true
```
> Avbryt åpnet og lukket modalen umiddelbart i setting av frist

- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagRepository.kt
- apps/etterlatte-beregning/src/main/resources/db/migration/V25__beregningsgrunnlag_navn.sql
- apps/etterlatte-beregning/src/main/resources/db/migration/V26__legg_til_beregningsmetode.sql
- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRepositoryIntegrationTest.kt
* Omdøpe bp_beregningsgrunnlag til beregnungsgrunnlag - den er allerede i bruk av OMS
* Legg til beregningsmetode felt - default verdi settes i hoved PR for EY-2747 - men dette gjør testing av branch lettere
> EY-2747 kun db endringer

- apps/etterlatte-brev-api/.nais/dev.yaml
- apps/etterlatte-brev-api/.run/etterlatte-brev-api.dev-gcp.run.xml
Ingresser i dev-fss er ikke konsekvente, så dokdist _uten_ `-q2` tilsvarer `q2`, og motsatt på de andre. Flotte greier!
> Gå over fra Q1 til Q2 i brev-api

- apps/etterlatte-grunnlag/src/main/resources/db/migration/V17__versjon_behandling.sql
Oppretter tabell separat slik at det ikke blir krøll i ettertid dersom resten av PR-en (som kommer) skulle feile, og en eventuell revert av koden ikke påvirker flyway.
> EY-2567 Tabell for å koble behandling til grunnlagsversjon

- apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelser.kt
- apps/etterlatte-trygdetid-kafka/src/test/kotlin/MigreringHendelserTest.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/BehandlingKlient.kt
Enkelte migrerte saker får ikke med seg noen trygdetidsinformasjon i migrering: https://gjenny.intern.dev.nav.no/behandling/23e33f63-5c9c-43e2-945a-e349923fccc9/trygdetid
Dersom det ikke er noen perioder, eller noe feiler ved opprettelse av perioder, skal vi overstyre med beregnet verdi.
> Overstyr trygdetid ved feil eller manglende perioder i Pesys

- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
Feilet når status i behandling skulle endres til iverksatt pga nøstede transaksjoner.
> Fikser problem med nøstede transaksjoner ved iverksetting

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/OverstyrtTrygdetid.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
- apps/etterlatte-trygdetid-kafka/src/test/kotlin/MigreringHendelserRiverTest.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidBeregningService.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/regler/BeregnTrygdetid.kt
- apps/etterlatte-trygdetid/src/main/resources/db/migration/V14__legg_til_overstyrt_poengaar.sql
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidRepositoryTest.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/regler/BeregnTrygdetidTest.kt
- libs/etterlatte-trygdetid-model/src/main/kotlin/Trygdetid.kt
EY-2924 - "legg til ny felt" del av EY-2912 - for norsk poengår overstyring (er to andre subtasker under 2912 - en for å kun vise det gitt riktig vilkår og en for å bruke verdi i beregningen)
> EY-2912 > EY-2924 - lagre overstyring av norsk poengaar > ny felter

- apps/etterlatte-pdltjenester/build.gradle.kts
- apps/etterlatte-pdltjenester/src/main/kotlin/config/ApplicationContext.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/ParallelleSannheterKlient.kt
- apps/etterlatte-pdltjenester/src/main/resources/application.conf
- apps/etterlatte-pdltjenester/src/test/kotlin/pdl/ParallelleSannheterKlientTest.kt
, og bruker i så fall ein hardkoda fallback. Unngår med det evig feilande løkke
> Tar høgde for at vi i dev kan ha folk utan namn

- libs/etterlatte-jobs/src/main/kotlin/jobs/LeaderElection.kt
- libs/etterlatte-jobs/src/test/kotlin/jobs/LeaderElectionTest.kt
Eg trur ikkje det er særleg reell fare, men kan jo fint innføre ein vaskemekanisme også her i backend. Sikkert lettare å løyse det enn å gang på gang markere som falsk positiv uansett
> Codescanning klagar på at vi loggar unsanitized input frå LeaderElection

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
- apps/etterlatte-behandling/src/test/kotlin/OmregningIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingIntegrationTest.kt
Hovudpoenget i denne PR-en er å gå frå 
```
val nyopprettaOppgave =
oppgaveService.hentOppgaverForSak(it.sak.id).first { o -> o.referanse == it.id.toString() }
```
til 
`                val nyopprettaOppgave = requireNotNull(behandlingOgOppgave.oppgave)`
> Returner oppgåve tilbake frå opprett behandling, og i migrering tildele akkurat denne oppgåva heller enn å grave bakover

- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt
- apps/etterlatte-trygdetid-kafka/src/test/kotlin/MigreringHendelserRiverTest.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TestHelper.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
- libs/etterlatte-trygdetid-model/src/main/kotlin/Trygdetid.kt
Setter opp et nytt interface for trygdetidservice, som har metoder som forstår flere trygdetider. Noen av de er ikke helt optimale (f.eks. yrkesskade) men der har vi uansett litt jobb å gjøre for å koble det fra vilkårsvurdering. 
Det nye interfacet brukes til å simulere det gamle interfacet (som fungerer topp så lenge vi kun har en trygdetid per behandling), og testene går fremdeles mot det gamle interfacet. Tenker å flytte testene over når det gamle interfacet fjernes.
Neste steg jeg ser for meg er å sette opp en v2 route for det nye api'et, og så se på å migrere konsumenter (i første omgang sannsynligvis beregning) over på det, for å kunne begynne å håndtere trygdetid til flere avdøde riktig i beregning.
> EY-2849 Trygdetidservice håndterer flere trygdetider per behandling

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/GrunnlagService.kt
- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/klienter/GrunnlagKlient.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/BehandlingGrunnlagRoutes.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/OpplysningDao.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/OpplysningsgrunnlagMapper.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/SakGrunnlagRoutes.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/BehandlingGrunnlagRoutesKtTest.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagServiceTest.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/SakGrunnlagRoutesKtTest.kt
- apps/etterlatte-grunnlag/src/test/kotlin/itest/GrunnlagDaoIntegrationTest.kt
- libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/grunnlag/Opplysningsbehov.kt
- libs/saksbehandling-common/src/main/kotlin/grunnlag/NyeSaksopplysninger.kt
Hovedsaklig henter man nå ut grunnlag basert på siste versjon tilknyttet `behandlingId`. 
Noen steder hvor man fortsatt henter på `sakId` for å sikre at man får komplett historikk. 
Gjenstår å rydde i endepunkter og funksjoner brukt ifm. versjonering av eksisterende data, men det fjernes når dette har fått kjøre litt og vi ser at det fungerer som det skal.
> EY-2917 Hente grunnlag med behandlingId

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
Bedre å ha aktivitetsplit-steget etter vilkårsvurdering i stedet for å ha det midt mellom beregningsgrunnlag og beregning.
> Flytter aktivitetsplikt-steget til etter vilkårsvurdering

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/BehandlingGrunnlagRoutes.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/OpplysningDao.kt
- apps/etterlatte-grunnlag/src/test/kotlin/Utils.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagServiceTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/OppdaterGrunnlagModal.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/kommerBarnetTilgode/KommerBarnetTilGodeVurdering.tsx
Kun systembruker kan kalle oppdater-grunnlag i grunnlag. HTTP 403 hvis grunnlag er låst på behandlingen. Test på oppdater grunnlag. Fikser "hooks count"-problem i React (useApiCall ble kalt eller ikke kalt avhengig av status i saken og det funker ikke).
> EY-2948: Flere forbedringer på oppdater-grunnlag

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/utils.test.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/utils.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/vilkaarsvurdering.ts
- apps/etterlatte-saksbehandling-ui/client/src/store/reducers/BehandlingReducer.ts
Det dukker nå opp en infoboks om at saksbehandler har utdatert vilkårsvurdering, med mulighet til å slette og opprette ny vilkårsvurdering på nytt regelverk.
EY-2826
> Lar saksbehandler slette gammel og opprette ny vilkårsvurdering.

- apps/etterlatte-pdltjenester/.nais/dev.yaml
- apps/etterlatte-pdltjenester/.nais/prod.yaml
- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlKlient.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonRoute.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonService.kt
- apps/etterlatte-pdltjenester/src/main/resources/pdl/hentAdressebeskyttelse.graphql
- apps/etterlatte-pdltjenester/src/test/kotlin/pdl/PdlKlientTest.kt
- apps/etterlatte-pdltjenester/src/test/kotlin/person/PersonServiceTest.kt
- apps/etterlatte-pdltjenester/src/test/resources/pdl/adressebeskyttelse.json
- libs/saksbehandling-common/src/main/kotlin/person/HentPersonRequest.kt
- libs/saksbehandling-common/src/main/kotlin/person/Person.kt
- libs/saksbehandling-common/src/test/kotlin/person/AdressebeskyttelseGraderingTest.kt
Gjøre det mulig å kun hente gradering ifm. opprettelse av nye saker på journalføringshendelser fra Joark .
> EY-2989 Nytt endepunkt for å hente adressebeskyttelse

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/AdresseService.kt
- apps/etterlatte-migrering/.nais/dev.yaml
- apps/etterlatte-migrering/src/main/kotlin/migrering/ApplicationContext.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/MigrerSpesifikkSakRiver.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt
- apps/etterlatte-migrering/src/test/kotlin/migrering/MigreringRiverIntegrationTest.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
- Går direkte mot PEN heller enn å gå via proxy, ref diskusjonen på slack: https://nav-it.slack.com/archives/C05MGJ6MZRN/p1698399557225319
- Adresse-oppslaget på systembrukaren _EY_ for å sette inn namn i brevet trynar (naturleg nok). Bruker foreløpig berre EY direkte, men her bør vi som nemnt på demo bytte til noko betre
- Ein del saker i Pesys i test har gjenlevande som ikkje fins i PDL. Innfører funksjonsbrytar for å kunne skru av at verifiseringa er stoppande, for å kunne teste med desse sakene lell
- Viss vi har rare trygdetidsperiodar, logg litt betre
> Fiksar div i migrering

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidVisning.tsx
Foreløpig ser det ut til å kun gjelde dersom:
- Det er førstegangsbehandling og du har huket av for å vurdere trygdeavtale.
- Det er en revurdering på grunn av sluttbehandling.
EY-2881
> Skal vurdere trygdeavtale i flere tilfeller

- apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/UhaandtertHendelse.tsx
Bugfix ble ikke så lett å se når jeg oppdaterte HTML, men det er kun et par som er fikset. 
Rekkefølgen på disse (setOpen til slutt): 
```
oppdaterKommentar('')
resetApiCall()
setOpen(false)
```
Og denne:
`onClose={() => setOpen((x) => !x)}` er nå bare `setOpen(false)`
> Fikse bug hvor det ikke er mulig å avbryte lukk hendelse

- apps/etterlatte-tilbakekreving/.nais/dev.yaml
- apps/etterlatte-tilbakekreving/.nais/prod.yaml
- apps/etterlatte-utbetaling/.nais/dev.yaml
- apps/etterlatte-utbetaling/.nais/prod.yaml
`name` og `protocol` er ikke (lenger?) støttet: https://docs.nais.io/nais-application/application/#accesspolicyoutboundexternalportsport
Vi får feil i loggene så lenge disse ligger i configen.
> Fjerner ports-parametere som ikke er støttet i nais

- apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
- apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
- Sjekker at behandling har riktig status for bruk av avkorting
- Behandling med status BEREGNET trigger ny beregning av avkorting da beregning er oppdatert
- Behandling med status IVERKSATT lar være å legge til info om forrige behandling fordi den henter forrige iverksatte som da vil være seg selv eller nyere
- Mer spesifik bruk av exception
- Generell rydding av kode og flere tester
> EY-2960 - Bedre tilstandshåndtering av avkorting

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts
- spesifikasjon av inntekt er ikke optional og settes som tom streng by default avkorting frontend
> EY-2960 Fikse feil i form inntektsavkorting - spesifikasjon av inntekt

- apps/etterlatte-trygdetid-kafka/src/main/kotlin/MigreringHendelserRiver.kt
- apps/etterlatte-trygdetid-kafka/src/test/kotlin/MigreringHendelserRiverTest.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
- libs/etterlatte-trygdetid-model/src/main/kotlin/Trygdetid.kt
Rydder opp i overstyringen slik at grunnlaget (som er feil) også slettes fra trygdetidsobjektet.
EY-3008
> Overstyrer med både anvendt TT og prorata

- apps/etterlatte-migrering/src/main/kotlin/migrering/PesysRepository.kt
Inneholder masse fødselsnummer og annen data om bruker og familie.
> Fjerner klartekst-logging av hele responsen fra Pesys.

- apps/etterlatte-samordning-vedtak/README.md
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtak.kt
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/VedtaksvurderingKlient.kt
- libs/etterlatte-ktor/src/main/kotlin/AuthorizationPlugin.kt
- libs/etterlatte-ktor/src/main/kotlin/MaskinportenScopeAuthorizationPlugin.kt
Auth-plugins kaster feil i stedet for å respondere direkte på call, for å støtte feiltypene i den allmenne feilhåndteringen
Får nå respons à dette ved valideringsfeil av scope:
```
{
"status": 401,
"detail": "Har ikke påkrevd scope",
"code": "GE-MASKINPORTEN-SCOPE",
"meta": {
"correlation-id": "30e9a443-f620-4c9e-9547-1bd77d4c86ca",
"tidspunkt": "2023-11-06T09:19:35.748618Z"
}
}
```
I stedet for
```
{
"status": 401,
"detail": "En ukjent feil oppstod",
"code": "UNKNOWN_ERROR",
"meta": null
}
```
> EY-2773 Utbedret dok for samordningsvedtak med feilkoder. 

- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/Application.kt
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/LoggingPlugins.kt
For ikke å logge `/health/isalive, isready `
> Redusere scope for samordning-logging

- .github/workflows/app-etterlatte-hendelser-samordning.yaml
Det ser ut til å ta litt tid før SAM og dens nye topic går til prod 🤷‍♂️ . Ønsker deploy til dev fortsatt.
> Disable deploy av hendelse-samordning til prod inntil videre

- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/brev/TilbakekrevingBrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Tilbakekreving.ts
Dukket opp en liten sak når jeg verifiserte tilbakekreving for BP. Det var ikke mulig å sende en underkjent behandling til attestering pga manglende status.
> EY-2996 Legger til status underkjent i for å kunne attestere

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BarnepensjonSammendrag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadSammendrag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/ProrataBroek.tsx
- Viser prorata-brøk i beregningssammendrag for omstillingsstønad på samme måte som i BP.
- Fikser et par små valideringsfeil på Avkorting.
> EY-2938 Viser prorata brøk i beregningssammendrag for omstillingsstønad

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/Vilkaarsresultat.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidVisning.tsx
- Fikser at beregning ble ikke lastet ved reload av beregningssiden - laster den hver gang beregningssiden vises for å være sikker på at denne er up-to-date
- Endrer på avkorting slik at den viser spinner når den lastes
- Drar ut vilkårsresultat i felles komponent da denne vises på tre ulike steg
> EY-2938 Fikser problem ved lasting av beregning

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/attestering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/BehandlingSidemeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/useSaksbehandlerGjeldendeOppgave.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sjekkliste/Sjekkliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/sidemeny/TilbakekrevingSidemeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/store/Store.tsx
- apps/etterlatte-saksbehandling-ui/client/src/store/reducers/SaksbehandlerGjeldendeOppgaveReducer.ts
Repeterer beskrivelsen fra jira
> Pr nå så gjøres det en sjekk mot "gjeldende oppgave" hver gang sjekkliste-fanen åpnes, for å kunne låse sjekklista for alle andre enn aktuell behandler. Dette medfører litt lag (småkjip brukeropplevelse avhengig av hvor ofte man svitsjer fane), og det bør vurderes forbedring
> EY-2982 State for saksbehandler på gjeldende oppgave

- apps/etterlatte-trygdetid/.run/etterlatte-trygdetid.dev-gcp.run.xml
- apps/etterlatte-trygdetid/build.gradle.kts
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/config/ApplicationContext.kt
- apps/etterlatte-trygdetid/src/main/resources/application.conf
- apps/etterlatte-trygdetid/src/test/kotlin/trygdetid/TrygdetidServiceTest.kt
Ikke mulig å behandle saker forbi trygdetid i produksjon fordi det ikke finnes trygdetidsberegninger på fast trygdetid. Legger sjekkene bak feature-toggle inntil trygdetid skrus på i produksjon.
> Legger sjekk av trygdetidsberegning bak feature-toggle

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/AutomatiskRevurdering.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Foerstegangsbehandling.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManuellRevurdering.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManueltOpphoer.kt
- apps/etterlatte-behandling/src/test/kotlin/OmregningIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/domain/RevurderingTest.kt
Siden statusen TRYGDETID_OPPDATERT settes når man trykker "Neste" i trygdetidssteget, må denne også tillates i behandling. Dvs, ingen mulighet til å lenger gå direkte fra VILKAARSVURDERT til BEREGNET.
> Krever status TRYGDETID_OPPDATERT også ved fast trygdetid

- apps/etterlatte-samordning-vedtak/.nais/dev.yaml
- apps/etterlatte-samordning-vedtak/.nais/prod.yaml
- apps/etterlatte-samordning-vedtak/.run/etterlatte-samordning-vedtak.dev-gcp.run.xml
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/Application.kt
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt
- apps/etterlatte-samordning-vedtak/src/main/resources/application.conf
- apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRouteTest.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/SamordningsvedtakRouteTest.kt
- libs/etterlatte-ktor/src/main/kotlin/AuthorizationPlugin.kt
- libs/etterlatte-token-model/src/main/kotlin/no/nav/etterlatte/token/BrukerTokenInfo.kt
Opprinnelig løsning antok (feilaktig) at obo-tokens også får custom-role, men nei - naisdok'en er ganske tydelig egentlig.
Dette er i kontekst av at tjenesten kalles fra PSAK (saksbehandlerløsningen) _via_ backend PEN
> Samordning - korrigert rollesjekk ved OBO-token

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
- Fjerner redigerknapp i aktivtetsplikt, også når behandlingen har status "FATTET_VEDTAK"
- Oppdaterer behandlingstatus i frontend til AVKORTET kun når vi er i redigeringsmodus og det finnes en avkorting
> EY-3109 Fjerner rediger-knapp i avkorting og aktivitetsplikt

- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/LoggingPlugins.kt
Er litt bedre med `dev-fss:pensjon-q2:pensjon-pen-q2` enn `92e4c1d4-d4ba-4849-91ff-caa4dce8d4bb`...
> Samordning - benytte lesbar-brukerid for logging av system-til-systemkall internt

- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakBehandlingService.kt
Og for å kunne noenlunde lett finne IDen når man trenger å poste melding via testdata for å shortcircuite den lange verdikjeden (a feature in the making)
> Logge vedtaksID ved forespørsel mot SAM

- apps/etterlatte-migrering/src/main/kotlin/migrering/Application.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/MigrerSpesifikkSakRiver.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/MigreringRiver.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/Migreringsstatus.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/PauseMigreringRiver.kt
- apps/etterlatte-migrering/src/test/kotlin/migrering/MigreringRiverIntegrationTest.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/MigreringHendelserRiver.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/VedtakService.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/MigreringHendelserRiverTest.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/AutomatiskBehandlingRoutes.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/AutomatiskBehandlingService.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/config/ApplicationBuilder.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/migrering/AutomatiskBehandlingRoutesKtTest.kt
- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/MigreringRequest.kt
- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/Migreringshendelser.kt
- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/PesysKeys.kt
- Ny migreringsstatus PAUSE
- Ny verdi på meldinger "migreringKjoringVariant" og tilhørende Enum MigreringKjoringVariant
- MigrerRiver og MigrerSpesifikkSakRiver vil kreve kjøringsvariant
- Vedtak Kafka vil kjøre deler av vedtaksløpet basert på kjøringsvariant (full kjøring, frem til fatting fra og med attester)
- Ny River PauseMigreringRiver for å oppdatere status på migrering når vedtak er fattet under migrering av type MED_PAUSE
- MigrerSpesifikkSakRiver går direkte til vedtak hvis kjøringsvariant er FORTSETT_ETTER_PAUSE
> EY-3087 - Mulighet for å pause migrering etter fattet vedtak

- apps/etterlatte-hendelser-samordning/.nais/dev.yaml
- apps/etterlatte-samordning-vedtak/.nais/dev.yaml
- apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/SamKlient.kt
ref https://nav-it.slack.com/archives/C063E3VAP24/p1700039680332509
Bakgrunn: TP-ordningene er koblet opp mot Q1. Nå er jo det et delt miljø med både prodkopi og synttestdata, men Gjenny får bare en tynn melding tilbake med 
```
vedtaksid
fagsystemkode
ytelseskode
```
> EY-1714 Skru om til SAM+TP Q1 for verdikjedetest samordning (m eksterne)

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/BehandlingSidemeny.tsx
Se #2723
Problemet er at når sjekklisten ikke hentes/opprettes før eventuell klikk på fanen, så roter det til for valideringen av sjekklista i modalen "send til attestering". Mulig at det kan ordnes på noe vis med den, men her og nå tenker jeg det kanskje er greiest å (dessverre) gå tilbake til opprinnelig løsning - men beholde 204 istedetfor 404 fra backend da.
> Sjekkliste - delvis rollback av endringen på når den hentes

- apps/etterlatte-samordning-vedtak/.nais/apiendpoints.yaml
- apps/etterlatte-samordning-vedtak/README.md
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakService.kt
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/VedtaksvurderingKlient.kt
- apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRouteTest.kt
- apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakServiceTest.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakBehandlingService.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
- apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V24__add_indices.sql
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/TestHelper.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt
`virkFom` har en mye snevrere betydning enn `fomDato`. Dette endepunktet er bygd over samme idé som det i Pesys, hvor parameteret er kun "_fom_", og det er meningen å gi ut informasjon som gjelder på fra-og-med angitt dato. Med virkFom sier man at det kun skal hentes data der vedtak.virkningstidspunkt >= virkFom, vil med andre ord skippe å gi ut gjeldende sannsynligvis. 
Denne PRen forenkler datauthentingen, med den følge at potensielt _mer_ data hentes ut enn hva som skal gis ut, noe som skyldes mangelen på noe slags vedlikehold av fom/tom ved nye vedtak. Hva som _faktisk_ skal returneres håndteres av EY-2901 #2706 
Med datamengden pr person inntil videre tenker jeg det er rimelig å anta at ytelsen ikke påvirkes enormt av dette i ganske god tid fremover.
> EY-2414 Samordning-grensesnitt korrigere param-navn

- apps/etterlatte-statistikk/src/main/resources/db/migration/V27__refresh_views_bigquery.sql
Vi har lagt til kolonner knyttet til migrering, og viewet må oppdateres før de blir synlige for bigquery-import-brukeren
> Oppdaterer views for statistikkproduktene

- apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
- apps/etterlatte-behandling/src/main/kotlin/sak/SakDao.kt
- apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
- apps/etterlatte-behandling/src/main/resources/db/migration/V75__legg_til_flyktning_status.sql
- apps/etterlatte-behandling/src/test/kotlin/sak/SakDaoTest.kt
- libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Flyktning.kt
Samme datagrunnlag blir senere benyttet i trygdetid for å gi 40 års trygdetid. For nå så lagres det kun ned som informasjon på saken. Det er nok ønskelig å hente det ut igjen å vise saksbehandler senere.
EY-3126
> Støtte for å lagre ned flyktningstatus fra Pesys.

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevRouteTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiverTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettVedtaksbrevForMigreringRiverTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/VedtaksbrevUnderkjentRiverTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/RedigerbartBrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Brev.ts
- apps/etterlatte-saksbehandling-ui/client/src/store/reducers/BehandlingReducer.ts
Videreføring av sjekken som ble gjort tidligere for å finne ut om en behandling har blitt endret etter at brev sist ble opprettet / lagret, men med noen endringer:
- Lagt på felt i vedtaksbrev `statusEndret` som gir hvilket tidspunkt siste statushendelse i brev oppsto. Dette endres feks hver gang et brev tilbakestilles, eller lagres.
- Når det trykkes på `Tilbakestill`, vil advarselen om at brevet er utdatert fjernes.
- Henter behandling når man går inn på brev for å sikre at vi har alle hendelser.
> EY-2949 Rediger behandling etter opprettet brev gir advarsel om mulig utdatert brev

- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/ListenerMedLogging.kt
- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/migrering/ListenerMedLoggingOgFeilhaandtering.kt
Merk at desse ikkje slår til viss eventnames er feil, som i grunn er bra, da slepp vi veldig mange falske positive
> Loggar feilande valideringar i rivers

- apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/hooks/useApiCall.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/statusbar/Statusbar.tsx
Dagens feilmelding ved person 404 er ikke veldig tydelig for sb. 
Har gjort en mini-oppgradering av feilmeldinger og delt opp i flere typer. 
**404 Not found**
**400 Bad request**
**Fnr. er ikke 11 siffer og kan ikke gjøre kall mot grunnlag**
> Forbedre feilmelding når henting av person feiler

- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakService.kt
- apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakServiceTest.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakBehandlingService.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakSamordningService.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/Vedtakstidslinje.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/config/ApplicationBuilder.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/SamordningsvedtakRouteTest.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/TestHelper.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtakSamordningServiceTest.kt
- libs/etterlatte-vedtaksvurdering-model/src/main/kotlin/VedtakDto.kt
Opprinnelig bug er at tidslinja korrigerer _utbetalingsperiodene_, mens det i samordning-vedtak er _avkortingsperiodene_ som er førende. Er en serie av commits her, som da i første omgang korrigerer dette i samordning-vedtak, men så har jeg flyttet denne logikken til vedtaksvurdering, og deretter til en egen service der da det etterhvert ble en del samordningsrelatert kode.
> EY-2901 Korrigert logikk for samordningsperioder

- libs/etterlatte-ktor/src/main/kotlin/MaskinportenScopeAuthorizationPlugin.kt
Fikk litt feil info i responsen som følge av dette dersom man forsøkte med et utløpt token. Fremdeles 401, men "pga manglende scope" noe som jo ikke er riktig.
> Ikke sjekke Maskinporten-scope dersom auth uansett ikke har validert token(s)

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/utenlandstilknytning/UtenlandstilknytningVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/Virkningstidspunkt.tsx
Noen forberedelser ifm en fiks som kommer senere på kravdato
- Flytter verdien som er satt for virkningstidspunkt ut fra "grunnlagskolonnen" og inn i vurderingskolonnen. 
- Setter header på vurderingene som manglet dette i søknadsoversikt
> Flytter virkningstidspunkt og setter titteler

- apps/etterlatte-brev-api/src/main/resources/graphql/dokumentoversiktBruker.graphql
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/dokumentliste.tsx
Mulig dette blir midlertidig siden vi "i teorien" kun skal ha journalposter som tilhører Gjenny og våre saker, men tenkte det er greit å ha hvert fall en periode for å sikre at sakene er tilkoblet riktig.
> EY-3170 Vise saksdetaljer (fra journalpost) i dokumentoversikten

- apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonService.kt
- apps/etterlatte-pdltjenester/src/test/kotlin/person/PersonServiceTest.kt
Når vi begynner med utlandssaker vil vi potensielt få mange brukere som mangler geografiskTilknytning i PDL. Vi må derfor støtte null og heller bruke standard enhet (p.t. Porsgrunn)
> Ey 3158 nullable geografisk tilknytning

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutesDtoer.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
- apps/etterlatte-behandling/src/test/kotlin/VerdikjedeTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.test.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/Virkningstidspunkt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
- libs/saksbehandling-common/src/main/kotlin/behandling/Virkningstidspunkt.kt
- Endrer fra YearMonth til LocalDate siden dette faktisk er en dato
- Fikser slik at verdien vises i behandlingen ved uthenting
Krever at eksisterende behandlinger som har kravdato satt fikses i db før merge.
Kravdato børde nok også ligget et annet sted enn inni Virkningstidspunkt-objektet, men det er en større endring.
> Fikser problemer med lagring og uthenting av kravdato

- apps/etterlatte-samordning-vedtak/.nais/dev.yaml
Så kan man bruke https://doc.nais.io/security/auth/azure-ad/usage/#token-generator
(for /pensjon-endepunktet)
> Lagt til støtte for azure token generator i dev for samordning-vedtak

- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakBehandlingService.kt
Dette er en quickfix for å gi en mer beskrivende feilmelding hvis saksbehandler ikke legger på inntektsavkorting. Kan selvfølgelig diskuteres om dette bør være obligatorisk, men ikke noe vi har tid til å gjøre noe med nå.
> EY-3184 Bedre feilmelding ved manglende avkorting OMS

- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
... men databasen sier noe annet.
Lurer på om det kan ha noe med å gjøre at det ble gjort i en also-block.
> Oppdaget en rar feil hvor trygdetid hevdet å ha overstyrt

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/AdresseService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/Avsender.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
Det er ikke alle enheter som har adresse (f. eks 0001), og det benyttes ikke videre i brevet heller.
EY-3190
> Ikke map avsenderadresse for brev.

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/barnepensjon/Foreldreansvar.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/barnepensjon/GyldigFramsattBarnepensjon.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/barnepensjon/GyldigFramsattVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/barnepensjon/Innsender.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/grunnlag.ts
Dette blir riktig når persongalleriet sin gjenlevende hentes fra søkers ansvarlige foreldre i PDL. Tror jeg
> EY-3063: Henter data for visning av bakgrunn for gyldighetsvurdering fra grunnlag

- apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt
Å kaste exception her braut litt med flyten vi hadde lagt opp, så vi får ikkje lagra feil ordentleg. Oppdaterer det så vi får flytta frå henta til verifisering feila som status også for desse
> Justerer feilhandtering for gjenlevende-søk mot PDL

- apps/etterlatte-samordning-vedtak/README.md
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtak.kt
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt
Det opprinnelige `virkFom` var feil (gir annen mening enn fomDato), men vi får støtte det litt til.
> Oppdatert feiltype med rett param

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidManueltOverstyrt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
- Valgmulighet for å oversytre manuell behandling med manuelt overstyrt trygdetid
- Form og endepunkt for å oppdatere manuelt overstyrt trygdetid
> EY-3056 - Opprettelse av manuell trygdetid manuell migrering

- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/BehandlingGrunnlagRoutes.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/PersongalleriSamsvar.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagServiceTest.kt
Tanken er å hente dette som en del av grunnlaget til frontend, og vise avvik hvis det er noen mellom det vi finner i PDL og det som ligger på saken allerede. 
Det er også tenkt at saksbehandler kan "forfremme" persongalleriet fra PDL til å være persongalleriet i saken, slik at de får oppdatert det hvis det er vesentlige feil. Og så kan persongalleriet legges inn ved førstegangsbehandling som vanlig, men ellers så ligger det bare der til saksbehandler oppdaterer (hvis det er behov for det). 
En slik oppdatering vil også oppdatere grunnlag, med påfølgende effekter. 
For denne PR'en skal jeg få skrevet noen tester for logikken, så kommer visning i frontend i en egen pulje. 
Har egentlig lyst til å ta dette med i en mer "beefy" grunnlagshenting for behandlingen, men har det på en egen route …
> Endepunkt for å hente samsvar mellom persongalleriet i sak og persongalleri hentet fra PDL

- apps/etterlatte-saksbehandling-ui/server/package.json
- apps/etterlatte-saksbehandling-ui/server/src/cache/cache-actions.ts
- apps/etterlatte-saksbehandling-ui/server/src/cache/index.ts
- apps/etterlatte-saksbehandling-ui/server/src/cache/token-cache.ts
- apps/etterlatte-saksbehandling-ui/server/src/middleware/getOboToken.ts
- apps/etterlatte-saksbehandling-ui/server/yarn.lock
- libs/ktor2client-onbehalfof/src/main/kotlin/AzureAdClient.kt
Bakgrunn: Under arbeidet med innføringen av requestloggingen så jeg at det ble gjort hyppige oppslag til azure for å få tak i token for det påfølgende kallet til en eller annen app, faktisk 1:1. Har sett nærmere på det nå, og det viser seg å være en kombinasjon av flere ting.
1. `Caffeine`-cachen i `AzureADClient` var satt opp med expiration etter 5 sek. Det er jo ikke en cache som bidrar fryktelig mye sånn i det hele tatt, ikke minst med 2+ pods av hver app også. 
Denne er nå justert til å benytte tokenets faktiske expiration, eventuelt fallback til 5 sek.
2. Caffeine-cachen traff stort sett _aldri_....  fordi frackend produserer nye OBO-tokens hele tiden...    
Løsning: innfører `NodeCache` for dette. 
Takk til Karl Jørgen, ref …
> Fikse caching av tokens i frackend og backend

- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Oppgavelistafiltre.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/VelgJournalpost.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/validator.ts
- apps/etterlatte-saksbehandling-ui/client/src/index.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/header/Search.tsx
- apps/etterlatte-saksbehandling-ui/client/src/utils/fnr.test.ts
- apps/etterlatte-saksbehandling-ui/client/src/utils/fnr.ts
- libs/saksbehandling-common/src/main/kotlin/person/FolkeregisteridentifikatorValidator.kt
- Sikrer skikkelig validering av fnr. med `fnrErGyldig` (tilsvarende sjekk i backend)
- Fnr. søk i oppgavelista trimmes
- Generelt søk etter sak/fnr. trimmes 
Har ved alt for mange anledninger/demoer sett at det kopieres og limes inn fnr. hvor det sniker seg inn et mellomrom. Mellomrom i teksten regnes som ugyldig i dagens løsning. Legger derfor til litt trimming slik at dette ignoreres og man får et litt "friere søk".
> Forbedring av fnr-validering + støtte tomrom i søk (fnr/sak)

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlagListe.tsx
Etter tilbakemeldinger fra saksbehandlere som ikke forsto at man også skulle legge til faktisk trygdetid fra Norge.
> Spesifiserer at det skal legges til faktisk trygdetid for Norge

- .github/workflows/app-etterlatte-hendelser-samordning.yaml
- apps/etterlatte-hendelser-samordning/.nais/prod.yaml
This reverts commit 7be6081fdb18357214ff07d4e64f49fdb2d865db.
Vært i møte med samhandlingsteamet, og alt deres er deployet til produksjon så på tide å sjekke integrasjonen/tilgangen her
> Revert "Disable deploy av hendelse-samordning til prod inntil videre (#2649)"

- apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningHendelseHandler.kt
- apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningHendelseKonsument.kt
- apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningVedtakHendelse.kt
- apps/etterlatte-hendelser-samordning/src/test/kotlin/no/nav/etterlatte/samordning/SamordningHendelseIntegrationTest.kt
Så det i dev, og det er også i prod - masse "tomme" meldinger som gjør at constructor og key ikke er bare-bare å benytte.
https://nav-it.slack.com/archives/C063E3VAP24/p1701341203910689?thread_ts=1701332241.471129&cid=C063E3VAP24
> Hendelse-samordning, takle meldinger bedre

- apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt
- apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/GyldighetsproevingServiceImplTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/RealManueltOpphoerServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
Gir tilgang til behandlinger, oppgaver og saker for alle enheter for våre fagressurser, samtidig som vi slår det av for resten av saksbehandlerene.
Tanken var å gjøre dette som en del av feature-togglen, halvparten av testene i behandling feilet, så går for den enkle varianten inntil jeg får på plass det 😛
> Fix justere tilgang med hardkodede brukeridenter

- apps/etterlatte-samordning-vedtak/.nais/dev.yaml
- apps/etterlatte-samordning-vedtak/.nais/prod.yaml
Dette er jo ikke akkurat den mest belastede tjenesten vi har, så har lyst til å se hvordan dette arter seg.
https://console.nav.cloud.nais.io/team/etterlatte/dev-gcp/app/etterlatte-samordning-vedtak/utilization?from=2023-11-01&to=2023-12-01
> Reduserer requested CPU for samordning-vedtak

- apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
Frontend kommer i en separat PR. Det er noe rot i tjenester mellom grunnlagshendelser og sak/oppgave på endring av enhet. Tenker å rydde opp der i en separat sak senere
> ny tjeneste på Sak for endring av enhet

- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
Fikser problem i produksjon ved at det forsøkes å opprette grunnlagshendelser på saker som ikke finnes i sakstabellen. Se post på slack: https://nav-it.slack.com/archives/C05MGJ6MZRN/p1701605248131549
> Filtrerer på saker som finnes ved opprettelse av grunnlagshendelse

- apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/FullfoerOppgaveModal.tsx
Siden det ikke er mulig å tildele en behandling til seg selv når man er i en behandling må det gjøres slik inntil videre.
> Sende sb til oppgavebenken ved opprettet behandling

- apps/etterlatte-gyldig-soeknad/src/main/kotlin/gyldigsoeknad/omstillingsstoenad/InnsendtSoeknadRiver.kt
Hører sammen med: 
https://github.com/navikt/pensjon-etterlatte/pull/949
> EY-3209 Midlertidig bruke fordelt=true på OMS for å korrigere journalføring

- libs/etterlatte-ktor/src/main/kotlin/feilhaandtering/StatusPagesKonfigurasjon.kt
For å unngå "ukjent" når man spør med utløpt token, og får
```
{
"status": 401,
"detail": "En ukjent feil oppstod",
"code": "UNKNOWN_ERROR",
"meta": null
}
```
> Spesifikk tekst for 401 i StatusPages

- apps/etterlatte-behandling/src/main/resources/db/migration/V78__legger_til_utlandstilknytning_behandling.sql
Tar ut database-endringene fra https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/2899. Gjør det enklere om vi evnt må gjøre rollback.
Oppretter nytt felt i behandling, og oppdaterer utlandstilknytning basert på verdien i sakene. Lar verdiene også ligge i sak inntil endringene er verifisert.
> EY-3191 Legger til utlandstilknytning i behandling (kun db migrering)

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingsstatusRoutes.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoReguleringTest.kt
- apps/etterlatte-oppdater-behandling/src/main/kotlin/BehandlingService.kt
- apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/ReguleringsforespoerselRiver.kt
- apps/etterlatte-oppdater-behandling/src/test/kotlin/regulering/ReguleringsforespoerselRiverTest.kt
- jobs/start-regulering/src/main/kotlin/Application.kt
Legger også opp til en manuell liste av sakIder istedet for å hente alt fra behandling.
> Endrer reguleringsflyten til kun å tilbakestille behandlinger vi ønsker å regulere.

- apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/AvkortetYtelse.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/InntektAvkorting.kt
- apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/Restanse.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/regler/omstillingstoenad/BeregnOmstillingstoenad.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/regler/omstillingstoenad/InstitusjonsoppholdreglerOMS.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/regler/omstillingstoenad/Konstanter.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/regler/omstillingstoenad/sats/OmstillingsstoenadSats.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/regler/omstillingstoenad/trygdetidsfaktor/Trygdetidsfaktor.kt
- apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRegelkjoringTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/regler/AvkortetYtelseTest.kt
- apps/etterlatte-beregning/src/test/kotlin/avkorting/regler/InntektAvkortingTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnBarnepensjonServiceTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnOmstillingsstoenadServiceTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/regler/sats/BarnepensjonSatsTest.kt
- apps/etterlatte-beregning/src/test/kotlin/grunnbeloep/GrunnbeloepRepositoryTest.kt
- apps/etterlatte-beregning/src/test/resources/grunnbelop.json
For å unngå for store omskrivinger, er det lagt til en ny json-fil for grunnbeløp som brukes i tester. Her legges det til et tenkt grunnbeløp frem i tid (mai 2024). Dette er gjort for å unngå å måtte gjøre alle beregninger som inkluderer komplekse utregninger av avkortinger + restanser for omstillingsstønad på nytt da disse tok utgangspunkt i 2023. Det ville vært en veldig omfattende jobb å beregne beløp i alle disse testene på nytt nå. 
Dette er ikke en optimal løsning da testene bør bruke samme fil for grunnbeløp som selve beregningene i produksjon.
> EY-3086 Endrer gyldig fra dato til 01.01.2024 for omstillingsstønad

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/VergeService.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/adresse/PersondataAdresse.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagHenterTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/detaljer/MottakerPanel.tsx
Sletter krav om at enten orgnr eller fnr må finnes i en BrevMottaker. Kan gjeninnføres hvis/når vi får orgnummer på samhandlere.
Fikser også adressevisning i mottaker-panel.
> EY-3250: Setter hverken orgnummer eller fnr på verges samhandleradresse

- apps/etterlatte-testdata/src/main/kotlin/testdata/features/soeknad/OpprettSoeknad.kt
opprettSoeknadJson gir allerede en streng som representerer json, så en toJson på den escaper alt i strengen og gir deg en gyldig streng som pakker inn et helt objekt - dobbelt
> Fjerner dobbel toJson for opprettSoeknad

- apps/etterlatte-utbetaling/.nais/prod.yaml
Må ha på plass grensesnittsavstemming før vi gjør første vedtak for OMS.
Konsistensavstemming blir ikke kjørt før 4. januar, men skrur på denne også.
> Slår på grensesnitts- og konsistensavstemming for OMS i prod

- apps/etterlatte-samordning-vedtak/.nais/dev.yaml
- apps/etterlatte-samordning-vedtak/.nais/prod.yaml
> Jeg har fått gjennom kall via GW til faktisk app med bruk av appens ingress i apiendpoints-oppsettet, men ikke ved bruk av http://<app-name>. Har åpnet opp i appen for innkommende fra etterlatte-krakend. Er det noe mangel på å åpne opp på krakend-siden for utgående til appen?
Tommy Trøen:
> _det skal settes opp automatisk netpol basert på appName  i apiendpoints specen, dvs der må du ha det samme navnet som appen du spesifiserer i http//app-name. mulig vi kan lage noe logikk som gjør at vi kan fjerne appName fra specen også hvis det ikke er så tydelig_
https://nav-it.slack.com/archives/C02C9GJP17D/p1698225646227899?thread_ts=1697806246.535379&cid=C02C9GJP17D
> Inbound krakend trengs ikke å spesifiseres i nais.yaml

- apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml
- apps/etterlatte-vilkaarsvurdering/.nais/prod.yaml
Bør være _veldig_ trygt iht nais console. Default er `200m`, https://docs.nais.io/nais-application/application/#resourcesrequestscpu.
> Justert ned cpu for vilkårsvurdering

- apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningHendelseKonsument.kt
Dette er for å analysere hva som skjer, fordi det kommer altså stadig vekk 100+ meldinger som ikke mappes som forventet. 
https://logs.adeo.no/app/r/s/osNYS
Har også spurt samhandlingsteamet (som eier topic'en) om de kan se på dette.
> Logger meldinger til sikkerlogg

- apps/etterlatte-behandling/src/main/kotlin/Application.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingRoutes.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingRoutesTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Revurderingaarsak.ts
- libs/saksbehandling-common/src/main/kotlin/behandling/Revurderingaarsak.kt
Denne skal brukes for å opphøre sak(er) fra som har blitt migrert fra pesys, men har etterpå blitt opphørt i pesys og dermed aldri skulle vært i Gjenny.
Dette er kun backend. Kommer en frontend-endring som kun viser denne revurderingsårsaken dersom saksbehandler er intern.
> EY-3269 Legger til revurderingsårsak for opphør uten brev

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
- apps/etterlatte-behandling/src/main/resources/db/migration/v81__sett_riktig_prosesstype_migrerte_saker.sql
- apps/etterlatte-behandling/src/test/kotlin/behandling/migrering/MigreringRoutesTest.kt
Vi har p.t over 10.000 saker som ligger med prosesstype `MANUELL` som burde vært tagget som `AUTOMATISK`.
> Migrering skal sette rett prosesstype + oppdater behandlinger som er feil

- apps/etterlatte-statistikk/src/main/resources/db/migration/V31__fiks_mismatch_automatisk_iverksatte_vedtak.sql
Jeg ser ikke helt hvorfor dette skjer kun med den automatiske vedtaksriveren, men det blir feil kontra vedtakene som er sendt ut derifra (men ikke i vanlig behandlingsflyt). Tar gjerne imot innspill 😅
> Fikser 1 time mismatch i teknisk tid for iverksatte vedtak

- apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/Utils.kt
- apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/river/UtilsTest.kt
Unngår ekstra shift av tidspunkt med 1 time ekstra
> Tolker den parsede zonedDateTime sin instant som UTC i statistikk

- apps/etterlatte-behandling/.nais/dev.yaml
- apps/etterlatte-behandling/.nais/prod.yaml
- apps/etterlatte-beregning-kafka/.nais/dev.yaml
- apps/etterlatte-beregning-kafka/.nais/prod.yaml
- apps/etterlatte-egne-ansatte-lytter/.nais/dev.yaml
- apps/etterlatte-egne-ansatte-lytter/.nais/prod.yaml
- apps/etterlatte-gyldig-soeknad/.nais/dev.yaml
- apps/etterlatte-gyldig-soeknad/.nais/prod.yaml
- apps/etterlatte-hendelser-joark/.nais/dev.yaml
- apps/etterlatte-hendelser-joark/.nais/prod.yaml
- apps/etterlatte-institusjonsopphold/.nais/dev.yaml
- apps/etterlatte-institusjonsopphold/.nais/prod.yaml
- apps/etterlatte-opplysninger-fra-soeknad/.nais/dev.yaml
- apps/etterlatte-opplysninger-fra-soeknad/.nais/prod.yaml
- apps/etterlatte-trygdetid-kafka/.nais/dev.yaml
- apps/etterlatte-trygdetid-kafka/.nais/prod.yaml
- apps/etterlatte-vedtaksvurdering-kafka/.nais/dev.yaml
- apps/etterlatte-vedtaksvurdering-kafka/.nais/prod.yaml
- apps/etterlatte-vilkaarsvurdering-kafka/.nais/dev.yaml
- apps/etterlatte-vilkaarsvurdering-kafka/.nais/prod.yaml
Så, fra default `200m` til `25m`. Ser ikke ut til at lytter-applikasjonene bruker veldig mye cpu, og selv med såpass stort kutt bør det være greit nok med cpu til å kjøre appen stabilt. Er jo ikke satt limit, så de spike'ne som kommer en gang iblant bør håndteres fint.
https://console.nav.cloud.nais.io/team/etterlatte/utilization?from=2023-12-12&to=2023-12-19
> Redusert cpu for lytter-apps

- apps/etterlatte-saksbehandling-ui/server/src/index.ts
- apps/etterlatte-saksbehandling-ui/server/src/middleware/logging.ts
- apps/etterlatte-saksbehandling-ui/server/src/tests/sanitize.test.ts
- apps/etterlatte-saksbehandling-ui/server/src/utils/sanitize.ts
Fjernet `isDev` sjekk som logget headers siden den så og si aldri er i bruk mtp. dagens oppsett av lokal kjøring. 
Logg output tilsvarer nå backend. Så loggmelding vil da eksempelvis være: 
`POST /api/beregning/<id>/overstyrt` 
... i stedet for dagens...
`Request` ...hvor man må åpne meldingen i Kibana for å se endepunkt og metode.
> Forbedre requestLoggerMiddleware

- apps/etterlatte-testdata/.nais/dev.yaml
Appen ser ut til å bruke lite, og appen blir kanskje heller ikke altfor hardt brukt...
> Redusert cpu for testdata-app kraftig

- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
- apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoReguleringTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingRoutesTest.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagHendelserRiver.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/itest/GrunnlagDaoIntegrationTest.kt
- apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/PersonHendelseFordeler.kt
- apps/etterlatte-klage/src/test/kotlin/KabalOversendelseTest.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/LandNormalisert.kt
- libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/Enheter.kt
'Enum.values()' is recommended to be replaced by 'Enum.entries' since 1.9
https://kotlinlang.org/docs/whatsnew19.html#stable-replacement-of-the-enum-class-values-function
> Erstatter 'Enum.values()' med 'Enum.entries' etter bumping av Kotlin

- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakBehandlingService.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRoute.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtakBehandlingServiceTest.kt
DTO i usynk med `vedtaksvurdering-kafka`
Hadde noe problemer med at kall feilet med at status var SAMORDNET i stedet for TIL_SAMORDNING, når den oppdateringen gjøres innenfor samme route. Ser ut til at å droppe suspend fjernet den feilen.
> Korrigert dto og gjort statusoppdatering blocking

- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/Journalpost.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/DokumentRoute.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/Model.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafClient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafService.kt
- apps/etterlatte-brev-api/src/main/resources/graphql/dokumentoversiktBruker.graphql
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokument/DokumentRouteTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/App.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/flyttjournalpost/FeilregistrerJournalpost.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/flyttjournalpost/FlyttJournalpost.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/flyttjournalpost/Sakstilknytning.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/flyttjournalpost/VelgJournalpost.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreSak.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/dokument.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/sak.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/styled.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Journalpost.ts
- apps/etterlatte-saksbehandling-ui/docker-compose.yml
Nå som gjenlevendepensjon og omstillingsstønad kjører parallelt kan vi potensielt motta mange feilsendte journalposter. 
Gjenlevendepensjon som havner i Gjenny er enkelt – bytt tema til `PEN` og den plukkes opp av Pesys/Gosys.
Omstillingsstønad som havner i Pesys er verre: journalposten blir ferdigstilt og vi har ingen støtte for å hente den ut. Denne endringen gjør det mulig å feilregistrere journalposten og knytte den til sak i Gjenny. 
Dette er en _**midlertidig fiks**_, derav litt rotete grensesnitt og kode. 
1. Pesys får "Søknad om gjenlevendepensjon"
2. Saksbehandler ser den skulle vært omstillingsstønad pga. dato for dødsfallet. 
3. Åpner Gjenny og `/flyttjournalpost` (skjult som adminverktøy enn så lenge)
4. ...forts under:
Når dette er gjort blir det opprettet en …
> EY-3274 Støtte flyttTilAnnenSak på feilregistrert journalpost

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/Brevutfall.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/AdoptertAv.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/GrunnForSoeskenjustering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/OmgjoeringAvFarskap.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/RevurderingAnnen.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/barnepensjon/GyldigFramsattBarnepensjon.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/omstillingsstoenad/GyldigFramsattOmstillingsstoenad.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidVisning.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/generellbehandling/KravpakkeUtland.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/klage/Klagebehandling.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/klage/formkrav/KlageFormkrav.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/Tilgangsmelding.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/ToggleMinOppgaveliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/brev/TilbakekrevingBrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/saksbehandler.ts
- apps/etterlatte-saksbehandling-ui/client/src/store/reducers/InnloggetSaksbehandlerReducer.ts
- apps/etterlatte-saksbehandling-ui/server/src/routers/innloggetBrukerRouter.ts
Tar backend i egen pr
Siden NKS har samme ad-rolle som våre saksbehandlere må vi basere oss på enheter, og NKS har tre enheter som kun er NKS så da kan vi bruke det.
De vil kun ha søkefelt da de kommer i j9, det får de nå. 
+ Sperre på redigerbar en del steder. Kanskje flere steder jeg burde lagt det på men kommer ikke på alle nå.
> Skrive les tilgang frontend

- apps/etterlatte-egne-ansatte-lytter/src/test/kotlin/AvrokonstanterTest.kt
- libs/etterlatte-kafka/build.gradle.kts
- libs/etterlatte-kafka/src/main/kotlin/kafka/Avrokonstanter.kt
- libs/etterlatte-kafka/src/main/kotlin/kafka/Kafkakonfigurasjon.kt
- libs/etterlatte-kafka/src/test/kotlin/AvrokonstanterTest.kt
I kafka-biblioteket trekkjer vi inn avroserializer-avhengnaden, som har mykje greier og er ganske omfattande. Vi bruker berre denne for å finne verdiane for eit par konstantar. Det er dyrt definerte konstantar.
Endrar derfor til at vi sjølv definerer desse konstantane i vår kode.
Er ikkje veldig uroleg for at desse konstantane endrar seg, men skulle dei gjera det, vil den nye testen avdekke det. Denne testen er i ein app som faktisk bruker avroserializer-avhengnaden, så det kostar ingenting å ha han der.
Avroserializer-biblioteket er brukt i seks applikasjonar (egne-ansatte-lytter, hendelser-joark, hendelser-pdl, hendelser-samordning, institusjonsopphold, klage), medan etterlatte-kafka er i bruk i 11 (desse seks pluss behandling, testdata, utbetaling, start-grunnlagsversjonering og …
> Tar bort avhengnad vi knapt bruker frå kafka-lib.

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/omregning/OmregningRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/omregning/OmregningService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/AutomatiskRevurderingService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
- apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingServiceIntegrationTest.kt
Trur det kan vera lurt å sjå på denne commit for commit, for å følgje tankerekka mi, men målet er iallfall det vi ser i `OmregningRoutes` - at `omregningService.opprettOmregning` er synkront og i ein transaksjon, og at grunnlag-kall m.m. som skjer etterpå ikkje skjer i den transaksjonen.
> Omregning - flytte asynkrone kall ut av databasetransaksjon

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Grunnlagmapper.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapper.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/AvslagBrevData.kt
Gjør noen endrer slik at avslagsbrevet kan ta høyde for over/under 18 + bosatt utland.
Inntil videre så hentes over/under 18 ut på samme måte som i migrering, ved bruk av fødselsdato fra pdl. Tanken er å endre dette til å bruke brevutfall, men det krever litt større endringer.
> Tilpasser avslagsbrev for barnepensjon iht oppdatert mal

- apps/etterlatte-utbetaling/.nais/prod.yaml
Midlertidig tiltak mens vi ser på å fikse koden. CPU-bruken er altfor høy, ser i Grafana at den øker til 10 (med 24t vindu) og 15!! (med 48t vindu). Litt rart det, men det er uansett tullete tall.
> Øke ressurser for utbetaling kraftig pga konsistensavstemming.

- apps/etterlatte-utbetaling/.nais/prod.yaml
Status: failure: Application/etterlatte-utbetaling (FailedSynchronization): persisting Deployment to Kubernetes: Invalid: Deployment.apps "etterlatte-utbetaling" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: "640Mi": must be less than or equal to memory limit of 512Mi (total of 1 errors)
https://github.com/navikt/pensjon-etterlatte-saksbehandling/actions/runs/7407820642
> utbetaling - øke memory limits pga request

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevdistribuerer.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/Brevdistribuerer.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/DistribusjonService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/DistribuerBrevRiver.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevRouteTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevdistribuererTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/DistribuerBrevRiverTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerTest.kt
Ser ingen grunn til at distribuering skal vera forskjellig avhengig av type brev, så samkøyrer det.
Har også på blokka å gjera liknande for journalføring og knaskje også andre steg i brevproduksjonen, men ein ting av gongen.
> Samkøyre logikken for korleis vi gjer distribuering for alle typar brev

- apps/etterlatte-utbetaling/build.gradle.kts
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/Konsistensavstemming.kt
- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingTest.kt
Et annet, noe mindre, tiltak for å redusere cpu-bruk. Her ved at man unngår standard-serializerens bruk av kotlin reflection. Til og med bruken av litt enkle "verdi"-typer som wrapper, for eks `SakId`, `UtbetalingslinjeId` påvirker dette ganske kraftig. Har derfor laget en test som er ment til å avdekke om man legger til nye felt men glemmer å oppdatere serializeren.
Reduserer cpu-bruken for denne delen av koden relativt med ca 75%, basert på gjentatte lokale kjøringer med ca 5000 innslag i utbetalingstabellen (resetter "sist kjørt"-data mellom hver gang, og stopper app/jvm).
- Før endring:
- Etter endring:
> Konsistensavstemming - benytte custom serializers ved skriving av sluttresultat

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Grunnlagmapper.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/VergeService.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/VergeServiceTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/Verger.tsx
- libs/saksbehandling-common/src/main/kotlin/person/Person.kt
> EY-3284: Håndterer at PDL kan ha vergemål uten vergens fødselsnummer.

- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/Utbetaling.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/iverksetting/utbetaling/UtbetalingDao.kt
- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/TestHelper.kt
- apps/etterlatte-utbetaling/src/test/kotlin/utbetaling/avstemming/KonsistensavstemmingServiceKtTest.kt
For en **_massiv_** ytelsegevinst, ved at man 
1) unngår å hente felter som ikke jobben ikke benytter fra databasen (vedtak/oppdrag/kvittering)
2) og dermed slipper kostbar deserialisering
Har bare kopiert eksisterende med alt det det medfører i stedet og fjernet det som ikke trengs. Jeg har sett litt på å unngå duplisering, men ser ikke helt noen løsning som ikke medfører noe annet enn mer kompleksitet uten noen særlig annen gevinst. Typ kotlin lazy, hierarkier og annet, men det krever en del endringer så jeg mener det er feil vei å gå. 
**Edit**: Om folk synes at de ekskluderte verdiene kan gjøres `nullable` i den opprinnelige typen, så er det forsåvidt en grei løsning tenker jeg, selv om man fremdeles bør ha en egen spørring slik at DB/nett slipper å hente dataene.
Lokale kjøringer med …
> Konsistensavstemming - egen type av Utbetaling for denne jobben

- apps/etterlatte-behandling/.nais/dev.yaml
- apps/etterlatte-behandling/.nais/prod.yaml
- apps/etterlatte-beregning/.nais/dev.yaml
- apps/etterlatte-beregning/.nais/prod.yaml
- apps/etterlatte-brev-api/.nais/dev.yaml
- apps/etterlatte-brev-api/.nais/prod.yaml
- apps/etterlatte-grunnlag/.nais/dev.yaml
- apps/etterlatte-grunnlag/.nais/prod.yaml
- apps/etterlatte-hendelser-pdl/.nais/dev.yaml
- apps/etterlatte-hendelser-pdl/.nais/prod.yaml
- apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/Application.kt
- apps/etterlatte-pdltjenester/.nais/dev.yaml
- apps/etterlatte-pdltjenester/.nais/prod.yaml
- apps/etterlatte-samordning-vedtak/.nais/dev.yaml
- apps/etterlatte-samordning-vedtak/.nais/prod.yaml
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/Application.kt
- apps/etterlatte-statistikk/.nais/dev.yaml
- apps/etterlatte-statistikk/.nais/prod.yaml
- apps/etterlatte-trygdetid/.nais/dev.yaml
- apps/etterlatte-trygdetid/.nais/prod.yaml
- apps/etterlatte-trygdetid/src/main/kotlin/Application.kt
- apps/etterlatte-utbetaling/.nais/dev.yaml
- apps/etterlatte-utbetaling/.nais/prod.yaml
- apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
- apps/etterlatte-vedtaksvurdering/.nais/prod.yaml
- apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml
- apps/etterlatte-vilkaarsvurdering/.nais/prod.yaml
- libs/etterlatte-ktor/src/main/kotlin/MetricsModule.kt
Ser ut som disse i større grad nå trenger litt mer. Om det skyldes mer bruk, andre forhold (konsekvenser av oppdatering til Java 21?) eller annet er ikke jeg sikker på. Har også lagt til et par metrikker til som default, da noe av bakgrunnen for PRen er hendelsen med konsistensavstemming i `utbetaling`. Der var nok en del av problemet GC som aldri tok slutt pga masse data i minnet fordi for lite minne, cpu. Men ikke alle appene gir ut disse metrikkene p.t.
> Justert opp memory på en del apps

- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/avstemming/KonsistensavstemmingJob.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/common/Utils.kt
- apps/etterlatte-utbetaling/src/main/kotlin/utbetaling/config/ApplicationContext.kt
- apps/etterlatte-utbetaling/src/main/resources/db/migration/V16__sletter_konsistensavstemming_som_feilet.sql
- Justerer ned antall detaljer pr avstemmingsmelding for å komme under 50k pr melding
- Fjerner eksisterende konsistensavstemming som oppdrag ikke kunne lese inn pga størrelse på meldingene. 
- Hardkoder dato for når avstemmingen skal kjøres. Ikke så pent, men bør fungere 😛 
En oppfølging på denne er å sette tilbake til riktig dato for avstemmingen.
> Reduserer antall detaljer pr avstemmingsmelding

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
Vi har sett at det i mange tilfeller opprettes vedtaksbrev automatisk når saksbehandler går inn på et iverksatt vedtak, og det av en eller annen grunn ikke har blitt opprettet i den automatiske behandlingen.
Dersom det ikke ligger noen vedtaksbrev der fra før av (f. eks pga. feil under migrerte eller omregnede saker), så vil det opprettes et nytt dersom saksbehandler går til brevsiden i Gjenny. Det er uheldig at brevet kan opprettes på en behandling som er iverksatt, for det vil heller aldri bli sendt, og er misvisende.
Tanken er å kaste feil å lene seg på feilhåndteringen i frontend, da dette ikke er noe som normalt skal skje.
> Sperrer for opprettelse av vedtaksbrev i feil behandlingsstatus

- libs/saksbehandling-common/src/main/kotlin/behandling/Revurderingaarsak.kt
Vi må sjekke GcpEnv sin .env variable - ikke .name (vi skal sammenligne prod-gcp med prod-gcp og ikke PROD) :)
> Fiks miljøsjekk for revurderingsårsak

- apps/etterlatte-utbetaling/src/main/resources/db/migration/V17__utbetalingshendelse_index.sql
Denne spørringen har kjørt hundretusenvis av ganger nå, de siste 7 dagene. Litt mer enn normalt antageligvis pga problemene med konsistensavstemmingen og rekjøring.
```
SELECT
id,
utbetaling_id,
tidspunkt,
status
FROM
utbetalingshendelse
WHERE
utbetaling_id = $1
```
https://console.cloud.google.com/sql/instances/etterlatte-utbetaling/insights;database=utbetaling;duration=P7D;trace=470e83cc06da0cba84ad27849fb4c143;span=7f358f4c109267ef;query_hash=5094536347900720165;sort_by=TOTAL_EXEC_TIME?authuser=0&project=etterlatte-prod-207c
Avg execution time: 3.99 ms
Times called: 409,184
Avg rows returned: 2.999
I og for seg så er det jo grei ytelse her, men volumet gjør at det blir litt. 
I lokal database med 2000 rader (dev-kopi, + litt) så gir gjentatte kjøringer av `explain analyze` følgende:
- …
> Lagt til index på fremmednøkkel utbetalingshendelse.utbetaling_id

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Revurderingaarsak.ts
- libs/saksbehandling-common/src/main/kotlin/behandling/Revurderingaarsak.kt
Legger til ny revurderingsårsak for aldersovergang i Barnepensjon. Kunne brukt "Opphør uten brev", men da mister vi litt informasjon ift statistikk etc.
> Ny revurderingsårsak for opphør pga aldersovergang

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/JournalfoerBrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiver.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiverTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerTest.kt
Tilsvarande som for distribusjon i https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/3302
Sikrar at vi journalfører likt uavhengig av om det er vedtaksbrev eller anna brev. Flytta med det samme logikk frå river til service, så river no kun hentar ut data frå pakka, kallar service og publiserer vidare.
Kan vera nyttig å sjå på denne commit for commit for å følgje tankerekka.
> Samkøyre logikken for korleis vi gjer journalføring for alle typar brev

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/MaanedVelger.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/Brevutfall.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallSkjema.tsx
- Det oppstår en del problemer pga datoer med og uten tidspunkter og sammenligning av disse. Har først å sette datoene med tidspunkter som er starten av dagen ved valideringen siden tidspunkter i denne sammenhengen er irrelevant. 
- Setter opp fra-dato fra virkningstidspunkt og til-dato til og med inneværende måned + 1 (noe usikker på den siste der)
> Fikser validering av etterbetaling og gjør det mulig å velge datoer over årsskifte

- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakBehandlingService.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtakEtterbetaling.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/SamordningsvedtakRouteTest.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtakBehandlingServiceTest.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtakEtterbetalingKtTest.kt
- apps/etterlatte-vedtaksvurdering/src/test/kotlin/vedtaksvurdering/VedtakEtterbetalingTest.kt
Endrer fra å bare sjekke avhukningen av etterbetalingen av saksbehandler, til å sjekke opp mot beløp i eventuelle tidligere vedtak. Hvis høyere beløp i vedtak som skal iverksettes enn i tidligere vedtak, så etterbetaling - men kun hvis vedtaket gjelder tilbake i tid og beløpet gjelder periode tilbake i tid.
> EY-3185 Samordning - vedtak og etterbetaling

- apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnBarnepensjonServiceTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/BehandlingTest.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagHenterTest.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagServiceTest.kt
- apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TestHelper.kt
- apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidServiceImplIntegrationTest.kt
- libs/saksbehandling-common/src/main/kotlin/grunnlag/Grunnlag.kt
- libs/testdata/src/main/kotlin/grunnlag/GrunnlagTestData.kt
- libs/testdata/src/main/kotlin/pdl/PersonTestData.kt
Fikser problemer hvis det er utdatert / feil grunnlag på en sak. Den faktiske endringen er kun i `libs/saksbehandling-common/src/main/kotlin/grunnlag/Grunnlag.kt`, og alle andre endringer er i tester / mocks av grunnlag der det ikke var satt opp personer med fødselsnummer eller samsvarende persongalleri i grunnlaget.
> Grunnlag gir ut personer basert på hva som ligger i persongalleriet

- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/ToggleMinOppgaveliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/minoppgaveliste/FristHandlinger.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/tildeling/RedigerSaksbehandler.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/nyoppgavebenk/tildeling/TildelSaksbehandler.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts
For å unngå feilsituasjoner knyttet til optimistisk låsing der kun én saksbehandler er involvert, f.eks. tildele seg og så fradele uten å ha brukt hent/refresh i mellomtiden. Gosys enforcer dette på alt av updates.
Kommer slike feil i backend når dette skjer: https://logs.adeo.no/app/r?l=DISCOVER_SINGLE_DOC_LOCATOR&v=8.11.3&lz=N4IglgdgJgpgHiAXCAnANhmgLADgMYAMAtCjgQIZECMVMKROAzBUTFQOwBGnU2nWUTiAA0IAE4B7AO4BJaPCQgANhIDmAZwAu5dQAsi5AA6H1RQ5KhECBNDgBMKEeOkyoigKKcAWkSIBNKQAhFAB9ACsCKQBlAHVGPwA1ADcARycxGAAzGDEMsUUAeiNDAqgwdTwJJJyAYgKAfhDVAF4ACk0wAFsYRFbMyU7ECGkiOyxdAFI7ADFdYU0JIekASmWAMhDyNsqlAFdOiHVEAEJWpRhqpWFu9XVyVRhhGAgkvCUddWFipTA8cg6JBBhIYJFBlsJILA4IgAOToTC4QgkMiUGh0BjMShsLg8PgCTgw4QpXY5ACevXeEFUu3uPT2eGej2JZNhcBClVyMHeAIgITAUEQjBgnAIeHQlDQKA4RFwKEYBiwjDsRAArFg8FB2FRNWMVQTViAAL5AA%3D%3D …
> Oppdatere versjon på gosys-oppgave i sesjon ved til-/fradeling

- apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingService.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnBarnepensjonService.kt
- apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SelvbetjeningAuthorizationPlugin.kt
- apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/NyTrygdetidRoutes.kt
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/grunnlag/GrunnlagVersjonValidering.kt
- libs/etterlatte-ktor/src/main/kotlin/feilhaandtering/StatusPagesKonfigurasjon.kt
- libs/saksbehandling-common/src/main/kotlin/feilhaandtering/ForespoerselException.kt
- libs/saksbehandling-common/src/main/kotlin/feilhaandtering/InternfeilException.kt
* Rydde litt hvor hvilke exceptions kastes
NB: Meta inneholder ikke sensitive data
Kun behandlingid og tidspunkt
> Få med stacktrace på forespørselexception - alltid

- gradle/libs.versions.toml
Ser ut som mange av sårbarheitene dependency track i nais-konsollet rapporterer om no kjem transitivt via r&r, kanskje særleg at den ligg eit patch-hakk bak for kafka-clients (3.6.0) enn kva vi har definert elles (3.6.1). Så oppgraderer.
Oppgraderte avhengnadar er einaste endring frå r&r-versjonen vi bruker no til den nye.
> Oppgraderer r&r-avhengnad

- apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
- apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/DatabaseExtension.kt
- apps/etterlatte-behandling/src/test/kotlin/OmregningIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/TilgangServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoReguleringTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingsstatusRoutesTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoRoutesTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/bosattutland/BosattUtlandDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageDaoImplTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageRoutesIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingRoutesTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingServiceIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/sjekkliste/SjekklisteIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/egenansatt/EgenAnsattRouteTest.kt
- apps/etterlatte-behandling/src/test/kotlin/egenansatt/EgenAnsattServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/institusjonsopphold/institusjonsopphold/InstitusjonsoppholdDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/metrics/BehandlingMetricsOppgaveTest.kt
- apps/etterlatte-behandling/src/test/kotlin/metrics/BehandlingMetricsTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/sak/SakDaoTest.kt
av alle tester for raskere bygg.
Brorpartene av endringene forårsakes av problemer med tester som 
- ikke rydder opp
- baserer seg på databasen skal være fullstendig tom
- gjenbruk av fnr/testdata, og dermed forventning om helt tom starttilstand
For de 2 siste så bør man ikke ha slike forventninger med mindre det er et funksjonelt case på det. Legg inn _dine_ data, og sjekk _dine_ data.
> behandling - gjenbruk av Postgres testcontainer på tvers

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingVedtakRoute.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/AutomatiskRevurdering.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Foerstegangsbehandling.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManuellRevurdering.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManueltOpphoer.kt
- apps/etterlatte-behandling/src/test/kotlin/VerdikjedeTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oppsummering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/person/behandlingsslistemappere.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt
- libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/BehandlingStatus.kt
- libs/etterlatte-oppgave-model/src/main/kotlin/Oppgave/OppgaveIntern.kt
Behandlinger som avvises blir værende med status ATTESTERT. Vi har da ingen enkel måte å skille behandlinger som avventer iverksettelse fra Oppdrag og de som er ferdig behandlet med avslag.
Legger derfor til ny status AVSLAG til behandling.
Hvis endringene blir godkjent skal jeg også lage flyway som setter status på eksisterende behandlinger som er vedtatt med avslag til AVSLAG (i en ny PR).
> Ny status til behandling - AVSLAG

- gradle/libs.versions.toml
endringen der er at `nav-token-support` er bumpet til v4, som allerede er gjort i dette repoet
> Bumped lib etterlatte-common

- apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageRoutes.kt
Lar oss styre om man kan ferdigstille en klagebehandling, for å kunne teste behandling underveis i produksjon uten å evt. brekke noe som krever masse opprydding
> Egen toggle for ferdigstilling av klage

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
[FAGSYSTEM-314343 Barnepensjon - feil i beregning av trygdetid til avdøde](https://jira.adeo.no/browse/FAGSYSTEM-314343)
> Verdier i skjema for trydetid ble ikke lagret riktig

- apps/etterlatte-behandling/src/main/kotlin/Contekst.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDaoMedEndringssporing.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
- apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
Merk her mister superbrukerne sine tilganger for oppgavelisten.
Fikset i https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/3497/commits/31135afedfe97b72b3963d6dafd3d85f225d420d
Men avventer svar på om det kan fjernes.
> Filtrer mot enheter direkte mot database for oppgaver og ikke etterpå

- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagHenter.kt
Vi har brukt innsender til litt ymse data. Saksbehandler-ident, vedtaksløsningsnavn, m.m. 
Må derfor sjekke at innsender faktisk er et gyldig fnr. før vi går videre og sjekker/lagrer det.
> Kun mappe innsender hvis gyldig fnr

- apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
Type er alltid "KLAGE", og statusen er basert på klagehendelsetypen
> justerer type og status for klage-statistikk-hendelser

- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
Det er litt manglende validering, men nå settes søskenjusteringen slik den skal for behandlinger på gammelt regelverk. Vi kan vurdere om vi vil ha en ekstra sjekk på om avdøde har barn her, med tanke på at det gjelder kun gammelt regelverk og vi aldri har hatt en slik sjekk.
> Går til gammel fallback manglende søsken

- apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/GrunnlagKlient.kt
- apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
I den aktuelle saken var søknad mottatt i desember 2023 og virkningstidspunkt satt til 01.12.2020. Dødstidspunkt var i midten av 2020. Saksbehandler fikk ikke satt virkningstidspunkt fra desember 2023 i dette tilfellet. Denne PR'en åpner for dette for Barnepensjon.
For omstillingsstønad gjelder reglene slik de var. Tidligste virkningstidspunkt der ville basert på § 22-13 vært januar 2023.
> FAGSYSTEM-313675 Tillater virkningstidspunkt 3 år bakover i tid inkludert søknadsmåned

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/Model.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/dokumentliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/dokumentoversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Journalpost.ts
Vise utsendingsinfo i json-format til saksbehandler. Minimumsløsning enn så lenge. 
Får ikke testet på en god måte verken lokalt eller i dev siden utsendingsinfo aldri blir satt i dev. 
Vil se omtrent slik ut:
> Enkel visning av utsendingsinfo på journalpost

- apps/etterlatte-behandling/src/main/kotlin/behandling/BrukerService.kt
- apps/etterlatte-behandling/src/main/resources/db/migration/V87__fiks_enhet_i_sak.sql
VI har 9 saker i prod med enhet navn i sak: `NAV Familie- og pensjonsytelser Utland` - burde vært enhetnr
> EY-3335 - fiks setting av utland enhetnr

- apps/etterlatte-behandling/src/main/kotlin/behandling/sjekkliste/Sjekkliste.kt
fra Mari
> Kunne du fjernet sjekkpunktet på OMS om samordning (Samordning - løst opp pga ingen refusjon, se eget notat) når du får tid? Dette er nok kommet med ved en feil. Ser det er vist til Pesys også, så sikkert tenkt å ha det der i tilfelle det skulle komme noe mer..
> Fjernet OMS-sjekklistepunkt om løst samordning

- apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt
Så dersom man logger warningen og returnerer null, så blir svaret 200
I det andre tilfellet, hvor det faktisk er en reell feil i forentet status, så kaster jo valideringen der en exception som skal medføre feilkode tilbake til vedtaksvurdering-kafka (som før)
> Svar med 200 dersom samordning-svarmelding skippes

- apps/etterlatte-migrering/src/main/kotlin/migrering/PesysRepository.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/start/MigrerSpesifikkSakRiver.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt
- apps/etterlatte-migrering/src/main/resources/db/migration/V13__legge_til_gjenopprettes_automatisk.sql
- apps/etterlatte-migrering/src/test/kotlin/migrering/PesysRepositoryTest.kt
- apps/etterlatte-migrering/src/test/kotlin/migrering/start/StartMigreringRiverIntegrationTest.kt
- libs/etterlatte-migrering-model/src/main/kotlin/no/nav/etterlatte/rapidsandrivers/migrering/MigreringRequest.kt
- Legge til felt kanBehandlesAutomatisk
- Verifisering skiller mellom "feil som fører til mistet rett på ytelse" og "gjenopprettes manuelt". Førstnevnte kaster feil og sistnevnte setter kanBehandlesAutomatisk=false
- Av verifiseringsfeil som finnes i koden per nå er samtlige "gjenopprettes manuelt" med unntak av søker er død.
> Tilpasser oppstart av migrering for gjenoppretting av tidligere saker

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/Model.kt
- apps/etterlatte-brev-api/src/main/resources/graphql/dokumentoversiktBruker.graphql
Må fjernes midlertidig pga. måten SAF er satt opp. Må etterspørre utsendingsinfo separat siden det å etterspørre i journalposten medfører tom liste i respons.
> Fjerne utsendingsinfo fra journalpost

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevoppretter.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/PDFGenerator.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/RedigerbartVedleggHenter.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstilling.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevKodeMapper.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
For nye brev no bruker vi kun prosesstypen redigerbar, og det har vi gjort ei god stund.
For dei med manuell opnar vi framleis for å generere PDF, sia det fins nokre brev i prod-databasen som ikkje er ferdigstilt, inklusive eit par frå midten av januar. Usikker på korvidt desse framleis er relevante eller ikkje, men tenkjer å følgje opp den delen seinare.
> EY-3431: Forenkle brevkode ved å rydde bort moglegheit til å lage brev med prosesstypane manuell og automatisk

- apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
Vi får denne feilmeldingen ganske ofte. Logger derfor `e` til backend for å se hva som _faktisk_ feiler.
> Logge errormelding ved rejection

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevoppretter.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/MigreringBrevDataService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/PDFGenerator.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstilling.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperRedigerbartUtfall.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevKodeMapper.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonOmregnetNyttRegelverk.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/migrering/OpprettVedtaksbrevForMigreringRiver.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/InformasjonsbrevTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettVedtaksbrevForMigreringRiverTest.kt
Revert "EY-3438: Rydde bort spesialhandtering som ikkje trengs lenger for migrering/omregning frå brev-api (#3667)"
This reverts commit 9474bbaeae5b2393c8fff1e77c33ea8f938ba3c1.
> Det var for tidleg å rydde bort spesialhandtering for migrering, vi treng dei jo for 1.1.24-sakene

- apps/etterlatte-hendelser-joark/.nais/dev.yaml
- apps/etterlatte-hendelser-joark/.nais/prod.yaml
- apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/JoarkHendelseHandler.kt
- apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/config/ApplicationContext.kt
- apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/oppgave/OppgaveKlient.kt
- apps/etterlatte-hendelser-joark/src/main/resources/application.conf
- apps/etterlatte-hendelser-joark/src/test/kotlin/joarkhendelser/JoarkHendelseHandlerTest.kt
Dersom journalposten mangler bruker vil vi opprette en manuell journalføringsoppgave i Gosys. 
Dette fordi OppgaveAPI-et støtter manglende bruker, i motsetning til vårt eget oppgavesystem.
> EY-3166 Opprette manuell jfr-oppgave ved manglende bruker

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstilling.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevRoute.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevService.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevRouteTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevdistribuererTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiverTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettVedtaksbrevForMigreringRiverTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/VedtaksbrevUnderkjentRiverTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/ForhaandsvisningBrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Brev.ts
Tar med konseptet _brevtype_ også over i frontend. Liker betre å bruke det til å skilje på forskjellige typar brev enn meir tangerande eigenskapar som behandling-id, sak-id osv.
> EY-3442: Førehandsvisning av varselbrev, pluss konseptet brevtype i frontend

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevoppretter.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/PDFGenerator.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/RedigerbartVedleggHenter.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevKodeMapperVedtak.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevTest.kt
BrevKodeMapper-klassa hadde eit veldig generisk namn, til trass for at ho kun gjer mapping for vedtak. For alle andre brev sender vi med brevkoden frå lengre ut.
Døper dermed om til å gjenspegle denne røynda. Gjer, vel så viktig, litt omstruktureringar så vi lenger innover i kodebasen ikkje treng å bry oss om denne i det heile tatt, men kun sjå på brevkoden direkte.
> Forenkle brevkodemapping

- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
- apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/JoarkHendelseHandler.kt
- apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/behandling/BehandlingKlient.kt
- apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/behandling/BehandlingService.kt
- apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/oppgave/OppgaveKlient.kt
- apps/etterlatte-hendelser-joark/src/test/kotlin/joarkhendelser/JoarkHendelseHandlerTest.kt
Setter oppgaver som ikke er avsluttet til status avbrutt dersom journalposten de tilhører har utgått. 
Ingen av våre saksbehandlere har (så vidt jeg er kjent) rettigheter til å se utgåtte journalposter og det er heller ikke noe behov for behandling av en utgått journalpost.
> EY-3458 Avbryte oppgaver hvor journalpost har utgått

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnholdMedVedlegg.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt
Feiler i produksjon og dev pga manglende enum da denne var lagret ned.
> Legger til vedlegg-enum

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDTO.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevData.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EtterlatteBrev.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonAvslag.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelse.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonOmregnetNyttRegelverk.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonOpphoer.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonRevurdering.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/klage/AvvistKlageFerdigData.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadAvslag.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadOpphoer.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadRevurdering.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/tilbakekreving/TilbakekrevingBrevData.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
Trur vi gjer livet enklare for oss sjølve med eit skarpare skilje og også meir eksplisittt typa kode.
Tilsvarande avgrensing som i `BrevDataMapperFerdigstillingVedtak` bør forresten på plass i `BrevDataMapperRedigerbartUtfallVedtak`, men der må det litt oppsplitting i eit par brevdatatypar på plass først, så det kan vente littegrann.
> Slette ubrukt brevdata wiring og skilje skarpare mellom brevdata for redigering og for ferdigstilling

- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/aldersovergang/AldersovergangDao.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/aldersovergang/AldersovergangTest.kt
Dette er pga av dataene i nyopprettet case i dev, enkel familie. Barnet født i mars 2004. Dersom sql'en kjøres med start/slutt 2004-03-01 til 2004-03-31, så returneres ingenting. Det er pga at det finnes 3 hendelser av type FOEDSELSDATO, men barnets/søker er den med lavest ID... så original spørring finner opplysningen for avdøde forelder. Bugfixen er dermed å sjekke at hendelsen som hentes ut tilhører _søker_.
> EY-3355 Korrigert uthenting av saker hvor bruker har gitt alder

- apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/BeroertePersonerVedDoedsfallService.kt
- apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/BeroertePersonerVedDoedsfallServiceTest.kt
- libs/saksbehandling-common/src/main/kotlin/person/Folkeregisteridentifikator.kt
I første versjon er det kun barn av avdøde som er støttet (EPS og tidligere EPS kommer etterhvert), og det sjekkes på alder og at barnet er i livet. Bruk av denne tjenesten kommer i en senere PR.
EY-3384
> Ny tjeneste for å hente ut berørte personer ved dødsfall.

- apps/etterlatte-brev-api/src/main/resources/db/migration/V14__oppdater_vedlegg_key.sql
Oppdaterer alle vedlegg hvor key er `BEREGNING_INNHOLD` til `OMS_BEREGNING` slik at vi kan fjerne quickfix'en som tillater begge varianter.
> Migrerer key fra BEREGNING_INNHOLD til OMS_BEREGNING for brev-vedlegg

- apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/DatabaseExtension.kt
- apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/TilgangServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoReguleringTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/bosattutland/BosattUtlandDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageDaoImplTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageRoutesIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/sjekkliste/SjekklisteIntegrationTest.kt
- apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/egenansatt/EgenAnsattServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/institusjonsopphold/institusjonsopphold/InstitusjonsoppholdDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/metrics/BehandlingMetricsOppgaveTest.kt
- apps/etterlatte-behandling/src/test/kotlin/metrics/BehandlingMetricsTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
- apps/etterlatte-behandling/src/test/kotlin/sak/SakDaoTest.kt
- apps/etterlatte-behandling/src/test/kotlin/saksbehandler/SaksbehandlerInfoDaoTransTest.kt
- apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/AldersovergangerIntegrationTest.kt
- apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/DatabaseExtension.kt
- apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/HendelsePollerIntegrationTest.kt
- apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiverTest.kt
- apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/JobbPollerIntegrationTest.kt
- libs/etterlatte-database/src/testFixtures/kotlin/no/nav/etterlatte/GenerellDatabaseExtension.kt
- unngå å ha selve extensionen som object/singleton
- konfigurering av reset sql via annotasjon
- ikke veldig mye jobb å gjøre dette som annotasjon på selve testklassen, men da må man jo selvfølgelig angi det pr testklasse  
- injisering av database som constructor param i testklassene
Erstatter #3734
> Videre refaktorering av db-extension

- apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/OppdaterJournalpost.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/modal/JournalfoerJournalpostModal.tsx
Fått tilbakemelding fra flere at "ferdigstill" er litt forvirrende, siden det også brukes om oppgave (ferdigstill oppgave). 
Endrer derfor til "journalfør" slik at det blir likt som i Gosys.
> Endre på ordlyd etter ønske fra flere saksbehandlere

- apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreDokumenter.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreTittelJournalpost.tsx
Endre slik at det matcher resten av skjemaet.
> Fikse styling på "endreTittelJournalpost"

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevoppretter.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/PDFGenerator.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevRouteTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevdistribuererTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiverTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettVarselbrevForGjenopprettaRiverTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettVedtaksbrevForMigreringRiverTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/VedtaksbrevUnderkjentRiverTest.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/spraak/BrevSpraak.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/spraak/BrevSpraakModal.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Brev.ts
Støtter endring av målform/språk i brev. 
Må nok på sikt gjøres noen endringer på "andre brev" når vi får maler der også, men enn så lenge løser dette hvert fall det meste av språkproblematikken.
> EY-3304 Endre språk/målform i brev

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/RedigerbartVedleggHenter.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/TrygdetidService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/beregning/BeregningService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperRedigerbartUtfallVedtak.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDatafetcherVedtak.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonVarsel.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/BrevDataMapperVarsel.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevService.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/TrygdetidServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/beregning/BeregningServiceTest.kt
- apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevTest.kt
- libs/saksbehandling-common/src/main/kotlin/behandling/Utlandstilknytning.kt
Vart litt uventa refaktorisering for å komme i mål. Viste seg nemleg at Brevdatafetcher baserer seg på at det fins virkningstidspunkt på _vedtaket_, og her har vi jo ikkje eit vedtak. Kunne nok ha tweaka litt for å få det til, men det kjens ryddigare å heller gå rett mot services.
Trur det generelt er lurt å gå mot ein liknande struktur i brev-api som vi har i resten av applikasjonen, med tynne klientlag, logikk i services og at vi spør om det vi treng.
Heng saman med https://github.com/navikt/pensjonsbrev/pull/538
> EY-3481 Innhaldet i varselbrevet

- apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottaker.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottakerModal.tsx
Kun låse til 4 siffer hvis norsk adresse.
> FAGSYSTEM-317799 Korrigere pattern på postnummer + tag på utland

- apps/etterlatte-behandling/src/main/kotlin/sak/SakTilgangDao.kt
- apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/TilgangServiceTest.kt
For å støtte at vi i andre apper kan sjekke om vi har tilgang til behandlingen med klageId, som dukker opp som en problemstilling i f.eks. vedtaksvurdering / brev-api
> Legger til tilgangssjekk for behandlinger med klageId

- apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/GrunnlagKlient.kt
- apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt
- libs/etterlatte-ktor/src/main/kotlin/no/nav/etterlatte/libs/ktorobo/DownstreamResourceClass.kt
- libs/etterlatte-ktor/src/main/kotlin/no/nav/etterlatte/libs/ktorobo/Models.kt
Forslag til oppdatering på `DownstreamResourceClient`. Gjør at den ikke lenger spiser http-responskoder, m.m.
Nå vil den returnere `ResponseException` i alle tilfeller det er mulig, og `ThrowableErrorMessage` i de resterende.
> Videresende ResponseException fra DownstreamResourceClient

- apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
- apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt
P.t. får saksbehandler bare beskjed om at "personen har ingen saker", når de enkelt kan se i eks. Pesys at dette ikke stemmer. Dette blir deretter rapportert som feil hos oss, noe det ikke er. 
Legger derfor på en ekstra sjekk og feilmelding for å gi de litt mer å gå på.
> Bedre feilmelding til saksbehandler ved manglende enhetstilgang

- apps/etterlatte-tidshendelser/.nais/dev.yaml
- apps/etterlatte-tidshendelser/.nais/prod.yaml
- apps/etterlatte-tidshendelser/.run/etterlatte-tidshendelser.dev-gcp.run.xml
- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/AppContext.kt
- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/JobbPoller.kt
- apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/JobbPollerTest.kt
Et alternativ kan være å angi dette i selve jobbtabellen.
Uansett så er poenget å ha litt mer kontroll, og at jobber helst starter på et tidspunkt hvor folk er våkne og kan eventuelt ta tak i problemer som måtte oppstå.
> EY-3355 Spesifisere når jobber kan starte ("åpningstid")

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDatafetcherVedtak.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadRevurdering.kt
Endrer fra å se på utbetalingsinfo, til å se på avkortingsinfo for å finne ut om vi har endring på utbetaling ift forrige iverksatte behandling. Ikke veldig fan av hvordan utbetalingsinfo og avkortingsinfo er strukturert pr nå, men tror det får duge inntil vi har fått på plass revurderingsbrevet i første utgave.
> Bruker riktige beløper for å beregne om revurdering medfører endring i utbretaling for omstillingsstønad

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/ForhaandsvisningBrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/RedigerbartBrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/TilbakestillOgLagreRad.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
Endrer slik at knappene i bunn følger etter dersom man åpner et vedlegg. Tidligere ville knappene bli liggende over hverandre.
> Fikser visning i redigerbare vedlegg på brev

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafKlient.kt
Kjapp fiks for å sikre at saksbehandler får sett flere enn 20. Løser problemet midlertidig. 
Vil bli kraftig forbedret i [EY-3521](https://jira.adeo.no/browse/EY-3521).
> Hotfix: Øke antall journalposter som hentes

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelse.kt
Per no får vi ein `NoSuchElementException`, som ikkje er openbar før du har sett litt på koden (og resonnert deg fram til kva for eitt av dei moglege høva som slår til): https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-003041?id=qPxksY0BDLTuiVdR0qdm
> Legg på eksplisitt feilhandtering av at dødsdato manglar

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/DokumentRoute.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafService.kt
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/dokumentModal.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/dokumentliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/dokumentlisteLiten.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/VelgJournalpost.tsx
Det er vanlig at det finnes vedlegg på en journalpost. P.t. er det ikke mulig for saksbehandler å se disse i Gjenny, ettersom dagens løsning bare tar `[0]` i dokument-arrayen. Denne endringen vil gjøre det mulig for sb å se resterende dokumenter.
> EY-3433 Støtte flere dokumenter på journalpost

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/DokumentRoute.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/Model.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafKlient.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafService.kt
- apps/etterlatte-brev-api/src/main/resources/graphql/utsendingsinfo.graphql
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/dokumentliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/dokument.ts
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Journalpost.ts
> EY-3300 Kun hente utsendingsinfo på utgående journalposter

- apps/etterlatte-saksbehandling-ui/server/package.json
- apps/etterlatte-saksbehandling-ui/server/yarn.lock
Unleash 5.5.0 og eldre har avhengnad til ein versjon av ip-pakka som er sårbar for ein CVE med høg risiko, CVE-2023-42282. Unleash-klienten bruker ikkje denne, så det bør ikkje vera nokon risiko for oss, men fint å få det ut av verda
Støta også på ein feil som gjorde at frackenden ikkje bygga, sjå dei tidlegare køyringane på denne PR-en. Det viste seg å vera https://github.com/eslint/eslint/discussions/17215 , så har også tatt inn fiksen på det (den nyaste minor-versjonen av Unleash-klienten bruker ein nyare versjon av glob, som igjen bruker ein nyare versjon av strip-ansi, som får ting til å tryne)
> Oppgradér til nyaste Unleash-klient, for å rette CVE

- apps/etterlatte-egne-ansatte-lytter/build.gradle.kts
- apps/etterlatte-hendelser-joark/build.gradle.kts
- apps/etterlatte-hendelser-pdl/build.gradle.kts
- apps/etterlatte-hendelser-samordning/build.gradle.kts
- gradle/libs.versions.toml
Det er sårbarheiter i commons-compress, inkludert ein kategorisert som high. Tar derfor i bruk nyaste patch-versjon, der sårbarheitene er retta. Den gamle versjonen kjem inn transitivt via Apache Avro, som oppdaterast (altfor, spør du meg) sjeldan, så det er ikkje godt å seie kor fort neste versjon der kjem.
Har gått nøye gjennom [release notes](https://commons.apache.org/proper/commons-compress/changes-report.html#a1.23.0) for Commons Compress mellom 1.22.0, som vi køyrer på i dag og som kom allereie i november 22, og 1.26.0, og det ser ut til å vera utelukkande små feilrettingar, kan ikkje sjå noko risikabelt der
> Oppgraderer til nyaste commons-compress

- apps/etterlatte-grunnlag/build.gradle.kts
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/aldersovergang/AldersovergangDao.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/aldersovergang/AldersovergangRoutes.kt
- apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/aldersovergang/AldersovergangService.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/GrunnlagDbExtension.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/aldersovergang/AldersovergangTest.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/itest/GrunnlagDaoIntegrationTest.kt
- apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/itest/RapidTest.kt
For å understøtte hendelser for OMS:
- Opphør tre år etter dødsfall
- Opphør etter ytterligere to år innvilget
- Sende infobrev om aktivitetsplikt fire mnd etter dødsfall
- Sende infobrev om aktivitetsplikt 10 mnd etter dødsfall
> EY-3530 API i grunnlag for å hente saker med dødsdato i angitt måned

- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/rivers/AldersovergangRiver.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/rivers/AldersovergangRiverTest.kt
Behandlingsmåneden er effektivt måneden som ytelsen skal løpe _ut_, og det gir derfor mening å sjekke om det finnes ytelse måneden _etter_. 
Uten denne endringen vil det kunne identifiseres løpende ytelse for aldersovergangen selv om den allerede er opphørt.
> EY-3355 Sjekke løpende ytelse for måneden etter behandlingsmåned

- apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseRiver.kt
- apps/etterlatte-oppdater-behandling/src/test/kotlin/TidshendelseRiverTest.kt
En løsning for å gi litt mer input til saksbehandler inntil oppgave(-lista) har gjennomgått endringer, som diskutert 19. feb, mtp å kunne ha noe mer egnede felter for slikt.
> EY-3526 Legg ved år i merknad på oppgave for aldersovergang

- apps/etterlatte-vilkaarsvurdering/src/main/resources/db/migration/V20__fikser_vilkaar_aktivitetsplikt.sql
Fikser vilkårsvurderingene som har blitt opprettet for omstillingsstønad med feil type på aktivitetsplikts-vilkåret.
> EY-3545: Setter riktig type i vilkår for aktivitetsplikt

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Vedtaksbrev.tsx
Her går vi jo ikkje innom beregna-steget i frontend, men systemet behandlar til og med varselbrev.
Etter varselbrevet er sendt ut kan saksbehandlar gå inn på behanldinga, og da trynar det per no, fordi vedtaket ikkje enno er oppretta.
Ser diffen her på github vart litt rar, men sjå commit for commit eller lokalt ved behov.
> Sikre at vi har vedtak for automatisk gjenoppretta saker

- apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseRiver.kt
- apps/etterlatte-vilkaarsvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/TidshendelseRiver.kt
Har ikke kontroll på hele mekanismen her, og det er ikke implementert noe spesifikt for `tidshendelser` for å håndtere det så inntil videre tenker jeg det er best å bare feile
> Ikke benytte feilhåndtering-lytter for tidshendelser-rivers

- apps/etterlatte-saksbehandling-ui/client/src/components/person/Samordning.tsx
- apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/SamKlient.kt
Kræsjer slik det er nå, men UIet er jo ikke supertilgjengelig da ettersom eller ingenting lite står og venter på samordning. 
Til info så jobbes det på en større endring på UIet her, ref EY-3314.
> Håndtere 204-respons fra SAM

- apps/etterlatte-saksbehandling-ui/Dockerfile
- apps/etterlatte-saksbehandling-ui/server/Dockerfile.dev
[Testa i dev](https://github.com/navikt/pensjon-etterlatte-saksbehandling/actions/runs/7971569969), fungerer fint.
Har skildra formålet i jirameldinga, men legg like godt inn her også:
> Vi bruker distroless baseimages for backend-applikasjonane våre, det kan vi med fordel gjera også for node-applikasjonane.
> 
> Trudde slim-versjonane av det offisielle node-baseimaget skulle vera slim, men desse inneheld ein god del andre bibliotek i tillegg. [Distroless-node](https://github.com/GoogleContainerTools/distroless/blob/main/nodejs/README.md) verkar meir eigna, der får vi kun med akkurat det vi treng.
> 
> Oppdaga gjennom sårbarheita i node-ip, som no gjer at [slsa-analysen ](https://console.nav.cloud.nais.io/team/etterlatte/vulnerabilities)viser at alle frontendapplikasjonane våre er …
> EY-3538: Distroless node

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/beregning/BeregningService.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDatafetcherVedtak.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt
- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadRevurdering.kt
Inntil nå har man hentet ut både beregning og beregning med avkorting for omstillingsstønad. Dette er unødvendig da alt (også beregningsmetode) returneres fra sistnevnte etter en liten endring i beregning.
> Fjerner ekstra kall for å hente utbetalingsinfo for omstillingsstønad-brev

- apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt
- apps/etterlatte-migrering/src/main/kotlin/migrering/verifisering/Verifiserer.kt
- libs/etterlatte-migrering-model/src/main/kotlin/no/nav/etterlatte/rapidsandrivers/migrering/MigreringRequest.kt
- Enhet til tidligere pesys sak skal ikke videreføres med utledes i Gjenny
- Gradering fra pdl sendes med videre til opprettelse av sak
> Gjenoppretting - Fjerner overstyr enhet og legger til gradering

- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelsePoller.kt
Kjørt noen jobber i prod i dag for aldersoverganger, og la litt tilfeldig merke til at hendelsepollertasken logger med en del metadata som ikke tilhører den, men til håndteringen av enkelthendelser - og som burde bli fjernet når man går ut av scopet der? 
https://logs.adeo.no/app/r/s/R7qsN
Byttet om til markers-interfacet så tråd-type problematikk unngås i sin helhet.
> Benytter logstash markers i stedet for logg-ctx ved polling

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/useVedtaksResultat.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/store/reducers/BehandlingReducer.ts
Endrer til å bruke samme begrep for vilkårsvurdering i redux-state som ellers i koden. Vilkårsprøving er noen gamle rester fra lang tid tilbake.
> Endrer navn fra vilkårsprøving til vilkaarsvurdering som brukes ellers i koden

- apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiUtils.ts
Eksempel med `mapApiResult`:
```tsx
mapApiResult(
klager,
<Spinner visible label="Henter klager i saken" />,
() => <ApiErrorAlert>Kunne ikke hente klager</ApiErrorAlert>,
(klageliste) => <KlageTabell klager={klageliste} />
)
```
Samme eksempel med `mapResult` (ja, kun pending er satt her -- men spinneren gir uansett kun mening når den er pending):
```tsx
mapResult(klager, {
success: (klageliste) => <KlageTabell klager={klageliste} />,
pending: <Spinner visible label="Henter klager i saken" />,
error: () => <ApiErrorAlert>Kunne ikke hente klager</ApiErrorAlert>,
})
```
> Mer fleksibel / lettleselig mappermetode for ApiResult

- docker/Dockerfile
Biblioteka våre oppdaterer seg mykje sjeldnare enn koden vår gjer. Dermed er det fint viss vi kan hente biblioteka frå Docker-cachen når vi kun har endra på vår kode. Biblioteka har typisk ein bindestrek i namnet, så kopierer inn dei først som eit eiget lag i dockerfila.
Skulle ideelt sett hatt regex eller noko som gjorde at vi kun kopierte dei med nummer etter bindestrek, for å hindre å få med våre eigne libs, men det var litt tricky å få med. Dette er uansett betre enn det var.
> Cacher bibliotek i dockerfila

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingService.kt
- apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt
- apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt
Sjekker opp gjeldende vilkår mot vilkår i den kopierte vurderingen
- Vilkår som ikke lenger finnes i listen over gjeldende vilkår fjernes
- Vilkår som er nye i listen over gjeldende vilkår legges til
Dersom nye vilkår er lagt til, vil disse mangle vurdering. Vi fjerner derfor totaltvurdering på vilkårsvuderingen.
Dersom vilkårene er uforandre, beholdes totaltvurderingen.
> EY-3426: Ved kopiering av vilkårsvurdering legges nye vilkår til og utdaterte fjernes

- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/typer.ts
Her burde vi på sikt vurdere om selve enum verdien til hendelse også bare burde hete `HENDELSE` og ikke `VURDER_KONSEKVENS`
> Gjør filter for hendelse mer lesbart

- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/ToggleMinOppgaveliste.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/FilterRad.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/filtrerOppgaver.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/typer.ts
- apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaver/Oppgaver.tsx
Etter ønske fra saksbehandlere. Var også ønske om å låse til eksakt match på fnr eller sakid for å ikke få så mye "støy" i resultatet.
> EY-3621 Filtrere fnr og sakid samme felt (exact match)

- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/Hendelse.kt
- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseDao.kt
- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiver.kt
- apps/etterlatte-tidshendelser/src/main/resources/db/migration/V3__loepende_ytelse.sql
- apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiverTest.kt
I stedet for å sjekke logger eller kolonna med fulle meldinger i json.
Poenget er at antallet hendelser som produseres kan være langt høyere enn de som faktisk medfører noe, og det bør være lett å finne ut av dette.
> Egen db-kolonne for å lagre om det er løpende ytelse på saken for enklere oppslag

- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/Tilbakekrevingsbehandling.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/brev/TilbakekrevingBrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/sidemeny/TilbakekrevingSidemeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/stegmeny/TilbakekrevingStegmeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingOppsummering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingOverordnet.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingOverordnetVisning.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingPerioder.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingPerioderVisning.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/alerts/Toast.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Tilbakekreving.ts
- Endrer måten vedtak som er til attestering, samt ferdige behandlinger vises på, slik at det blir tilsvarende de andre behandlingene vi har. Dette i stedet for bruk av readonly-felter. 
- Legger inn felter i sidemenyen (sakId, ytelse, status og sett til vent)
- Legger inn manglende streker over knappene i bunn av skjermbildet
- Forenkler dropdown-lister ved å mappe over en liste som også kan brukes ved visning
- Legger inn en success-alert når lagring av vurdering eller lagring av perioder er utført. Dette for å tydeliggjøre at det faktisk ble lagret.
> EY-3637 Endre visning ved attestering og attestert for tilbakekreving

- apps/etterlatte-brev-api/src/main/resources/graphql/dokumentoversiktBruker.graphql
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/DokumentRad.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/FeilregistrerJournalpost.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/FlyttJournalpost.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/HaandterAvvikModal.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/OpphevFeilregistreringJournalpost.tsx
- Støtte feilregistrering og flytting av journalpost
- Ved flytting blir journalposten automatisk feilregistrert
TODO: 
- Litt grumsete kode i `FlyttJournalpost.tsx`, men prioriterer å få ut fiksen. Har som plan å opprette oppgave på saksbehandler når de vil endre på journalpost for å øke sporbarheten. 
- Må støtte flere avvik. Journalpost utgår, avbrutt, m.m.
> EY-3636 Håndtere avvik på journalpost

- apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrevHandlingerPanel.tsx
Enkel påminnelse til sb om at innholdet i brevet må lagres. 
En bedre løsning er å legge til forsinkelse av journalføring/distribusjon, men det er et større prosjekt som ikke blir prioritert akkurat nå.
> EY-3634 Påminnelse om lagring av brev

- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/HaandterAvvikModal.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/KnyttTilAnnenBruker.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/KnyttTilAnnenSak.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/common/SakOverfoeringDetailjer.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/BehandleJournalfoeringOppgave.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/dokument.ts
Endre litt på måten man flytter en journalpost til annen sak/bruker i tilfeller hvor journalposten ikke er ferdigstilt/journalført. 
Endepunktet `/knyttTilAnnenSak` i dokarkiv fungerer kun dersom journalposten allerede har en sakstilknytning, noe den ikke nødvendigvis har.
> EY-3636 Støtte flytting av journalpost som ikke ikke er ferdigstilt

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafKlient.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlOboKlient.kt
- apps/etterlatte-testdata/src/main/kotlin/Application.kt
- libs/etterlatte-ktor/src/main/kotlin/no/nav/etterlatte/libs/ktorobo/AzureAdClient.kt
- libs/etterlatte-ktor/src/main/kotlin/no/nav/etterlatte/libs/ktorobo/DownstreamResourceClass.kt
- libs/etterlatte-ktor/src/main/kotlin/no/nav/etterlatte/token/BrukerTokenInfo.kt
- libs/etterlatte-ktor/src/test/kotlin/no/nav/etterlatte/libs/ktorobo/AzureAdClientTest.kt
- libs/etterlatte-ktor/src/test/kotlin/no/nav/etterlatte/libs/ktorobo/DownstreamResourceClientTest.kt
Som det er no har vi eit par-tre forskjellige inngangsvegar til å hente tokens, korav ikkje alle støttar systembrukar-kall.
Dels kjens det som unødvendig kompleksitet, men mest av alt kjens det som noko som på eit tidspunkt vil gjera at vi introduserer feil, og at regulering eller andre automatiske jobbar plutseleg sluttar å funke fordi vi endra ein plass utan å tenkje på dét.
Løyser det derfor ved at AzureAdClient kun eksponerer ut éin metode offentleg, og den tar høgde for at det kan vera systembrukar eller saksbehandlar.
> Skriv om så vi har éin og berre éin måte å hente tokens på

- apps/etterlatte-behandling/src/main/kotlin/Contekst.kt
- apps/etterlatte-behandling/src/test/kotlin/SaksbehandlerMedEnheterOgRollerTest.kt
Var litt hastverk i går kveld etter merge av lesetilgang.
Denne rydder hotfixen ved å gjøre det enklere samt tar med at vi tester kanSeOppgaveBenken() på saksbehandler.
> Rydde/forenkle etter gårsdagens hotfix samt test kanSeOppgaveBenken()

- apps/etterlatte-saksbehandling-ui/client/src/components/klage/Klagebehandling.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/klage/formkrav/KlageFormkravVisning.tsx
Bruk av hooks conditionally på render (`useKlageRedigerbar` og `useNavigate`) bryter reglene og gir feil
> Fikser opp i feil med hooks-kall for klage

- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/ParallelleSannheterKlient.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlOboKlient.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/PersonMapper.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/personweb/PersonWebRoute.kt
- apps/etterlatte-pdltjenester/src/main/kotlin/personweb/PersonWebService.kt
- apps/etterlatte-pdltjenester/src/main/resources/pdl/hentPersonNavn.graphql
- apps/etterlatte-saksbehandling-ui/client/src/shared/api/pdltjenester.ts
Vi får ofte aktørid i bruker-objektet på journalposter. Som en følge av det er det vanskelig for saksbehandler å se at det er koblet til riktig person ved behandling av journalføringsoppgaver. 
Legger derfor til støtte for henting av navn på aktørid slik at vi kan vise navnet til personen ved siden av bruker-identen fra dokarkiv.
> EY-3672 Støtte henting av navn med aktørid

- apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveRoute.kt
Vi har ingen støtte for sjekk av enhet mot Gosys. Fjerner derfor denne inntil videre slik at saksbehandlere får gjort jobben sin. 
Må undersøke om Gosys har sjekk av dette på sin side. Hvis så kan vi mest sannsynlig bare la det være.
> Fjerne sjekken på skrivetilgang mot Gosys-apiet

- apps/etterlatte-samordning-vedtak/.nais/apiendpoints.yaml
deploy feilet: https://github.com/navikt/pensjon-etterlatte-saksbehandling/actions/runs/8264180480/job/22607504532
Endring i krakend-operator: https://github.com/nais/krakend/commit/2f11949c571cae49f97663faeb74327ad55c1ac3
Krakend er jo litt i beta ennå, har ikke funnet noe annonsering av dette men ser at et par andre har også fått samme feil.
Jeg har annonsert mot tp-leverandørene at krakend likevel _ikke_ blir tingen å bruke hos oss, endepunktet får leve frem til sommeren-ish.
> krakend-operator spec endret: scope -> scopes

- apps/etterlatte-testdata/.nais/dev.yaml
Virker som det er litt kluss med de ulike AD-gruppene og at **type** må være `Exchange` eller `Microsoft 365`. 
Gruppen for utviklere i nav er av type `sikkerhet` og fungerer ikke...? 
Bruker derfor `po-pensjon` i stedet. Gir også litt mer mening siden det er mest aktuelt for pensjonsområdet å bruke løsningen.
> Bytte til po-pensjon tilgang

- apps/etterlatte-saksbehandling-ui/client/src/components/klage/brev/KlageBrev.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/EndeligVurderingVisning.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/InitiellVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurdering.tsx
- apps/etterlatte-saksbehandling-ui/client/src/shared/types/Klage.ts
- libs/etterlatte-behandling-model/build.gradle.kts
- libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt
- libs/etterlatte-behandling-model/src/test/kotlin/no/nav/etterlatte/libs/common/behandling/KlageTest.kt
Nullstiller hvis "formkrav oppfylt" eller "framsatt innen frist" endres. Viser felter for initielt utfall bare hvis klagen har initielt utfall. Navigeringsknapp ved redigering av initielt utfall. Required settes på feltet initielt_utfall.begrunnelse.
> EY-3679: Nullstiller utfall og initielt utfall ved gitte endringer i formkrav

- apps/etterlatte-behandling/src/main/kotlin/behandling/omregning/OmregningRoutes.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/omregning/OmregningService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/AutomatiskRevurderingService.kt
- apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
- apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseRiver.kt
- apps/etterlatte-oppdater-behandling/src/test/kotlin/TidshendelseRiverTest.kt
- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiver.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/rivers/AldersovergangRiver.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/rivers/AldersovergangRiverTest.kt
- apps/etterlatte-vilkaarsvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/TidshendelseRiver.kt
- apps/etterlatte-vilkaarsvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/services/VilkaarsvurderingService.kt
- apps/etterlatte-vilkaarsvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/TidshendelseRiverTest.kt
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/Application.kt
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/AldersovergangRoutes.kt
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/AldersovergangService.kt
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRoutes.kt
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingService.kt
- apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/config/ApplicationContext.kt
- apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/AldersovergangRoutesTest.kt
- apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/AldersovergangServiceTest.kt
- apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt
- libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Omregningshendelse.kt
- libs/etterlatte-vedtaksvurdering-model/src/main/kotlin/VedtakAldersovergangStepEvents.kt
Beklager størrelsen, men det er mest tester samt refaktorering (extract method) som drar opp.
Flyt etter at `vedtaksvurdering` har identifisert om det er løpende ytelse, og dermed skal behandles
1. `oppdater-behandling` forsøker å opprette omregning, hvis ikke fallback til eksisterende oppgaveløsning
2. `vilkårsvurdering` kopierer forutgående vilkårsvurdering, men setter aldersvilkår og totalvurdering til ikke oppfylt
3. `vedtaksvurdering` fatter og attesterer vedtak, kafka-biten sender ut både vedtakshendelse som medfører at vedtaket blir iverksatt samt markerer tidshendelsen som behandlet
4. `tidshendelser` markerer hendelsen som ferdig
> EY-3631 Automatisk opphør ved hendelse for barnepensjon 20 år

- apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/OmregningHendelserRiver.kt
- apps/etterlatte-beregning-kafka/src/test/resources/omregningshendelse.json
- apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/OmregningsHendelserRiver.kt
- apps/etterlatte-oppdater-behandling/src/test/resources/omregningshendelse.json
- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/regulering/LoependeYtelserforespoerselRiver.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/regulering/OpprettVedtakforespoerselRiver.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/regulering/LoependeYtelserforespoerselRiverTest.kt
- apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/regulering/OpprettVedtakforespoerselRiverTest.kt
- apps/etterlatte-vilkaarsvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRiver.kt
- apps/etterlatte-vilkaarsvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRiverTest.kt
- jobs/start-regulering/Dockerfile
- jobs/start-regulering/src/main/kotlin/Application.kt
- libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/ReguleringHendelseType.kt
- libs/rapidsandrivers-extras/src/test/kotlin/rapidsandrivers/FeilhaandteringKtTest.kt
- Unngår å hardkode inn årstal i jobben, trur det er ganske trygt å gå ut frå at den gjeld for inneverande år
- Døper om hendingane til å ha namn om kva som faktisk har skjedd heller enn kva som er tenkt å skje. Det er lettare å resonnere rundt og også meir eintydig
- Oppgraderer imaget til Java 21, som vi bruker overalt elles
> Småforbetringar på regulering

- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutes.kt
- apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt
- apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt
- apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
Viss vi har manuelt overstyrt beregning, har vi ikkje nødvendigvis eit beregningsgrunnlag inne. Det er forventa, feks ved manuell migrering frå Pesys. Ønskjer derfor ikkje å kræsje viss det manglar og det er sagt at vi overstyrer beregning
> Takle manglande beregningsgrunnlag ved duplisering for overstyrt beregning

- apps/etterlatte-behandling/src/main/resources/db/prod/V103__endre_til_riktig_enhet_oppgave.sql
Bare saken fikk endret enhet i https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/4230
Og oppgavene ble da følgelig utilgjengelig for 4817 sber.
> Sett riktig enhet for oppgave tilknyttet endret sak

- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseDao.kt
- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiver.kt
- apps/etterlatte-tidshendelser/src/main/resources/db/migration/V4__drop_trigger.sql
Kommer [problemer](https://logs.adeo.no/app/r?l=DISCOVER_SINGLE_DOC_LOCATOR&v=8.12.2&lz=N4IglgdgJgpgHiAXCAnANhmgLADgMYAMAtCjgQIZECMVMKROAzBUTFQOwBGnU2nWUTiAA0IAE4B7AO4BJaPCQgANhIDmAZwAu5dQAsi5AA6H1RQ5KhECBdtYBMI8dJlRFAOQkBHIgDUAmlgAQjAAVn4AGlQA6hAoMjIw5I5iMABmMGIpYooA9EaGOVBg6ngSAG4ZAMQ5APwA%2BqoAvAAUmmAAtjCIzamS7YgQ0kR2WLoApHYAYrrCmhID0gCUiwBkdeQtpUoAru0Q6ogAhM1KMBVKwp3q6uSqMMIwEGV4SjrqwvlKYHjkbRIQwkMEigi2EkFgcEQAHJ0JhcIQSGRKDQ6AxmJQ2FweHwBJwocJPNsMgBPbqvCCqba3Lo7PCPe6EknQuB1UqZGCvP4QOpgKCIKDkdKMGBQSypFCCohYTi2IicNBUYh0qDsACsqvI5Ds6HIUOWIAAvkA) med triggeren nå. 
Har prøvd ```SET enable_seqscan=off;``` men det så ut til å fungere bare litt..? Ref [denne posten](https://stackoverflow.com/questions/42288808/why-does-postgresql-serializable-transaction-think-this-as-conflict).
Triggeren …
> Endret til å ferdigstille jobb uten db-trigger

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/BehandlingSidemeny.tsx
- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/IBehandlingInfo.ts
Konteksten her er aldersoverganger, mer spesifikt at det må være en måte for saksbehandlere å kunne se at vedkommende har fått med seg yrkesskadefordel pre-01.01.2024, dvs migrert. Da er opphør ved 21 år, ikke 20 år.
Avklart med Mari.
En oppfølger er å vise mer spesifikk informasjon om yrkesskaden på saksoversikten, men det er litt mer jobb så tar denne først da aldersoverganger kjøres for en god bestand i morgen (20. mars).
> Vise kilde i behandlingens sidemeny

- apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/migrering/OpprettVarselbrevForGjenopprettaRiver.kt
No trur vi at vi har oppretta varselbreva for gjenoppretting som vi skal opprette automatisk, og skulle det dukke opp nye, får vi handtere det. Behovet for å kunne skru distribuering av og på er iallfall ikkje der per no
> Tar bort utdatert brytar for å hindre distribuering av brev for gjenoppretting

- apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
Her er det kanskje mer å rydde opp i, men dette er da noe. Uten denne fiksen så viser vi "fikk en feil i parsing av data / rejection i fetch. Feilen ligger i meta' i GUI når vi får 503 :)
Sett i klagebehandling hvor vi skal hente dokumenter for sidemenyen og får 503.
> EY-3721: Feiler litt penere når backend ikke sender med errorinfo som JSON-objekt

- apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/ForhaandsvisningBrev.tsx
Gjør det lettere for sb å laste ned eller printe brevet i tilfeller hvor noe stopper opp hos oss.
> Vise PDF-toolbar på brevoversikten

- apps/etterlatte-tidshendelser/.nais/dev.yaml
- apps/etterlatte-tidshendelser/.nais/prod.yaml
- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseDao.kt
- apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelsePoller.kt
- apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/DatabaseExtension.kt
- apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/HendelsePollerIntegrationTest.kt
Dette er ifb med [denne situasjonen](https://nav-it.slack.com/archives/C043C5ZGW5T/p1710923126770249).
Antagelsen er at utsendingen av eventen og påfølgende oppdateringer av raden (via river) kommer så kjapt at statusoppdateringen går i beina på den. Restrukturert for å unngå dette.
I tillegg lagt på at man forsøker å re-sende hendelsen dersom den har feilet, men først i senere `poll()`
> Restrukturert oppdatering av status på hendelser 
