.github/workflows/app-etterlatte-samordning-vedtak.yaml
apps/etterlatte-samordning-vedtak/README.md

Ref oppdatering/presisering fra nais-teamet vedrørende krakend og GCP-apper: https://nav-it.slack.com/archives/C02C9GJP17D/p1708006799303129

Oppdatert dok vedrørende ekstern gateway for samordning-api

---

.github/workflows/app-etterlatte-tidshendelser.yaml
apps/etterlatte-tidshendelser/README.md

Bruker github sin mermaid-støtte. Diagrammet er litt lavterskel sett opp mot muralen.
For å rendre automatisk i intellij, så last ned JetBrains' mermaid-plugin.
For å se det rendret gå til https://github.com/navikt/pensjon-etterlatte-saksbehandling/tree/feature/tidshendelser-dok/apps/etterlatte-tidshendelser

Dok, diagram for tidshendelser-app

---

apps/etterlatte-tidshendelser/README.md
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/AldersovergangerService.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/Hendelse.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/JobbPoller.kt

Med den vanlige løypa fra BP-implementasjonene gjennom 
- vedtaksvurdering : for å sjekke løpende vedtak
- vilkårsvurdering (ikke aktuelt/NO-OP for OMS67)
- oppdatere behandling: opprette oppgave hvis løpende vedtak,
- manuelt opphør inntil videre.

EY-3526 Aldersovergang OMS ved 67 år

---

apps/etterlatte-behandling/src/main/kotlin/common/klienter/PesysKlient.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/Doedshendelse.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseDao.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunkt.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt

Starter på oppsett for å identifisere kontrollpunkter.

---

apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/aldersovergang/AldersovergangTest.kt

ble litt uklart når dødsdato i begge hendelsene var i samme måned

EY-3530 Korrigert testdata for å vise intensjon bedre

---

apps/etterlatte-behandling/src/main/kotlin/Contekst.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/GyldighetsproevingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/AutomatiskRevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/statistikk/StatistikkRoute.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/GyldighetsproevingServiceImplTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgaveGosys/GosysOppgaveServiceImplTest.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/Enheter.kt

nøp, nks og nfp har nasjonal tilgang som gir lestilgang, de har "nasjonal tilgang" som også betyr les, sjekker dette på enhet direkte.

Refactor/fjern filtrer for enhet for saksoversikt - lesetilgang nøp

---

gradle/libs.versions.toml

Trur ikkje den påverkar oss, men fint å ha det ute av verda
Sjå feks https://salsa.nav.cloud.nais.io/projects/8a2269c8-b3b7-4f2d-a9cd-5bd8e0d144c7/findings

Critical CVE i postgresql 42.7.1, så oppgraderer

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt

Skal rette https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-003044?id=qwXXxo0Bgsc8t73Qktf2

Sjekk at listen med utvandring ikke er tom

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunkt.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt

Opprett kontrollpunkt ved samtidig dødsfall og manglende annen forelder

---

apps/etterlatte-saksbehandling-ui/client/src/shared/api/github.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/header/HeaderBanner.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/header/ReleaseAlerts.tsx
apps/etterlatte-saksbehandling-ui/server/src/index.ts
apps/etterlatte-saksbehandling-ui/server/src/routers/githubRouter.ts

EY-3524 Vise utgivelser til saksbehandler

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/utils/oppgaveutils.ts

* Er allerede oppdatert OK mot backend

Kun sette frist om man finner oppgaven i lista

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt

Denne løysinga er ikkje heilt fin, men ho funkar, så eg fiksar heller problemet no og grublar på ei betre løysing etter kvart

Enkel løysing for å få rett brevkode for varselbrev ved hent nytt innhold

---

apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/BehandlinghendelseRiver.kt

Ref https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-003046?id=DKwp1o0Bgsc8t73Qf68Z

Logginga av feil her kræsjar no fordi behandling.id ikkje er deklarert

---

apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseRiver.kt
apps/etterlatte-oppdater-behandling/src/test/kotlin/TidshendelseRiverTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx

https://nav-it.slack.com/archives/C01PG1JM9D4/p1708690955391219

EY-3355 Endret til oppgavetype revurdering

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/SettPaaVent.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/frist/FristHandlinger.tsx

- Dra "sett på vent" i eget komponent. 
- Justering av design
- Høyrestille knapper i "sett frist"-modalen
**Sett på vent**
**Endre frist og sett merknad**
**Sett frist (høyrestilte knapper)**
**Oppgave satt på vent med merknad**
**Fjerne ventetilstand**

Pynte litt på designet til 'sett på vent'

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseDao.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseDaoTest.kt

OppgaveId må persisteres i databasen ved ferdigstilling av oppgave

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.test.ts
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.ts
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidVisning.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/Tags.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveFiltrering/oppgavelistafiltre.ts
apps/etterlatte-saksbehandling-ui/client/src/components/person/behandlingsslistemappere.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/Tags.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/formattering.ts
libs/etterlatte-oppgave-model/src/main/kotlin/oppgave/OppgaveIntern.kt

- Fjernet siste rest av behandlingstypen i frontend
- Fjernet alt tilknyttet oppgave
Har _ikke_ fjernet manuelt opphør `Aarsak` (på behandling) siden jeg er litt usikker på hva denne brukes til. 
Databasen er også tømt for oppgaver tilknyttet `MANUELT_OPPHOER`

EY-3550 Fjerne mer tilknyttet manuelt opphør

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/GrunnlagForVirkningstidspunkt.tsx

Ledetekst ikke avklart ennå, se kommentarer i EY-3478

EY-3571 Vise fødselsdato/dato for 67 år i grunnlag for virkningstidspunkt ved aldersovergang

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaver/Oppgaver.tsx

https://react.dev/errors/310?invariant=310

Fiks render minified 310

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/underkjent.tsx

Ref: https://jira.adeo.no/browse/FAGSYSTEM-320239

Mulig å sette på vent for returnerte oppgaver

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/EndreEnhet.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/SakOversikt.tsx

`Warning: validateDOMNesting(...): <dialog> cannot appear as a descendant of <p>.`

Fikse error i domvalidering

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseDao.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/OppdaterDoedshendelseBrevDistribuert.kt

Oppdater status for begge brev og bruk brevkode konstanter

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/ToggleMinOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveFiltrering/FilterRad.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveFiltrering/oppgavelistafiltre.ts
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaver/Oppgaver.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaverTable/OppgaverTable.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaverTable/OppgaverTableHeader.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaverTable/OppgaverTableRow.tsx

- Søkefelt for sakid
- Vise sakid i egen kolonne
- Lite delay før det legges i filteret for å redusere lasten

EY-3596 Vise sakid i oppgavelisten + filter

---

apps/etterlatte-tidshendelser/README.md

EY-3532 Oppdatert dok om opphør OMS n år etter dødsfall

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveFiltrering/FilterRad.tsx

Legge til et lite delay på søk for å ikke re-rendre ved hvert eneste tastetrykk

Legge til kort delay på fnr søk

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnOverstyrBeregningService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt
apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnOverstyrServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt

FAGSYSTEM-320305 - tillatt revurdering av overstyrt beregning

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobServiceTest.kt

..., slik at vi kan kjøre i produksjon og samle inn data.
EY-3603

Feature toggle opprettelse av oppgave og utsending av brev

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BrevApiKlient.kt
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/ForhaandsvisningBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurderingFelles.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/klage.ts
apps/etterlatte-saksbehandling-ui/server/src/index.ts
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt

Limer sammen det resterende på stadfesting av vedtak, med opprettelse og ferdigstilling av et tilpasset brev til klager, og journalføring / forhåndsvisning av notat til KA i saken.

EY-3559: Opprettelse av oversendelsesbrev KA og journalføring / forhåndsvisning av blankett til KA

---

apps/etterlatte-tidshendelser/src/main/resources/db/migration/V2__ferdigstille_jobb.sql
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiverTest.kt

Vet ikke om det har vært diskutert noe her i prosjektet vedrørende bruk av triggers/functions vs kode? For meg fremstår caset her som veldig rett-frem for slikt.

Ferdigstiller jobb når alle tilhørende hendelser er ferdige

---

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/oppdrag/OppdragJaxb.kt
apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/iverksetting/oppdrag/OppdragJaxbTest.kt

Feilet på parsing av testen som ble lagt til i dev

Fikser case sensitive kvitteringsmapping

---

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobServiceTest.kt

Vent 5 dager på sende brev om dødshendelser i produksjon

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/SamordningSak.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/vedtak/typer.tsx
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/Samordningsdata.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt

EY-3314 Lenke fra vedtak i samordningsoversikt til behandling

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunkt.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt

…, slik at den blir avbrutt
https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-003053?id=-YLaDo4BxiYEs1IqW1dg

Må opprett kontrollpunkt for avdød dersom det ikke finnes saker

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml

Legg til accesspolicy for krr i behandliing

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/NotatService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/Journalpost.kt

Det er mulig vi trenger noe annet for å ferdigstille senere

Fikk feil i setting av behandlingstema journalføring

---

apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseRiver.kt
apps/etterlatte-oppdater-behandling/src/test/kotlin/TidshendelseRiverTest.kt

Etter diskusjon med Mari og Helge om kjøretidspunkt for hendelser, hvor mye tid saksbehandlere trenger og siste frist opp mot Oppdrag. Ble bestemt å endre fra 20. til siste i måneden.

EY-3355 Endret frist til siste dag i måneden

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/SettPaaVent.tsx

større inputfelt for 'sett på vent'

textarea på SettPaaVent.tsx

---

apps/etterlatte-vedtaksvurdering/.nais/dev.yaml

Har vært satt til Q1 pga test med eksterne samhandlere men det stadiet er forbi nå. Får heller skru temporært til Q1 om behovet skulle gjenoppstå.

Skrur dev over/tilbake til å benytte SAM i Q2

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/GosysOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/OppgaveFeilWrapper.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/FilterRad.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/filtrerOppgaver.ts
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/velgOppgaveliste/VelgOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/velgOppgaveliste/oppgavelisteValg.ts

Visning av Gosys-oppgavene i egen fane:
Og ved kun innloget sb's Gosys-oppgaver:

EY 3642 splitt ut gosys oppgaver i egen fane

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/GosysOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts

EY-3652 Støtte ferdigstilling av gosys-oppgave

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/migrering/TaAvVentRiver.kt
libs/etterlatte-oppgave-model/src/main/kotlin/oppgave/VentefristGaarUtRequest.kt

Løyser https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-prod-006973?id=BcgAHI4BaSd17irJ8vfs

Implementasjonen av ta av vent var litt for tett knytta til gjenoppretting-varianten

---

apps/etterlatte-trygdetid/.nais/prod.yaml

Vil ikke ha alt for lang timeout generelt - nå at den migrering med lang kjøretid er ferdig

Reset timeout - long migration is now applied

---

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveRoute.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/BehandlingIntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/gosys/FerdigstillGosysOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/gosys/OverfoerOppgaveTilGjenny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/GosysOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/alerts/ResultAlert.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts
apps/etterlatte-saksbehandling-ui/docker-compose.yml

Gjelder i første omgang kun flytting av journalføringsoppgave, men tanken er å støtte overføring av alle oppgaver på sikt. 
Er en del ting som må fikses før vi kan støtte det, så dette får fungere enn så lenge.

EY-3662 Støtte flytting av journalføringsoppgave fra Gosys

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt

Vi ønsker å teste hendelsene på barnepensjon først, som er klar for å rulles ut.

Egen feature-toggle på EPS

---

apps/etterlatte-saksbehandling-ui/client/index.html
apps/etterlatte-saksbehandling-ui/client/public/index.html
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/Behandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/generellbehandling/GenerellBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/Klagebehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/Oppgavebenk.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/BehandleJournalfoeringOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/Tilbakekrevingsbehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/hooks/useSidetittel.tsx

Gir litt bedre indikasjon på hva som ligger i fanene man har oppe.

Vise forskjellig sidetittel avhengig av hvor man er

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt

Hvis ikke forsøker vi å opprette sak: https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-test-003060?id=pxHVPI4BkGvVqUX9Vemt

Det må være et kontrollpunkt hvis det ikke finnes iverksatte behandlinger

---

apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagHenter.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/SamsvarPersongalleri.tsx
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/grunnlag/Opplysningsbehov.kt

Visningen ligger bak en toggle!

Visning av mismatch persongalleri

---

apps/etterlatte-behandling/src/main/kotlin/behandling/vedtaksbehandling/FiksVedtaktstilstandDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/vedtaksbehandling/VedtaksbehandlingRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/vedtaksbehandling/VedtaksbehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/Application.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/FiksVedtakstilstand.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakFiksBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/config/ApplicationContext.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/BehandlingKlient.kt
apps/etterlatte-vedtaksvurdering/src/main/resources/application.conf
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/BehandlingMedStatus.kt
libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt

Skjult bak funksjonsbrytar, så ingenting skjer før vi skrur den på.

Hentar ut behandlingar der vedtaksstatusen kan ha vorte feil, og rettar opp

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunkt.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt

se https://navno.sharepoint.com/sites/fag-og-ytelser-pesys/SitePages/D%C3%B8dsmeldinger.aspx

EY-3686 Oppgavetekst som beskrevet på sharepoint

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt

Har vært en del feil på linje 116 i `TrygdetidService`: 
`opprettTrygdetiderForBehandling(behandlingId, brukerTokenInfo).minBy { it.ident }`
Ser ikke helt hvorfor trygdetid mangler i dette tilfellet. Legger derfor til mer logging for vår del, og feilmeldinger til sb. 
- Døpe om `tilstandssjekk` til `kanOppdatereTrygdetid` siden det er litt mer beskrivende for hva den gjør. 
- Mer logging
- Kaste feil i tilfeller hvor det ikke har blitt opprettet trygdetid eller essensiell data mangler.

Litt mer logging og feilhåndtering på oppretting av trygdetid

---

apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/SaksbehandlerJobService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/AxsysKlient.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/NavAnsattKlient.kt
apps/etterlatte-behandling/src/main/kotlin/common/klienter/SkjermingKlient.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/klienter/NavAnsattKlientTest.kt
apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt
libs/etterlatte-ktor/src/main/kotlin/Ping.kt

Gir mindre spam i loggene om eksterne tjenester er nede

Pinge før vi kaller, kall kun ved serviceup

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt

Fiksar https://logs.adeo.no/app/discover#/?_g=(time:(from:now-24h%2Fh,to:now))&_a=(query:(language:lucene,query:'x_correlation_id:e8f94f00-c162-46d1-9dcd-c9b9d8bd17fe'))

For frist går ut-uthentinga, sjekk at status på oppgåva faktisk er på vent

---

apps/etterlatte-vilkaarsvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/TidshendelseRiver.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/AldersovergangService.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingService.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/AldersovergangServiceTest.kt

_Kopier_-kallet burde kanskje ikke ta med seg resultatet?

EY-3631 Fjerne resultat på kopiert vv før oppdatering

---

libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt

Utløysande grunn til denne er at eg jobbar med regulering i manuelt overstyrt, så da kom eg over denne.

Opnar for at saksbehandlar kan lukke oppgåve som er tileigna systemet.

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/SamsvarPersongalleri.tsx

Justeringer visning av avvik i persongalleri for OMS

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/FristGaarUtJobb.kt

Så legg på litt meir før vi køyrer i prod

Var litt lite logging for automatisk avskriv frist-jobben

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx

Rettar desse to: https://github.com/navikt/pensjon-etterlatte-saksbehandling/security/code-scanning

Codeql beregningsgrunnlag

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/Application.kt
libs/etterlatte-ktor/src/main/kotlin/HttpClient.kt
libs/etterlatte-ktor/src/main/kotlin/initialisering/EmbeddedServerConfig.kt
libs/etterlatte-ktor/src/main/kotlin/ktor/EmbeddedServerConfiguration.kt

fyi: prøver å løse https://nav-it.slack.com/archives/C043C5ZGW5T/p1710494023327609

Sett timeout for embedded servere og fjern shutdownhook på httpclients

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml

Tror dere var litt ivrig på slettingen her, `brev-api` må kunne slå opp mot behandling.

Legger til manglende tilgang for brev-api

---

apps/etterlatte-behandling/src/main/kotlin/behandling/tilgang/TilgangRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt

Prøver å løse concurrent serializble https://logs.adeo.no/app/r?l=DISCOVER_SINGLE_DOC_LOCATOR&v=8.12.2&lz=N4IglgdgJgpgHiAXCAnANhmgLADgMYAMAtCjgQIZECMVMKROAzBUTFQOwBGnU2nWUTiAA0IAE4B7AO4BJaPCQgANhIDmAZwAu5dQAsi5AA6H1RQ5KhECBNOkYjx0mVEUAFMJzgBhAJpYAQgScAK4AYqEo%2FowAagD6AHIAEg5iMABmMGKpYooA9EaGuVBg6ngSAG6ZAMS5APyxqgC8ABRpYEqameqIAITNAJTCmmAAtjCIrZIjiADkAEwEc1hWjFZYACpUBIhYc4gArGgAdATsVABaM0MSswtLK1Y463NUiIxYiKdHWCj7l%2F39ABksXILTKSmCIwg3T6ShglSUwjG6nU5FUMGEMAg5TwSh06mEBSUYDw5GGEggwi05DwAGtYpoxDSYIM2h0ur1ms0ZgASamdGYTLQSVKIAoAZW0nUGY20E3IxJ0vUpxVRnDhUF6aWEbRgSk1EHIyMMzOEkFgcFmXH2MDIeHY1Ht9AEBH2DAIOEscxwOHYWH2cxQNKwaSutJgAE9EIbjaaIDBVGTxj1tSamSNus0AI7BTJRmCaTpiPGFllDCOGcaGXRM9RlnN5iYjMl4XSxau18bNGMwdQmvDjAtFkvSgHCbl8qUwQXNYWiiVTmUF8jyxUwlUlcjqmCalM6sB6zVYnF4lFm%2BSWmbW20Ee2O9jOqCu92eoje33%2BwP …

Fjern intransaction for tilgangtilperson som håndterer ds selv

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidVisning.tsx

Venter tekst sjekk/endring fra fag

Hotfix - ikke opprett trygdetid hvis fattet og avslag og tt mangler

---

apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts

Hente ut innhold fra respons kun én gang

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseServiceTest.kt

gyldigFraOgMed har bedre kvalitet enn gyldigTilOgMed ref https://pdldocs-navno.msappproxy.net/ekstern/index.html

EY-3726 Avdøed sjekk siste gyldige bostedsadresse

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/DelvilkaarRepository.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRepository.kt

Ref https://nav-it.slack.com/archives/C01PG1JM9D4/p1710933382787489

Hente alle delvilkår sammen med vilkår for å unngå et skred av db-kall

---

apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/Application.kt
apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/rivers/TidshendelseRiver.kt
apps/etterlatte-vedtaksvurdering-kafka/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/rivers/TidshendelseRiverTest.kt

ref 
- https://github.com/navikt/pensjon-etterlatte-saksbehandling/blob/main/apps/etterlatte-vilkaarsvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/TidshendelseRiver.kt
- https://github.com/navikt/pensjon-etterlatte-saksbehandling/blob/main/apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseRiver.kt
Synes det er bedre mtp å kjapt søke opp i IntelliJ

Døpt om tidshendelser-relatert river mtp konsistens med de andre

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/PersonFnrMedRelasjon.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseServiceTest.kt

Se på relevante sivilstatuser og unngå duplikate personer som treffer flere statuser

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseServiceTest.kt

Det ville bare ført til dobbelt opp med hendelser
EY-3727

Ingen grunn til å legge til samboere dersom de var gift med avdød.

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/Application.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt
libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt

Trur det skal halde å sende ut meldingane på nytt no når tilstanden er som forventa i både vedtak og behandling.

Send ut meldingar på nytt for dei som sist veke berre var attestert og ikkje vart iverksatt eller breva journalført

---

apps/etterlatte-behandling/src/main/kotlin/behandling/doedshendelse/DoedshendelseReminderService.kt

https://logs.adeo.no/app/discover#/?_g=(time:(from:now-24h%2Fh,to:now))&_a=(columns:!(level,message,envclass,application,pod),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96e648c0-980a-11e9-830a-e17bbd64b4db',key:application,negate:!f,params:(query:etterlatte-behandling),type:phrase),query:(match_phrase:(application:etterlatte-behandling))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96e648c0-980a-11e9-830a-e17bbd64b4db',key:level,negate:!f,params:(query:Error),type:phrase),query:(match_phrase:(level:Error)))),hideChart:!f,index:'96e648c0-980a-11e9-830a-e17bbd64b4db',interval:auto,query:(language:lucene,query:''),sort:!(!('@timestamp',desc)))

Legg tilintransaction for dødshendelserreminderservicejob

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/attesterTilbakekreving.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oppsummering/TilbakekrevingVurderingOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/sidemeny/TilbakekrevingSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/stegmeny/TilbakekrevingStegmeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingSkjema.tsx

- Endrer oppsummeringstabell
- Nullstiller verdier som ikke lenger vises i skjema basert på valg
Kommer til å jobbe med validering og bruk av react-form i neste PR

EY-3653: Justerer tilbakekrevingsflyt etter testing

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/OverstyrBeregningGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/OverstyrBeregningPeriode.tsx

- Validrere trygdetid tilhører fnr
- Riktig default på fom første periode

Smaafikser overstyrt beregning form

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx

Avkorting må korrigere inntekt etter ny virk

---

apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/brevbaker/BlockTilSlateKonvertererTest.kt
libs/etterlatte-database/src/main/kotlin/DataSourceBuilder.kt
settings.gradle.kts

Pga at https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/4348 feilet.
- https://github.com/JetBrains/kotlin/releases/tag/v1.9.23
- https://youtrack.jetbrains.com/issue/KT-66044
- https://youtrack.jetbrains.com/issue/KTIJ-29200/Highlighting-False-negative-unresolved-reference-for-addLast-or-addFirst-on-immutable-list

Bump kotlin-jvm from 1.9.22 to 1.9.23, revised

---

apps/etterlatte-samordning-vedtak/README.md
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakService.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/Tjenestepensjon.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/TjenestepensjonKlient.kt
apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakServiceTest.kt
apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/TjenestepensjonKlientTest.kt

EY-3745 Alltid kreve at det foreligger tjenestepensjonsytelse ved oppslag fra TP-leverandører

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidVisning.tsx

Det er oppdaterStatusRequest og ikke oppdaterBehandlingsstatus som kaster feil her.
Testing tidligere fungerte pga "forhåndsutfyllt fremtidig" - som jeg ikke tenkt over.

FAGSYSTEM-324425 - sjekk for avslag rundt riktig blokk

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/OpprettSakModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/SakOversikt.tsx

Superenkel løsning for å la sb opprette sak ved behov. Eksempelvis nødvendig ved flytting av journalpost fra Pesys.

FAGSYSTEM-324549 La sb opprette sak hvis ingen finnes

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/HaandterAvvikModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/KnyttTilAnnenSak.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/OpprettJournalfoeringsoppgave.tsx

EY-3755 Støtte manuell oppretting av jfr-oppgave

---

clone-dev-db.sh
libs/etterlatte-database/src/main/kotlin/DataSourceBuilder.kt

Lager en "eksakt" kopi av databasen i dev og setter den opp lokalt. Eneste som fjernes er priv/acl.
Dumper tabeller og innhold, for så å gjenopprette lokalt. Man trenger derfor ikke lenger kjøre flyway lokalt først for at alt skal fungere.

Forbedre db script

---

.github/workflows/.build-job.yaml
.github/workflows/.build.yaml
.github/workflows/.lib-test.yaml
.github/workflows/.test-job.yaml
.github/workflows/.test.yaml

Som kjapt diskutert på utviklersync. Ser på å få gjort noen bygg for å vurdere effekten før denne eventuelt merges.
https://github.com/gradle/gradle-build-action?tab=readme-ov-file

Benytte setup-gradle action, med versjon angitt av wrapper med sikte på raskere bygg

---

apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/LoggingPlugins.kt

fra koden:
> For å kunne gruppere i relevant verktøy uten unike identifikatorer, og med path params sine faktiske navn i koden.
>  - "/api/vedtak/123" -> "/api/vedtak/{vedtakId}"
>  - "/api/vedtak?fomdato=2024-01-01&noe=annet" -> "/api/vedtak?fomdato,noe"

Logge forespurt url-metdata med faktisk(e) parameternavn fra route

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/LukkHendelseModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/UhaandtertHendelse.tsx

EY-3750 Opprydding + varsel til sb hvis oppgave er tildelt

---

apps/etterlatte-saksbehandling-ui/client/src/shared/header/ReleaseAlerts.tsx

Gjøre utgivelse dropdown litt bredere

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/JournalfoerBrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiver.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt

Betre å samle dei opp og så handtere desse spesifikt etterpå

Spesialhandtering for brev som feilar for gjenoppretting. 

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt

Tanker for eller imot? 
Vil hvert fall løse en del smårusk og unødvendige "feil" for saksbehandlere.

Hvis status er NY og ikke tildelt, kan oppgave tildeles automatisk

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-behandling/.run/etterlatte-behandling.dev-gcp.run.xml
apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/AxsysKlient.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/KlageKlient.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/MigreringKlient.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/TilbakekrevingKlient.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/selftest/SelfTestReport.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/selftest/SelfTestRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/selftest/SelfTestService.kt
apps/etterlatte-behandling/src/main/kotlin/common/klienter/PdlTjenesterKlient.kt
apps/etterlatte-behandling/src/main/kotlin/common/klienter/SkjermingKlient.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/klienter/GrunnlagKlient.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/klienter/GrunnlagKlientOboTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/klienter/NavAnsattKlientTest.kt
apps/etterlatte-klage/.nais/dev.yaml
apps/etterlatte-tilbakekreving/.nais/dev.yaml
libs/etterlatte-ktor/src/main/kotlin/Ping.kt
libs/etterlatte-ktor/src/main/kotlin/RestModule.kt
libs/etterlatte-ktor/src/main/kotlin/initialisering/EmbeddedServerConfig.kt

fremtidige forbedringer
1. bruke https://kotlinlang.org/docs/typesafe-html-dsl.html
2. flytte deler av funksjonaliteten til libs bibl

EY-3430 Selftest poc

---

apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakService.kt

uteglemt da vi gikk fra å alltid kreve ytelse, ikke bare forhold (#4363)

Korrigert feilmelding ved sjekk av TP-ytelse

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseUtil.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunkt.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt

Det skal opprettes oppgave dersom den gjenlevende (barn, eps) ikke har aktiv adresse

---

apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/utbetalinger/TilbakekrevingVurderingPerioderSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/components/datoVelger/ControlledDatoVelger.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/components/radioGruppe/ControlledRadioGruppe.tsx

Ikke helt landet hvordan selve valideringen vil gjøres, men antageligvis blir det i backend siden alle felter er optional slik at saksbehandlerene kan mellomlagre.

EY-3638: Legger på react-hook-form i tilbakekrevingsflyt

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt

Rettelse for feilene i produksjon. Må muligens ta en ny titt på det funksjonelle

Ikke kast feil hvis adresse mangler

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/config/ApplicationContext.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/TrygdetidKlient.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingServiceTest.kt

Bruk bare den evt. første treff.
Dette er samme som beregning også gjør pt.
Ekte støtte for vedtaksvurdering av flere trygdetider kommer i EY-3794

EY-3789 - bruk ny trygdetid endepunkt

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/uhaandtereHendelser/LukkHendelseModal.tsx

https://github.com/navikt/pensjon-etterlatte-saksbehandling/security/code-scanning/117

This negation always evaluates to true.

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottakerModal.tsx

Burde forbedres ytterligere med henting av landkode fra norg2 e.l.

Sikre at felter på mottaker har gyldig format

---

apps/etterlatte-beregning/src/main/kotlin/Application.kt
apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonRepository.kt
apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonService.kt
apps/etterlatte-beregning/src/main/resources/db/migration/V36__create-sanksjon.sql
apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt
apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonRepositoryTest.kt
apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonServiceTest.kt

Første del, frontend vil bli lagt til i egen PR

EY-3774: Sett opp tabell for sanksjoner

---

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingFeilmeldinger.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingValidering.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingDaoTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/brev/TilbakekrevingBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oppsummering/TilbakekrevingOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oppsummering/TilbakekrevingVurderingOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/stegmeny/TilbakekrevingStegmeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/tilbakekreving.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/components/datoVelger/ControlledDatoVelger.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/components/radioGruppe/ControlledRadioGruppe.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Tilbakekreving.ts
libs/etterlatte-tilbakekreving-model/src/main/kotlin/Tilbakekreving.kt
libs/etterlatte-tilbakekreving-model/src/main/kotlin/TilbakekrevingBehandling.kt

Legger på et kall for å validere at vurdering og perioder er riktig fylt ut før saksbehandler kan generere brev og fatte vedtak

EY-3638: Validerer vurdering og perioder i tilbakekreving

---

apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oppsummering/TilbakekrevingOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/sidemeny/TilbakekrevingSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/tilbakekreving.ts

Fikser følgende:
- Feil ved uthenting av oppgave når man går inn fra saksoversikt
- Bruker feil method mot /valider endepunktet etter at dette ble endret i backend

Fix bugs tilbakekreving

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/underkjent.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/SettPaaVent.tsx

Flytte sjekken på oppgavetilstand til `SettPaaVent`-komponenten.

hotfix: Sjekke om oppgave kan redigeres før SettPaaVent vises

---

apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oppsummering/TilbakekrevingOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oppsummering/TilbakekrevingVurderingOppsummering.tsx

Bruker to komponenter siden det er to ulike sider, og blir litt kaotisk hvis alt skal legges i en stor liste.

EY-3812: Bruker ErrorSummary for å vise valideringsfeil i tilbakekreving

---

apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingDao.kt

https://logs.adeo.no/app/discover#/doc/54ddb3d2-7257-4a8e-9231-34973a5b16c6/logstash-apps-prod-007055?id=w-sVzY4BZi3RtCTjG6AR

Hotfix: GenerellBehandling innhold er nullable

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/Revurderingsoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/utils.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Revurderingaarsak.ts
libs/saksbehandling-common/src/main/kotlin/behandling/Revurderingaarsak.kt

La det som "KunIDev" foreløpig.

EY-3716 - legg til revurderingsårsak for foreldreløs

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-beregning/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-fordeler/.nais/dev.yaml
apps/etterlatte-grunnlag/.nais/dev.yaml
apps/etterlatte-gyldig-soeknad/.nais/dev.yaml
apps/etterlatte-institusjonsopphold/.nais/dev.yaml
apps/etterlatte-klage/.nais/dev.yaml
apps/etterlatte-migrering/.nais/dev.yaml
apps/etterlatte-oppdater-behandling/.nais/dev.yaml
apps/etterlatte-opplysninger-fra-soeknad/.nais/dev.yaml
apps/etterlatte-pdltjenester/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-statistikk/.nais/dev.yaml
apps/etterlatte-testdata/.nais/dev.yaml
apps/etterlatte-tidshendelser/.nais/dev.yaml
apps/etterlatte-tilbakekreving/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-utbetaling/.nais/dev.yaml
apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml

https://docs.nais.io/security/auth/azure-ad/usage/#token-generator

La alle apper støtte azure-token-generator

---

.github/workflows/app-etterlatte-vedtaksvurdering.yaml
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V110__legg_til_sende_brev_i_tilbakekreving.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/klage/VedtaksbehandlingRoutesIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingRoutesIntegrationTest.kt
apps/etterlatte-vedtaksvurdering/build.gradle.kts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakTilbakekrevingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/config/ApplicationContext.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/BehandlingKlient.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakTilbakekrevingServiceTest.kt
libs/etterlatte-tilbakekreving-model/src/main/kotlin/TilbakekrevingBehandling.kt

Vedtaksbrev er ikke påkrevet dersom beløpet som tilbakekreves er under 4 rettsgebyr. Vi må likevel behandle kravgrunnlaget. Saksbehandler trenger derfor et valg hvor det er mulig å ikke sende brev. Endringene i frontend kommer i egen PR.

EY-3804: Legger på parameter "sendeBrev" for å velge om TK skal sende vedtaksbrev

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonBeregning.kt

Sjekka i trygdetidstabellen at det berre fins eitt innslag per behandling for desse.

Workaround for å få gjennom brev i spesifikke gjenopprettingssaker

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerKlient.kt

Som forrige PR, men no også med install av pluginen, sånn at det faktisk funkar. Testa OK i dev.

Brevbaker timeout take2

---

gradle/libs.versions.toml

Spesifikt for å få oppgradert kafka-clients, men også fint generelt.

Nyare versjon av rapids and rivers med oppdaterte avhengnadar

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktEktefelleService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktEktefelleServiceTest.kt

Forsøker også å forenkle lesbarheten av logikken her.

Støtt at vi for mange personer mangler informasjon om sivilstandsstatus GIFT.

---

apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/Tilbakekrevingsbehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oppsummering/TilbakekrevingOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oppsummering/TilbakekrevingSkalSendeBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oppsummering/TilbakekrevingVurderingOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/stegmeny/TilbakekrevingStegmeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/tilbakekreving.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Tilbakekreving.ts

Saksbehandler kan velge og ikke sende brev dersom en tilbakekreving feks er under 4 rettsgebyr og ikke skal kreves tilbake fra bruker.

EY-3804: Saksbehandler kan velge om vedtaksbrev skal sendes for tilbakekreving

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-beregning/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-grunnlag/.nais/dev.yaml
apps/etterlatte-migrering/.nais/dev.yaml
apps/etterlatte-pdltjenester/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/azuread-etterlatte-saksbehandling-ui-lokal.yaml
apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml

Første del av EY-3684 - Legger kun inn ny saksbehandlerrolle i dev for verifisering

Legge til Gjenny-saksbehandler i tenant for dev

---

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveRoute.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/oppgaveGosys/GosysOppgaveServiceImplTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/gosys/OverfoerOppgaveTilGjenny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/OppgaveFraJournalpostModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/gosys.ts

Forenkler koden i frontend en hel del og gir oss mer trygghet mtp. tester og sporbarhet.

Flytte kode for oppgaveflytting til backend

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/ferdigstilloppgave/FerdigstillOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/ferdigstilloppgave/FerdigstillOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/FullfoerOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/OpprettNyBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/OppsummeringOppgavebehandling.tsx

Lar sb selv ta stilling til om de vil gå tilbake til oppgavelisten eller sakoversikten til personen tilknyttet oppgaven de nettopp fullførte.

Gi saksbehandler valg ved ferdigstilt oppgave

---

apps/etterlatte-beregning/.run/etterlatte-beregning.dev-gcp.run.xml
apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonRepository.kt
apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonService.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonRepositoryTest.kt
apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sanksjon/Sanksjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/sanksjon.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/components/maanedVelger/ControlledMaanedVelger.tsx

Hovedsakelig fokus på funksjonalitet, så blir det å jobbe med brukeropplevelsen med fag og design når ting er mer klart.

EY-3775: La saksbehandler slette og endre en sanksjon

---

.github/workflows/app-etterlatte-saksbehandling-ui.yaml
README.md
apps/etterlatte-saksbehandling-ui/client/package.json
apps/etterlatte-saksbehandling-ui/package.json
apps/etterlatte-saksbehandling-ui/server/package.json

Ganske greitt å få denne til å køyre automatisk, så da kan vi jo like godt det

Automatiserer lisenssjekken i frontend

---

apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/BeregningService.kt
apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/OmregningHendelserRiver.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/OmregningHendelserRiverTest.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/OmregningsHendelserTest.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/RegulerOverstyrt.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/overstyr/BeregnOverstyr.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/regler/overstyr/RegulerOverstyrt.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/RegulerOverstyrtKtTest.kt
libs/etterlatte-beregning-model/src/main/kotlin/OverstyrBeregningsGrunnlag.kt

Inneholder:
- Ny regelkode for å G-regulere overstyrt beregning
- Endepunkt for å utføre reguleringa av overstyrt
- Reguleringsflyt kaller nytt endepunkt

Regel for regulering av overstyrt beregnet beløp

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
libs/etterlatte-oppgave-model/src/main/kotlin/oppgave/OppgaveIntern.kt

Når en oppgave attesteres skal den tildeles saksbehandleren som sendte den til attestering.

EY-3614 Tildel attestert oppgave tilbake til saksbehandler

---

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveRoute.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt
apps/etterlatte-behandling/src/test/kotlin/oppgaveGosys/GosysOppgaveServiceImplTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/GosysOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/typer.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/api/gosys.ts

Lagt til toggle group for å kunne se gosys oppgaver som ikke er tildelt en SB:

EY-3850 filter for ikke tildelte gosys oppgaver

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx

De ønsket egentlig scrollbar, men det er litt mer mikk. Legger til resize i stedet som en kjapp fiks

Resize på begrunnelse avkorting av inntekt

---

apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt
libs/etterlatte-ktor/src/main/kotlin/route/RouteUtils.kt

Synes det er vanskeleg å finne ut akkurat kor i koden det stoppar særleg når vi får 401 forbidden, så legg på debuglogging for å kunne sjå det i loggane

Loggar tilgangssjekking

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Gradering.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/BehandlingsBehov.kt
libs/saksbehandling-common/src/main/kotlin/behandling/Persongalleri.kt

Fjerner også gradering ved manuell behandling i frontend

Valider persongalleri ved opprettelse av ny behandling

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/RedigerFamilieforhold.tsx

Kan være ukjent avdød eller manglende fnr/dnr

Fjerner validering på minst en avdød ved redigering av familieforhold

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktTidslinje.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/NyAktivitet.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/aktivitetsplikt.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Aktivitetsplikt.ts

[EY-3820](https://jira.adeo.no/browse/EY-3820)
Første utkast, bak feature toggle.

Frontend-støtte for å vise og legge til aktiviteter for aktivitetsplikt

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutesDtoer.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/VirkningstidspunktRequest.kt

Samt legg på retry-mekanisme for å parse YearMonth

Tilgjengeleggjer virkningstidspunktrequest i bibliotek for å kunne bruke frå testdata-generering

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt

[EY-3864](https://jira.adeo.no/browse/EY-3864)

Støtte for å slette og endre eksisterende aktiviteter

---

libs/etterlatte-ktor/src/main/kotlin/Ping.kt

Skal være slik https://etterlatte-saksbehandling.intern.nav.no/internal/selftest
ikke https://etterlatte-saksbehandling.intern.nav.no/internal/selftest/behandling

Skal returnere 0 eller 1 ikke up eller down tilbake i resultatet

---

apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml

Gjelder at UI skal kalle ny simuleringstjeneste i `utbetaling`

EY-3389 Outbound ui -> utbetaling

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt

Fix for feil meldt i EY-3871. Saksbehandler ble kun fjernet fra oppgaver som var under behandling

Fjerning av SB for oppgaver med status attestering og på vent ved endring av enhet

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelse.kt

Brukes ifm denne https://github.com/navikt/pensjonsbrev/pull/725

EY-3748: Nytt felt harUtbetaling for barnepensjon innvilgelse utfall

---

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/UtbetalingRoutes.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/simulering/Simulering.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/simulering/SimuleringOsService.kt
apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/simulering/SimuleringOsRouteTest.kt

Fortrinnsvis mer UI-vennlig. Noe basert på hva andre systemer mapper opp. GUI er påbegynt men kommer i separat PR.

EY-3389 Mappe simuleringsresultatet til lokal og spisset type

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/AktivitetspliktInfoModal.tsx

EY-3876: Vis modal for oppfølging av aktivitetsplikt

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/DokumentlisteLiten.tsx

Pynte litt på grensesnittet

---

.github/workflows/app-etterlatte-brev-api.yaml
apps/etterlatte-brev-api/build.gradle.kts
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/tilbakekreving/TilbakekrevingTesthjelper.kt

Og det er det ikkje eigentleg nokon grunn til

Oppgraderer brevbaker-modellen, vi heng litt etter no

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakDao.kt

For å på den måten få ut våre nyoppretta saker til regulering under testing. Per no er denne koden kun til bruk i regulering, så det er ganske udramatisk, men eg tenkjer at denne uansett er heilt grei

Sorterer uthenting av saker etter sakid, nyaste først

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt

Endrer til å bruke metoden for erUnderbehandling, som også inkluderer underkjent

Retter fjerning til å gjelde alle oppgaver under behandling

---

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/oppdrag/OppdragMapper.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/utbetaling/UtbetalingService.kt
apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/TestHelper.kt
apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/iverksetting/oppdrag/OppdragJaxbTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/iverksetting/oppdrag/OppdragMapperTest.kt
apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/iverksetting/utbetaling/UtbetalingDaoIntegrationTest.kt

Baseres på
https://nav-it.slack.com/archives/C03793FA1EE/p1714727569457189

Tekst til lønnslipp g-regulering

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingServiceIntegrationTest.kt

Når en behandling revurderes, skal aktiviteter lagt til på forrige behandling kopieres med til den nye.
EY-3902

Kopier aktiviteter ved revurdering

---

apps/etterlatte-samordning-vedtak/README.md
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtak.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakService.kt

Tenker denne er grei uansett hva vi kommer frem til om å sende eller ikke sende samordningshendelser under reguleringskjøringene

EY-3798 Mappe revurderingsårsak regulering i API til eksterne

---

apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/PersonRoutes.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/VergeFeilhaandtering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottaker.tsx

hvis det ikke finnes vergeadresse for personen som har verge.

EY-3870: Henting av verges adresse gir 204 istedenfor 404

---

apps/etterlatte-saksbehandling-ui/client/src/shared/components/datoVelger/ControlledDatoVelger.tsx

ref https://jira.adeo.no/browse/EY-3487
og https://nav-it.slack.com/archives/C01PG1JM9D4/p1715174022500219

Ikke legg inn dato til datepicker før blur, skaper bare problemer

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/AktivitetspliktInfoModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/aktivitetsplikt.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Aktivitetsplikt.ts

EY-3877: Lagre vurdering og ferdigstill oppgave om oppfølging av aktivitetsplikt

---

apps/etterlatte-statistikk/src/main/kotlin/statistikk/jobs/RyddUtlandstilsnittJob.kt

Siden det gis exception og ikke null må vi try-catche hentingen fra behandling

Håndtere feil fra behandling i rydding

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDao.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V120__ny_tabell_aktivitetsplikt_unntak.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDaoTest.kt

Blir litt duplisering på tvers her, siden strukturene er ganske like. Det er en tanke om å slå sammen og rydde opp i modellen senere når vi får landet hvordan vi ønsker å modellere aktivitetsplikt totalt sett.

Støtte for unntak i en vurdering

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDao.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V121__ny_kolonne_fom_aktivitetsplikt_unntak.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDaoTest.kt

Trengs ikke p.t., men behovet vil dukke opp etterhvert.
EY-3922

Legg til fra og med dato for unntak.

---

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/oppdrag/OppdragSender.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/utbetaling/UtbetalingService.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/utbetaling/Utbetalingsvedtak.kt
libs/etterlatte-mq/src/main/kotlin/no/nav/etterlatte/mq/JmsConnectionFactory.kt
libs/etterlatte-mq/src/testFixtures/kotlin/etterlatte/DummyJmsConnectionFactory.kt

ref https://nav-it.slack.com/archives/CBF1W2DAB/p1715675681218169

EY-3824 Benytte lav prioritet på oppdragsmeldinger ved regulering

---

apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
apps/etterlatte-statistikk/src/main/resources/db/migration/V38__patch_tilbakekreving_resultat.sql
libs/etterlatte-tilbakekreving-model/src/main/kotlin/Tilbakekreving.kt

Samler resultatene fra periodene etter en prioritert rekkefølge

Mapper resultat fra tilbakekreving til statistikk

---

apps/etterlatte-tidshendelser/src/main/resources/db/migration/V5__Jobb_aktivitetsplikt_oppgave_4_mnd.sql

For sakene der dødsdato var i desember 2023.
EY-3926

Jobben oppretter oppgave for å vurdere aktivitetsplikt etter 4 måneder

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingsHendelserService.kt

Behandling skal sende tidspunkt for teknisk tid

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevParametre.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/AktivitetspliktBrevdata.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/AktivitetspliktInfoModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/BrevOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrevModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/alerts/Toast.tsx
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/EtterlatteBrevkode.kt

Valg i select
Valg av aktivitetsgrad og om bruker har utbetaling
Med feilmelding

EY-3925: Lag støtte for manuelt brev til informasjon om aktivitetsplikt ved 4 mnd

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakDao.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt

Flytte henting av sak av type til databasen og rydde litt koden.

Ey 3932 forenkling hent saker

---

apps/etterlatte-behandling/src/main/kotlin/behandling/doedshendelse/DoedshendelseReminderService.kt

https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/logstash-apps-prod-007147?id=TYjsmY8BnqYND5Vps9HG

Ikke send remainder før dødsmelding er skrudd på

---

apps/etterlatte-grunnlag/.nais/prod.yaml

Satt nais timeouts tilbake etter deploy av ny indeks

---

apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/SjekkOmOverstyrtBeregningRiver.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/SjekkOmOverstyrtBeregningRiverTest.kt
apps/etterlatte-beregning-kafka/src/test/resources/omregningshendelse_sjekk_overstyrt.json

Vi kan ikke bruke tilbakestilte_behandlinger fra melding fordi det er ikke alltid tilfelle

Bruker behandling_vi_omregner_fra istedenfor tilbakestilte_behandlinger

---

apps/etterlatte-brev-api/build.gradle.kts
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BlockTilSlateKonverterer.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/Brevbakerdeserialisering.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/brevbaker/BlockTilSlateKonvertererTest.kt

Bytter `RenderedLetterMarkdown` med `LetterMarkup`

Ny versjon av brevbaker api model

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/OpprettNyBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/OppsummeringOppgavebehandling.tsx

Gir også saksbehandler advarsel dersom de forsøker å opprette behandling hvor saktype er forskjellig fra journalposten sitt tema.

EY-3962 La saksbehandler sette sakstype selv

---

.github/workflows/codeql.yml
gradle.properties

Mange commits for ei linje kodeendring, men som Alberto Brandolini seier, systemutvikling er ein læringsprosess og fungerande programvare er ein bieffekt.

Meir minne til code scanning-analysen for å forhindre outofmemory-exception

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/AktivitetspliktInfoModal.tsx

Endre knapp type og tekst

---

apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/BeregningService.kt
apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/OmregningHendelserBeregningRiver.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/OmregningHendelserBeregningRiverTest.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/OmregningsHendelserTest.kt

Nytt beløp bør vera gamalt beløp gangar omregningsfaktoren. Køyrer det i første omgang som warning, litt usikker på korleis det er mtp avrunding etc, og om vi har nokre spesialhøve som skal vera unntak.

Verifiserer faktoromregning fortløpande under regulering

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/HendelseBeskrivelse.tsx

Lagt til kommentar under mer detaljert visning av hendelse:

FAGSYSTEM-331322 kommentar for hendelse mangler

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakDao.kt
jobs/start-regulering/src/main/kotlin/Application.kt

Dei første er sannsynlegvis enkle og løpande.

Snu sorteringa så vi regulerer eldste sak først

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt

Legger til manglende utlandstilsnitt avbrutt klage

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/AktivitetspliktInfoModal.tsx

Lar saksbehandler ferdigstille en sak som har unntak med sluttdato

Gjør sluttdato om til dato for toISOString

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonRevurdering.kt

se https://github.com/navikt/pensjonsbrev/pull/750 for endringer i pensjonsbrev

brukerUnder18Aar trengs for redigerbart utfall revurdering

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/AktivitetspliktInfoModal.tsx

En feil har skjedd slik at en saksbehandler har klart å lagre en vurdering, men ikke fått til ferdigstilling. Så hvis man nå åpner oppgaven så sjekker vi om den har status ferdigstilt hvis den har en vurdering. Hvis den ikke er ferdigstilt, så lar vi saksbehandler ferdigstille.

La saksbehandler ferdigstille oppgave som allerede har en vurdering

---

apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/prod.yaml

Brukes til å vise varsel til uføre-saksbehandlere

EY-3968 Tilgang for PEN til bp-api

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/SamordningSak.tsx

Mappe om boolean til ja/nei i refusjonskrav-kolonne

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx

Lukker denne: https://github.com/navikt/pensjon-etterlatte-saksbehandling/security/code-scanning/121

Fix code scanning #121: Fjerner overflødig ||

---

apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/prod.yaml
apps/etterlatte-brev-api/.run/etterlatte-brev-api.dev-gcp.run.xml

Må bruke pdfgen for å generere notater siden Brevbakeren tvinger alt i et "brevformat". 
Fortsettelse følger.

EY-3728 Legge til pdfgen på brev (wip)

---

apps/etterlatte-statistikk/src/main/resources/db/migration/V43__kolonne_for_oppdatering_anvendt_sats.sql

Egen PR så det er mulig å teste oppdateringen i dev uten å ødelegge for deploys på grunn av ny migrering

Legger til kolonne for tracking av oppdatering av sats

---

apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/joark/SafGraphql.kt
apps/etterlatte-hendelser-joark/src/main/kotlin/joarkhendelser/joark/SafKlient.kt

```
1 feil oppsto ved kall mot saf: {"message":"Variable 'journalpostId' has an invalid value: Expected a String input, but it was a 'Integer'","path":[],"extensions":{"code":null,"classification":"ValidationError"}}
```

Sende journalpostId som string

---

apps/etterlatte-behandling/src/main/resources/db/prod/V131__fikse_kravpakke_behandling_etter_regulering.sql

Blei feilaktig tilbakestilt under regulering

Setter tilbake status til oppgave knyttet til kravpakke behandling til attestering

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoReguleringTest.kt
apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/SjekkOmOverstyrtBeregningRiver.kt
apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/SjekkOmOverstyrtBeregningRiverTest.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/ReguleringsforespoerselRiver.kt
apps/etterlatte-oppdater-behandling/src/test/kotlin/regulering/ReguleringsforespoerselRiverTest.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/sak/SakIDListe.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/IkkeStandardiserteKeys.kt

Gjelder oppgave [EY-3977](https://jira.adeo.no/browse/EY-3977)

Avbryte alle aapne behandlinger med overstyrt beregning

---

apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt

Tildele oppgave kravpakke utland sb som fattet vedtak

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDao.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDaoTest.kt
apps/etterlatte-saksbehandling-ui/client/package.json
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktTidslinje.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/NyAktivitet.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/aktivitetsplikt.ts
apps/etterlatte-saksbehandling-ui/client/yarn.lock

Lar saksbehandler opprette en vurdering av aktivitetsplikt for en førstegangsbehandling og revurdering.
Usikker om det er riktig flyt i selve valgene i vurderingen, men det er klart til å se på overordnet.

EY-3952: Vurdering av aktivitetsplikt under behandling

---

.github/workflows/app-etterlatte-tidshendelser.yaml
apps/etterlatte-tidshendelser/build.gradle.kts
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/klient/BehandlingKlient.kt
apps/etterlatte-tidshendelser/src/main/resources/db/migration/V7__aktivitetsplikt_oppflging_4mnd_januar_februar.sql

Får ut oppgaver om infobrev / vurdering av aktivitet for de med avdødes dødsmåned januar / februar 2024.

Tidshendelsekjoering om vurdering av aktivitetsplikt 4mnd

---

README.md

Scriptet tar ikke lengre hensyn til input av argument, istede vises en liste over applikasjoner

Oppdatere steg for henting av secrets i README.md

---

apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/dolly/BestillingUtil.kt

ref tråd i dolly, https://nav-it.slack.com/archives/CA3P9NGA2/p1717501854766699

Relatert person i testdata bør også være helsyntetisk

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingServiceIntegrationTest.kt

Flytter logikken for opprettelse av revurdering fra route til service

---

apps/etterlatte-brev-api/src/test/resources/grunnlag.json
apps/etterlatte-opplysninger-fra-soeknad/src/main/kotlin/no/nav/etterlatte/opplysningerfrasoknad/opplysninger/Utbetalingsinformasjon.kt
apps/etterlatte-opplysninger-fra-soeknad/src/main/kotlin/no/nav/etterlatte/opplysningerfrasoknad/opplysningsuthenter/Opplysningsuthenter.kt
apps/etterlatte-opplysninger-fra-soeknad/src/test/kotlin/no/nav/etterlatte/opplysningerfrasoknad/OpplysningsuthenterBarnepensjonTest.kt
apps/etterlatte-opplysninger-fra-soeknad/src/test/kotlin/no/nav/etterlatte/opplysningerfrasoknad/OpplysningsuthenterOmstillingsstoenadTest.kt
gradle/libs.versions.toml

Endre oensketSkattetrekkProsent -> oensketSkattetrekk og legg til beskrivelse

Legger til ny common

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/BehandlingService.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseRiver.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseService.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Aktivitetsplikt.kt
libs/etterlatte-oppgave-model/src/main/kotlin/oppgave/OppgaveIntern.kt

Kun endringer i backend. Frontend kommer i egen PR.
EY-3378

Skal opprette oppgave om aktivitetsplikt dersom man har en åpen behandling

---

apps/etterlatte-tilbakekreving/.nais/dev.yaml
apps/etterlatte-utbetaling/.nais/dev.yaml

fjerne cascadingDelete true fra nais.yaml

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDao.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDaoTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktVurderingVisning.tsx

Backend for oppdatering av unntak og aktivitetsgrad.
Frontend kommer i egen PR -  https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5066

La saksbehandler oppdatere unntak og aktivitetsgrad

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt

Fjern default saksbehandler EY fra revurderingen som opprettes

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktOMSService.kt

Saker i Pesys med status OPPRETTET skal ikke være kryssende

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDao.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt

Vi skal se på siste vurdering, som må være enten unntak eller aktivitet.
[EY-4001](https://jira.adeo.no/browse/EY-4001)

Skal se på siste vurdering for å avgjøre om aktivitetsplikt er oppfylt

---

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/PersonMapper.kt
apps/etterlatte-pdltjenester/src/main/kotlin/personweb/PersonWebService.kt
apps/etterlatte-pdltjenester/src/main/kotlin/personweb/familieOpplysninger/FamilieOpplysninger.kt

I mappingen av foreldre for barnepensjon er det
forelder-barn-relasjonen som er viktig for rettighet

Bytter fra ansvarlige foreldre til foreldre

---

apps/etterlatte-testdata/src/main/resources/templates/dolly/opprett-og-behandle.hbs

Fikser feedback opprett-og-behandle

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/doedshendelse/DoedshendelseReminderService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingServiceIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingServiceIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/doedshendelse/DoedshendelseReminderServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgaveGosys/GosysOppgaveServiceImplTest.kt
libs/etterlatte-oppgave-model/src/main/kotlin/oppgave/OppgaveIntern.kt

opprydding i navn og måten vi oppretter oppgave
forarbeid til ey-4032 (oppgave uten sak/fnr)

opprydding opprett oppgave

---

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningServiceTest.kt

trace 97df9059238d81183b1c1c013d89227e

Ikke hent behandling dobbelt i beregning

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/BehandleJournalfoeringOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/handling/StartOppgavebehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreBruker.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/OppdaterJournalpost.tsx
apps/etterlatte-saksbehandling-ui/client/src/utils/formattering.ts

Foreløpig bak feature toggle. Ser slik ut: 
Vil se slik ut når det aktiveres:

EY-3267 Støtte endring av bruker journalpost

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/notat/NotatHandlinger.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/notat/NotatRedigeringModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/notat/NyttNotatModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/notat/RedigerNotatTittel.tsx

Justeringer iht. kommentarer fra design
- Legge til lagreknapp, selv om det automatisk lagres
- Egen lukkeknapp til venstre
- Gjøre det enklere å redigere tittel

EY-3728 Småfikser på notat design

---

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModellSoek.kt
apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlOboKlient.kt
apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/PersonMapper.kt
apps/etterlatte-pdltjenester/src/main/kotlin/personweb/PersonWebRoute.kt
apps/etterlatte-pdltjenester/src/main/kotlin/personweb/PersonWebService.kt
apps/etterlatte-pdltjenester/src/main/kotlin/personweb/SporingService.kt
apps/etterlatte-pdltjenester/src/main/kotlin/personweb/dto/PersonNavnFoedselsaar.kt
apps/etterlatte-pdltjenester/src/main/kotlin/utils/PdlKlientUtils.kt
apps/etterlatte-pdltjenester/src/main/resources/pdl/hentPerson.graphql
apps/etterlatte-pdltjenester/src/main/resources/pdl/soekPerson.graphql

må sees sammen med https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5138

EY-4054 Søke etter personer med navn og fødselsdato

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt

Sikrer at eventuelle forespoerselexceptions kommer til sb

Lesbar feilmeld v feil i oppgave v lukking av hendelse

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/SamsvarPersongalleri.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/barnepensjon/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreBruker.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/OppdaterJournalpost.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/modal/AvansertSoek.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/modal/SoekPersonPdl.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/pdltjenester.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts

Baserer seg på https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5143
Foreløpig er søket "strengt" siden fødselsdato MÅ matche nøyaktig && fritekst søk på navn.

EY-4054 soek person

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkorting.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkortingDetaljer.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts

Viser riktig sanksjontype og viser ikke tekster for sanksjon hvis det ikke er skrudd på

Fikser småfeil i avkortingsbildet 

---

apps/etterlatte-behandling/src/main/resources/db/prod/V136__fikser_feil_status_oppgave.sql

revert oppgave+endringer som ble feil ved regulering

---

apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V30__avkortet_ytelse_populer.sql

EY-4080 Fyller avkortet_ytelse-tabellen med eksisterende data fra vedtak.avkorting

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt

Veldig godt mogleg at fleire av dei andre oppgåvetypene her heller ikkje skal endrast

Tilbakestiller ikkje oppgåver til attestering for oppgave som er kravpakke utland

---

apps/etterlatte-utbetaling/.nais/dev.yaml
apps/etterlatte-utbetaling/.nais/prod.yaml
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/Application.kt

ref https://nav-it.slack.com/archives/C01KJ597UAU/p1718792577978669

Justert health-endepunkter på utbetaling iht UI sin selftest-forventninger

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevParametre.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrevModal.tsx

Nye manuelle informasjonsbrev ved dødsfall for BP+OMS.

---

apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/utbetalinger/TilbakekrevingVurderingPerioderSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/tilbakekreving.ts

EY-4067: Legger på en knapp for å hente oppdatert kravgrunnlag

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/MinOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/Oppgavelista.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaver/Oppgaver.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaverTable/OppgaverTable.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaverTable/OppgaverTableRow.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/utils/oppgaveHandlinger.ts
apps/etterlatte-saksbehandling-ui/client/src/components/person/AktivitetspliktInfoModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/AktivitetspliktRevurderingModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/ForenkletOppgaverTable.tsx

Det er oppgaver for aktivitetsplikt som ferdigstilles i oppgavelista og som da trengs å settes til ferdigstilt.

Oppdater oppgavelisten ved oppdatering av status

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sanksjon/Sanksjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/utils/formattering.ts

Endrer også litt på feilmelding / visning på måneder

Henter avkorting på nytt ved sletting av sanksjon

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakDao.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/ReguleringsforespoerselRiver.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/VedtakAttestertRiver.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/ReguleringService.kt

Rettar småfeil i reguleringsflyten

---

apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/aldersovergang/AldersovergangServiceTest.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/ReguleringsforespoerselRiver.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/AppContext.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/JobbPoller.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/regulering/ReguleringDao.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/regulering/ReguleringService.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/regulering/Reguleringskonfigurasjon.kt
apps/etterlatte-tidshendelser/src/main/resources/db/migration/V8__reguleringskonfig.sql
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/JobbPollerIntegrationTest.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/regulering/ReguleringDaoTest.kt
libs/etterlatte-database/src/main/kotlin/KotliqueryUtils.kt
libs/etterlatte-database/src/testFixtures/kotlin/no/nav/etterlatte/DataSourceInsert.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/ReguleringEvents.kt

Sånn at vi enkelt og effektivt kan justere for kvar køyring.

EY-4108 Konfigurerer opp regulering ut frå databasetabell

---

apps/etterlatte-hendelser-samordning/.nais/dev.yaml

Forglemmelse fra tidligere, da vi hadde alt av SAM/TP skrudd mot Q1 (pga test mot eksterne TP-ordninger, uten full støtte for syntetiske testdata)
:/

Skrur over til å lytte på Q2-topic for SAM-hendelser

---

apps/etterlatte-behandling/src/main/kotlin/common/klienter/PesysKlient.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunkt.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt

https://github.com/navikt/pesys/pull/13037

Nytt kontrollpunkt som sjekker om den tilstøtte er behandlet i Pesys allerede

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/SimulerUtbetaling.tsx

ref møte
Ble en del linjeendringer automatisk pga den eslint-"feilen" vi hadde inne og som jeg bypasset i forrige PR på visningen

EY-3389 Spisse linjebeskrivelse ved tilbakeføring

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/SimulerUtbetaling.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/utbetaling.ts
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/UtbetalingRoutes.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/simulering/SimuleringDao.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/simulering/SimuleringOsService.kt

Dette er først og fremst ment som et verktøy til attestanten.

EY-4143 Vise lagret simulering hvis den finnes

---

apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDaoTest.kt

Denne testen ser ut til å kunne intermittently faile

Mer eksplisitt styring på tidspunkt i test

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/RedigerFamilieforhold.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidManueltOverstyrt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/manuelbehandling/ManuellBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/BehandleJournalfoeringOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/ferdigstilloppgave/FerdigstillOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/handling/StartOppgavebehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreAvsenderMottaker.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreBruker.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreDokumenter.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreTema.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreTittelJournalpost.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/OppdaterJournalpost.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/OpprettNyBehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/OppsummeringOppgavebehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/PersongalleriBarnepensjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/nybehandling/PersongalleriOmstillingsstoenad.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/oppretteklage/OpprettKlagebehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/oppretteklage/OppsummeringKlagebehandling.tsx

Bruke aksel sine komponenter i stedet for hjemmemekka greier

Opprydding i komponenter fra jfr-oppgave

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt

Hele tjenesten er befestet med forskjellige inTransaction rare steder, som gjør det heller vanskelig å bruke de forskjellige funksjonene siden de av og til setter opp en transaksjon, og av og til ikke.
Nå gjør _ingen_ av funksjonene noe med inTransaction, og stoler heller på at route utenfor oppretter det.

Flytter transaksjoner ut til routes for aktivitetspliktService

---

apps/etterlatte-statistikk/src/main/kotlin/statistikk/river/AktivitetspliktHendelseRiver.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/river/AktivitetspliktHendelseRiverTest.kt

Legger også på en enkel test på innlesing i riveren

Fikser innlesing av melding i AktivitetspliktRiver

---

apps/etterlatte-behandling/src/main/kotlin/behandling/doedshendelse/DoedshendelseReminderService.kt

For dødshendelsene som ble opprettet før opprettelse av brev ble skrudd på, så kan vi ikke opprette oppfølgingsoppgave fordi det ikke finnes noen sak.

Fikser NPE i DoedshendelseReminderJob.

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/barnepensjon/Soeskenliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/omstillingsstoenad/BarneListe.tsx

Nok et tilfelle av at `gyldigFraOgMed` er null og tidligere "bare har fungert" og gitt feil dato...

Hotfix: Flere tilfeller av dato som er NULL

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt

Aktivitetsplikt gjelder for den 7. måneden.

Aktivitetsplikt gjelder for den 7. måneden.

---

apps/etterlatte-tidshendelser/src/main/resources/db/migration/V10__aktivitetsplikt_kjoeringer_juli_august.sql

Aktivitetsplikt-jobber for juli og august

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/SimulerUtbetaling.tsx

`utbetaling` kan jo gi 204 her så greit nok, men tenker får høre med økonomi om hva slags situasjon som leder til dette. 
Dette ble jo oppdaget ved en førstegangsbehandling av OMS i dev (ikke sjekket prod-saken) og det skal jo være grei skuring.

EY-4165 Håndtere 204 ved simulering

---

apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/prod.yaml

https://nav-it.slack.com/archives/C01KJ597UAU/p1720089659566119?thread_ts=1720083496.893589&cid=C01KJ597UAU

Øker cpu/mem for samordning-vedtak

---

.github/workflows/app-etterlatte-samordning-vedtak.yaml

https://github.com/navikt/pensjon-etterlatte-saksbehandling/actions/runs/9795710864

Fiks feil i samording yanml fil

---

.github/workflows/app-etterlatte-samordning-vedtak.yaml

https://github.com/navikt/pensjon-etterlatte-saksbehandling/actions/runs/9795967583/job/27049349516

Deploy trenger build

---

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/utbetaling/Utbetaling.kt

Lagt til enum for frivilling skattetrekk BP

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/SamordningSak.tsx

EY-4182 Sanert toggle for å redigere samordningsmelding

---

apps/etterlatte-beregning/src/main/kotlin/beregning/regler/barnepensjon/BeregnBarnepensjon.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/regler/BeregnBarnepensjonTest.kt

todo: må også gjøres for OMS, tar dette i egen pr

EY-4088 Fiks for lavt beløp for inst bp

---

apps/etterlatte-tidshendelser/src/main/resources/regulering.puml

EY-4017: Diagram som viser korleis reguleringsflyten heng saman

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt

* Siden vanlig sb på vanlig enhet kan behandle fortrolig saker

Kun varsle hvis strengt fortrolig

---

apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingServiceIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgaveGosys/GosysOppgaveServiceImplTest.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/Brevdistribuerer.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/beregning/BeregningServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/notat/NyNotatServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/oversendelsebrev/OversendelseBrevServiceImplTest.kt
apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRouteTest.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt
libs/etterlatte-ktor/src/main/kotlin/TokenUtils.kt
libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt
libs/etterlatte-ktor/src/test/kotlin/no/nav/etterlatte/libs/ktorobo/AzureAdClientTest.kt
libs/etterlatte-ktor/src/test/kotlin/no/nav/etterlatte/token/BrukerTokenInfoTest.kt
libs/etterlatte-ktor/src/testFixtures/kotlin/no/nav/etterlatte/ktor/TokenIssuer.kt

se https://nav-it.slack.com/archives/C60FFACN5/p1688640594913279?thread_ts=1687257982.242899&cid=C60FFACN5

Bruk ny systembrukersjekk idtyp claim

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-beregning/.nais/dev.yaml
apps/etterlatte-beregning/.nais/prod.yaml
apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/prod.yaml
apps/etterlatte-grunnlag/.nais/dev.yaml
apps/etterlatte-grunnlag/.nais/prod.yaml
apps/etterlatte-migrering/.nais/dev.yaml
apps/etterlatte-migrering/.nais/prod.yaml
apps/etterlatte-pdltjenester/.nais/dev.yaml
apps/etterlatte-pdltjenester/.nais/prod.yaml
apps/etterlatte-saksbehandling-ui/.nais/azuread-etterlatte-saksbehandling-ui-lokal.yaml
apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml
apps/etterlatte-samordning-vedtak/.nais/dev-api.yaml
apps/etterlatte-samordning-vedtak/.nais/dev.yaml
apps/etterlatte-samordning-vedtak/.nais/prod-api.yaml
apps/etterlatte-samordning-vedtak/.nais/prod.yaml
apps/etterlatte-testdata/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/prod.yaml
apps/etterlatte-utbetaling/.nais/dev.yaml
apps/etterlatte-utbetaling/.nais/prod.yaml
apps/etterlatte-vedtaksvurdering/.nais/dev.yaml
apps/etterlatte-vedtaksvurdering/.nais/prod.yaml
apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml
apps/etterlatte-vilkaarsvurdering/.nais/prod.yaml

Claimsa blir alltid satt på tokenet ref https://nav-it.slack.com/archives/C5KUST8N6/p1720705713445719

Fjern unødvendig extra på azure token som vi alltid får

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/DetaljertBehandlingDto.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/ViderefoertOpphoerTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.test.ts
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/viderefoere-opphoer/ViderefoereOpphoer.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/viderefoere-opphoer/ViderefoereOpphoerVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/api/vilkaarsvurdering.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/BehandlingReducer.ts

Skjult bak funksjonsbrytar.
Gjenstår å vise fram eit venleg namn for vilkårstypen, samt å liste ut alle vilkårstypane. Tenkjer det kan komme i ein separat PR.

EY-4102: Viderefør opphør

---

apps/etterlatte-behandling/src/main/kotlin/Contekst.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingServiceIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgaveGosys/GosysOppgaveServiceImplTest.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacadeImplTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/hentinformasjon/beregning/BeregningServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/notat/NyNotatServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/oversendelsebrev/OversendelseBrevServiceImplTest.kt
apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/LoggingPlugins.kt
apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRouteTest.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt
libs/etterlatte-ktor/src/main/kotlin/TokenUtils.kt
libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt
libs/etterlatte-ktor/src/test/kotlin/no/nav/etterlatte/libs/ktorobo/AzureAdClientTest.kt
libs/etterlatte-ktor/src/test/kotlin/no/nav/etterlatte/token/BrukerTokenInfoTest.kt
libs/etterlatte-ktor/src/testFixtures/kotlin/no/nav/etterlatte/ktor/BrukerTokenInfoTestGenerator.kt
libs/etterlatte-ktor/src/testFixtures/kotlin/no/nav/etterlatte/ktor/TokenIssuer.kt

* Ha standard oppsett av brukertokeninfo for tester

Fjern oid og sub fra brukertokeninfo

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/GrunnlagKlient.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt

* da det kan komme endringer som brekker grunnlaget for sak

Lås statistikkmeldinger for aktivitetsplikt til behandling

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagMetode.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/boddEllerArbeidetUtlandet/BoddEllerArbeidetUtlandetVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/EnkelPersonTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/OverstyrtTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/avtaler/TrygdeAvtale.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/components/AvdoedesTrygdetidReadMore.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/components/EksportvurderingReadMore.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/components/PoengaarReadMore.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/components/TrygdetidMelding.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/detaljer/BeregnetFaktiskTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/detaljer/BeregnetFremtidigTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/detaljer/BeregnetSamletTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/detaljer/TrygdetidDetaljer.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/styled.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/utils.ts

Opprydning i trygdetidavtale:
Og i poengår:
+ litt andre visuelle småfiks

EY-4110 opprydning i trygdetid v3

---

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/utbetaling/Utbetaling.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/simulering/Simulering.kt

https://jira.adeo.no/browse/FAGSYSTEM-338743?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D

Støtt statsforvalter der kreditor disponerer

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidGrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/trygdetidPerioder/TrygdetidPerioder.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/trygdetidPerioder/TrygdetidPerioderTable.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/components/datoVelger/ControlledDatoVelger.tsx

Flytting av "Rediger trygdetid periode" inn i expandable rowen den tilhører

Småfiks i trygdetid bildet

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadSammendrag.tsx

Bytt Brutto stønad før avkorting med beregning gjelder

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonRevurdering.kt

Dermed blir tittelen i brevet også riktig.

FAGSYSTEM-338819: Sender med dato for vedtaket som omgjerast

---

libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/IkkeStandardiserteKeys.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/ListenerMedLoggingOgFeilhaandtering.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/RetryOgFeilhaandtering.kt
libs/rapidsandrivers-extras/src/test/kotlin/rapidsandrivers/RetryOgFeilhaandteringKtTest.kt
libs/saksbehandling-common/src/main/kotlin/Retry.kt

Prøver på nytt i handteringa av meldinga, for å auke sjansen for at vi klarer å handtere meldingane i rett rekkjefølgje

Retry handteringa av meldinga før vi sender ut på kø igjen

---

apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/DoedsmeldingJob.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktOMSServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/OpprettAvsenderRequest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/SamordningsnotatRiver.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiverTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerTest.kt
apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRouteTest.kt
apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/AutomatiskBehandlingRiver.kt
apps/etterlatte-testdata/src/main/kotlin/Application.kt
libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt
libs/etterlatte-ktor/src/test/kotlin/no/nav/etterlatte/token/BrukerTokenInfoTest.kt
libs/etterlatte-ktor/src/testFixtures/kotlin/no/nav/etterlatte/ktor/token/BrukerTokenInfoTestGenerator.kt
libs/etterlatte-ktor/src/testFixtures/kotlin/no/nav/etterlatte/ktor/token/TokenIssuer.kt

Eksplisitt struktur for hardkoda systembrukarar, og også enda litt meir struktur rundt systembruker-tokens.

EY-4211: Struktur rundt hardkoda systembrukarar

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sanksjon/Sanksjon.tsx

Justere tekst for sanksjoner i beregningsbildet

---

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/MigrertYrkesskadeOppdaterer.kt
apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/config/ApplicationContext.kt
apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/MigrertYrkesskadeTest.kt
libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt

Justerer endringane i vilkårsvurdering ut frå oppdateringane på main

Fiksar brekt bygg for vilkårsvurdering

---

apps/etterlatte-brev-api/build.gradle.kts
apps/etterlatte-testdata/build.gradle.kts
apps/etterlatte-tilbakekreving/build.gradle.kts
apps/etterlatte-vilkaarsvurdering-kafka/build.gradle.kts
gradle/libs.versions.toml
libs/etterlatte-ktor/build.gradle.kts
libs/etterlatte-ktor/src/test/kotlin/no/nav/etterlatte/libs/ktorobo/AzureAdClientTest.kt

Jo færre avhengnadar vi har, jo lettare er det å halde tritt.
Desse ser ut til å ha vore med oss lengje.

Slettar enda nokre ubrukte avhengnadar

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageBrevService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BrevApiKlient.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageServiceImplTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingServiceIntegrationTest.kt
apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/KlageMottakerRequestTest.kt
apps/etterlatte-klage/src/main/kotlin/no/nav/etterlatte/klage/modell/KlageOversendelse.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/Brev.kt

Utvider den igjen med journalpostId og bestillingId

Bruker common-modulen i brev for henting av data klage

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx

Gammel feilmelding:
Ny feilmelding:

Viser mer passende feilmelding hvis trygdetid ikke er valgt

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/StickyToppMeny.tsx

Fikset valdering av dato da tidlinjen ikke vises per dags dato

EY-4147: z-index for tidslinje

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevParametre.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/AktivitetspliktBrevdata.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrevModal.tsx
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/EtterlatteBrevkode.kt

La saksbehandler sende manuelt brev om aktivitetsplikt ved 6mnd

---

apps/etterlatte-statistikk/src/main/kotlin/statistikk/database/AktivitetspliktRepo.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
apps/etterlatte-statistikk/src/main/resources/db/migration/V50__patch_feil_aktivitetsplikt_statistikk.sql
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/service/AktivitetspliktServiceIntegrationTest.kt
apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/service/StatistikkServiceTest.kt

Tar regenerering av statistikken etter dialog med statistikkteamene

Fikser feil i mapping av aktivitetsplikt månedsstatistikk

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevParametre.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnhentingAvOpplysninger.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrevModal.tsx
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/EtterlatteBrevkode.kt

Nytt brev for innhenting av informasjon (OMS)

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevParametre.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInformasjonMottattSoeknad.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrevModal.tsx
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/EtterlatteBrevkode.kt

https://github.com/navikt/pensjonsbrev/pull/840 Må merges først.
EY-4230

Nytt kvitteringsbrev for BP

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevParametre.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnhentingAvOpplysninger.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrevModal.tsx
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/EtterlatteBrevkode.kt

Nytt brev for innhenting av opplysninger (BP)

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/BrevOversikt.tsx

EY-4120 Visning av dato for utsendelse

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/AktivitetspliktRevurderingModal.tsx

Lar saksbehandler skrive inn beskrivelse i merknad-feltet på oppgaven

---

apps/etterlatte-beregning/src/main/kotlin/ytelseMedGrunnlag/YtelseMedGrunnlagService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Beregning.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/beregning/BeregningService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EtterlatteBrev.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadRevurdering.kt
libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt

Legg til institusjonsopphold i beregningstabell

---

apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/Application.kt
apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/InntektsjusteringRiver.kt
apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/JournalfoerInntektsjusteringService.kt
apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/gyldigsoeknad/config/AppBuilder.kt
libs/saksbehandling-common/src/main/kotlin/event/InntektsjusteringInnsendt.kt

InntektsjusteringsRiver journalfører mottatt inntektsjustering som PDF.
PdfGen sin endepunkt/mal "notat/tom_mal"  er midlertidig benyttet men det skal byttes ut med en ny egen mal for inntektsjustering.

Inntektsjustering arkiver

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/AktivitetspliktInfoModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/aktivitet/Aktivitet.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/aktivitetsplikt.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Aktivitetsplikt.ts

Ligger bak featuretoggle inntil videre da periodisering ikke er 100% løst.
Vil også legge til tidslinje på denne siden, men det kommer i egen pr.

Vis vurdering av aktivitetsplikt på sak

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktTidslinje.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/aktivitet/Aktivitet.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/aktivitetsplikt.ts

Denne gjelder kun fremvisning av data. Er en egen oppgave for å håndtere endringer på tidslinjen

Vis tidslinje med aktiviteter på sak

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt

Burde også fjerne `pensjon-etterlatte.kan-sende-brev-og-opprette-oppgave`, men der var det ein del testar som feilar, så tar det separat

Fjern dødshendelse-brytarar

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadRevurdering.kt

Henter ut datoVedtakOmgjoering for OMS

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/HaandterAvvikModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/KnyttTilAnnenBruker.tsx

Endre navn fra "Overfør" til "Knytt til annen sak", som er det man gjør. Flyten fra front til back blir da også litt mer sammenhengende.

Opprydding på knytt til annen sak

---

apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
apps/etterlatte-statistikk/src/main/resources/V51__rydd_maaned_statistikk.sql

og rekjører statistikken for juli

Filterer bort skjermede saker fra stønadsstatistikken

---

apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/api/feature.ts

Copy paste av @madsop-nav og av backend retry :D

Retry unleash frontend

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
libs/saksbehandling-common/src/main/kotlin/behandling/Persongalleri.kt

Legger også til annen forelder i personopplysninger

EY-4312: Nytt endepunkt for å legge til info om annen forelder i persongalleriet

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/AktivitetspliktInfo6MndVarigUnntakModal.tsx

Oppdater tekst i oppgave om varig unntak

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/regler/BeregnTrygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/regler/BeregnTrygdetidGrunnlag.kt

- Add some more comments describing rules
- Move trygdetid grunnlag rules to own file

Tidy trygdetid regler and add comments.

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/aktivitet/Aktivitet.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/tags/AktivitetspliktUnntakTypeTag.tsx

Legger til tag for type unntak

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/regler/BeregnTrygdetid.kt

RegelRef navn må være unik

---

apps/etterlatte-behandling/src/main/kotlin/behandling/doedshendelse/DoedshendelseReminderService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseRouteTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/mellomAttenOgTjueVedReformtidspunkt/BehandleDoedshendelseServiceTest.kt

Og rydder bort gammel testkode.

Fjerner feature-toggle for dødshendelser

---

apps/etterlatte-behandling/src/main/kotlin/behandling/sjekkliste/Sjekkliste.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/sjekkliste/SjekklisteService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/sjekkliste/SjekklisteIntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/BehandlingSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sjekkliste/Sjekkliste.tsx

OMS revurdering:
BP revurdering:

EY-3712 sjekklister for revurdering behandling

---

apps/etterlatte-behandling/src/main/resources/db/prod/V155__sett_oppgave_til_ferdigstilt.sql

ref https://jira.adeo.no/browse/FAGSYSTEM-343926?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D
Behandlingen er iverksatt men oppgaven har status NY som hindrer ny revurdering

Sett oppgave som skulle vært ferdigstilt til ferdigstilt

---

apps/etterlatte-klage/src/main/kotlin/no/nav/etterlatte/klage/KabalKlient.kt

Siden klagen allerede er sendt er sendingen "ok".
Løser en klage som er stuck i produksjon.

Kaster ikke feil videre hvis det er conflict i fra Kabal

---

apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/MaanedStatistikk.kt

Med overstyrt beregning / problemer i persongalleriet for migrerte saker tar vi en ekstra sjekk for å utlede anvendt sats

Korrigerer sakytelsesgruppe i statistikken for overstyrt beregning BP

---

apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/dolly/Model.kt

se https://github.com/navikt/testnorge/pull/3603

Ny dolly modell for foedsel

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/FlereAvdoedePerioderHelper.kt

ref https://jira.adeo.no/browse/FAGSYSTEM-344515?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D
viser kun illegalstateexception til sb, det er ikke veldig hjelpsomt

Gi ordentlig feilmelding ikke illegalstateexception til front

---

.github/dependabot.yml
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/etterlatte.common.gradle.kts
buildSrc/src/main/kotlin/etterlatte.libs.gradle.kts
gradle/libs.versions.toml
libs/etterlatte-behandling-model/build.gradle.kts
libs/etterlatte-beregning-model/build.gradle.kts
libs/etterlatte-brev-model/build.gradle.kts
libs/etterlatte-database/build.gradle.kts
libs/etterlatte-funksjonsbrytere/build.gradle.kts
libs/etterlatte-institusjonsopphold-model/build.gradle.kts
libs/etterlatte-jobs/build.gradle.kts
libs/etterlatte-kafka/build.gradle.kts
libs/etterlatte-ktor/build.gradle.kts
libs/etterlatte-migrering-model/build.gradle.kts
libs/etterlatte-mq/build.gradle.kts
libs/etterlatte-oppgave-model/build.gradle.kts
libs/etterlatte-pdl-model/build.gradle.kts
libs/etterlatte-regler/build.gradle.kts
libs/etterlatte-sporingslogg/build.gradle.kts
libs/etterlatte-tilbakekreving-model/build.gradle.kts
libs/etterlatte-trygdetid-model/build.gradle.kts
libs/etterlatte-utbetaling-model/build.gradle.kts
libs/etterlatte-vedtaksvurdering-model/build.gradle.kts
libs/etterlatte-vilkaarsvurdering-model/build.gradle.kts
libs/rapidsandrivers-extras/build.gradle.kts
libs/saksbehandling-common/build.gradle.kts

Såg ein del potensiale for forenkling da eg jobba med Kotlin 2, som ikkje var direkte Kotlin-relatert, så her er det, i ein eigen PR. Litt forskjellige endringar, men inndelt i commits per endring.

Rydde og forenkle gradleoppsett

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageDao.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageDaoImplTest.kt

Hvis ikke blir ikke mottatt dato oppdatert i lagringen.

Lagre oppdatert felt fra klagen i dao

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallVisning.tsx

Alle valg saksbehandler har gjort i brevutfall skal vises. Litt usikker på hvordan gamle saker med tanke på data om krav og skattetrekk er så har lagt inn sjekk på hvert felt.

Vis alle valg av brevutfall

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/DistribusjonKlient.kt

Fange `SocketTimeoutException` fra dokdist. Det har skjedd 12 ganger denne uken, så vi får unødvendig mye støy i alerts-kanalen. 
Gir heller sb en feilmelding og beskjed om å prøve på nytt, så får de varsle oss dersom en feil eventuelt vedvarer.

Gi sb bedre feilmelding ved timeout mot dokdist

---

apps/etterlatte-brev-api/build.gradle.kts
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/Notat.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NotatService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NyNotatService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/pdfgen/PdfGeneratorKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/pdfgen/SlatePDFMal.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/NotatServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/notat/NyNotatServiceTest.kt
apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/gyldigsoeknad/journalfoering/JournalfoerSoeknadService.kt
apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/gyldigsoeknad/pdf/PdfGeneratorKlient.kt
apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/inntektsjustering/JournalfoerInntektsjusteringService.kt
apps/etterlatte-gyldig-soeknad/src/test/kotlin/no/nav/etterlatte/inntektsjustering/InntektsjusteringRiverTest.kt
gradle/libs.versions.toml
libs/etterlatte-behandling-model/build.gradle.kts
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt

Starta med ei hypotese om at det var lurt å flytte all bruk av denne til brev-api, men er ikkje lenger så overtydd om at det er verdt det.
Men rakk å lage litt struktur rundt det på vegen til den konklusjonen, og den strukturen trur eg er fin og nyttig å ha.

EY-4356: Strukturere pdfgen-kall

---

apps/etterlatte-tidshendelser/src/main/resources/db/migration/V14__kjoerer_AO_BP_20_paa_nytt.sql

Jobben med å finne ut av hvorfor tas senere.

Begge disse kjøringene ligger som "STARTET" i basen, uten noen oppgaver

---

apps/etterlatte-behandling/src/main/resources/db/prod/v161__sett_oppgave_til_ferdigstilt.sql

Ferdigstille en oppgave for behandling som er IVERKSATT
Ref https://jira.adeo.no/browse/FAGSYSTEM-344020

FAGSYSTEM-344020 ferdigstille oppgave

---

apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt

retter tilfeller hvor attesteringsoppgaver ikke endret frist på oppgaven til 2 dager

Sørge for at attesteringsoppgaver blir satt til 2 dagers frist

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelse.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelseForeldreloes.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonRevurdering.kt

Vi er litt i limbo der vi går fra å ha frivillig skattetrekk i etterbetaling til å ha det i brevutfall. Er noen saker som har registrert det i etterbetaling så gjør en ekstra sjekk før man gir en feilmelding.

Sjekk om frivillig skattetrekk er i etterbetaling

---

apps/etterlatte-saksbehandling-ui/client/src/index.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/logger.tsx

guide: https://mariusschulz.com/blog/declaring-global-variables-in-typescript
relevant: https://ishwar-rimal.medium.com/typeerror-failed-to-fetch-a-k-a-pain-in-the-ass-fa04dda1514c

Ikke logge fetch requests som blir cancelled av unload event

---

.github/workflows/.build-and-deploy.yaml

Sett opp token-variable iht tips frå Youssef på nais-teamet: https://nav-it.slack.com/archives/C5KUST8N6/p1727154134562499?thread_ts=1727082677.061639&cid=C5KUST8N6

Fiksar SBOM-generering

---

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/ParallelleSannheterKlient.kt
apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt
apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/PersonMapper.kt
apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/VergeMapper.kt
apps/etterlatte-pdltjenester/src/main/kotlin/personweb/dto/PersonNavnFoedselsaar.kt
apps/etterlatte-pdltjenester/src/main/resources/pdl/hentPersonNavnFoedsel.graphql
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/Behandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/Verger.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/personopplysninger/Personopplysninger.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/personopplysninger/Vergemaal.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/statusbar/Statusbar.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/tags/VergemaalTag.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts

Viser nå tag for **vergemål** i statusbar dersom person har verge.

EY-4398 Vise tag ved vergemål

---

apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/HendelseDao.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/JobbPoller.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/JobbPollerIntegrationTest.kt

Prøver også å fikse problemet selv, hvis det er mulig. Feilmeldingene er mer presise enn det som kom i loggene før ('Timer job "JobbPollerTask" has failed' eller noe i den dur).

EY-4455: Fanger feilsituasjoner i jobbpolling

---

apps/etterlatte-saksbehandling-ui/server/src/middleware/getOboToken.ts

Vil redusere spam i loggene i tilfeller hvor vi ikke får svar fra azuread

Sette "feil" i getOboToken til warn

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/aktivitet/Aktivitet.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/aktivitet/utils.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/tags/AktivitetspliktStatusTag.tsx

Her er jeg veldig usikker på hva som ligger bak at aktivitetkrav er oppfylt osv

EY-4249 tag for status på aktivitetsplikt

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt

Loggar det som error, og held så fram vidare. Unngår dermed å ta ned heile brev-løysinga.

Takle at automatisk handtering av brev feilar

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt

Håndteringen på feiling i distribuering av brev hjelper ikke når det feiler i opprettingen. Siden dette tar ned brev-api dytter jeg ut en shotgun-catching av feil igjen, og så må loggene gås igjennom i ettertid for å passe på at ikke noe har glippet her (annet enn det som stanger og tar ned R&R-appen)

Fanger feil i brev kafka aggressivt

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt

Eksplisitt feilmelding viss beregningsperiodar manglar på avkorting

---

apps/etterlatte-behandling/src/main/kotlin/behandling/doedshendelse/DoedshendelseReminderService.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDaoMedEndringssporing.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/doedshendelse/DoedshendelseReminderServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt

for å rette opp disse https://logs.adeo.no/app/r?l=DISCOVER_SINGLE_DOC_LOCATOR&v=8.15.2&lz=N4IglgdgJgpgHiAXCAnANhmgLADgMYAMAtCjgQIZECMVMKROAzBUTFQOwBGnU2nWUTiAA0IAE4B7AO4BJaPCQgAdFADORCOQBuAGwkBzdQCYCRrEoIolR9kQL2ArI3Yjx0mVEUBHAOIArVQBZBxkAIQcAMQARAE8AJQIARRwAeX19AGtXMRgAMxgxHLFFAHpyAAdykqgwVTwJLQKAYhKAfgB9fQBeAAoAFzAAWxhEHtzJQcQIaSIzAAsAUiMIueE%2BiSnpAEotgDJ28l76nQBXQYhVRABCHp0YRp1hYdVVcn0YYRgILTwdchfhBVyjowHhyAMJBBhOUJFAtsIoODyABlCQnMR4EY9RF9cgANTAMFkUEQAHJ0JhcIQSGRKDQ6AxmJQ2FweHwBJxSWsYuURjj8YSpPCvCcCjFRn8IPoTm8RqdMRAPiKxWS4O16oUYH8IRB2mASewUORGIwUA4HERGDAsJwiFg0DgjCRcFgiGgUJxGFQHdajDByKSdiAAL5AA%3D%3D%3D
org.postgresql.util.PSQLException: ERROR: out of shared memory
Hint: You might need to increase max_pred_locks_per_transaction.
at …

Sjekk om oppgave av type finnes for dødsmeldinger

---

.github/workflows/.build-and-deploy.yaml
.github/workflows/app-etterlatte-saksbehandling-ui.yaml

se https://nav-it.slack.com/archives/C5KUST8N6/p1727706010511229

fiks feilende sbom generering

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/Brevdistribuerer.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/oppgave/OppgaveService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtaksbrev/VedtaksbrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/DistribuerBrevRiver.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt

greit å se i sammenheng med at routsene ble lagt inn her i går https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5886
Må også flytte brevmodellene for de automatiske brevene. Gjør dette i egen pr

EY-4499 Litt endringer i routes laget for ny river app

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevParametre.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Personer.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt
libs/etterlatte-brev-model/build.gradle.kts
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/behandling/Avdoed.kt
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/model/BarnepensjonInformasjonDoedsfall.kt
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/model/BarnepensjonInformasjonDoedsfallMellomAttenOgTjueVedReformtidspunkt.kt
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/model/OmstillingsstoenadInformasjonDoedsfall.kt

trengs i river app for brev-api -> https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5859

EY-4499 Tilgjengeliggjør brevmodeller

---

apps/etterlatte-grunnlag/.nais/dev.yaml
apps/etterlatte-grunnlag/.nais/prod.yaml

gjøre klar tilkobling for ny app https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5859

EY-4499 Legg inn brev-kafka-tilgang-grunnlag

---

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/utbetaling/Utbetaling.kt

Ref feil ved simulering i prod: https://nav-it.slack.com/archives/C043C5ZGW5T/p1728284731451579

Legger til manglende klassifikasjonskode TBTREKK

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/navansatt/NavansattKlient.kt

Dele opp koden litt for å se om retryen sluker en feil vi burde håndtert bedre

midlertidig justering for å debugge navansattklient error

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt

todo: skal teste i dev mot at den klarer å plukke opp meldingene som denne mottok
se https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5859
NB: Skal ikke merges!!
edit: skal kanskje merges allikevel

EY-4499 Skru av riverers i brev-api

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/tidligereFamiliepleier/TidligereFamiliepleierVisning.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/tidligereFamiliepleier/TidligereFamiliepleierVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/components/datoVelger/ControlledDatoVelger.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IDetaljertBehandling.ts
libs/saksbehandling-common/src/main/kotlin/behandling/TidligereFamiliepleier.kt

EY-4550: Legg til startdato for pleieforhold

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
apps/etterlatte-statistikk/src/main/resources/db/migration/V52__rydd_saksstatistikk.sql
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/klage/StatistikkKlage.kt

Rydder i saksbehandlingsstatistikken og sender meldinger om klagevedtak

Ey 3597 fikser klagevedtak saksbehandlingsstatistikken

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt

https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5951

EY-4499 Skru av brev rivers i api app i prod

---

apps/etterlatte-brev-kafka/.nais/prod.yaml
apps/etterlatte-brev-kafka/src/main/kotlin/no/nav/etterlatte/Application.kt

rydder opp i brev-api når dette har gått OK
ups, trenger en godkjenning på denne og https://github.com/navikt/pensjon-etterlatte-felles/pull/345

EY-4499 Skru på brev kafka i prod

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/tidligereFamiliepleier/TidligereFamiliepleier.tsx

EY-4539: Legg til tekst og hjemler for tidlgere familiepleier

---

apps/etterlatte-behandling/src/main/resources/db/prod/V170__oppdater_behandling_til_iverksatt.sql

Sjekket i utbetaling og vedtaksvurdering. Vedtaket har status IVERKSATT og utbetalingen har status GODKJENT. Denne behandlingen skal ha status IVERKSATT og ikke ATTESTERT.

EY-4545: Oppdaterer status for behandling som var iverksatt men hadde status attestert

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/tidligereFamiliepleier/TidligereFamiliepleier.tsx

EY-4539: Fjern en setning og legg vilkår inn i en readmore

---

apps/etterlatte-saksbehandling-ui/server/package.json
apps/etterlatte-saksbehandling-ui/server/yarn.lock

fikser https://github.com/advisories/GHSA-pxg6-pf52-xh8x

Oppgrader 21.1 for å få bort en svakhet

---

libs/etterlatte-ktor/src/main/kotlin/route/RouteUtils.kt

Dagens feilmelding er en NullPointerException med en uforståelig stacktrace

Hvis sakId ikke er med i en route gi en god feilmelding

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/db/BrevRepositoryIntegrationTest.kt

EY-4499 Glemte å slette en relatert funksjon for å fjerne underkjentbrev

---

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/UtbetalingRoutes.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/config/ApplicationContext.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/klienter/BehandlingKlient.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/klienter/VedtaksvurderingKlient.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/simulering/SimuleringOsService.kt
apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/simulering/SimuleringOsRouteTest.kt

Greit at strukturen er lik andre apper på slike ting

Flytter klienter til egne pakker tilsvarende andre apper

---

apps/etterlatte-api/.nais/prod-api.yaml
apps/etterlatte-api/.nais/prod.yaml

https://nav-it.slack.com/archives/C01KJ597UAU/p1728634274240899

Gi alderspensjon-endringssoknad-backend tilgang i prod

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/grunnlag/GrunnlagKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/grunnlag/GrunnlagService.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/OpplysningDao.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/SakGrunnlagRoutes.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/OpprettSaksgrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/SakOversiktHeader.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/grunnlag.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/api/sak.ts
apps/etterlatte-saksbehandling-ui/docker-compose.yml

...kan man anta at det mangler grunnlag. Viser derfor knapp for å opprette grunnlag i tilfeller hvor det ikke finnes behandlinger på en sak. 
Bruker samme endepunkt som ved opprettelse av ny sak. Tjenesten sjekker om sak finnes og bruker den, men oppretter grunnlaget på nytt.

FAGSYSTEM-348687 Støtte opprettelse av manglende grunnlag + bedre sjekker

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/vilkaarsvurdering/service/VilkaarsvurderingService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
apps/etterlatte-behandling/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt

* Fjern unødvendig runblocking legacy
Se https://logs.adeo.no/app/r?l=DISCOVER_SINGLE_DOC_LOCATOR&v=8.15.2&lz=N4IglgdgJgpgHiAXKMUkgMYDYsDMCMA7ACwCcAtKQKwxbnEBMGu5AHBlMeQMz74BGDXFSwBDYvwAMIADQgALmHkAbGOmUB7AOYBnclpgQYAJzAZysXKICuy%2BTIiiAbpt0zXeiFshwAdKIwMGB09Sxs7d209flF5DAALCxgrW3lZBTAAWxgAMTAYZSgAOVFs9AABRWydeVKAB3SdDWtjILy7Ex0kAG0AXTl5AE86mABZGFqkYABfOVx8wpyNY0zYruQQAA1yAGFl4wLYsA0IcgBJABEp8DREEBrTL3S60WNS9dAX4x0YKABVYzKa7LMDeCDoeLyeR1HSIAD0cNEknwojqLnwpHw%2FlgGl8EA0iFYxGI3GesXijjKd0RdTqcIA1mAYo50jEfgAFcnoEDTXmzEDGawQKq5BZQUaoqb8%2BYFKAAQSh3ylclEyk0AHcihoztB4EgrMofnJKWo7nLacowPTRDoAFYnHSuAzGdKqjUACVQsHBiANP35xg06p1sAQd18UE8zg85AYkgYxF8%2BEkSa4knTWGIWHSgeDtxAO345EIYCoZwAQuqIMpRAAVHIAdSoAGkAEowek55ImA4u6moulQMA6DAaJwmADEcIA%2FAB9LQAXgAFCLEEvcIHMoh8eryPgqJkZPICTuAJSngBks9Ey9HymsmQgsIAhEvVOP …

Rett opp manglende instransaction

---

apps/etterlatte-brev-kafka/src/main/kotlin/no/nav/etterlatte/klienter/BrevapiKlient.kt
apps/etterlatte-brev-kafka/src/main/kotlin/no/nav/etterlatte/klienter/GrunnlagKlient.kt
libs/saksbehandling-common/src/main/kotlin/Retry.kt

Ref https://nav-it.slack.com/archives/C043C5ZGW5T/p1729024216555319
Sikkert fint å ha litt tålmodighet mot brev-api om den skrur redeployer. Tar mye kortere tid å vente 5 ganger med api kall kontra at appen kommer i restart loop.

Retry mot brev-api og grunnlag fra brev-kafka

---

apps/etterlatte-utbetaling/.nais/dev.yaml
apps/etterlatte-utbetaling/.nais/prod.yaml

Kan medføre noen problemer, se her https://github.com/navikt/rapids-and-rivers. Men har fungert greit nok i brev-api så langt. Satse på at det går greit i utbetaling også?

Fjerner recreate pga ca 1 min nedetid ved deploy

---

apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoDao.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoDaoTest.kt

* SingleorNull gir jo deg lov om det finnes eetterbetaling men du henter brevutfall men da tryner den siden .let manglet spørsmålstegn

Hente brevutfall maybe, getstring jdbc returnerer null.

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/flereAvdoede/BeregningsMetodeRadForAvdoed.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/EnkelPersonTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidManueltOverstyrt.tsx

Overstyrt trygdetid med ukjent avdød mulig for revurderinger:

Ey 4553 trygdetid med ukjent avdoed frontend

---

apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/logger.tsx
apps/etterlatte-saksbehandling-ui/server/src/routers/loggerRouter.ts

ref utviklersync med ønske om mindre logging av error på div frontend kall

Logge ting som info ikke error i frontend api ting

---

apps/etterlatte-api/.nais/dev-api.yaml
apps/etterlatte-api/.nais/prod-api.yaml

Enda en app for inntektsfilteret

---

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/simulering/Simulering.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/simulering/SimuleringOsService.kt
libs/etterlatte-utbetaling-model/src/main/kotlin/Simulering.kt

Ønsker å kunne simulere vedtak fra vedtaksvurdering ifm omregning for verifisering.

EY-4513: Flytter modell for simulering til utbetaling-model

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Varselbrev.tsx

Kaste feil i varselbrev om det er feil.
Kan vurdere å evt vise en advarsel i stedet for.
kan være vi kan konsolidere det her litt mer med stegmenyen men tenker jeg tar det i v2.
Kanskje lurt å legge inn dette på hver subside i behandlingen også?

Gi mulighet til å sjekke om route er gyldig

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx

Smudere rendring av routes for stegmeny

---

apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonService.kt
apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sanksjon/Sanksjon.tsx

Fikser at valideringen i sanksjoner frontend og backend kan slå feil ut når man avslutter en sanksjon.

EY-4615 Rydder i valideringen av sanksjoner i ytelsen

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDao.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V175__ekstra_kolonner_12mnd_vurdering_aktivitetsplikt.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDaoTest.kt

Bare nye kolonner og litt validering i lagring, samt tester.

EY-4606 Legger til støtte for ny vurdering av aktivitetsplikt i backend

---

apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/prod.yaml
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/virusskanning/VirusScanService.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/virusskanning/VirusScanServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/LastOppBrev.tsx

Ser at grensen er 10mb i backend, er det intensjonen?

FAGSYSTEM-351478 2mb filer

---

apps/etterlatte-beregning-kafka/build.gradle.kts
apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/Application.kt
apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/BeregningService.kt
apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/SjekkOmTidligAlderpensjonRiver.kt
apps/etterlatte-beregning/build.gradle.kts
apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
apps/etterlatte-beregning/src/main/kotlin/klienter/BehandlingKlient.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt

Hvis tidlig alderspensjon så skal det opprettes en oppgave med merknad og frist før alderspensjonen
Merknad: Opphør av ytelse på grunn av alderspensjon

EY-4618 opprett oppgave om opphør ved tidlig alderspensjon 

---

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt

obs, ikke merge før vi har tatt ned appene og migrert data

EY-4499 Aktivere vilkårsvurdering i behandlingbasen

---

apps/etterlatte-behandling/src/main/resources/db/prod/V177__migrere_status_samordnet.sql
apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V33__manuell_migrering_til_samordning.sql

ifm testing av samordning fix, så må vi migrere tilbake en behandling som har havnet i feil tilstand

manuell migrering for samordnet behandling

---

libs/etterlatte-jobs/src/main/kotlin/jobs/LeaderElection.kt

ref alle disse https://logs.adeo.no/app/discover#/?_g=(time:(from:now-24h%2Fh,to:now))&_a=(columns:!(level,message,envclass,application,pod),dataSource:(dataViewId:'96e648c0-980a-11e9-830a-e17bbd64b4db',type:dataView),filters:!(),hideChart:!f,interval:auto,query:(language:lucene,query:'x_correlation_id:6fb67069-476b-4ddd-a062-12ef69b7f338'),sort:!(!('@timestamp',desc)))

Mer forståelig feilmelding om leaderelection tryner

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntektForm.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts

Felt er allerede renamet backend og fører til visningsfeil i frontend nå

Rename til innviglaMaaneder frontend

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/behandling/BehandlingKlient.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/behandling/BehandlingService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperRedigerbartUtfallVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadAvslag.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt

Krever godkjenning av https://github.com/navikt/pensjonsbrev/pull/991 for å kunne merges.

EY-4596: Send med tidligere familiepleier til innvilgelse og avslag for OMS

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktKopierService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktOppgaveService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktKopierServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktOppgaveServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDaoTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/OppgaveVurderingRoute.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/VurderAktivitetspliktOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/sidemeny/AktivitetspliktSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/VurderAktivitet.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/Vurderinger.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/aktivitetsplikt.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Aktivitetsplikt.ts
apps/etterlatte-saksbehandling-ui/server/src/index.ts

Setter opp en spesialisert service for å håndtere vurderinger av aktivitet gjort i forbindelse med infobrevoppgavene.

EY-4607 se eksisterende vurderinger aktivitet

---

apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/SjekkOmTidligAlderpensjonRiver.kt

River for SjekkOmTidligAlderpensjon ser ikke ut til å trigges

Rette initRiver for SjekkOmTidligAlderpensjonRiver.kt

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt

Havner i en crashloop pga mangler respons

Manglet respons for endepunkt tidlig alderspensjon

---

.husky/pre-commit

Vil da se ut slik: 
...i stedet for:

Prefikse pre-commit err med rød ERROR

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktBrevDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktOppgaveService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V178__aktivitetsplikt_brev.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktBrevDaoTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktOppgaveServiceTest.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevParametre.kt
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/model/AktivitetspliktBrevdata.kt

relatert frontend pr https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/6151

EY-4644 Lagre brevdata for OMS aktivitetsplikt 10mnd backend

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/boddEllerArbeidetUtlandet/BoddEllerArbeidetUtlandet.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/boddEllerArbeidetUtlandet/BoddEllerArbeidetUtlandetVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/barnepensjon/GyldigFramsattVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/omstillingsstoenad/GyldigFramsattVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/kommerBarnetTilgode/KommerBarnetTilGodeVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/kommerBarnetTilgode/OversiktKommerBarnetTilgode.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/utlandstilknytning/Utlandstilknytning.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/utlandstilknytning/UtlandstilknytningVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/Virkningstidspunkt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/vurderingsboks/VurderingsboksWrapper.tsx

Kun vis avbryt hvis det allerede er en vurdering der for de felter som er obligatoriske. 
Det vil se slik ut der `virkningstidspunkt` er obligatorisk, men `opphør fra og med` er valgfri
Eksempel på 3 ulike states fra vilkårsvurdering (Vurdert, redigerer, opprettet første vurdering):

EY-4601: Fjern legg til vurdering for de vurderinger som er obligatoriske 

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/soeskenjustering/Soeskenjustering.tsx

tror dette fikser https://nav-it.slack.com/archives/C043C5ZGW5T/p1730281224511989
ting tryner når sb trykker "legg til periode" i beregningsgrunnlaget for søskenjustering

Ikke bruk tomt søskenarray men opprett fra grunnlagsdata

---

apps/etterlatte-beregning/src/main/kotlin/Application.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingTidligAlderspensjonService.kt
apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTidligAlderspensjonServiceTest.kt

Hvis det er førstegangsbehandling skal den sjekke om det er overstyrt grunnet alderspensjon inneværende og neste år

Trekker ut logikk for opprette oppgave hvis alderspensjon i egen service og justerer logikk

---

apps/etterlatte-hendelser-samordning/src/main/kotlin/no/nav/etterlatte/samordning/SamordningHendelseHandler.kt

Det har noen ganger blitt mottatt samordnings hendelser som mangler informasjon, dette har ikke blitt fanget opp.

Bedre logger for samordning hendelser

---

apps/etterlatte-behandling/src/main/kotlin/behandling/GrunnlagServiceImpl.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/inntektsjustering/AarligInntektsjusteringJobbService.kt
apps/etterlatte-behandling/src/test/kotlin/inntektsjustering/AarligInntektsjusteringJobbServiceTest.kt

- Sjekke om personopplysninger har endret seg i pdl for å sende til manuell
- Omstrukturert metode/logikk for å returnere en begrunnelse som kan lagres i kjøringstabell

Inntektsjusteringsjobb sjekke personopplysninger pdl

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/handlinger/BrevUtgaar.tsx

I enkelte tilfeller er det aktuelt å journalføre brevet _før_ det markeres som utgått. 
Eksempelvis vedtaksbrev som aldri ble sendt ut. Brevet må journalføres, men vi unngår å sende det ettersom det har gått så lang tid.

Støtte journalføring av brev som utgår

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt

Saker som har stått TIL_SAMORDNING men som kan løses opp og dytte videre til utbetaling

flere saker som kan løse opp samordning

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/RedigerMottakerModal.tsx
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/Brev.kt

EY-4689 Fikse skjema for utenlandsk adresse (brevmottaker)

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt

På grunn av måten utledning av all brevdata gjøres gjemte det seg dypt nede i en fil at man ikke kan lese revurderingårsak uten et vedtak -- men det er ikke garantert at man har opprettet i flyten når man sender varselbrevet. følgefeil blir at vi bruker feil data til brevet i ferdigstillingen.
Siden revurderingårsak uansett er kjent for disse bare flytter jeg utledningen ut av "forenklet" vedtak.

Fix feil utledning i varselsbrev: Bare henter revurderingsaarsak fra behandlingen

---

.github/dependabot.yml

fjerne config som ikke fungerer som tiltenkt

Update dependabot.yml fjerne automerge

---

apps/etterlatte-api/.nais/dev-api.yaml
apps/etterlatte-api/.nais/prod-api.yaml
apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/samordning/sak/BehandlingSakRoutes.kt

Her er det sikkert en smartere måte å fikse dette på, så alle tips er velkommene :D

EY-4663 - Åpne opp for å la selvbetjening sjekke om bruker har sak

---

apps/etterlatte-behandling/src/main/kotlin/common/klienter/PdlTjenesterKlient.kt
apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt
apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlKlient.kt
apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt
apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonRoute.kt
apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonService.kt
apps/etterlatte-pdltjenester/src/test/kotlin/pdl/PdlKlientTest.kt
libs/saksbehandling-common/src/main/kotlin/person/HentFolkeregisterIdenterForAktoerIdBolkRequest.kt

Ikke lenger i bruk etter Gosys la til fnr. i oppgavene sine.

Opprydding/forarbeid ifm. EY-4561

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/AutomatiskRevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/sjekkliste/SjekklisteDao.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakendringerDao.kt
apps/etterlatte-hendelser-pdl/src/main/kotlin/hendelserpdl/PersonHendelseFordeler.kt

Bytte ut noen exceptions med `InternfeilException` og fjerne noen unødvendige `.also()`

Opprydding i diverse smårusk

---

apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/Vurderinger.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/aktivitetsgrad/AktivitetsgradIOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/aktivitetsgrad/LeggTilNyVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/aktivitetsgrad/VisAktivitetsgrad.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/aktivitetsgrad/VurderingAktivitetsgradForm.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/unntak/UnntakIOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/unntak/VisUnntak.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Aktivitetsplikt.ts

EY-4718 Fikse nedtrekk lesevisning + endre på design etter nye skisser

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingServiceTest.kt

En liten bug som hadde sneket seg inn ved mapping av `regelverk` fra beregningsperioder til avkortingsperioder.

FAGSYSTEM-355734: Fikser problem ved mapping av regelverk for avkortingsperiode

---

apps/etterlatte-behandling/src/main/kotlin/vilkaarsvurdering/AldersovergangRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/vilkaarsvurdering/service/AldersovergangService.kt
apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt
apps/etterlatte-behandling/src/test/kotlin/tilgangsstyring/TilgangsstyringTest.kt
apps/etterlatte-behandling/src/test/kotlin/vilkaarsvurdering/AldersovergangRoutesTest.kt
apps/etterlatte-behandling/src/test/kotlin/vilkaarsvurdering/AldersovergangServiceTest.kt
libs/etterlatte-ktor/src/testFixtures/kotlin/no/nav/etterlatte/ktor/RunServer.kt

* Og fiks standard oppsett for mocking av routes hvis man bruker runServer uten module i behandling

Legg inn aldersovergangservicetetss

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktAktivitetsgradDao.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRepository.kt
apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/RegulerOverstyrt.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/Journalpost.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevKodeMapperVedtak.kt
apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/GrunnlagService.kt
apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/soeknad/OpprettSoeknad.kt
apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/avstemming/vedtak/Vedtaksverifiserer.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakOgBeregningSammenligner.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakOgBeregningSammenlignerTest.kt
libs/saksbehandling-common/src/main/kotlin/feilhaandtering/Utils.kt

Fjerner alle requires i en annen da prene her skal være små på fiksedagen

EY-4669 Fjerne alle checks i appen

---

apps/etterlatte-saksbehandling-ui/client/src/components/klage/formkrav/KlageFormkravRedigering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurderingForms.tsx

Satt de til å være maks 42.5rem i bredde siden det er anbefalt maks bredde for lesbar tekst.

EY-4620 bredere text areas i klage

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt

Bedre feilmelding / kaster bedre exception ifm overstyring av samordning og henting av data for vedtak

EY-4517: Kaster litt bedre exceptions.

---

apps/etterlatte-brev-api/.nais/dev.yaml
apps/etterlatte-brev-api/.nais/prod.yaml
apps/etterlatte-brev-api/.run/etterlatte-brev-api.dev-gcp.run.xml
apps/etterlatte-brev-api/src/main/resources/application.conf

Må få inn config (i hovedsak outbound) for at det skal fungere med testing lokalt

EY-4481 Legge til config for å koble til dokdistkanal

---

README.md
apps/etterlatte-api/README.md
apps/etterlatte-behandling/README.md
apps/etterlatte-behandling/src/main/kotlin/behandling/sjekkliste/Sjekkliste.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/AdresseService.kt
apps/etterlatte-brev-api/src/main/resources/notat/nordisk_vedlegg.json
apps/etterlatte-hendelser-pdl/README.md
apps/etterlatte-hendelser-pdl/src/main/avro/no/nav/person/identhendelse/v1/common/adresse/Adresse.avdl

Endret alle steder det er synlig, ligger fortsatt noe igjen i variabelnavn og tester

Endre NAV til Nav

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallVisning.tsx

Endringer i brevbaker som hører til: https://github.com/navikt/pensjonsbrev/pull/1044

EY-4611: Ny tekst for valg av brevutfall

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/notat/NotatOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/notat/NotatVisningModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/notat/SlettNotatModal.tsx

Samme som ble gjort på brev-oversikten

EY-4484 Åpne notat i eget vindu

---

apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/aktivitetsgrad/VurderingAktivitetsgradForm.tsx

bare for å gjøre det eksplisitt at det ikke påvirker brevet og kun er en intern vurdering

Ekstra presisering ved skjønnsmessig vurdering

---

apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/aktivitetsgrad/VurderingAktivitetsgradForm.tsx

Ekstra beskrivelse på valg for skjønnsmessig vurdering

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/RedigerbartVedleggHenter.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/AarligInntektsjusteringBrev.kt

Skal ikke være vedlegg for dette brevet

Unngår vedlegg til årlig inntektsjustering 

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt

Fjerner jobb for omregning av klassifikasjonskode

---

apps/etterlatte-tidshendelser/.nais/prod.yaml

Vi vil av og til kjøre jobber senere

Åpner for senere jobbkjøring

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakLesDao.kt

Hvis vi kun har lagt inn en feila kjøring -- ikke ekskluder den fra å bli prøvd på nytt

Fikser siste kjøring har feila ble sjekket feil hvis vi kun har feila

---

apps/etterlatte-behandling/src/main/kotlin/inntektsjustering/AarligInntektsjusteringJobbService.kt
apps/etterlatte-behandling/src/test/kotlin/inntektsjustering/AarligInntektsjusteringJobbServiceTest.kt

Oppgave for ny manuell revurdering mangler merknad med årsak til manuell behandling

EY-4774 revurdering mangler begrunnelse med årsak

---

apps/etterlatte-behandling/src/main/kotlin/inntektsjustering/AarligInntektsjusteringJobbService.kt
apps/etterlatte-behandling/src/test/kotlin/inntektsjustering/AarligInntektsjusteringJobbServiceTest.kt

Slå opp på søker og ikke innsender

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx

Når saksbehandler revurderer ny søknad og avslår, skal det komme et eget steg for trygdetid dersom dette er en sak med utlandsopphold.

FAGSYSTEM-351287: Legger til trygdetidsteg ved avslag ny søknad

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/MottattInntektsjusteringModal.tsx

Lenke til bruker i modal for mottat inntektsjustering

---

apps/etterlatte-api/.nais/dev-api.yaml
apps/etterlatte-api/.nais/prod-api.yaml

Trengs for: https://github.com/navikt/pensjon-etterlatte/pull/1623

EY-4739: La innsendt-soeknad hente fra etterlatte api

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt

alle sakene er sendt til utbetaling, og problemet med samordning skal være løst

fjerne samordning workaround

---

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/config/ApplicationContext.kt

Datoene skal være som følger:
Dato
03.01.2025
30.01.2025
27.02.2025
27.03.2025
29.04.2025
23.05.2025
27.06.2025
30.07.2025
01.09.2025
29.09.2025
30.10.2025
21.11.2025

Legger inn datoer for kjøreplan konsistensavstemming 2025

---

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/inntektsjustering/selvbetjening/InntektsjusteringSelvbetjeningService.kt
apps/etterlatte-behandling/src/test/kotlin/inntektsjustering/selvbetjening/InntektsjusteringSelvbetjeningServiceTest.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/inntektsjustering/AarligInntektsjusteringRequest.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/inntektsjustering/InntektsjusteringRequest.kt

Når inntektsjustering er meldt inn via selvbetjening må vi avgjøre om denne skal behandles automatisk eller manuelt av saksbehandler

EY-4769 sjekk for automatisk behandling av inntektsjustering fra selvbetjening

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EtterlatteBrev.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonBeregning.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelse.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/BarnepensjonBeregningTest.kt

Tillater å opprette brev uten kjent avdød.

EY-3360: Endrer modell mot brev til å tillate ukjent avdød

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/avtale/AvtaleService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/config/ApplicationContext.kt
apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidServiceIntegrationTest.kt
apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidServiceTest.kt

Noen som kan trygdetid må kontrollere at jeg ikke er helt på bærtur her

EY-4790 Kopiere avtale med trygdetid, hvis finnes

---

apps/etterlatte-api/README.md

Vise i docs at fnr skal i body ikke i header

EY-4809 Oppdatere docs for etterlatte-api

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
apps/etterlatte-behandling/src/main/kotlin/inntektsjustering/selvbetjening/InntektsjusteringSelvbetjeningService.kt
apps/etterlatte-behandling/src/test/kotlin/inntektsjustering/selvbetjening/InntektsjusteringSelvbetjeningServiceTest.kt

7 dagers frist for inntektsopplysninger, fjerne vedtakType prefix for inntekts merknad

EY-4773 Mindre rettinger for oppgave knytt til inntekt

---

apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/VedtaksvurderingKlient.kt

Det ligger også som x_user på de requestene det gjelder men vanskelig å finne de i loggene

logg orgnr som kaller vedtak via etterlatte-api

---

apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/VedtaksvurderingKlient.kt
apps/etterlatte-api/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/VedtakvurderingKlientTest.kt

ref feil her https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/6563

Legg til tester for vedtaksklient i api

---

apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/inntektsjustering/InntektsjusteringRiver.kt
apps/etterlatte-gyldig-soeknad/src/test/kotlin/no/nav/etterlatte/inntektsjustering/InntektsjusteringRiverTest.kt
apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/OmregningsHendelserBehandlingRiver.kt
apps/etterlatte-testdata/src/main/resources/templates/egendefinert/ny-melding.hbs
gradle/libs.versions.toml
libs/etterlatte-inntektsjustering-model/src/main/kotlin/no.nav.etterlatte.libs.inntektsjustering/MottattInntektsjustering.kt

Det er avvik i tidspunkt for dokument inntektsendring og vedtaksbrev

EY-4773 rett tidspunkt for mottatt inntektsendring

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/InnholdTilRedigerbartBrevHenter.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/RedigerbartVedleggHenter.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Behandling.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevTest.kt

Automatisk behandling av inntektsendring trenger ikke redigerbar del for beregning i vedlegg

EY-4773 ikke legge til redigerbar del i brev for beregning hvis behandling er automatisk

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveRoute.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/SettPaaVentModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/frist/SettNyOppgaveFristModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/tildeling/VelgSaksbehandler.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/gosys.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts

Fjerner duplikatkode og ting som ikke lenger er aktuelt for vårt eget oppgave-api

Fjerner unødvendig kode fra oppgave

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/barnepensjon/Foreldreansvar.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/gyldigFramsattSoeknad/barnepensjon/GyldigFramsattBarnepensjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/kommerBarnetTilgode/OversiktKommerBarnetTilgode.tsx

og vis frem hen som har foreldreansvar hvis det ikke er innsender eller gjenlevende.
Hvis innsender ikke er gjenlevende, men har foreldreansvar
Hvis den som har foreldreansvar ikke er gjenlevende eller innsender. Mulig man skulle skrevet noe her om det?

EY-4399: Vis frem innsenders adresse hvis hen har foreldreansvar 

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDaoMedEndringssporing.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/tildeling/VelgSaksbehandler.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/amplitude.ts
apps/etterlatte-saksbehandling-ui/docker-compose.yml

Sjekker om det finnes flere oppgaver med samme `gruppeId` og `type`. 
Hvis det finnes flere enn 1 oppgave vil saksbehandler få opp modal hvor de kan velge flere oppgaver.

Ey 4597 vise alle oppgaver med gruppeid

---

apps/etterlatte-saksbehandling-ui/server/src/routers/githubRouter.ts

Vi får hyppig `rate limit` error fra Github siden vi ikke kaller på API-et med innlogget bruker. Får p.t. rundt 500 warnings om dagen... Forsøker å øke varighet på cache for å se om det løser litt opp i problemet.

Cache respons lenger + bedre feilhåndtering

---

.github/workflows/app-etterlatte-statistikk.yaml
apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt

Fiks i statistikk etter endring på tilbakekreving

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt

denne logger fnr så må fjernes

ikke logg hele oppgaven

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakLesDao.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakSkrivDaoTest.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/OmstillingsstoenadService.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/klient/BehandlingKlient.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/OmstillingsstoenadAktivitetspliktTest.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/OmstillingsstoenadDoedsdatoTest.kt

når man henter saker for dødsdato i forbindelse med aktivitetsplikt

EY-4763 Henter også relevante tidligere familiepleier-saker

---

libs/etterlatte-inntektsjustering-model/README.md
libs/etterlatte-omregning-model/README.md

Dokumentasjon inntektsjustering og omregningsflyt

---

.github/workflows/.build-and-deploy.yaml
.github/workflows/.deploy-main-prod.yaml
.github/workflows/.deploy-main.yaml
.github/workflows/app-etterlatte-api.yaml
.github/workflows/app-etterlatte-saksbehandling-ui.yaml

se https://nav-it.slack.com/archives/C5KUST8N6/p1734433204824029

Skru på tracing i deploys for å se hvorfor bygg evt tar lang tid og feiler

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx

Skal ikke trenge å legge til inntekt neste år hvis det ikke er noen løpende måneder i 2025

Enda en midlertidig håndtering av inntekt to år ved dette årskifte i påvente av EY-4632

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/utils.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
apps/etterlatte-saksbehandling-ui/client/src/useUnleash.ts
apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/prod.yaml
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/PesysKlient.kt
apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidServiceTest.kt
libs/etterlatte-ktor/src/main/kotlin/ktor/ktorobo/DownstreamResourceClient.kt
libs/etterlatte-ktor/src/main/kotlin/ktor/ktorobo/Models.kt

OBsobs kommer nytt datoformat her https://github.com/navikt/pensjon-pen/pull/14592
se eks:
https://github.com/navikt/pensjon-pen/pull/14606#issuecomment-2554226220

EY-4348 Hent trygdetid fra pesys

---

apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoDao.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoDaoTest.kt
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/BrevutfallDto.kt

Klarer ikke finne en grunn til at den skal være optional

fjerne optional behandlingsId fra brevutfallDto

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/GosysOppgaveliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/gosys/GosysOppgaveRow.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/gosys/GosysOppgaver.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/gosys/GosysOppgaverTable.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/ForenkletGosysOppgaverTable.tsx

Per nå er lokale endringer borte om man navigerer i lista siden man bruker lokalstate som unmountes. Mens backend blir da i usync med front.

EY-4840 Faktisk oppdatere staten til gosys oppgaven ved tildeling

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottakerPanel.tsx

Gir beskjed til saksbehandler om å sjekke om det er verge ved tilbakekreving eller klage-behandlinger. Disse kan ikke gjøres på tilsvarende måte som en vanlig behandling da grunnlaget ikke er registrert på disse behandlingene.

EY-4884: Legger på varsel om å sjekke verge for klage og tilbakekreving

---

apps/etterlatte-saksbehandling-ui/client/src/components/klage/formkrav/KlageFormkravRedigering.tsx

EY-4728: Legg til hjelpetekster for klage

---

apps/etterlatte-hendelser-ufoere/.nais/prod.yaml

Bruk prod pool i prod 

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
apps/etterlatte-behandling/src/main/resources/db/prod/V209__fjerner_kravdato_viderefoert_opphoer.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/ViderefoertOpphoerTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/viderefoere-opphoer/ViderefoereOpphoerVurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts

Feltet `kravdato` er ikke i bruk, ser ingen grunn til at vi skal ha med dette videre.

Fjerner ubrukt felt kravdato fra videreført opphør

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/barnepensjon/AnnenForelderSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/grunnlag.ts

EY-4381: Tilpasser til bare ett valg for annen forelder.

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/utils.ts

- Gjør det tydeligere for saksbehandler hva som må gjøres. 
- Endrer fristen for denne hendelsestypen til 24 timer.

Forbedrer tekst og endrer frist for uføretrygd-hendelser

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/Hendelser.tsx

Blitt enig med fag om å fjerne denne advarselen.

Fjerner advarsel i hendelser som ble lagt på etter regulering

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt

Mangler en sjekk for varig unntak før opprettelse av revurdering

EY-4910 Legger på sjekk om man har varig unntak ved oppfyller aktivitet

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/BehandlingSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/utils/amplitude.ts

Vi ønsker å få et bilde på hvor mye historikk brukes i behandlinger

EY-4915: Legger på tracking av klikk på Historikk i behandling

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/AutomatiskBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakEtterbetaling.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/config/ApplicationContext.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/BeregningKlient.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/SamordningsKlient.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingServiceTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakEtterbetalingTest.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/SamordningsKlientTest.kt

Nytt forsøk på utregning av etterbetaling over 0.5G. 
Utregningen er justert til å summere alle månedene det blir etterbetaling.

EY-4767 Etterbetaling over 0.5G skal gi utvidet frist (SAM)

---

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/resources/db/dev/V214__sette_doedshendelser_ferdig.sql

* samt sette alle nye saker til ferdig i dev da pdl er bugga

Forsinke dødsmeldinger i dev og lokalt ved oppstart og kjøring

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Resultat.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/utils.ts

https://github.com/user-attachments/assets/c2fe3860-7fda-4436-a82e-fd1f048d8527

Ikke reset vurdering ved sletting

---

apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/ApplicationContext.kt
apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/behandling/sak/BehandlingSakRoutes.kt
apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/behandling/sak/BehandlingService.kt
apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/behandling/sak/VedtaksvurderingKlientSak.kt
apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/behandling/sak/VedtaksvurderingSakKlient.kt

Mulig det er en bedre løsning å slå sammen VedtaksvurderingKlient for etterlatte-api,  men det var en del som var samordning spesifikt så droppet det i denne omgang.

EY-4898: Sjekk om bruker har løpende sak

---

apps/etterlatte-brev-api/src/main/resources/db/prod/V29__fjerne_status_distribuert.sql
apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/BrevOversikt.tsx

Mer info her: https://jira.adeo.no/browse/EY-4955

EY-4955 Gjøre det mulig å distribuere feilede brev på nytt

---

apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V37__endre_revurderingsaarsak_sluttbehandling_utland.sql

ref feilmelding 
etterlatte-vedtaksvurdering:
No enum constant no.nav.etterlatte.libs.common.behandling.Revurderingaarsak.SLUTTBEHANDLING_UTLAND

Rename revurderingsaarsak SLUTTBEHANDLING_UTLAND -> SLUTTBEHANDLING

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidServiceTest.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/grunnlag/GrunnlagVersjonValidering.kt

Legger inn logging for å kunne vite mer nesten gang dette skjer.

Fagsystem-364802: kan ikke kopiere trygdetid

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/OmstillingsstoenadInnvilgelseTest.kt

Vi skal sjekke om saken er **innvilget** mindre en 4 mnd etter dødsfall

EY-4960 rette feil logikk utlede innvilgetMindreEnnFireMndEtterDoedsfall

---

apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/rivers/GrunnlagHendelserRiver.kt
apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/itest/RapidTest.kt
libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/StandardKeys.kt

Fjerner nøkkel `@behov` som ikke lenger er i bruk

fjerne ubrukt river-kode i grunnlag (EY-4942)

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt

Forrige fix var på feil sletting, nå skal det være riktig

Endret til riktig kall parameter for slett hendelse og aktivitet etter slurvete fix

---

apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Grunnlagsendringshendelse.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/ManuellRevurderingServiceTest.kt

Legger inn revurderingsårask i merknad hvis vi ikke har noe annen beskrivelse

Revurderingsaarsak i merknad

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt

Dette er ikke noe problem for statistikken sin del siden vi produserer kun statistikk på de som har løpende ytelse

Fjerner error-logging hvis vi ikke har en behandling til aktivitetspliktoppdatering

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt

Sleng på ekstra test for vedtakdao

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationContext.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadAktivitetspliktVarsel.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/BrevDataMapperRedigerbartUtfallVarsel.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevHelper.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevService.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevHelperTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevTest.kt

Tilsvarende endring i pensjonsbrev
https://github.com/navikt/pensjonsbrev/pull/1211

EY-4954 utlede om 6mnd eller 12 mnd varsel stans om ikke akt.plikt 

---

apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/vedtak/VedtaksvurderingKlient.kt
apps/etterlatte-api/src/main/resources/vedtakSwaggerV1.yaml
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt

* Vedtak klient i etterlatte-api hadde feil url og manglet content negotiation
* Bug under uthenting av vedtak i VedtakRepo for to saktyper 
* Legger til auth med bearer token i etterlatte-api swagger for vedtak

Fikse mangler med vedtak api

---

apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/Application.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/AppContext.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/JobbPoller.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/JobbScheduler.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/aarliginntektsjustering/AarligInntektsjusteringService.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/aldersovergang/AldersovergangerService.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/hendelser/Hendelse.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/hendelser/HendelseDao.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/hendelser/HendelsePoller.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/hendelser/HendelsePublisher.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/hendelser/HendelseRiver.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/omstillingsstoenad/OmstillingsstoenadService.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/regulering/ReguleringService.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/AldersovergangerIntegrationTest.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/HendelsePollerIntegrationTest.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/HendelseRiverTest.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/JobbPollerIntegrationTest.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/JobbTestdata.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/JobberIntegrationTestScheduler.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/OmstillingsstoenadAktivitetspliktTest.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/OmstillingsstoenadDoedsdatoTest.kt

Var litt vanskelig å forstå hvordan ting henger sammen, så gjorde noen forbedringer som gjør det lettere for nestemann.
- Har endret på noen navn, og la til noen kommentarer. 
- Flyttet file til egne pakker, det for å enklere se hva som håndterer tidshendelser

Litt endringer for bedre forståelse av tidshendelser

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/YrkesskadeTrygdetid.tsx

Fikser feilen for å unngå støy i console

Checkbox om yrkesskade ga warning ved utvikling. 

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BeregneOMS.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/utils/amplitude.ts

Hvis det er førstegangsbehandling som blir innvilget så ligger den på beregningsteget
Ved avslag så ligger den på trygdetid

EY-4968: Vis tilbakemelding for utland

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktOppgaveService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/vurdering/AktivitetspliktUnntakDao.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktOppgaveServiceTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/typer.ts
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/OppfoelgingsOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/tags/OppgavetypeTag.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/oppgave.ts
libs/etterlatte-oppgave-model/src/main/kotlin/oppgave/OppgaveIntern.kt

Når du vurderer en aktivitetspliktoppgave. Det skal også komme hvis du ferdigstiller en førstegangsbehandling / revurdering.
Ligger bak en featuretoggle, så funksjonaliteten kan gå ut i kun dev.

EY-4900 Legger inn oppfølgingsoppgave hvis unntak uten frist

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
apps/etterlatte-saksbehandling-ui/client/src/utils/amplitude.ts

Legg inn tilbakemelding i informasjon fra bruker revurdering

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt

meldt inn her [FAGSYSTEM-366901](https://jira.adeo.no/browse/FAGSYSTEM-366901)

Opprett grunnlag krever systembruker fordi behandlingen ikke finnes eller revurderingen pga man er i en intransaction

---

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt

Siden det ikke er støttet bruker vil heller localdate -> tidspunkt

EY-4900 Fikser feil med å legge til måneder på tidspunkt

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperRedigerbartUtfallVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/AarligInntektsjusteringBrev.kt

Se tilsvarende endring i pensjonsbrev https://github.com/navikt/pensjonsbrev/pull/1230

EY-4823 forenkle begrunnelse for vedtak - inntektsendring

---

apps/etterlatte-behandling/src/main/kotlin/behandling/GrunnlagServiceImpl.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt

Blir alltid hardkodasystembruker.opprettgrunnlag, men den trenger vi bare til auth.
Alle som bruker denne har en kontekst.

Sett riktig kilde på grunnlagsbehov

---

apps/etterlatte-behandling-kafka/src/main/kotlin/no/nav/etterlatte/AppBuilder.kt

kjapp fiks av klient-bruk for å sikre expectsuccess true

---

apps/etterlatte-behandling-kafka/src/main/kotlin/no/nav/etterlatte/brukerdialog/soeknad/OpprettBehandlingRiver.kt

Inkludere søknad-ID i loggene for å enklere debugge mot `innsendt-soeknad`

Forbedre logger ved mottatt søknad

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/OppfoelgingsOppgaveModal.tsx

EY-4899 legge til hyperlenke til saksoversikt i oppgavetype oppfølging

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/ForenkletOppgaverTable.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/OpprettOppfoelgingsoppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/SakOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/oppgave.ts
apps/etterlatte-saksbehandling-ui/client/src/useUnleash.ts
apps/etterlatte-saksbehandling-ui/client/src/utils/amplitude.ts

Har lagt det bak en toggle og lagt på amplitude-tracking på bruk

EY-4971 Mulighet for å opprette en oppfølgingsoppgave i sak

---

apps/etterlatte-behandling/src/main/kotlin/sak/KomplettSak.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakendringerDao.kt

Midlertidig fiks for å stoppe crashloop i produksjon

Hotfix: Tillate sak opprettet tidspunkt NULL

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktOppgaveService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktOppgaveServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingIntegrationTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/brev/FerdigstillAktivitetspliktOppgaveModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/aktivitetsplikt.ts

Passer på å opprette oppgaver også ved behandlinger og ferdigstilling av oppgaver uten brevutsendelse

EY-4900 opprett oppgave ogsaa uten brev

---

apps/etterlatte-behandling/src/main/resources/db/prod/V225__aks_sette_oppgave_ferdig.sql

* Sb har distribuert brevet via brevoversikten ikke via aktivitetspliktssiden

FAGSYSTEM-368361 Sette aktivitetsplikt oppgave ferdigstilt

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/SoeknadInformasjon.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/Soeknadoversikt.tsx

Er litt vanskelig å vite om man skal sjekke på innsender, søker, avdød osv. Fint om noen tar en dobbelsjekk

EY-4988 forbedret visning av søknadsinformasjon

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/Journalpost.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafKlient.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreBruker.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Journalpost.ts

Ref feil i produksjon
```
En feil har oppstått ved deserialisering.
```

legge til typer som mangler i brukerIdType

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/SoeknadInformasjon.tsx

Noen som vet hvordan dette vil fungere hvis innsender er saksbehandler?

Viser navn på innsender i søknadsinformasjon.tsx istedenfor koden for det

---

apps/etterlatte-behandling-kafka/src/main/kotlin/no/nav/etterlatte/brukerdialog/omsmeldinnendring/OmsMeldtInnEndringRiver.kt
apps/etterlatte-behandling-kafka/src/test/kotlin/no/nav/etterlatte/brukerdialog/omsendring/OmsMeldtInnEndringRiverTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/MeldtInnEndringOppgaveModal.tsx

Inneholder:
- Revurderingsårsaker i kronologisk rekkefølge
- Navigering inn i sak før man kan se meld inn endring oppgave
- Bedre merknad på meld inn endring oppgave

Forbedringer i behandling av meldt inn endring

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperRedigerbartUtfallVedtak.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt

Se tilsvarende endring i pensjonsbrev 
https://github.com/navikt/pensjonsbrev/pull/1293

EY-3821 legge til datoVedtakOmgjoering i oms innvilgelse utfall

---

apps/etterlatte-behandling/src/main/kotlin/grunnlag/SakGrunnlagRoutes.kt

Feilplassert curly gjorde enkelte endepunkter utilgjengelige.

Hotfix: Legge tilbake curly som forsvant

---

apps/etterlatte-trygdetid/.nais/dev.yaml
apps/etterlatte-trygdetid/.nais/prod.yaml
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/GrunnlagKlient.kt
apps/etterlatte-trygdetid/src/main/resources/application.conf

Gå mot identisk route som nå er i `etterlatte-behandling`
Avhenger av https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/7046

EY-4942 Koble trygdetid til grunnlag via behandling

---

apps/etterlatte-behandling/.nais/dev.yaml
apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-brev-kafka/.nais/dev.yaml
apps/etterlatte-brev-kafka/.nais/prod.yaml
apps/etterlatte-brev-kafka/src/main/kotlin/no/nav/etterlatte/Application.kt
apps/etterlatte-brev-kafka/src/main/kotlin/no/nav/etterlatte/klienter/GrunnlagKlient.kt
apps/etterlatte-brev-kafka/src/main/resources/application.conf

Gå mot identisk route som nå er i etterlatte-behandling
Avhenger av https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/7046

EY-4942 Koble brev-kafka til grunnlag via behandling

---

apps/etterlatte-beregning/.nais/dev.yaml
apps/etterlatte-beregning/.nais/prod.yaml
apps/etterlatte-beregning/src/main/kotlin/klienter/GrunnlagKlient.kt
apps/etterlatte-beregning/src/main/resources/application.conf

Gå mot identisk route som nå er i `etterlatte-behandling`
Avhenger av #7046

EY-4942 Koble beregning til grunnlag via behandling

---

apps/etterlatte-saksbehandling-ui/.nais/dev.yaml
apps/etterlatte-saksbehandling-ui/.nais/prod.yaml
apps/etterlatte-saksbehandling-ui/server/src/config/config.ts

Selve påkoblingen i `index.ts` ble gjort i https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/7046

EY-4942 Fjerne rester av kobling mot grunnlag fra UI

---

apps/etterlatte-tidshendelser/.nais/dev.yaml
apps/etterlatte-tidshendelser/.nais/prod.yaml
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/AppContext.kt
apps/etterlatte-tidshendelser/src/main/resources/application.conf

Gå mot identisk route som nå er i `etterlatte-behandling`
Avhenger av https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/7046

EY-4942 Koble tidshendelser til grunnlag via behandling

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/types.ts

For å bedre forstå behovet / omfanget i endringsønsket i EY-5007

EY-5007 Legger til returårsak "Saksbehandler ba om retur"

---

apps/etterlatte-behandling/src/main/kotlin/brev/BrevService.kt
apps/etterlatte-behandling/src/main/kotlin/brev/TilbakekrevingBrevService.kt

Frontend-koden krever det jo. Er dette kanskje ikke tatt i bruk i prod ennå?

Returnerer brevet ved oppretting av vedtaksbrev for tilbakekreving

---

apps/etterlatte-klage/src/main/kotlin/no/nav/etterlatte/klage/modell/KlageOversendelse.kt

* noen grunn til at vi ikke kan legge inn alle her?

legg til BEHANDLING_ETTER_TRYGDERETTEN_OPPHEVET i kabalsaktype

---

apps/etterlatte-grunnlag/src/main/resources/db/migration/V29__fjern_backup.sql

ser ut som migrering av innsender i persongalleriet gikk ok, kan fjerne backup.

Fjern tmp backup tabell

---

apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/egendefinert/EgendefinertMeldingFeature.kt

fikser https://github.com/navikt/pensjon-etterlatte-saksbehandling/security/code-scanning/127

Fjerner ubrukt variabel

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Grunnlagopplysninger.tsx

Viser fødselsnummer til avdød i trygdetidsgrunnlag

---

libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/model/tilbakekreving/TilbakekrevingBrevData.kt

Fører til litt uheldige konsekvenser i brevene.

Feil referanser tilbakekreving model

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/Familieforhold.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/TabellOverAvdoedesBarn.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/TabellOverGjenlevende.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts

FAGSYSTEM-370288 Fikser visningen av hvem forelder er for barnepensjon

---

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt

Krever at tabeller i grunnlagdatabase er migrert fra grunnlag til behandling.

EY-4942: Fjerne bruk av grunnlag proxy i dev

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/typer.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/tags/OppgavetypeTag.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/oppgave.ts
libs/etterlatte-oppgave-model/src/main/kotlin/oppgave/OppgaveIntern.kt

Slang også på en toggle også så vi ikke får noe rart i produksjon før vi vil ha det enabled

EY-5043 Oppretter etteroppgjørsoppgave når etteroppgjør opprettes

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingValider.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingValiderTest.kt

Det antas at det er gjenåpning hvis til og med på siste inntekt er satt

Ved en gjenåpning etter opphør må det være mulig å legge til inntekt

---

apps/etterlatte-behandling/src/main/resources/db/prod/V240__sette_ferdigstilt_feiloppretta.sql

sb oppretta feil oppgave og vi støtter ikke å avbryte denne enda. Legger inn endringsønske

Sett ferdigstilt på feiloppretta oppgave

---

apps/etterlatte-api/.nais/dev-api.yaml
apps/etterlatte-api/.nais/dev.yaml

ref https://nav-it.slack.com/archives/C01C7Q1NK8S/p1740578175999339?thread_ts=1739274441.611669&cid=C01C7Q1NK8S

Gå mot tjenestepensjon q2 ikke q1 da det er feil

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt

Den andre fiksen feiler, denne bør fungere

FAGSYSTEM-371203 fiks for brev som allerede er slettet

---

apps/etterlatte-behandling/src/main/resources/db/prod/V246__fullfoere_feilet_tilbakekreving.sql

Må også fikse statistikk, kommer i egen PR

FAGSYSTEM-372475: Fikser opp i tilstand etter feilet tilbakekreving

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/sjekkadressebeskyttelse/SjekkAdressebeskyttelseJob.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/sjekkadressebeskyttelse/SjekkAdressebeskyttelseJobDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/sjekkadressebeskyttelse/SjekkAdressebeskyttelseJobService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt

Denne jobben henter ned alle saker, og sjekker adressebeskyttelse mot PDL for hver enkelt. 
I første runde sjekke 10 stk for verifikasjon.

EY-5077: Jobb for å sjekke alle saker i Gjenny for riktig adressebeskyttelse

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/BehandlingSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/NotatPanel.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/notat.ts

Første runde i forbedringene av notat, som er at man blir sendt til dokumentoversikten istedenfor at notat modalen tar hele behandlings skjermen

EY-5040 - forbedringer i notat, part 1

---

apps/etterlatte-brev-api/src/main/resources/db/prod/V33__fjerne_status_ferdigstilt.sql
apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V39__fikser_tilbakekreving_vedtak.sql

Må rulle tilbake status i vedtak og status i brev.

Fikser tilbakekreving som feilet pga ugyldig vedtak

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BrevApiKlient.kt
apps/etterlatte-behandling/src/main/kotlin/brev/BrevKlientImpl.kt
apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/BeregningService.kt
apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/BrevService.kt
apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/TrygdetidService.kt
libs/etterlatte-ktor/src/main/kotlin/ktor/ktorobo/DownstreamResourceClient.kt

Legger til samme timeout-config på den andre brevklienten. Øker til 30 sek.

Øker timeout ved generering av pdf

---

apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/sjekkadressebeskyttelse/SjekkAdressebeskyttelseJobService.kt

Ref https://jira.adeo.no/browse/FAGSYSTEM-373636

Oppdaterer skjerming i sak

---

apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/VedtakKlientImpl.kt

```
java.lang.NumberFormatException: For input string: "{2024}"
```

EY-5086 rette feil i url param for henting av sak med utbetaling for inntektsaar

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/sigrun/SkatteoppgjoerHendelserDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/sigrun/SkatteoppgjoerHendelserService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/VedtakKlientImpl.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt

Får en ```	java.lang.OutOfMemoryError: Java heap space```, prøver å hente kun sakid i stede for hele vedtak.
Rettet og mindre problemer når vi kaller endepunkt i vedtak og behandling

EY-5086 rette problemer med kjøring av hente saker for etteroppgjør 

---

apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/samordning/LoggingPlugins.kt
apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt
apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/VedtaksvurderingSamordningKlient.kt

Her blir orgnr logget i både message og som eget felt i jsonen til elastic. Se https://www.innoq.com/en/blog/2019/05/structured-logging/#structuredarguments

EY-5111 Logge eget felt til elastic for orgnr spørringer

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Resultat.tsx

Teksten var litt off ift hvordan det egentlig gjøres.

FAGSYSTEM-374336: Endrer tekst ved endret virkningstidspunkt i vilkårsvurdering

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/EndreEnhet.tsx

Denne blir vel ugydlig om vi går for å endre fra/til spesialenheter.
Kanskje må vi da sjekke mot pdl/skjerming om endring fra, hvis vi får lov til lokalt system som avviker og alle implikasjonene det kan få.

EY-5076 Infoboks hvis spesialsak ved endre enhet

---

gradle/libs.versions.toml

Bumper da token validator har bumpet sine deps en del

Bump token validator sine bumps

---

apps/etterlatte-behandling/src/main/kotlin/brev/BrevService.kt

Nå som kall proxy'es igjennom behandling blir alle 4xx-feil til interne feil i vår løsning, og de er litt stress å finne igjen.
Setter heller opp slik at vi leser feilene og kaster riktige versjoner av de videre der vi proxy'er direkte.
Fikser at saksbehandling ikke får informasjon i f.eks. https://jira.adeo.no/browse/FAGSYSTEM-375715

Feilmeldinger til saksbehandler fra brev-api

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/EtteroppgjoerService.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/EtteroppgjoerResultatBeregning.kt
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/oversiktOverEtteroppgjoer/OversiktOverEtteroppgjoer.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/oversiktOverEtteroppgjoer/fastsettFaktiskInntekt/FastsettFaktiskInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/oversiktOverEtteroppgjoer/resultatAvForbehandling/ResultatAvForbehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/etteroppgjoer.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Etteroppgjoer.ts
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/EtteroppgjoerReducer.ts
libs/etterlatte-beregning-model/src/main/kotlin/Beregningstall.kt

Beregner og viser resultat av etteroppgjøret

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/EtteroppgjoerService.kt

Mapper også forbehandling

---

apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Grunnlagsendringshendelse.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringsHendelseFilter.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/SamsvarHelper.kt
apps/etterlatte-behandling/src/main/resources/db/dev/V255__slette_hendelsergrunnbeloep.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/ManuellRevurderingServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringsHendelseFilterTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt

Sletter de som er i dev så ikke ting går i stå der, finnes ingen av de i prod.

Fjern grunnbeleop hendelse da den ikke er i bruk

---

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlag/GrunnlagService.kt
apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/AdressebeskyttelseTest.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/ManuellRevurderingServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/grunnlag/GrunnlagServiceTest.kt

Lurt å sjekke tilganger på nytt ved endringer av pg

FAGSYSTEM-376040 Oppdater tilganger ved endringer i pg

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/aktivitetspliktTidslinje/AktivitetPeriode.tsx

som gjør at man ikke får hoppet over datovelger

Tar bort feilmeldingslabel for ikke-obligatorisk felt

---

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt

Ønske fra fag fått muntlig + Mari

Sorter brev til brevoversikt

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerModel.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerBrevService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/BrevData.kt

Og fikser riktig type for sending til brev-api

Retter henting forbehandlinger

---

apps/etterlatte-behandling/src/main/kotlin/behandling/tilgang/TilgangRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/sak/SakTilgangDao.kt
apps/etterlatte-behandling/src/main/kotlin/sak/TilgangServiceSjekker.kt
apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt
apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/TilgangServiceTest.kt

org.postgresql.util.PSQLException: ERROR: invalid input syntax for type uuid: "12575"
https://logs.adeo.no/app/r?l=DISCOVER_APP_LOCATOR&v=8.17.4&lz=N4IgJghgLhBqCWBTA7gZQA6IMYgFynjDxAHYAmRMABgDYBWEgWizrpsYBYqBGMxgDiwBOJgCMaiUULAkIiMjxAAaEFHhQANomIaA9gHMAzo32IAdogBO8LIzCIAZhACuGqErMQAbnqNLfxmb68GYAHgB0EFhYiIbG9k6u7gGMotBYABZ2ji5uyqrwALaIAGJIGmAAchDFxAACasWGMIXo%2BYa6zpYxZW5WhngA2gC6KlAAnpgAsogweMAAvioO5WAlupaF0AP4IAAajADCG5aIGtDwumaMAJIAIvMghMTN1kH56BCWNTugn5aGSgAVUsGkeG3gwTMxAyUCg6EMuAA9EiIDwIOgfNwhNxIvZdOEzLpcPwOBwAMwfaAZTy1XAgVHodBIgDW8DSnnyaUBAAVqcQQAshUsQJZnGZGqVVlMMfMRRANHpkJVdDczPZQngnBpASpadp6QBBJkaeAsiCGABWV0MvlMlnyCqVAAlCPZobhtYCRSs%2BgChqMQABHZxWcaPENh4j6wyfGK4WZQKznOGIAAEhsqdzT5i8WHOcVw6AzWbTWi8Z1wAFFLJYNvlzkFnBBTDpnDELIKxkVEAAlCBBA2gBx1wrEBRkOiMKgcadkAAqvFwHBIuDo%2FHCHDIHAAWvkoL …

Ikke la ugyldige ider gå mot base spørringer

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreSak.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/OppdaterJournalpost.tsx
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/JournalfoeringOppgaveReducer.ts

I de tilfellene der bruker har to aktuelle saker bør man kunne journalføre dokument til den andre saken også.

Tilbyr mulighet til aa journalfoere paa alternativ sak for bruker

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/sigrun/SkatteoppgjoerHendelserDao.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V259__rename_etteroppgjoer_tabeller.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/etteroppgjoer/sigrun/SkatteoppgjoerHendelseDaoTest.kt

Kan være vanskelig å finne riktige tabeller ifm etteroppgjør

Gi databasetabeller konsekvente navn ifm etteroppgjør

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerModel.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/etteroppgjoer/EtteroppgjoerForbehandlingDaoTest.kt

enum i stedet for string for status. Har oppdatert dev-db til å ha riktig status `OPPRETTET` på alle forbehandlinger.

Endrer fra string til enum for forbehandlingstatus

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/SettPaaVent.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/klage/sidemeny/KlageSidemeny.tsx

Legger på mulighet for å kunne sette klage på vent.

EY-5129: Legger på mulighet til å sette klageoppgave på vent

---

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/OppfoelgingsOppgaveModal.tsx

EY-5074 - mulighet for å opprett ny oppfølgingsoppgave ved ferdigstilling

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/SettPaaVentModal.tsx
libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/StatistikkBehandling.kt

Legger på ny årsak for å angi at en sak er i bero.

EY-4445: Legger til ny "På vent"-årsak for sak i bero

---

apps/etterlatte-saksbehandling-ui/client/package.json
apps/etterlatte-saksbehandling-ui/client/src/shared/header/HeaderBanner.tsx
apps/etterlatte-saksbehandling-ui/client/yarn.lock

no-more-roger-mode

---

apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnBarnepensjonServiceTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/EtterlatteBrevTrygdetidTest.kt
apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgetDTOTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/BegrunnelseForTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/EnkelPersonTrygdetid.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRepository.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt
apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
apps/etterlatte-trygdetid/src/main/resources/db/migration/V23__begrunnelse_trygdetid.sql
apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidServiceIntegrationTest.kt
libs/etterlatte-trygdetid-model/src/main/kotlin/Trygdetid.kt

Legger til mulighet for å begrunne trygdetiden.

EY-4370: Begrunnelse for trygdetid (som helhet)

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt

Har feilet noen ganger i prod pga dette.

Legger på manglende transaksjon ved omgjøring

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/uttrekk/AvbrytAldersovergangJob.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/uttrekk/AvbrytAldersovergangJobService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt

Satt opp en jobb som gjør følgende:
- Henter oppgave, setter riktig referanse til behandling
- Avbryter behandling, som også medfører at oppgave avbrytes

EY-5162: Jobb for å avbryte behandlinger og oppgaver som feilet ved aldersovergangskjøring

---

apps/etterlatte-behandling/src/main/resources/db/migration/V263__legge_til_nytt_felt_etteroppgjoer_forbehandling.sql

Pusha branch til dev som opprettet et par ting i databasen. Feiler ved deploy.

Rette flyway script som forsøker å legge til eksisterende felt

---

apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/Etteroppgjoeroversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/oversiktOverEtteroppgjoer/OversiktOverEtteroppgjoer.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/oversiktOverEtteroppgjoer/fastsettFaktiskInntekt/FaktiskInntektSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/oversiktOverEtteroppgjoer/fastsettFaktiskInntekt/FaktiskInntektVisning.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/oversiktOverEtteroppgjoer/fastsettFaktiskInntekt/FastsettFaktiskInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/components/textField/ControlledInntektTextField.tsx

For å gjøre det enklere for saksbehandler å se at de faktisk har lagret endringer under fastsetting av faktisk inntekt:

EY-5163 visningsmodus av faktisk inntekt

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingBrevService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/revurdering/EtteroppgjoerRevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/brev/BrevService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtaksbrev/StrukturertBrevService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/EtteroppgjoerSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/brev/EtteroppgjoerBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/etteroppgjoer.ts
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt

Mindre endringer for å sammenstille flyt for etteroppgjør

EY-5165 etteroppgjør forbehandling og revurdering flyt

---

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerModel.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingBrevService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/revurdering/EtteroppgjoerRevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/brev/BrevService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V264__slette_etteroppgjoer_felt_relatertForbehandlingID.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt
apps/etterlatte-behandling/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingIntegrationTest.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingTidligAlderspensjonService.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/etteroppgjoer/EtteroppgjoerService.kt
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Etteroppgjoer.ts

- Får kun `Collection contains no element matching the predicate.`, rette til bedre feilmelding
- `opprettOppgaveHvisTidligAlderspensjon` feiler for etteroppgjør, den trenger ikke oppgave da den har satt opphør så endrer til å returnere 
- fjerne relatertForbehandlingId da vi finner anne løsning for kopi av forbehandling

la til bedre exception for henting av aarsoppgjoer ifm etteroppgjør

---

apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/EtteroppgjoerForbehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/EtteroppgjoerSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/sidemeny/EtteroppgjoerSidemeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/sidemeny/EtteroppgjoerSidemenyOppsummering.tsx

EY-5168 - etteroppgjoer forbehandling sidemeny

---

apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/JobbScheduler.kt
apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/JobberIntegrationTestScheduler.kt

Så slipper vi å manuelt etterfylle disse

EY-5144 Legger inn automatisk opprettelse av aldersovergang-jobber

---

apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingBrev.tsx

Venter også på at ferdigstillingen går bra før du blir sendt tilbake til saksoversikten

EY-5184 Putter ferdigstilling av etteroppgjør forbehandling i en modal

---

apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/revurdering/EtteroppgjoerRevurderingOversikt.tsx

Endre knapp for neste steg i revurdering etteroppgjør

EY-5186 endre tekst knapp revurdering etteroppgjør

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/revurdering/EtteroppgjoerRevurderingService.kt

Oppgave for revurdering etteroppgjør har kun revurderingsårsak som merknad. 
Endrert til `"Etteroppgjør <etteroppgjoersAar>"`

EY-5187 sette merknad for revurdering etteroppgjør

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerModel.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/EtteroppgjoerForbehandlingListe.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/Etteroppgjoer.ts

- alternativt gjøre det i sql spørring..

EY-5189 ikke vise kopier av forbehandling som brukes i revurdering

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRegelkjoring.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/InntektInnvilgetPeriode.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRegelkjoringTest.kt

Se også regelspesifisering i confluence: https://confluence.adeo.no/pages/viewpage.action?pageId=698681186

EY-5130 Regelkode for beregning av faktisk inntekt avkorting

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/sigrun/SkatteoppgjoerHendelserService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/EtteroppgjoerJobService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt

Litt endringer på periodiske jobb for opprette etteroppgjør og forbehandlinger.
- Tar inn hendelseskjøring mot skatt senere, eller i separat jobb. Trigges manuelt i førsteomgang 
- Jobben har egen toggle i unleash

EY-5192 periodisk jobb for opprette etteroppgjør, forbehandling

---

apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/sjekkadressebeskyttelse/SjekkAdressebeskyttelseJobService.kt

For å dobbeltsjekke en porten-sak

Dobbeltsjekker gradering i sak opp mot pdl-persongalleriet

---

apps/etterlatte-behandling/src/main/kotlin/behandling/doedshendelse/DoedshendelseReminderService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseDao.kt
apps/etterlatte-behandling/src/test/kotlin/doedshendelse/DoedshendelseReminderServiceTest.kt

Fjerner en feilsituasjon som spammer ned dev-loggene våre

Håndterer at vi har slettet saken dødshendelsen peker på

---

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseDao.kt

id-kolonnen er definert som text ikke uuid

---

apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/uttrekk/UttrekkFylt18JobService.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt

Midl jobb for å hente ut brukere som fyller 18 år i mai

EY-5209 uttrekk for fylt 18 år i Mai

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/brev/EtteroppgjoerBrevModel.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/etteroppgjoer/EtteroppgjoerDaoTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/fastsettFaktiskInntekt/FaktiskInntektSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/fastsettFaktiskInntekt/SumAvFaktiskInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/inntektsopplysninger/OpplysningerFraAInntekt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/inntektsopplysninger/OpplysningerFraSkatteetaten.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/resultatAvForbehandling/BrevutfallAvForbehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/forbehandling/EtteroppgjoerForbehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/forbehandling/sidemeny/EtteroppgjoerForbehandlingSidemenyOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/revurdering/EtteroppgjoerRevurderingOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/etteroppgjoer/EtteroppgjoerSaksoversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/EtteroppgjoerForbehandlingListe.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/etteroppgjoer.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/EtteroppgjoerForbehandling.ts
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/EtteroppgjoerReducer.ts
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/model/oms/EtteroppgjoerBrevData.kt

wip fane for å se status på etteroppgjøret en sak er tilknytt 
Her er skisser over hvordan det er ønskelig at det skal bli

Legge til fane for Etteroppgjør i saksoversikt

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/Behandlingsliste.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/EtteroppgjoerForbehandlingListe.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/TilbakekrevingListe.tsx

For alle tabeller der vi viser lister av behandlinger (ikke oppgaver, der er det fremdeles gå til)

Se behandling i stedet for gå til behandling

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/BegrunnelseForTrygdetid.tsx

FAGSYSTEM-380696 Viser begrunnelse for trygdetid for attestant også

---

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt

vi får det i logging av GosysInternalFeil uansett

Ikke nødvendig å ta inn message - logger blir vanskelig å lese

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingDao.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingModel.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
apps/etterlatte-behandling/src/main/resources/db/migration/V268__legge_til_felter_for_ugunst.sql
apps/etterlatte-behandling/src/test/kotlin/behandling/etteroppgjoer/EtteroppgjoerForbehandlingDaoTest.kt
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/revurdering/EtteroppgjoerRevurderingOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/etteroppgjoer.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/EtteroppgjoerForbehandling.ts

Neste blir å se på å bruke en form context for skjemaene i revurderingen. Nå begynner det å bli veldig messy

EY-5228 endring er til ugunst for bruker

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/brev/EtteroppgjoerForbehandlingBrevService.kt
apps/etterlatte-behandling/src/main/kotlin/brev/BrevService.kt

Mindre forbedringer forbehandlingBrevService

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingValider.kt
apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingValiderTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/BeregnAvkortingTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/MottattInntektsjusteringServiceTest.kt
libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt

Dette er del 1 som håndterer det riktig i backend. Del to som oppdaterer registreringen i frontend kommer i en annen PR.

EY-5219 Håndterer flere inntekter i en registrering i backend avkorting

---

apps/etterlatte-behandling-kafka/src/test/kotlin/no/nav/etterlatte/brev/model/oms/EtteroppgjoerBrevDataTest.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/brev/EtteroppgjoerForbehandlingBrevService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/brev/EtteroppgjoerRevurderingBrevService.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/etteroppgjoer/EtteroppgjoerService.kt
libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/model/oms/EtteroppgjoerBrevData.kt

Rydde opp data vi sender til brevbaker for korrekt visning i beregningsvedlegget
Se endringer i pensjonsbrev: https://github.com/navikt/pensjonsbrev/pull/1544

EY-5242 sende med inntekt til brevbaker

---

apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/resultatAvForbehandling/ResultatAvForbehandling.tsx

- legge til hjelpetekst for resultatet av etteroppgjør
- hjelpetekst for avviksbeløp
- bytte rekkefølge nyBruttoStoenad og utbetaltStoenad

EY-5243 hjelpetekst resultat etteropgjør

---

apps/etterlatte-beregning/src/main/resources/grunnbelop.json
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRegelkjoringTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/BeregnAvkortingMedToInntektsTest.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/BeregnAvkortingTest.kt

Oppdaterer også noen tester, men her gjenstår det en del jobb for å fikse disse til å ikke være avhengig av grunnbeløpsendringer

Oppdaterer med nytt grunnbeløp for mai 2025

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/fastsettFaktiskInntekt/FaktiskInntektSkjema.tsx
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/BehandlingReducer.ts

Dette sikrer at vi henter oppdatert avkorting når vi viser beregning

Reset avkorting i state hvis vi endrer i forbehandling

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/OppdaterIdentModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/useUnleash.ts

Siden toggle har vært på i 4 måneder og den skaper trøbbel i hendelser-listen fjernes toggle'en.

Fjerner feature-toggle for oppdatering av ident

---

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt

Håndterer avvik i eksisterende avkorting riktig

Haandter avvik i eksisterende avkorting

---

apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt

rename som ikke oppdaterte alle plasser, intellij varslet

rett parameternavn

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/handling/StartOppgavebehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreBruker.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/SakOversiktHeader.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/pdltjenester.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/statusbar/Statusbar.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/tags/AdressebeskyttelseGraderingTag.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/types/sak.ts

Får ta en sjekk på etterlevelsesdokumentasjonen om dette er nok

EY-5217 vis at sak er adressebeskyttet the squequal

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingService.kt
apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V43__fix_time_precision_datoiverksatt.sql
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt

truncate timestamp to milliseconds 

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt
apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt

fjerner inntil videre uthentingen

Vi har problemer med å hente ut tidspunktene som blir migreret

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt

Jobb for migrering er ikke helt bra satt opp, så tar med saker som feiler konstant. Legger på offsett

Legge til offsett på migrering

---

buildSrc/build.gradle.kts

This reverts commit a4eb782c041c364ebe5b10997329e4a8342af6dd.

Revert "Bump jvm from 2.1.21 to 2.2.0 (#7643)"

---

apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/vedtak/VedtakRoute.kt
apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/vedtak/VedtakService.kt
apps/etterlatte-api/src/test/kotlin/no/nav/etterlatte/vedtak/VedtakServiceTest.kt

Vi har migrert tidspunkt for iverksettelse. Men vi har ikke tilgjengeliggjort feltet i vedtak api enda

EY-5028 legge til iverksettelsesTidspunkt i vedtak api

---

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt

Et Avslag er teknisk sett et ferdigstilt vedtak, og burde returneres

Returnere Avslag som ferdigstilt vedtak

---

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt

Før krevde vi at oppgaven var tildelt en saksbehandler og ikke avsluttet, men nå krever vi bare at den ikke er avsluttet. Det er noe litt merkelig som skjer med en konkret sak, og vil teste om dette jobber rundt problemstillingen.
Det sjekkes uansett på om saksbehandler har oppgaven i frontend, og ingenting knekker hvis en saksbehandler får laget en revurdering selv om oppgaven ikke er tildelt.

FAGSYSTEM-391383 Litt mildere krav for oppretting av revurdering fra oppgave

---

apps/etterlatte-behandling/src/test/kotlin/tilgangsstyring/OppdatererTilgangServiceTest.kt
apps/etterlatte-tidshendelser/.run/etterlatte-tidshendelser.dev-gcp.run.xml
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/JobbPoller.kt
apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/JobbScheduler.kt

Også litt bedre testdekning og oppsett for lokal kjøring

Skru av jobben OPPDATER_SKJERMING_BP, siden vi skal fikse en feil knyttet til verges skjermet-status.

---

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt

Fjerner unødvendig spam i prod-alerts

Trygdetid kan ikke endres på er ikke en error-logging

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/etteroppgjoer/EtteroppgjoerSvarfristUtloeptJobService.kt
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/EtteroppgjoerSvarfristUtloeptModal.tsx

- Legge til mulighet til å avslutte oppgave 'tidsfrist utløpt'
- Endre interval for tidsfrist utløpt i dev til 15 minutter

Mindre fix etter demo etteroppgjør

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/revurdering/EtteroppgjoerRevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingRoutes.kt

Problemet er at vi forsøker å kopiere trygdetid for en revurdering som enda ikke er opprettet

rette inTransaction etteroppgjør opprette revurdering

---

apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/EtteroppgjoerForbehandlingListe.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/SakOversikt.tsx
apps/etterlatte-saksbehandling-ui/client/src/useUnleash.ts

og styrer knapp for etteroppgjør på egen toggle kun for dev

Fjerner mulighet for å opprette revurdering fra tabell

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
apps/etterlatte-behandling/src/test/kotlin/behandling/etteroppgjoer/EtteroppgjoerForbehandlingDaoTest.kt

Lagrer ikke retur objektet til oppdaterBrukerHarSvart

Lagre oppdatert informasjon fra bruker

---

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BeregningKlientImpl.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDaoMedEndringssporing.kt
apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt
apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/AnnullerForbehandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingBrev.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/forbehandling/sidemeny/EtteroppgjoerForbehandlingSidemenyOppsummering.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/forbehandling/stegmeny/EtteroppjoerForbehandlingStegmeny.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/OpprettEtteroppgjoerForbehandlingModal.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/EtteroppgjoerForbehandlingListe.tsx
apps/etterlatte-saksbehandling-ui/client/src/shared/api/etteroppgjoer.ts
apps/etterlatte-saksbehandling-ui/client/src/shared/types/EtteroppgjoerForbehandling.ts
apps/etterlatte-saksbehandling-ui/client/src/store/reducers/EtteroppgjoerReducer.ts

- når vi oppretter forbehandling via oppgave sendes ikke saksbehandler direkte til forbehandlingen i saksbehandling-ui, vi returnerer ikke rett data i backend
- rydder også opp litt, litt blanding av `etteroppgjørForbehandling` og `detaljertForbehandling` flere steder
TODO: Se på bruk og annen navngiving for detaljertForbehandling?

Rette feil som oppstår ved oppretting av forbehandling fra oppgave

---

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/Behandling.tsx
apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/revurdering/EtteroppgjoerRevurderingOversikt.tsx

Tenkte vi kunne flytte henting av etteroppgjør til Behandling, som er den komponenten som er "mor" for alle stegene. Henting manglet for beregn-siden og brev-siden.

EY-5363: Fikser stegviser for EO.

---

apps/etterlatte-behandling/.nais/prod.yaml
apps/etterlatte-behandling/src/main/kotlin/Application.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/sigrun/SigrunKlient.kt
apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/etteroppgjoer/behandling/jobs/etteroppgjoer/StartpunktSkatteoppgjoerHendelserJob.kt
apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt

Den behandler også en hendelse...

Jobb for å sette startpunkt for skattehendelse-lesing ifm etteroppgjør.
