apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingResource.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/SakOversikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/vilkaarsvurdering.ts
Så saksbehandler får grei input om at ytelsen da varer til vedkommende fyller 21 år, ikke 20.
- Dette er ønsket av Mari, slik at man også kan skjønne eventuelle automatiserte aldersoverganger.
- Benytter samme stil som melding om at søker er markert som flyktning
=> Vise info om at søker har yrkesskadefordel fra før reformtidspunktet

apps/etterlatte-beregning/src/main/kotlin/klienter/BehandlingKlient.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/NotatRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/DokumentRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/oversendelsebrev/OversendelseBrevRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevRoute.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/OversendelsesbrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokument/DokumentRouteTest.kt, apps/etterlatte-grunnlag/src/main/kotlin/klienter/BehandlingKlient.kt, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/BehandlingKlient.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/BehandlingKlient.kt, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/klienter/BehandlingKlient.kt, libs/etterlatte-ktor/src/main/kotlin/route/Tilgangssjekker.kt
To første commits er å skrive om til å bruke samme tilgangssjekker-klasse overalt, siste commit er faktisk endring.
=> EY-3731: Cache resultatet av tilgangssjekk i 1 min

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingDaoTest.kt, apps/etterlatte-brev-api/.run/etterlatte-brev-api.dev-gcp.run.xml, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/tilbakekreving/TilbakekrevingTesthjelper.kt, apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingSkjema.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Tilbakekreving.ts, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/TestHelper.kt, libs/etterlatte-tilbakekreving-model/src/main/kotlin/Tilbakekreving.kt
Vi har rettslig grunnlag - men denne vil ikke inneholde hjemler utledet senere i flyten. Har derfor behov for et eget felt som er den utledede hjemmelen som også sendes i vedtaket.
=> EY-3732: Legger til utledet hjemmel i tilbakekreving

.github/dependabot.yml
Nokre avhengnadar i backend som er ganske "vanlege"/trygge kan vi fint gruppere med resten. Prom-client og Unleash-client var malplassert i frontend - dei er ikkje i klienten, men i frackenden
=> Gruppering dependabot

settings.gradle.kts
This reverts commit 503fa018ca2e18c6c6cd8b747176c70c49cbae36.
Pga feil med `.addFirst(String)` 
Burde se på hvorfor vi ikke bygger noe som følge av denne endringen
=> Revert "Bump jvm from 1.9.22 to 1.9.23 (#4348)"

.github/workflows/codeql.yml
CodeQL-bygga har tima ut eit par gongar dei siste dagane. Prøver å skru på gradle-cachen, kanskje det hjelper. Synes uansett det verkar fornuftig å ha denne aktivert
=> Caching i code-scanning-jobben

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidVisning.tsx
Dette vises ved avslag kun for utlandssaker - og her er TT opsjonelt. Det brukes ikke til noe annet enn at sh. vil ha et kopi lagret.
=> FAGSYSTEM-324425 - ikke valider og sett status hvis avslag

apps/etterlatte-trygdetid/.run/etterlatte-trygdetid.dev-gcp.run.xml
Samme URL som brukes nå i dev/prod nais (gamle FSS URL er skrudd av i dev)
=> EY-3747 - bruk GCP url for kodeverk for lokal kjøring av trygdetid

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/ParallelleSannheterKlient.kt, apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlKlient.kt, apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt, apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/SivilstandMapper.kt, apps/etterlatte-pdltjenester/src/main/resources/pdl/hentPerson.graphql, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/omstillingsstoenad/Sivilstand.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts, libs/saksbehandling-common/src/main/kotlin/person/Person.kt
Trengs for å finne tidligere ektefeller og partnere ifm. dødsmelding.
Usikker på om dette kan ha uønskede effekter andre steder?
=> Vi må hente historiske sivilstander for gjenlevende og avdøde

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt
java.lang.IllegalArgumentException: er_over_18_aar is unknown; keys must be declared as required, forbidden, or interesting
https://logs.adeo.no/app/r?l=DISCOVER_SINGLE_DOC_LOCATOR&v=8.12.2&lz=N4IglgdgJgpgHiAXCAnANhmgLADgMYAMAtCjgQIZECMVMKROAzBUTFQOwBGnU2nWUTiAA0IAE4B7AO4BJaPCQgANhIDmAZwAu5dQAsi5AA6H1RTTC1ECBZuwCsI8dJlRFAfTABVFBKxYAQgBiAOpSUoEAUgCujKoRAJpEjmIwAGYwYiliigD0RoY5UGDqeBIAbhkAxDkA%2FG6qALwAFJpgALYwiE2pkm2IENJEAExYugCkQ4G6wpoS%2FdIAlAsAZG7kzaVKUW0Q6ogAhE1KMBVKwh3q6uSqMMIwEGV4SjrqwvlKYHjkrRIQwoYSKALYSQWBwRAAcnQmFwhBIZEoNDoDGYlDYXB4fAEnAhwgAjlEMgBPLrPCCqKLXTpbPD3W4E4mQuBuUqZGDPH4QDxQRA4KicPBUVJDPCsPB4LBELAoKBUAxUFBDEhUIbkWAcFBCnAQpYgAC%2BQA%3D%3D%3D
=> Forsøker å hente ut verdi som ikke er deklarert

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelse.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelseForeldreloes.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt
- Legger til felt `harUtbetaling`
- Fjerner ubrukt felt `bareEnPeriode` fra foreldreløs-brev og endrer `ingenUtbetaling` til `harUtbetaling` for å være mer konsistent med andre maler.
=> EY-3748: Legger til felt harUtbetaling for innvilgelsesbrev

apps/etterlatte-vedtaksvurdering/.nais/dev.yaml, apps/etterlatte-vedtaksvurdering/.nais/prod.yaml, apps/etterlatte-vedtaksvurdering/.run/etterlatte-vedtaksvurdering.dev-gcp.run.xml, apps/etterlatte-vedtaksvurdering/README.md, apps/etterlatte-vedtaksvurdering/src/main/kotlin/Application.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/config/ApplicationContext.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/outbox/OutboxItem.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/outbox/OutboxJob.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/outbox/OutboxRepository.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/outbox/OutboxService.kt, apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V26__create_outbox.sql, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/outbox/OutboxIntegrationTest.kt
Benytter outbox-patternet for å ikke involvere enda en ikke-transaksjonell komponent inn i alt som foregår i statusoppdateringene rundt vedtak. Custom enkel poller i stedet for CDC (typ Debezium) fordi behovet, volum osv er veldig lite. Betyr ingenting om det tar litt tid  før hendelsen kommer til Pesys.
=> EY-3754 Sende ut vedtakshendelser til eksterne

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/outbox/OutboxService.kt
Kun for å gjøre det lett å sjekke i kibana at det skjer ting her (slippe å sjekke db)
=> EY-3754 Logge at vedtakshendelse er sendt ut

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseServiceTest.kt
Disse ble identifisert som både samboer og ektefelle, det riktige er at disse blir identifisert én gang, som samboer.
EY-3792
=> Tidligere ektefeller med barn som nå er samboere skal ikke identifiseres

apps/etterlatte-behandling/.nais/dev.yaml, apps/etterlatte-behandling/.nais/prod.yaml, apps/etterlatte-behandling/.run/etterlatte-behandling.dev-gcp.run.xml, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BeregningKlientImpl.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/migrering/MigreringService.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/resources/application.conf, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt, apps/etterlatte-behandling/src/test/kotlin/integration/BehandlingIntegrationTest.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, apps/etterlatte-beregning/.nais/dev.yaml, apps/etterlatte-beregning/.nais/prod.yaml, apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt, apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/avkorting.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts, libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt
- Hoved endring er at når virkningstidspunkt endres så fjernes avkorting fra behandling istedenfor å kun varsle om at inntekt lagt til må oppdateres.
- Behandling trenger beregningsklient for å kunne slette avkortingen
- Har også gjort en del refaktorering i avkorting i forkant av endringen (flytte logikk fra frontend og route til service og domeneklasse).
=> Inntektsavkorting slette hvis endret virk

apps/etterlatte-egne-ansatte-lytter/src/main/resources/logback.xml, apps/etterlatte-institusjonsopphold/src/main/resources/logback.xml, apps/etterlatte-klage/src/main/resources/logback.xml, apps/etterlatte-pdltjenester/src/main/resources/logback.xml
For at sporingslogging skal funke, må applikasjonen ha ei `logback-sporing.xml`-fil, og denne må vera referert til frå `logback.xml` på tilsvarande vis som vi elles gjer for sikkerlogg.
Tar bort konfigen der det ser ut til å vera malplassert, og legg på referansen der det ser ut som han manglar.
=> Ryddar opp i sporingslogg-konfig

apps/etterlatte-brev-api/src/main/resources/db/prod/V16__slett_varselbrev_gjenoppretting_uten_adresse.sql
Trur det ryddigaste og enklaste er at sb opprettar nytt varselbrev etter adresse er på plass
=> Markerer varselbrev som er journalført utan adresse som sletta

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingVedtakRoute.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt, libs/etterlatte-oppgave-model/src/main/kotlin/oppgave/OppgaveIntern.kt, libs/saksbehandling-common/src/main/kotlin/VedtakType.kt
- Flytte kall mot `oppgaveService` ut av `BehandlingVedtakRoute`
- Forbedre merknader på oppgave. Bl.a. legge til vedtaktype slik at sb enkelt kan se om oppgaven førte til innvilgelse, e.l.
- Flere tester
=> Forbedre merknad på oppgave ved attestering

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt, apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveRoute.kt, apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, apps/etterlatte-behandling/src/test/kotlin/oppgaveGosys/GosysOppgaveServiceImplTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/GosysOppgaveliste.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/FilterRad.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Gosys.ts, apps/etterlatte-saksbehandling-ui/docker-compose.yml
Grunnet gammel moro med konvertering av Gosys-oppgave til Gjenny-oppgave, vil det her se litt rart ut siden oppgavetype og saktype mappes til noe vilkårlig. Eks. vil alt av **pensjon** bli mappet til **barnepensjon**. 
Må ryddes opp i fortløpende slik at Gosys-oppgaver blir _helt_ fristilt.
=> EY-3815 Støtte søk på tema PEN på gosys-oppgaver

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDaoMedEndringssporing.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx, libs/saksbehandling-common/src/main/kotlin/UUID30.kt
Dersom feilutbetaling er valgt i brevutfall, opprettes det en oppgave for tilbakekreving. Formålet med denne oppgaven er bare å synliggjøre at behandlingen som ble gjort, resulterte i tilbakekreving.
- Oppgaven opprettes når en behandling settes til Iverksatt med merknad "Venter på kravgrunnlag"
- Når kravgrunnlag er mottatt, opprettes det tilbakekrevingsbehandling, referansen på oppgaven kobles mot denne behandlingen og merknad settes til "Kravgrunnlag mottatt"
=> EY-3739: Oppretter oppgave for tilbakekreving ved feilutbetaling valgt i brevutfall

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunkt.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktEktefelleService.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktEktefelleServiceTest.kt
Dersom vi ikke finner et giftemål/partnerskap på avdød opprettes nå et kontrollpunkt.
=> fix: Sjekker på flere statuser og returnerer kontrollpunkt fremfor å kaste exception.

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/ParallelleSannheterKlient.kt
Konsekvensen her er at vi ikke kan styre hvilke "kilde" vi potensielt får (det vil være flere), men alternativet er at det krasjer. Vi benytter ikke dette til noe automatisk, så får leve med den ulempen.
PPS har heller ikke støtte for å prioritere kilde.
=> fix: Dersom en person har flere sivilstander som er like, så velger vi den som er registrert sist.

apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonRepository.kt, apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonService.kt, apps/etterlatte-beregning/src/main/resources/db/migration/V37__endre_opprettet_og_endret_sanksjon.sql, apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt, apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonRepositoryTest.kt, apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonRoutesTest.kt, apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadSammendrag.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sanksjon/Sanksjon.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/sanksjon.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/components/maanedVelger/ControlledMaanedVelger.tsx
Ta gjerne en ekstra titt på hvordan opprettet og endret er løst. Har brukt samme konsept som kilde på begge felter, sånn at man får med data om hvilken saksbehandler som gjør hvilken del.
Mulig man burde bruke textarea fremfor textfield for beskrivelse
=> La saksbehandler legge til sanksjoner i en tabell på beregning siden

apps/etterlatte-pdltjenester/src/main/kotlin/utils/PdlKlientUtils.kt
Tidligere endringer som ble gjort for å hente ut sivilstandshistorikk fra PDL ble fjernet i https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/4268 ved refaktorering.
=> fix: sivilstandshistorikk hadde blitt fjernet fra avdøde og gjenlevende

apps/etterlatte-behandling/src/main/resources/db/migration/V111__resett_doedshendelser_hvor_sivilstandshistorikk_manglet.sql
Motivasjonen for å kjøre disse på nytt, er å avdekke eventuelle feil før vi kan teste på nytt om 5 dager.
=> Resett dødshendelser som ble prosessert mens vi manglet sivilstandshistorikk

apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/DokumentModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/DokumentlisteLiten.tsx
Løser: 
```
Error occurred in '../../src/components/person/dokumenter/DokumentModal.tsx' (line: 66, col: 45):
Cannot read properties of undefined (reading 'saksbehandlerHarTilgang')
"{}"
```
https://logs.adeo.no/app/discover#/doc/b53f9434-0d96-4fb4-8314-15eac8a5b7c8/logstash-apps-prod-007071?id=ek7f744B1xFu5Myr6sr3
=> hotfix: Sjekke om dokumentvariant er undefined

apps/etterlatte-vedtaksvurdering/.nais/dev.yaml, apps/etterlatte-vedtaksvurdering/.nais/prod.yaml, apps/etterlatte-vedtaksvurdering/.run/etterlatte-vedtaksvurdering.dev-gcp.run.xml, apps/etterlatte-vedtaksvurdering/build.gradle.kts, apps/etterlatte-vedtaksvurdering/src/main/kotlin/Application.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/config/ApplicationContext.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/simulering/SimuleringOsKlient.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/simulering/SimuleringOsRoutes.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/simulering/SimuleringOsService.kt, apps/etterlatte-vedtaksvurdering/src/main/resources/application.conf, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/simulering/SimuleringOsRouteTest.kt, gradle/libs.versions.toml
- kun backenddel i denne
- bevisst gjort enkel/direkte i returverdien her inntil videre, da UI på ingen måte er designet.
- ikke gjort noe mtp å eventuelt persistere simuleringen, slik at man kan se den senere for ferdigstilte behandlinger.
=> EY-3389 Simulere mot oppdragssystemet

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
Nå vises "Du må fylle ut utfall i brev" som ikke forsvinner om du fyller ut avkorting heller, men først når du har fylt ut avkorting også brevutfall...
=> Vis riktig feilmelding for avkorting mangler i OMS

apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/rivers/GrunnlagHendelserRiver.kt, apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/itest/RapidTest.kt, apps/etterlatte-opplysninger-fra-soeknad/src/main/kotlin/no/nav/etterlatte/opplysningerfrasoknad/StartUthentingFraSoeknadRiver.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/EventNames.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/IkkeStandardiserteKeys.kt
Primært for å tilretteleggje for eksperimentering med automatisk behandling i test, men dette er uansett ei fin standardisering i retning sånn vi vanlegvis gjer det for resten.
=> Flyttar eventname-key for ny opplysning over til enum-standardformatet

apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingServiceIntegrationTest.kt
Fra jira:
> Det har vært et par tilfeller hvor aldersovergang har kjørt, hvor det var åpen behandling på aktuell sak, men det likevel har blitt utført et automatisk opphør. Se [FAGSYSTEM-326368](https://jira.adeo.no/browse/FAGSYSTEM-326368) (https://nav-it.slack.com/archives/C01PG1JM9D4/p1713349531997109), og 20. april saksid 16735. Forventningen var at det ble opprettet oppgave om opphør.
> 
> Bjørn har også testet å kjøre regulering der det finnes åpen behandling og den gikk gjennom.
> 
> Det ser ut til at denne endringen i oppførsel skyldes den store omskrivingen av oppgave, hvor oppgavene ble slått sammen og det ble innført nye statuser i stedet.
=> EY-3852 Sjekk for åpen behandling ved omregning må sjekke flere oppgavestatuser

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevoppretter.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/PDFService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/AdresseService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/oversendelsebrev/OversendelseBrevService.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevdistribuererTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/OversendelsesbrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/GrunnlagmapperTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/db/BrevRepositoryIntegrationTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/BrevModelTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/MottakerRequestTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/oversendelsebrev/OversendelseBrevServiceImplTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevTest.kt, libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/Brev.kt, libs/saksbehandling-common/src/main/kotlin/person/Folkeregisteridentifikator.kt
To poeng her:
1. Flytte Brev-klassa med tilhøyrande klassar over til modellen, for å ha denne tilgjengeleg for den som ønskjer å kalle brev-api-endepunkta
2. Liker ikkje heilt at fødselsnummer-klassa frå brevbaker-modellen skal lekkje langt inn i koden vår. Byttar heller over til Folkeregisteridentifikator-klassa, ser ingen grunn til at det skal vera forskjellig her
Har testa å hente eksisterande manuelle brev, hente og oppdatere eksisterande vedtaksbrev, behandle ei ny sak med nytt vedtaksbrev, oppdatert dette, ferdigstilt.
=> Flytte brevmodellen frå brev-api til modellen for å tilgjengeleggjera

apps/etterlatte-behandling/src/main/kotlin/Application.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/resources/db/migration/V112__ny_tabell_aktivitetsplikt_aktivitet.sql, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktDaoTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt
På sikt skal vi nok støtte å kunne legge til aktiviteter kun basert på sak, men for nå må det gjøres i en behandlings-kontekst.
=> Backend-støtte for å hente og opprette aktiviteter for aktivitetsplikt

apps/etterlatte-behandling/.nais/dev.yaml, apps/etterlatte-beregning/.nais/dev.yaml, apps/etterlatte-brev-api/.nais/dev.yaml, apps/etterlatte-opplysninger-fra-soeknad/src/main/kotlin/no/nav/etterlatte/opplysningerfrasoknad/StartUthentingFraSoeknadRiver.kt, apps/etterlatte-trygdetid/.nais/dev.yaml, apps/etterlatte-vedtaksvurdering/.nais/dev.yaml, apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/Behandlingssteg.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/Kontekst.kt
Dette er endringane i alle andre appar enn testdata og testdata-behandler frå #4579 , sjå der for korleis desse blir brukt (yaml-endringane ser du bakgrunnen for i Behandler.kt, medan StartUthentingFraSoeknadRiver sender meldinga som skal bli plukka opp i den nye riveren)
Tanken er at ved å få inn denne blir det enklare å teste og ferdigstille 4579.
=> Tilretteleggje for generer testdata - endringane i dei andre appane

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/ParallelleSannheterKlient.kt
Parallelle-sannheter takler at vi får flere av samme type, dersom de har ulik dato. Velger derfor å ikke logge disse.
Endrer også til `warning`, så ser man det dersom man skal følge opp en feil som kastes fra PPS.
=> Litt mindre agressiv logging når vi får dårlig sivilstandsdata fra PDL

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt, apps/etterlatte-grunnlag/src/main/kotlin/Application.kt, apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/config/ApplicationContext.kt, apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/ApplicationIntegrationTest.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/RapidEnv.kt
Configen som tidligere ble brukt for lokal kjøring er fjernet i nyere versjon av rapids & rivers. Har lagt til en lokal konfig som kopierer den lokale configen som ligger i rapids & rivers, men som ikke krever TestContainer som parameter. 
Se forøvrig endringen som gjør at vi må endre dette her: https://github.com/navikt/rapids-and-rivers/commit/009c5dd149c50f9fd24fcde8cc06fc452c33df02
=> Ny config for apper som kjører mot kafka lokalt

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingRoute.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/statistikk/StatistikkRoute.kt, apps/etterlatte-behandling/src/main/kotlin/egenansatt/EgenAnsattRoute.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseRoute.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseRoutes.kt, apps/etterlatte-behandling/src/main/resources/logback.xml, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/ytelseMedGrunnlag/YtelseMedGrunnlagRoutes.kt, apps/etterlatte-beregning/src/main/resources/logback.xml, apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/PersonRoutes.kt, apps/etterlatte-grunnlag/src/main/resources/logback.xml, apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRouteTest.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/vedtak/TilbakekrevingVedtakRoutes.kt, apps/etterlatte-tilbakekreving/src/main/resources/logback.xml, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/avtale/AvtaleRoutes.kt, apps/etterlatte-trygdetid/src/main/resources/logback.xml, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/UtbetalingRoutes.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/AutomatiskBehandlingRoutes.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt, apps/etterlatte-vedtaksvurdering/src/main/resources/logback.xml, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/AldersovergangRoutes.kt, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRoutes.kt, apps/etterlatte-vilkaarsvurdering/src/main/resources/logback.xml, libs/etterlatte-ktor/src/main/kotlin/route/RouteUtils.kt
Alle debug-kall til application.log blir berre slukt, sia denne er udefinert i logback-konfigen, og dermed går som eit barn av root-logger, som er vår catch-all og denne har nivået info. Dermed mistar vi debuglogginga.
Innfører derfor ein spesifikk route-logger, for å unngå støy, og endrar konfig i alle appane der vi bruker routeLogger-en til å ta med også debuglogging. Denne loggeren bruker vi jo kun der vi eksplisitt ønskjer å få logga
=> Separat logger for routes

apps/etterlatte-utbetaling/README.md, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/UtbetalingRoutes.kt, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/common/OppdragDefaults.kt, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/config/ApplicationContext.kt, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/oppdrag/OppdragMapper.kt, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/utbetaling/Utbetalingsvedtak.kt, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/simulering/SimuleringOsService.kt, apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/simulering/SimuleringOsRouteTest.kt
- Delvis gjenbruk av mappingen fra oppdrag (som brukes ved iverksetting), men ikke fullt pga forskjellige namespace/mindre variasjoner på typene i kontraktene. Ser ikke verdien i å innføre noe abstraksjon for å hindre litt duplisering, det hadde blitt like mye (om ikke mer) kode.
- Testet ok med en revurdering
=> EY-3389 Justert mapping for simulering

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/hendelse/HendelseDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingFeilmeldinger.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingDaoTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingRoutesIntegrationTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingServiceIntegrationTest.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/klienter/BehandlingKlient.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagConsumer.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagService.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/TestKravgrunnlagRoutes.kt, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/TestHelper.kt, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagConsumerTest.kt, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagServiceTest.kt, libs/etterlatte-tilbakekreving-model/src/main/kotlin/StatistikkTilbakekreving.kt, libs/etterlatte-tilbakekreving-model/src/main/kotlin/TilbakekrevingBehandling.kt
Lagt til støtte for ENDR, SPER og AVSL i tillegg til NY som støttes allerede.
- SPER: Betyr at det kan komme endringer i kravgrunnlaget - Her settes oppgaven på vent.
- ENDR: Kommer typisk etter en SPER. Hvis den ikke inneholder perioder, er kravet uendret - oppgaven kan settes aktiv igjen. Hvis denne koden kommer med perioder, betyr det at kravgrunnlaget er endret. Eksisterende tilbakekreving vil avbrytes og ny vil bli opprettet.
- AVSL: Her har kravgrunnlaget blitt nullet ut og er ikke lenger aktuelt. Eksisterende behandling avbrytes.
=> EY-3387: Støtte ulike statuser i kravgrunnlag

apps/etterlatte-behandling/src/main/kotlin/behandling/doedshendelse/DoedshendelseReminderService.kt, apps/etterlatte-behandling/src/test/kotlin/doedshendelse/DoedshendelseReminderServiceTest.kt
Sakene ble spammet med oppgaver fordi det ble opprettet en ny oppgave hver gang jobben ble kjørt.
=> Ikke opprett oppgave for BP ikke søkt hver gang

apps/etterlatte-tilbakekreving/build.gradle.kts, apps/etterlatte-utbetaling/build.gradle.kts, gradle/libs.versions.toml
MQ-biblioteket vi bruker trekkjer med seg bouncycastle-versjonar med kjente sårbarheiter, korav nokre er tagga med risiko høg. Det er ikkje så kult å ha i prod.
Det er ikkje meir enn eit par veker sia forrige versjon av MQ-biblioteket kom heller, så det er ikkje grunn til å tru at det blir retta med det første. Innfører derfor samme workaround som vi per no bruker i etterlatte-proxy, altså at vi eksplisitt overstyrer versjoneringa for dette biblioteket.
Har kikka på release notes for bouncycastle, og ved å gå frå 1.77 som vi bruker i dag til 1.78.1 ser det ut som vi får retta fleire CVE-ar, og at det utover det ser det ut som berre småting.
=> EY-3879: Oppgraderer det transitive bouncycastle-biblioteket

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveEndring.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/egenansatt/EgenAnsattServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/BehandlingSidemeny.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/IBehandlingInfo.ts, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/OppgaveEndring.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/oppgaver.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/styled.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/oppgave.ts
**MVP** for visning av historikk på oppgave og behandling. 
Fletter sammen hendelser fra oppgave og behandling. Tanken er at det på sikt kan flette flere typer hendelser.
Må gjøres en god del endringer i måten vi håndterer oppgaver og tilknyttede behandlinger for å sikre at dette også vises på avsluttede behandlinger. Vil nå kun være tilgjengelig så lenge en behandling er "under behandling".
=> EY-3605 Fane for visning av historikk i behandling/oppgave

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgave.kt, apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt, apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveService.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, apps/etterlatte-behandling/src/test/kotlin/oppgaveGosys/GosysOppgaveServiceImplTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/gosys/GosysBrukerWrapper.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/gosys/GosysOppgaveRow.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/gosys/GosysOppgaver.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/gosys/OverfoerOppgaveTilGjenny.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/GosysOppgaveModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/utils/oppgaveSortering.ts, apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/OppgaveFraJournalpostModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Gosys.ts
Gosys har lagt til et nytt felt på oppgaveobjektet: `Bruker`
```
"bruker": {
"ident": "string",
"type": "PERSON"
}
```
Som en følge av dette kan vi da fjerne kall mot `etterlatte-pdltjenester` og mapping av aktørid.
=> EY-3899 Støtte nytt bruker-felt fra gosys

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
og ikke identen i saken, siden hendelsen gjelder identen i hendelsen og ikke mottaker av ytelsen
=> Sjekken for duplikat hendelse må ta med hendelsens ident

apps/etterlatte-vedtaksvurdering/README.md, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/outbox/OutboxService.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/TestHelper.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/outbox/OutboxIntegrationTest.kt
Ønsker ikke et eget felt for revurderingsårsak ettersom det da må være nullable.
Hovedformålet er å unngå at andre systemer må slå opp mot oss for å finne ut av om det er regulering, som er litt spesielt kasus med høyt-ish volum (i Gjenny-målestokk).
=> EY-3798 Spesifiere REGULERING i vedtakshendelser til NAV-interne systemer

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt
Dette henger igjen fra da vi hadde en cron-job og måtte opprette hendelsen før jobben kjørte også kjørte resten av koden for verifiseroghaandterhendelse, nå fjerner jeg opprettelsen av hendelsen for å så oppdatere den.
Det reduserer kompleksiteten betraktelig, feks nå så sjekker hendelsen om den er en duplikat mot seg selv. Det blir borte her.
Delvis relatert [EY-3793](https://jira.adeo.no/browse/EY-3793)
=> Bare opprett hendelse med riktig info, ikke opprett så update

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt, apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TestHelper.kt, apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidTest.kt
Før så var det en forventning at input til normalize var sortert. Det har forsvunnet. Sorter innvendig - da er det garantert
=> FAGSYSTEM-329157 - fiks normalization av trygdetid perioder

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EtterlatteBrev.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/EnkelPersonTrygdetid.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidManueltOverstyrt.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
Får stadig meldinger fra saksbehandlere på teams som sitter fast fordi de glemmer å legge til avdøde ved oppretting av ny behandling når de har huket av "overstyrt trygdetid". Dette sparer oss og dem for mye unødvendig bruk av tid...
Kjenner ikke trygdetid godt nok til å si om dette kan ha uheldige bivirkninger, så her må noen med erfaring på trygdetid kontrollere.
=> Støtte oppretting av ny overskrevet trygdetid

apps/etterlatte-behandling/src/main/kotlin/Application.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/sak/SakTilgangDao.kt, apps/etterlatte-behandling/src/main/kotlin/sak/TilgangService.kt, apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt, apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/TilgangServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/attesterTilbakekreving.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/handinger/underkjennTilbakekreving.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/oppsummering/TilbakekrevingOppsummering.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/utbetalinger/TilbakekrevingVurderingPerioderSkjema.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingSkjema.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/tilbakekreving.ts, libs/etterlatte-ktor/src/main/kotlin/route/RouteUtils.kt
Denne sjekker tilgang bare i tilbakekreving-tabellen, i motsetning til klage, behandling og tilbakekreving. Ny call parameter TILBAKEKREVINGID_CALL_PARAMETER, som brukes i tilbakekrevingRoutes.
=> EY-3889: Tilgangsstyring for tilbakekreving slik det ble gjort for klage

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/VedtaksvurderingKlient.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/Vedtak.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt
Vedtak opprettes tidligere i vilkårsvurdering, men oppdateres jo her og der. Vedtaket som hentes av `utbetaling` for å simulere bør ha så ferske data som mulig - så lenge det ikke er blitt attestert (osv) ennå.
Dette kan forsåvidt orkestreres fra `utbetaling` (eller andre steder), men synes det er litt omstendelig.
=> EY-3389 Oppdatere vedtak når det simuleres på et som ikke er attestert

apps/etterlatte-statistikk/src/main/resources/db/migration/V36__sett_riktig_patch_status.sql, apps/etterlatte-statistikk/src/main/resources/db/migration/V37__rydd_bort_duplikate_sak_rader.sql
Det ble sendt duplikate opprettet-rader for alle automatisk opprettede behandlinger i gjenopprettingen. Det er litt hipp som happ mellom de to radene, men vi velger å beholde radene som har satt en pesysid for original behandling.
=> Rydd bort duplikate sakrader gjenoppretting

apps/etterlatte-statistikk/src/main/resources/db/migration/V39__indekser.sql
Basert på informasjon i GCP-konsollet.
Ikke sikkert at det vil ha voldsomt å si her og nå ettersom mengden data påvirker hvorvidt indeksen(e) faktisk blir brukt, men det vil jo bare bli mer og mer data over tid.
=> Lagt til indekser for behandlingsID i statistikk

apps/etterlatte-behandling/src/main/kotlin/behandling/sjekkliste/SjekklisteDao.kt, apps/etterlatte-behandling/src/main/resources/db/migration/V124__indekser.sql, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
Basert på data fra GCP-konsollet.
- for oppgaveendringer så kalles den ikke ekstremt hyppig, men har veldig drøy svartid
- sjekkliste_items kalles ganske ofte, med en medium svartid.
=> Lagt til indekser for oppgaveendringer og sjekklisteitems i behandling

apps/etterlatte-grunnlag/.nais/dev.yaml, apps/etterlatte-testdata-behandler/.nais/dev.yaml, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/AppBuilder.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/Behandler.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/BehandlingService.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/GrunnlagService.kt, apps/etterlatte-testdata-behandler/src/main/resources/application.conf, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/dolly/Model.kt, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/OpprettOgBehandle.kt, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/automatisk/Familieoppretter.kt, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/dolly/BestillingUtil.kt, apps/etterlatte-testdata/src/main/resources/templates/dolly/opprett-og-behandle.hbs
Gjør det mulig å sette tidligere dødsdato for avdød i testdata når man oppretter søknader som blir automatisk behandlet. Dette har vi behov for når vi tester regulering og trenger saker som er løpende før reguleringstidspunkt, og ikke bare etter.
=> EY-3936: Sette tidligere dødsdato for avdød i testdata

apps/etterlatte-behandling/src/main/resources/db/prod/V125__slette_feilregistrert_sak.sql
Hurtigfiks for å sikre at saksbehandler kan fortsette behandling på den gyldige søknaden. 
På sikt må vi få på plass et mer robust system for disse tilfellene med selvbetjening for sb, sakshistorikk, m.m.
=> Slette feilregistrert sak 17020

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
Basert på GCP-konsollet.
Ser ut til at subqueryen alltid henter rundt 18-19k rader, noe som fremstår veldig rart/unødvendig... tror ikke jeg har misforstått hva som forsøkes oppnådd her. Det er totalt ca 90k rader i `hendelse`.
https://console.cloud.google.com/sql/instances/etterlatte-brev-api/insights;database=etterlatte-brev;duration=P7D;trace=f206505668dc4e4c8e5caafd6e0fdded;span=f6d676ecc49dd811;query_hash=17985515780848363997;sort_by=TOTAL_EXEC_TIME/executed?project=etterlatte-prod-207c
Test med db i docker (med data dumpet fra dev) viser forbedring typisk fra 10-15ms til sub-0.5ms.
=> Ikke hente titusenvis av rader i subquery, men begrens til involvert(e) brev

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt
Validering på virk er basert på rettigheter basert på når bruker søker og det er ikke noen ny søknad i disse tilfellene
=> Droppe validering på virk for behandlinger som er migrering eller gjenoppretting fra Pesys

apps/etterlatte-grunnlag/src/main/resources/db/migration/V21__gin_index_opplysning_tekst.sql
Dette er pga veldig hyppig bruk av dette oppslaget i `OpplysningDao`:
```
SELECT * FROM grunnlagshendelse
WHERE opplysning LIKE ?
AND opplysning_type = ?;
```
60ms er drøyt for noe som kalles sååå ofte.
=> Lagt til GIN-basert index på grunnlagshendelse.opplysning for vesentlig raskere LIKE-søk med fnr

apps/etterlatte-behandling/src/main/kotlin/behandling/sjekkliste/Sjekkliste.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/sjekkliste/SjekklisteIntegrationTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx
Er fjernet fra sjekkliste og side om oppfølging av aktivitet da det nå gjøres automatisk i gjenny.
Er også flyttet til bunn da det nå er informasjon om at det skjer og ikke lenger en oppgave.
=> Fjern opprett oppgave om oppfølging av aktivitetsplikt i gosys 

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/oppdrag/OppdragMapper.kt, apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/iverksetting/oppdrag/OppdragMapperTest.kt
Fikk beskjed av PO-Utbetaling at Tekst140-linjene ikke kan ha flere enn 40 chars. Endrer til to linjer og omformulerer litt for å unngå en tredje linje med to ord. Dette er avklart med fag.
=> EY-3956: Splitter opp tekst over 40 tegn i utbetalingssplipp for regulering

apps/etterlatte-oppdater-behandling/src/main/kotlin/AppBuilder.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseRiver.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseService.kt, apps/etterlatte-oppdater-behandling/src/test/kotlin/TidshendelseServiceTest.kt
Vi styrer det uansett med hvordan vi legger inn jobbkjøringer, så denne er forvirrende å ha som et "ekstra" steg å sjekke av
=> Fjerner feature toggle for oppgave aktivitetsplikt

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakEtterbetaling.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/TestHelper.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakEtterbetalingTest.kt
Dette er pga repository-kallet `hentFerdigstilteVedtak` inkluderer TIL_SAMORDNING, SAMORDNING. Dette da de er ferdig fra et saksbehandlerperspektiv.
Det er ikke umulig at dette kan ha medført noen feil hittil, dvs manglende samordning. Har ikke sjekket hvor mange OMS-revurderinger som er gjennomført i prod.
=> Ved sjekk om etterbetaling, ikke sjekke mot vedtak under behandling

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt
Ifm med testing av nye kravgrunnlag ser jeg at det vil bli rart om det opprettes ny oppgave for tilbakekreving dersom man allerede har en under behandling, og gjør en ny revurdering. Her skal man heller gjenbruke eksisterende - sette denne på vent, for så å koble denne til ny tilbakekreving dersom kravgrunnlaget blir endret..
=> EY-3903: Gjenbruker eksisterende feilutbetalingsoppgave dersom ny feilutbetaling oppstår

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingResource.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt, apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt
Henter alle saker på bruker. Hvis det finnes mer enn 1 vil det gjøres en enkel prioritering avhengig av hvilken sak som har flest "uavbrutte" behandlinger. 
Dette gjør at sb kan avbryte en behandling på en feilregistrert sak, og person-/sakoversikten vil da vil da vise saken som er relevant. 
I fremtiden burde dette gjøres på en bedre måte. Gjenny burde ha: 
- Status på sak
- Støtte for flere saker
- Funksjonalitet for å feilregistrere en sak
...men alt dette får vente enn så lenge.
=> EY-3932 Prioritere sak dersom det finnes flere

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/OppgaveEndring.tsx
Kommer av at behandling henter oppgave under behandling. I tilfeller hvor noe er ferdig behandlet, er det ikke noen oppgave å hente.
=> Sjekke om oppgave er null/undefined

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/MinOppgaveliste.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/Oppgavelista.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/ForenkletOppgaverTable.tsx
Vise `FilterRad` selv om oppgaver laster. Gjør at grensesnittet "hopper" litt mindre. 
Fjerner også delay som skjer ved tildeling av oppgave fra listen på saksoversikten.
=> Forbedre spinner hentoppgaver + fjerne delay tildeloppg. saksoversikt

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/JournalfoerBrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivService.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokarkiv/DokarkivServiceTest.kt
DokarkivService burde ikke måtte forholde seg til mapping av brev til dokarkiv-request. Fjernet for å gjøre servicen så generell som overhodet mulig. 
Forarbeid ifm. [EY-3728](https://jira.adeo.no/browse/EY-3728)
=> Dumme ned DokarkivService og forenkle koden

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/SamKlient.kt
Vi har forsøkt å sjekke status i prod, men fikk bare 204 tilbake fra SAM. Sjekket nærmere en sak i Q2 og det viser seg at saksreferansen vi sender med i samordningsforespørselen ikke blir lagret. Dermed filtreres ting vekk når vi spør her. Skrur av det parameteret slik at vi får alle meldinger på bruker for fagområdet. I Gjenny så gjør ikke det noe da kun OMS er samordningspliktig. Når feilen er rettet bør det skrus på igjen, fremstår som mest riktig.
=> Spørre SAM kun på pid inntil videre

apps/etterlatte-saksbehandling-ui/client/src/components/person/SamordningSak.tsx
Liten oppfølger til forrige feilretting av visning. Av en eller annen grunn er refusjonskrav-kolonnen i SAM not-nullable, slik at vi får false tilbake her når samordningsmeldinger har status SENDT. Det gir ingen mening i å vise ettersom det ikke er vi (NAV) som setter det, men snarere når TP-ordningene sender inn svaret på meldingene, altså hvorvidt de mener de har refusjon eller ei.
Hvorvidt dette kanskje burde vært korrigert et annet sted kan diskuteres.
=> Ikke vise ja/nei i refusjonskrav med mindre samordningsmelding er besvart

apps/etterlatte-samordning-vedtak/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/LoggingPlugins.kt, libs/saksbehandling-common/src/main/kotlin/logging/LogUtils.kt
Kibana logger ikke lenger `user`, `correlation_id`, m.m. 
Før det nylig ble oppdatert kom det advarsel om "duplicate key", så min mistanke er at disse nøklene er reservert. Legger til prefiks for å se om det utgjør en forskjell
=> Legge til prefix for MDC logg keys

apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/OpplysningsgrunnlagMapper.kt
I fordums tid hadde vi et konsept av grunnlagsopplysninger som eksisterte som en periodisert opplysning (over flere grunnlagshendelser). Dette konseptet ble fjernet siden det ikke fungerer -- se https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/1218 for en mer detaljert gjennomgang av hvorfor
så har vi denne sjekken som en liten kode-blindtarm som ble betent når vi ryddet opp i bruken av assert vs. check. Men konseptet "samme type" for grunnlagshendelse når vi snakker om periodisering har forsvunnet. Det er kun "konstante" opplysninger vi sitter igjen med
=> Fjerner gammel logikk for å sjekke periodisert opplysning eller ikke

apps/etterlatte-statistikk/src/main/kotlin/statistikk/database/StoenadRepository.kt, apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/MaanedStatistikk.kt, apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/StoenadRad.kt, apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt, apps/etterlatte-statistikk/src/main/resources/db/migration/V44__ny_kolonne_stoenad_ytelsesgruppe.sql, apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/StoenadRepositoryTest.kt, apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/domain/MaanedStatistikkTest.kt, apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/river/VedtakhendelserRiverTest.kt
Bruker allerede mappede verdier for saksbehandlingsstatistikken, både i etterfylling og i logikken for utfylling
=> Legger til sakYtelsesgruppe for stønadsstatistikk

apps/etterlatte-behandling/src/main/kotlin/behandling/omregning/OmregningRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/omregning/OmregningService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/AutomatiskRevurderingService.kt, apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/regulering/LoependeYtelserforespoerselRiver.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/Vedtak.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/Vedtakstidslinje.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt, libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Omregningshendelse.kt
Utledning av opphoerFraOgMed skal skje basert på forrige revurdering men for regulering 2024 så ble feltet innført i forkant uten å få populert alle revurderinger.
Denne utledningen som fjernes i denne commiten var for å midlertidig kompensere for det.
=> Fjerner opphoerFraOgMed fra Vedtakslinje brukt i sammenheng med regulering 2024

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringsHendelseFilter.kt
Logikken starter i grunnlagsendringshendelseService#131, og må være der intill dødsmelding er på lufta (som ikke er langt unna).
Ser ut som det ble innført noen endringer i https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/4757
=> Dødsmeldinger blir ignorert for brukere som har ytelse i Gjenny

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktTidslinje.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/NyAktivitet.tsx
Legger til muligheten for å "zoome" 1, 2 og 3 år fra dødsdato. 
Default verdi er 3 år, men det er opp for diskusjon.
Det er brukt Togglebutton og ikke de innebygde zoom knappene da de ikke støtter å sette en spesifikk startDate
=> Legg til zoom for timeline

apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/ytelseMedGrunnlag/YtelseMedGrunnlagService.kt, apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRepositoryTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/BeregnAvkortingTest.kt
Refaktorering av avkorting / årsoppgjør for å legge til rette for at det vil være avkorting relevant for flere år.
Endrer feltet aarsoppgjoer til å være en liste med samme klasse.
=> Avkorting aarsoppgjoer liste

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
Liten fortsettelse av d3990de1b72f51891466131321a4c9e62735b1db 
Fjerner koden siden den samme funksjonaliteten er bygget inn i `ferdigStillOppgaveUnderBehandling`
=> Fjerne unødvendig kode

apps/etterlatte-beregning/src/main/kotlin/beregning/Beregning.kt, apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRepository.kt, apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt, apps/etterlatte-beregning/src/main/resources/db/migration/V41__status_overstyr_beregning.sql, apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRepositoryTest.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningServiceTest.kt
For å kunne seie at overstyringa ikkje lenger er gyldig.
Regulering avslørte eit scenario der saksbehandlar i ei revurdering la inn overstyrt beregningsgrunnlag og overstyrt beregning, men så avbraut den behandlinga. Dermed vart saka framleis merka som overstyrt beregning, men ingen av dei iverksatte eller pågåande behandlingane hadde overstyrt beregning.
Lager ein mekanisme for å handtere at dette kan skje, sånn at vi da markerer denne overstyringa som ugyldig og i praksis handsamar ho tilsvarande som at det ikkje fins overstyring i det heile tatt.
Forventar ikkje at dette skjer særleg ofte, så trur ein mekanisme kor vi manuelt overstyrer i databasen når det skjer er god nok.
=> Status på overstyrt beregning

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingServiceTest.kt
Fikser muligheten for å oppdatere beregning / avkorting uten å oppdatere vedtaket før fatting, som gjør det mulig å ha mismatch mellom den siste beregningen og det vi utbetaler
=> Oppdaterer vedtak med hentede data ved fatting

gradle/libs.versions.toml
Merk at oppgraderinga er til simpleclients-versjonen. Dette er fordi den vanlege versjonen har breaking changes, som også er dårleg dokumentert i migreringsguiden.
Å bytte til simpleclients-versjonen er det dei tilrår viss du vil ha ei enkel og smertefri oppgradering, så går for det i denne omgang, og satsar på at innan det er på tide å gå bort frå den (den er jo deprecated) så er dokumentasjonen både frå micrometer-folka sjølv og andre langt betre enn det som er no.
=> EY-4000: Oppgraderer til nyaste micrometer

apps/etterlatte-saksbehandling-ui/client/vitest.config.ts
https://stackoverflow.com/questions/72146352/vitest-defineconfig-test-does-not-exist-in-type-userconfigexport
=> Bruk testconfig til tester vite

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt, apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt, apps/etterlatte-behandling/src/test/kotlin/egenansatt/EgenAnsattServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt
Uten dette får man p.t. ikke opprettet manuelt brev da dette trenger grunnlaget for saken.
Fremtidig ønske er å hente grunnlaget for manuelt brev rett fra PDL, da er grunnlagsopplysninger for en sak mindre viktig.
=> leggInnNyttGrunnlagSak alltid

apps/etterlatte-samordning-vedtak/README.md
bakgrunn er at jeg fikk et spørsmål vedr at lenkene ikke fungerte, noe som jo aldri har vært intensjonen
=> Fjernet protokoll fra integrasjonsverdier i dok slik at det ikke genereres klikkbare lenker

apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRegelkjoring.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/ytelseMedGrunnlag/YtelseMedGrunnlagService.kt, apps/etterlatte-beregning/src/main/resources/db/migration/V47__innvilga_maaneder_aarsoppgjoer.sql, apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRegelkjoringTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRepositoryTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/BeregnAvkortingTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts, apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/Beregning.kt, libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt
Det vil alltid forbli det samme etter årsoppgjøret blir opprettet til et eventuelt opphør som først håndteres i et etteroppgjør.
=> Løfter og endrer "relevanteMaanederInnAar" til årsoppgjør som "forventaInnvilgedeMaaneder"

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkorting.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/YtelseEtterAvkortingDetaljer.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadSammendrag.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sanksjon/Sanksjon.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts
Endrer en del på hvordan vi setter spacing / wrapping for å få det konsekvent i beregningsbildet.
Flytter også sanksjoner inn rett ved visning av det som blir beregnet.
=> Rydder i avkortingsbildet og viser informasjon om sanksjon

apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt, apps/etterlatte-beregning/src/main/kotlin/ytelseMedGrunnlag/YtelseMedGrunnlagService.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
Fjerner transitive felter for avkortetYtelseFraVirk og avkortetYtelseForrigeVedtak.
Siden det er kun relevant gjennom DTO så holder det å utlede det ved maping til dto.
=> Flate ut årsoppgjør ved uthenting av avkorting

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt, apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V29__avkortet_ytelse.sql, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/TestHelper.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt
Tenker å ta dette stegvis.
1) Opprette tabell, begynne å populere ved normal operasjon.
2) SQL for å etterpopulere
3) Ta ny tabell i bruk ved uthenting av data
=> EY-4080 Persistere strukturert avkortingsinformasjon i egen tabell i vedtaksvurdering

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakOgBeregningSammenligner.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingServiceTest.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakOgBeregningSammenlignerTest.kt
Avkorting kan medføre fleire/endra periodar frå kva beregning gir, så eksisterande logikk vart misvisande.
=> Samanlikne med avkorting når vi verifiserer match vedtak - beregning/avkorting

apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiverTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/VedtaksbrevUnderkjentRiverTest.kt, apps/etterlatte-statistikk/src/main/kotlin/statistikk/database/StoenadRepository.kt, apps/etterlatte-statistikk/src/main/kotlin/statistikk/domain/StoenadRad.kt, apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt, apps/etterlatte-statistikk/src/main/resources/db/migration/V46__opphoer_fom_og_vedtaksperioder.sql, apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/database/StoenadRepositoryTest.kt, apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/domain/MaanedStatistikkTest.kt, apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/river/VedtakhendelserRiverTest.kt, apps/etterlatte-statistikk/src/test/kotlin/no/nav/etterlatte/statistikk/service/StatistikkServiceTest.kt, apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/VedtakHelper.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/Vedtak.kt, libs/etterlatte-vedtaksvurdering-model/src/main/kotlin/VedtakDto.kt
For å utlede riktig statistikk på måneder må statistikk vite om opphør fra og med, og utbetalingsperiodene sendt i vedtaket.
Oppdatering av eksisterende vedtak, samt oppdatering av hvordan vi mapper ut månedsstatistikken med tanke på opphør kommer i senere PR!
=> EY-4086 oppdaterer stønadsrader i statistikk

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakSamordningService.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakSamordningServiceTest.kt, libs/etterlatte-vedtaksvurdering-model/src/main/kotlin/VedtakDto.kt
=> EY-4080 Benytte data fra avkortet_ytelse_periode tabell i stedet for vedtak.avkorting

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
Validerte ikke riktig noe som medførte at sb ikke fikk lagre gyldige verdier.
Har flyttet validering til RHF som gir bedre og mer korrekt validering av verdiene slik at sb kan fullføre saken sin. 
Gir nå også feilmelding på feltet som ikke er gyldig, i stedet for en generell alert nederst.
=> fikse validering på avkorting

apps/etterlatte-statistikk/src/main/resources/db/migration/V48__fjerner_opphoerte_vedtak_fra_maanedsstatistikk.sql
Disse radene ble med på grunn av feil / manglende logikk i månedsstatistikk
=> EY-4103 Sletter rader for opphørte vedtak

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingServiceIntegrationTest.kt, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
To endringer
- Må tillate å sette oppgave på vent selv om den ikke er tildelt noen saksbehandler for tilbakekreving. Dette fordi vi kan få SPER på kravgrunnlaget fra MQ selv om ingen har begynt på oppgaven.
- Når nytt kravgrunnlag hentes skal tilbakekrevingsbehandlingen settes til UNDER_ARBEID igjen
=> EY-4062: Setter status ved oppdatert kravgrunnlag og fikser paavent håndtering tk

apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/SamordningOppdaterMeldingModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/SamordningSak.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/vedtak/typer.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/vedtaksvurdering.ts, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/Samordningsdata.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/SamordningsKlient.kt
Dette dekker opp manglende funksjonalitet, som man har i Pesys (litt annerledes der).
Rutinen er at om noe haster så ringer saksbehandler opp aktuell TP-ordning for å sjekke opp refusjon, og så legger det inn manuelt i stedet for at systemet venter (i opptil 6 uker, + eventuell purreperiode).
Første versjon her har ikke mulighet for å legge inn refusjonsperiode (fom, tom, beløp, referanse). Tar det separat for ikke å forsinke denne.
Avhengig av deploy av SAM til prod: https://nav-it.slack.com/archives/CQ08JC3UG/p1719301589297069?thread_ts=1719213332.280149&cid=CQ08JC3UG
=> EY-4115 Manuell behandling av samordningsmeldinger v1

apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/TilbakekrevingHendelseRepository.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/config/ApplicationContext.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagConsumer.kt, apps/etterlatte-tilbakekreving/src/main/resources/db/migration/V4__legg_til_status_og_jms_timestamp.sql, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/TilbakekrevingHendelseRepositoryTest.kt, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagConsumerTest.kt, libs/etterlatte-mq/src/testFixtures/kotlin/etterlatte/DummyJmsConnectionFactory.kt
Vi har i produksjon opplevd at en melding har kommet inn og feilet, blitt lagt på backout-queue, mens en ny melding har kommet inn og blitt prosessert. I den aktuelle saken var det ikke et problem da meldingen som feilet kun var en status-oppdatering på tilbakekrevingsoppgaven, men det kan muligens oppstå større problemer med dette i andre saker. 
Legger på en status for hendelser (NY, FERDIGSTILT) og lagrer også `jmsTimestamp` som er tidpunktet meldingen ble lagt på MQ. 
Vi kan da bruke dette for å sikre at en melding som leses fra MQ ikke behandles hvis forrige melding i en sak har status `NY`. I tillegg kan vi bruke `jmsTimestamp` til å sjekke at meldingene ikke prosesseres i feil rekkefølge.
=> EY-4124: Feiler dersom meldinger fra MQ blir forsøkt prosessert i feil rekkefølge

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt, apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/PersonMapper.kt, apps/etterlatte-pdltjenester/src/main/kotlin/personweb/dto/PersonNavnFoedselsaar.kt, apps/etterlatte-pdltjenester/src/main/resources/pdl/hentPersonNavnFoedsel.graphql, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/Behandling.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/soeskenjustering/Soeskenjustering.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.ts, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/GrunnlagForVirkningstidspunkt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/GrunnlagForVirkningstidspunkt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/omstillingsstoenad/Sivilstand.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/Barn.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/Soesken.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/utils.test.ts, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/utils.ts, apps/etterlatte-saksbehandling-ui/client/src/components/person/personopplysninger/Foreldre.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/personopplysninger/Sivilstatus.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/statusbar/Statusbar.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/tags/DoedsdatoTag.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts
Har også fikset at alder regnes ut korrekt i tilfeller hvor bruker er død.
=> EY-4119 Vise hvis bruker er død + standardisere dødsdato tag

apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/TilbakekrevingHendelseRepository.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagConsumer.kt, apps/etterlatte-tilbakekreving/src/main/resources/db/migration/V5__oppdater_sak_til_ferdigstilt.sql, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/TilbakekrevingHendelseRepositoryTest.kt, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagConsumerTest.kt, libs/etterlatte-database/src/main/kotlin/KotliqueryUtils.kt
Her ble det en god gammeldags testing i prod. Det ble innført noen issues med feilhåndteringen som denne PR'en skal fikse.
- Glemt å oppdatere enum i KravgrunnlagConsumer som resulterte i problemer lenger ned i løypa
- Ferdigstill-funksjonaliteten fungerte ikke som forventet, fikset query og fikk dette inn i tester (som det burde vært i utgangspunktet)
- Endret `hent` metoden i repo til å bruke kotliquery som resten, og fikset et par potensielle issues der
- Migrerer to hendelser til `FERDIGSTILT` da disse kom gjennom hele flyten, men feilet på siste oppdateringen. Disse meldingene blir slettet manuelt fra backout-køen på MQ.
=> Fikser problemer innfoert pga feilhaandtering

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/Adressevisning.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAdresse.ts
Har bare på magisk vis fungert tidligere siden alle nullable strings ble automatisk konvertert til dato. 
Når respons fra backend er `null` blir det med `new Date` bare konvertert til `1 januar 1970`... flotte greier.
=> Hotfix: Viser seg at AdresseSamsvar kan mangle gyldigFraDato

apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/LastOppBrev.tsx
Sikrer at saksbehandler får bedre varsel i tilfeller hvor filen er for stor. Blir da også forhindret i å laste opp slik at vi slipper å få `HTTP 413 Content too large`.
=> FAGSYSTEM-334552 Sette maks filstørrelse på opplastet brev

apps/etterlatte-saksbehandling-ui/client/src/components/person/SamordningOppdaterMeldingModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/SamordningSak.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/vedtak/typer.tsx, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/Samordningsdata.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/SamordningsKlient.kt, apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V31__samordning_manuell.sql
- Ønsket sluttstatus i operasjonen fra saksbehandler er at det opprettes et notat med denne informasjonen, men uansett så fremstår det riktig å lagre dette i relevant ey-db.
- Informasjonen som lagres her bør nok også brukes i opphentingen av meldingene, slik at man kan se i samordningsUIet at det er manuelt håndtert (med eller uten kommentaren)
=> EY-4115 Kreve kommentar ved manuell håndtering av samordningsmelding

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
Sjekker januar og ikke februar da getMonth() returnerer 0-indeksert resultat.
=> getMonth() tar utgangspunkt i at januar har indeks 0

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx
Ved virk i januar er det ikke nødvendig å oppgi fratrekk-innår. Dette er løst ved å disable disse feltene, men react-form har validering på feltene slik at det ikke er mulig å lagre. Løser dette med å fjerne at feltene er påkrevet ved `fulltAar`, samt å sette disse til 0 dersom de ikke er satt siden det er påkrevet at de har en verdi i backend.
=> Fratrekk-innår skal ikke være påkrevet når disse feltene er disabled ved inngang i januar  

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/Beregningsgrunnlag.tsx
Hvis en overstyrt beregning deaktiveres, oppdateres ikke visningen korrekt før siden lastes på nytt
Årsaken er feil logikk i endring EY-4168
=> EY-4183 rette feil som oppstår ved deaktivering av overstyrt beregning

apps/etterlatte-samordning-vedtak/.nais/dev.yaml, apps/etterlatte-samordning-vedtak/.nais/prod.yaml
Ref https://nav-it.slack.com/archives/C01KJ597UAU/p1720083496893589
Initielt: kun TP-leverandørene.
Mens spesielt Pesys, selvbetjening og nå etterhvert den nye pensjonskalkulatoren trykker vesentlig mer enn TP.
I tillegg så er det jo på trappene at dette blir etterlatte sin generelle API-app utad.
=> Øker min/max pods for samordning-vedtak pga høyere last enn da verdiene ble initielt satt

apps/etterlatte-samordning-vedtak/.nais/dev.yaml, apps/etterlatte-samordning-vedtak/.nais/prod.yaml
Da selv etter å ha økt ressursene en del så spinnes det opp 4 pods i både dev og prod. Men kan nok tyne CPUen mer, derav denne endringen
https://doc.nav.cloud.nais.io/workloads/application/reference/application-spec/#replicasscalingstrategy
NB! Vi bruker ellers cpuThresholdPercentage, men denne er [deprekert](https://doc.nav.cloud.nais.io/workloads/application/reference/application-spec/#replicascputhresholdpercentage)
=> Lagt til scalingStrategy for samordning-vedtak

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/Notat.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NotatRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NotatSamordning.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NyNotatService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/NotatRiver.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/SamordningsnotatRiver.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/notat/NyNotatServiceTest.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRapidService.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt, libs/etterlatte-vedtaksvurdering-model/src/main/kotlin/VedtakKafkaHendelseHendelseType.kt
Regner med det kanskje kommer noe endringsønsker her, men a) fint å få funksjonaliten/løypa på plass, og b) ikke akkurat verdens mest sentrale logikk. Jeg var inne på tanken og bare gjøre det fra UI, men virker kronglete og virkelig ikke nødvendig.
=> EY-4115 Opprette notat ved manuell samordning

.github/workflows/app-etterlatte-samordning-vedtak.yaml, apps/etterlatte-samordning-vedtak/.nais/dev-api.yaml, apps/etterlatte-samordning-vedtak/.nais/prod-api.yaml
Siden samordning-vedtak skal bli vårt eksterne grensesnitt feks "etterlatte-api" utad er det greit å ha en overgangsperiode der nye konsumenter går mot api delen mens de eksterne som ikke har fått migrert går mot den gamle. På sikt skal de nye api yamlene erstattene dagens dev/prod yamler når konsumentene får byttet over.
=> Legge til api app for samordning for overgang til samordning som api

apps/etterlatte-vedtaksvurdering/.nais/dev.yaml, apps/etterlatte-vedtaksvurdering/.nais/prod.yaml
må ha både samordning og api mens man får eksterne konsumenter over
=> Tilgang for etterlatte-api

.github/workflows/vaktmesteren.yml
~Ingen grunn til å ta vare på alle imagene, og vi har hundre/tusenvis av dem. Har testet det tidligere (https://github.com/navikt/pensjon-docs-site/blob/main/.github/workflows/prune.yml), men da uten matrix.
Tenker også å få inn at man rydder i workflow executions, er bare unødvendig å ta vare på historikk i evighet.~
Rydder nå kun workflow executions, som vi i skrivende stund har 87749 stykker av.
=> Cronjobb for å slette gamle workflow runs

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Foerstegangsbehandling.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManuellRevurdering.kt, apps/etterlatte-behandling/src/main/resources/db/migration/V142__viderefoert_opphoer-tabell.sql, apps/etterlatte-behandling/src/test/kotlin/behandling/ViderefoertOpphoerTest.kt
Jobbar også med frontend-biten, men for å få testa den trengs opppsettet i backend, så kan jo like godt ta backend-delen her først.
Lagrar vidareført opphør i databasen.
Lagrar ned også vilkåret som ikkje lenger er oppfylt
Opphør fom vi skal lagre på behandlinga her er jo eigentleg akkurat samme som for vanleg opphør, så gjenbruker samme dao-metode.
=> EY-4102: Endepunkt og databaseoppsett for videreført opphør

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonVarsel.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/BrevDataMapperFerdigstillVarsel.kt
Når vi no gjer så beregningsvedlegget i varselmalen ikkje blir med viss det er avslag, så kan vi også unngå å hente inn beregningsinformasjonen generelt for avslag. Da omgår vi også alle problema med denne datainnhentinga
FAGSYSTEM-338004
Obs: Heng saman med https://github.com/navikt/pensjonsbrev/pull/811 - så ta QA på denne samtidig.
=> FAGSYSTEM-338004: Ikkje hent utbetalingsinfo for varselbrev viss det er avslag

apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt, apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/TilgangServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageServiceImplTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/RevurderingServiceIntegrationTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingServiceIntegrationTest.kt, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/oppgaveGosys/GosysOppgaveServiceImplTest.kt, apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/saksbehandler/SaksbehandlerServiceImplTest.kt, apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/NotatServiceTest.kt, apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TestHelper.kt, apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidServiceIntegrationTest.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/TestHelper.kt, libs/etterlatte-ktor/src/test/kotlin/no/nav/etterlatte/libs/ktorobo/AzureAdClientTest.kt, libs/etterlatte-ktor/src/testFixtures/kotlin/no/nav/etterlatte/ktor/token/BrukerTokenInfoTestGenerator.kt
Lager også ein parameter som tar inn claims, og ein hjelpemetode for å opprette systembrukar.
Etter denne har vi berre éin plass vi opprettar saksbehandlar-token i testane.
=> EY-4211: Førebuing del 2 av 2: Tar i bruk hjelpemetode for å opprette saksbehandler

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/omregning/OmregningRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/omregning/OmregningService.kt, apps/etterlatte-behandling/src/main/kotlin/common/klienter/PesysKlient.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktOMSService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktOMSServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/JournalfoerBrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiver.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiverTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerTest.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/AutomatiskBehandlingRiver.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/Behandler.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/AvkortingService.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/BehandlingService.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/BeregningService.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/BrevService.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/GrunnlagService.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/TrygdetidService.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/VedtaksvurderingService.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/automatisk/VilkaarsvurderingService.kt, libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt
Og bruker `brukerTokenInfo` frå kallet der vi har det tilgjengeleg.
Målbildet er at vi kun bruker systembruker-hardkodinga frå ein automatisk jobb eller frå rivers, kor vi faktisk ikkje har eit kallande system. Kjem ein eller fleire PRs etter denne som går vidare.
(Denne er første del i ei meir strukturert tilnærming til å ende ca samme plass som https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5392 )
=> EY-4211: Flyttar hardkoding av systembrukarar heilt ut til job og river

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/ListenerMedLogging.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/ListenerMedLoggingOgFeilhaandtering.kt
I dag svelgjer vi unna exceptions som skjer her (dvs det hamnar i onSevere, som er ein noop-metode). Med denne loggar vi det ordentleg.
=> Ordentleg logging av exceptions i r&r-listeners

apps/etterlatte-behandling/src/main/kotlin/Application.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/OppdaterAktivitetspliktRepo.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/SendTilStatistikkJob.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/resources/db/migration/V145__resend_aktivitetsplikt_statistikk_tabell.sql
for alle saker som har registrert noe i basen, for å dekke de tilfellene der det ikke ble sendt før nå.
Enkel jobb som bare prøver å sende 100 saker i gangen, hvert femte minutt. Tabell og kodeendringer skal fjernes etter at sakene er jobbet igjennom.
=> EY-4155 Sender aktivitetspliktDto til statistikk

apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/ApplicationLocalhost.kt, apps/etterlatte-grunnlag/src/main/kotlin/Application.kt, apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-migrering/src/main/kotlin/Application.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/Application.kt, apps/etterlatte-opplysninger-fra-soeknad/src/main/kotlin/Application.kt, apps/etterlatte-statistikk/src/main/kotlin/Application.kt, apps/etterlatte-statistikk/src/main/kotlin/statistikk/config/ApplicationContext.kt, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-trygdetid-kafka/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/config/ApplicationContext.kt, apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/ApplicationIntegrationTest.kt, apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/Application.kt, apps/etterlatte-vilkaarsvurdering-kafka/src/main/kotlin/no/nav/etterlatte/Application.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/InitRogR.kt
I dag gjer vi initialisering og oppstart av appane våre på mange forskjellige måtar.
Nokre forskjellar er det, men stort sett ønskjer vi å gjera det samme for kvar applikasjon vi startar opp. Den kognitive lasten vil bli mindre viss vi sørgjer for at vi gjer det likt der det kan og bør vera likt.
Startar i ein ende ved å ta applikasjonane som er basert på rapids and rivers, og får dei over på samme underliggjande init-metode. Med det sikrar vi at ting er likt, og i tillegg får vi innkapsla mykje av r&r-oppsettskoden i r&r-biblioteket vårt, sånn at det ikkje lekkjer ut i resten av kodebasen, kor det i stor grad er teknisk støy.
Har andre idear til oppfølgings-endringar, som kanskje eller kanskje ikkje kjem som PRs, er litt usikker på kor omfattande og knotete det er:
- statuslisteners på …
=> EY-4233: Samkøyrer initialiseringa av R&R-appane våre

gradle/libs.versions.toml, libs/etterlatte-ktor/build.gradle.kts, libs/etterlatte-ktor/src/main/kotlin/RestModule.kt, libs/etterlatte-ktor/src/main/kotlin/feilhaandtering/EscapeUtils.kt, libs/etterlatte-ktor/src/main/kotlin/feilhaandtering/StatusPagesKonfigurasjon.kt, libs/etterlatte-ktor/src/test/kotlin/no/nav/etterlatte/feilhaandtering/EscapeUtilsTest.kt
Viss vi får feil under deserialisering, er det veldig greitt å veta kva request-objektet som feila var. Loggar derfor det ut i rein tekst til sikkerlogg.
For å få til det må vi konfigurere opp ktor til å la oss køyre receive på requesten fleire gongar, så innfører double receive-pluginen til ktor for å opne for det.
Dette er jo ein trade-off, å innføre ein ny plugin kun for dette, samtidig gjer det feilsøkinga såpass mykje enklare i desse høva at eg tenkjer at det er verdt det.
=> EY-4241: Loggar requestobjektet som tekst ved feilande deserialisering

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BarnepensjonSammendrag.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/soeskenjustering/Soeskenjustering.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts
Hvis det ligger lagret en søskenjustering som ikke har med alle søsken i periodene for justering, vises det nå et varsel til saksbehandler, og de har mulighet til å legge til de manglende søskenene.
Løser porten-sak FAGSYSTEM-339480
Her er en revurdering av en sak som opprinnelig ikke hadde noen søsken, men et nytt barn til avdøde ble lagt til etter innvilgelse:
etter trykk på knappen for å oppdatere søsken:
=> EY-4235 Gjør det mulig å legge til manglende søsken

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/vilkaarsvurdering/VilkaarsvurderingKlient.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/vilkaarsvurdering/VilkaarsvurderingService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelse.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelseForeldreloes.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonRevurdering.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgetDTOTest.kt, apps/etterlatte-vilkaarsvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/services/VilkaarsvurderingService.kt, apps/etterlatte-vilkaarsvurdering/build.gradle.kts, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/Application.kt, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/MigrertYrkesskadeOppdaterer.kt, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRepository.kt, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRoutes.kt, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingService.kt, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/config/ApplicationContext.kt, apps/etterlatte-vilkaarsvurdering/src/main/resources/db/migration/V24__migrert_yrkesskade.sql, apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/MigrertYrkesskadeTest.kt, libs/etterlatte-vilkaarsvurdering-model/src/main/kotlin/vilkaarsvurdering/MigrertYrkesskadefordel.kt
Avhengig av https://github.com/navikt/pensjonsbrev/pull/823
For migrert yrkesskadefordel er maksalder for å få barnepensjon 21 år. Det må også gjenspeglast i brevet.
Det er nokre fleire brev og brevfragment der vi har hardkoda inn 20 år også. Er litt usikker på kor 21 er relevant der, så tar ikkje det i denne omgang, kun der det faktisk er aktuelt no - altså innvilgelsesbrev.
=> FAGSYSTEM-328806: For migrert yrkesskadefordel er maksalder for BP 21 år

libs/etterlatte-ktor/src/main/kotlin/feilhaandtering/StatusPagesKonfigurasjon.kt
Ser i loggane at vi får "En feil har oppstått ved deserialisering. Requestobjektet var ", så da har vi ikkje fått objektet. Prøver å bytte over frå receiveText til receive<String>, for å sjå om det gjer nokon forskjell. Legg også på logging av antal teikn i requestobjektet, for å utelukke at det er escapinga som kåler det til
=> Nytt forsøk på å logge requestobjekt ved deserialiseringsfeil

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/vilkaar/OmstillingstoenadVilkaar.kt, libs/etterlatte-vilkaarsvurdering-model/src/main/kotlin/vilkaarsvurdering/VilkaarType.kt
Saker med det gamle vilkåret vil bli tvunget til å svare ut det nye vilkåret ved neste revurdering.
EY-4146
=> Endrer vilkåret som går på krav til aktivitet.

apps/etterlatte-beregning/src/main/kotlin/ytelseMedGrunnlag/YtelseMedGrunnlagService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/behandling/Beregning.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/beregning/BeregningService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EtterlatteBrev.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadRevurdering.kt, libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt
Sender nå med hele sanksjonen fra beregning slik at man lettere kan bruke den senere. I brevet er det per dags dato kun nødvendig å vite om det finnes en sanksjon eller ikke.
=> EY-3940: Legg til sanksjon i ytelse med grunnlag periodisert

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/KodeverkKlient.kt, libs/saksbehandling-common/src/main/kotlin/feilhaandtering/ForespoerselException.kt
Sikrer også at våre logger ikke blir spammet ned når kodeverk har nedetid/trøbbel.
=> Gi saksbehandler bedre feilmelding når kodeverk gir timeout

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/KodeverkKlient.kt
`io.ktor.network.sockets.SocketTimeoutException` og `io.ktor.client.network.sockets.SocketTimeoutException` er for sikkerhets skyld ikke samme
=> bruke SocketTimeoutException fra riktig pakke

.github/workflows/.build-and-deploy.yaml, .github/workflows/.lib-test.yaml, .github/workflows/.test.yaml, buildSrc/src/main/kotlin/etterlatte.common.gradle.kts, gradle.properties, libs/etterlatte-regler/build.gradle.kts
Skrur på Gradle configuration cache
Ifølgje dokumentasjonen (https://docs.gradle.org/current/userguide/configuration_cache.html) skal Gradle configuration cache gjera at bygg skal gå raskare, ved å gjenbruke konfig frå cache, omtrent tilsvarande som korleis caching elles funkar i Gradle.
Det er ikkje alle plugins som er støtta, men det ser ut som dei fleste viktige er det, så tenkjer vi kan teste det ut.
=> Skrur på konfigurasjonscachen i Gradle

.github/workflows/.build-and-deploy.yaml, .github/workflows/.lib-test.yaml, .github/workflows/.test.yaml
Det sparer ein del tid under bygg, og eg trur det skal vera godt nok for alt vi kan komme borti av problematikk. Sjølvsagt ei avveging, men tida vi sparer for kvart PR-bygg trur eg er verdt det
=> Køyrer kun lisenssjekken ved deploy, og verifiserer at denne er ok før deploy til prod

apps/etterlatte-behandling/build.gradle.kts, apps/etterlatte-samordning-vedtak/build.gradle.kts, apps/etterlatte-testdata/build.gradle.kts, gradle/libs.versions.toml, libs/etterlatte-ktor/build.gradle.kts, libs/rapidsandrivers-extras/build.gradle.kts
EY-4264: Ekskluderer ktor-avhengnadane vi får inn transitivt gjennom openapi, rapids&rivers og token-biblioteket. Kjens mykje tryggare å sjølv deklarere desse og spesifisere rett versjon.
Er eit lite dilemma her om vi skal ekskludere alt under io.ktor her, men det ber jo også med seg ein risiko for at vi plutseleg manglar ein avhengnad i runtime viss desse biblioteka endrar kva dei er avhengige av, så da kjens det greiare å spesifisere opp eksplisitt.
Er litt usikker på forholdet mellom ktor-server og ktor-server-core, samt mellom ktor-server-core og ktor-server-core-jvm, så må teste litt før eventuell merge.
=> EY-4264: Ikkje importer ktor-avhengnadar transitivt frå andre

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingServiceImplTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/revurderingsoversikt/GrunnlagForVirkningstidspunkt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/Virkningstidspunkt.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
I enkelte revurderinger kan det være aktuelt å sette virkningstidspunkt til et tidspunkt som er _før_ det opprinnelige virkningstidspunktet de satt på førstegangsbehandlingen som er iverksatt. 
Endringen her kaster feilmelding og gir saksbehandler mulighet til å overstyre med ny virk, selv om den er "ugyldig". 
Liten advarsel når nytt virk er før første virk:
=> FAGSYSTEM-335584 Støtte setting av virk FØR første iverksatte virk

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/utbetaling/Utbetaling.kt
Erstatter https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5517 pga for langt branch-navn som medførte issues ved bygg.
=> EY-4295: Legge til klassekode for feilutbetaling omstillingsstønad

apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/handling/StartOppgavebehandling.tsx
Siden ny behandling eller klage opprettes med utgangspunkt i brukeren tilknyttet oppgaven må vi forhindre at saksbehandler oppretter på feil person. 
Funksjonalitet for overføring til annen bruker er bak feature toggle, men skal åpnes så snart denne endringen er ute.
=> Låse klage + bedre feilmelding ved ulik bruker på oppg. og journalpost

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
Skulle eigentleg vore med i https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5532 , men oppdaga det litt for seint
=> Oppdaga at foreldreløs-funksjonsbrytaren også er i bruk i frontend

.github/workflows/.build-and-deploy.yaml, .github/workflows/app-etterlatte-behandling.yaml, .github/workflows/app-etterlatte-beregning-kafka.yaml, .github/workflows/app-etterlatte-beregning.yaml, .github/workflows/app-etterlatte-brev-api.yaml, .github/workflows/app-etterlatte-egne-ansatte-lytter.yaml, .github/workflows/app-etterlatte-grunnlag.yaml, .github/workflows/app-etterlatte-gyldig-soeknad.yaml, .github/workflows/app-etterlatte-hendelser-joark.yaml, .github/workflows/app-etterlatte-hendelser-pdl.yaml, .github/workflows/app-etterlatte-hendelser-samordning.yaml, .github/workflows/app-etterlatte-institusjonsopphold.yaml, .github/workflows/app-etterlatte-klage.yaml, .github/workflows/app-etterlatte-migrering.yaml, .github/workflows/app-etterlatte-oppdater-behandling.yaml, .github/workflows/app-etterlatte-opplysninger-fra-soeknad.yaml, .github/workflows/app-etterlatte-pdltjenester.yaml, .github/workflows/app-etterlatte-samordning-vedtak.yaml, .github/workflows/app-etterlatte-statistikk.yaml, .github/workflows/app-etterlatte-testdata-behandler.yaml, .github/workflows/app-etterlatte-testdata.yaml, .github/workflows/app-etterlatte-tidshendelser.yaml, .github/workflows/app-etterlatte-tilbakekreving.yaml, .github/workflows/app-etterlatte-trygdetid-kafka.yaml, .github/workflows/app-etterlatte-trygdetid.yaml, .github/workflows/app-etterlatte-utbetaling.yaml, .github/workflows/app-etterlatte-vedtaksvurdering-kafka.yaml, .github/workflows/app-etterlatte-vedtaksvurdering.yaml, .github/workflows/app-etterlatte-vilkaarsvurdering-kafka.yaml, .github/workflows/app-etterlatte-vilkaarsvurdering.yaml
Innførte Gradle configuration cache i https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5494, men oppdagar at han ikkje funkar utan at vi har sett _encryption-key_-variabelen i byggejobben, så definerer opp den.
https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#optimizing-cache-effectiveness
Inspirert av [løysinga frå dagpenger](https://github.com/navikt/dp-behandling/blob/main/.github/workflows/deploy.yaml).
=> EY-4287: Konfigurerer opp configuration cache for Gradle

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingRoutesIntegrationTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingServiceIntegrationTest.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/klienter/BehandlingKlient.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagService.kt, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagServiceTest.kt
Hvis et kravgrunnlag for eksempel blir avsluttet fordi det er motregnet mot uføretrygd, blir tilbakekrevingen som er opprettet avbrutt. Denne endringen legger på en merknad i oppgaven, slik at det blir tydeligere hvorfor dette skjedde. 
Tilsvarende vil det også legges på en merknad dersom en tilbakekreving blir avbrutt fordi det har kommet endringer på kravgrunnlaget.
=> EY-4160: Viser årsak ved avbrutt tilbakekreving

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/FeilutbetalingUtils.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/Brevutfall.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallVisning.tsx, libs/saksbehandling-common/src/main/kotlin/behandling/Brevutfall.kt
Legger til ekstra valg for brevutfall og feilutbetaling hvor saksbehandler kan velge at det ikke legges ved vedlegg ved feilutbetaling fordi kravet vil bli nullet ut eller endres som følge av motregning mot annen ytelse.
=> EY-4010: Legger til brevutfallvalg for feilutbetaling ved motregning mot annen ytelse

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/avstemming/GrensesnittsavstemmingJob.kt, apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/config/ApplicationContext.kt, apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/avstemming/GrensesnittsavstemmingsJobTest.kt
Kjører grensesnittavstemming for 3. og 4. januar på nytt etter forspørsel fra økonomi. Både for BP og OMS. Disse dagene hadde blit kjørt sammen av en eller annen grunn (sannsynligvis fordi utbetaling var nede i tidsrommet jobben skulle kjørt i første gang). 
Endringene her fjernes så fort kjøringen er gjort.
=> FAGSYSTEM-340116: Kjøre avstemming for 3. og 4. januar på nytt

apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingRoutesTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingsstatusRoutesTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseRouteTest.kt, apps/etterlatte-behandling/src/test/kotlin/sak/SakRoutesTest.kt, apps/etterlatte-behandling/src/test/kotlin/tilgangsstyring/TilgangsstyringTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRoutesTest.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningRoutesTest.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/OversendelsesbrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/dokument/DokumentRouteTest.kt, apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/BehandlingGrunnlagRoutesKtTest.kt, apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/PersonRoutesTest.kt, apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/SakGrunnlagRoutesKtTest.kt, apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/aldersovergang/AldersovergangTest.kt, apps/etterlatte-pdltjenester/src/test/kotlin/person/PersonRouteTest.kt, apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/sak/BehandlingSakRoutesTest.kt, apps/etterlatte-samordning-vedtak/src/test/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRouteTest.kt, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/TilbakekrevingRoutesTest.kt, apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidRoutesTest.kt, apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/avtale/AvtaleRoutesTest.kt, apps/etterlatte-utbetaling/src/test/kotlin/no/nav/etterlatte/utbetaling/simulering/SimuleringOsRouteTest.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/SamordningsvedtakRouteTest.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRouteTest.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/migrering/AutomatiskBehandlingRoutesKtTest.kt, apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/AldersovergangRoutesTest.kt, apps/etterlatte-vilkaarsvurdering/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt, libs/etterlatte-ktor/src/test/kotlin/RestModuleTest.kt, libs/etterlatte-ktor/src/testFixtures/kotlin/no/nav/etterlatte/ktor/KtorEnvironmentTestConfigOauth.kt
Hindrer feil i testkjøringer / delays ved bruk av samme port. Vi hadde flere som kjørte på port 1234
bedre å bruke start() som gir random port, gjør det tydeligere med extension function og renamer mockAuthServer var lik overalt.
=> Kun randomized port for mockauthservder

apps/etterlatte-behandling/src/main/kotlin/common/klienter/PesysKlient.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt
Pesys behandler ikke lengre dødsmeldinger for OMS eller BP, vi kan fjerne oppslag mot Pesys for å se om sak har blitt behandlet der.
EY-4324
=> Ikke gjør oppslag mot Pesys for å sjekke behandlingsstatus

apps/etterlatte-behandling/.run/etterlatte-behandling.dev-gcp.run.xml, apps/etterlatte-behandling/src/main/kotlin/Application.kt, apps/etterlatte-behandling/src/main/kotlin/krr/KrrKlientImpl.kt, apps/etterlatte-behandling/src/main/kotlin/krr/KrrResponse.kt, apps/etterlatte-behandling/src/main/kotlin/krr/KrrRoute.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottaker.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/krr.ts, apps/etterlatte-saksbehandling-ui/server/src/index.ts
Viser nå brukers valg i KRR i mottakerpanelet på brevsiden. Dette gjør det enklere for saksbehandler å vite om brevet sendes digitalt eller ei, og om de er nødt til å tvinge sentral print…
=> EY-4317 Vise brukers valg i KRR til saksbehandler

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/SimulerUtbetaling.tsx
Det kommer nå opp en melding som ser ut som en feilmelding, mens dette er en helt forventet respons i mange tilfeller hvor ytelsen ikke kommer til utbetaling, feks ved avkorting til 0.
=> EY-4327: Endrer tekst ved simulering av 0-utbetaling

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/institusjonsopphold/InstitusjonsoppholdBeregningsgrunnlagSkjema.tsx
Pr nå så vises egen reduksjon selv om saksbehandler velger noe annet. Dette blir veldig misvisende da det ikke i disse tilfellene brukes i beregningen. 
Grunnen til at det skjer, er fordi feltet blir stuck i skjemaet med mindre man setter på `shouldUnregister: true`.
=> EY-4294: Fjerner egen reduksjon når et annet valg velges for institusjon

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktDaoTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktTidslinje.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/NyAktivitet.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/aktivitetsplikt.ts
Har nå lagt til muligheten for å legge til, endre og slette aktivitet fra sak. 
Alt er lagt parallelt med måten man gjør det med behandling, men siden man nå kan slette og endre ting som tidligere er lagt på behandling så burde man kanskje skrive om den delen til å basere seg på sakId og ikke behandling?
=> La saksbehandler legge til, endre og slette aktivitet fra sak

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/opphoer/OpphoerIntegrationTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/viderefoere-opphoer/ViderefoereOpphoerVurdering.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts
Dumt å sende inn en tom string når man forventer 0 eller en string som er en gyldig `vilkaarType`.
=> Ikke send inn tom streng for vilkaartype

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
Ref FAGSYSTEM-343341: sette status til Ny ved enhetsendring, så ny enhet kan prioritere innkommende saker korrekt
=> Sette status til ny på oppgaver når man endrer enhet på sak og oppgaver

libs/etterlatte-ktor/src/main/kotlin/feilhaandtering/StatusPagesKonfigurasjon.kt, libs/saksbehandling-common/src/main/kotlin/feilhaandtering/InternfeilException.kt
Nå logges bare standard "En intern feil oppstod i et endepunkt. Svarer frontend med 500-feil"
Selvom vi har definert en feilmelding i `internfeil.message` som ikke brukes, mye tydligere feil i loggen om vi forsøker å vise denne meldingen.
=> Logg message fra egendefinert exception, ikke generell feilmelding

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/GrunnlagServiceImpl.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/GrunnlagKlient.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilgang/TilgangRoutes.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/ManuellRevurderingServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt
Tidligere brukte man bare systembruker mot grunnlag i opprett behandling e.l. noe som ikke var intensjonen. Setter på det for now siden det er låst inni inTransaction slik at man får opprettet behandlinger og revurderinger
=> Send inn systembruker for grunnlag ved opprett behandling/revurderinger

libs/etterlatte-ktor/src/main/kotlin/feilhaandtering/StatusPagesKonfigurasjon.kt, libs/saksbehandling-common/src/main/kotlin/feilhaandtering/InternfeilException.kt
Hvis feilen selv ikke setter message så får vi i alle fall feilklassen i loggene. Gjør også UkjentInternfeilException umulig å bruke utenfor StatusPagesKonfigurasjon.
=> Legger på canonical name til klassen som feilen har

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingValidering.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/tilbakekreving/TilbakekrevingBrevData.kt, apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/vurdering/TilbakekrevingVurderingSkjema.tsx
Må kunne sende over vedtaksdato når det er angitt at varsel var åpenbart unødvendig. Dette fordi vi har gamle saker hvor det ikke ble sendt med forhåndsvarsel i brev.
=> FAGSYSTEM-343711: Sender med varseltype til brev for tilbakekreving

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/grunnlag/GrunnlagService.kt
Avklarer de også som "UkjentVergemaal". Loggen vår er mest for å fange opp at dette skjer, slik at vi kan se om vi trenger noe ekstra håndtering på dette tilfellet.
=> Logger tilfeller der vi har verge uten ident til feil

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonBeregning.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgetDTOTest.kt
Siden avdoedeForeldre ikke populeres på beregninger på gammelt regelverk må vi benytte trygdetidForIdent for å finne den avdøde på gamle perioder (her garanterer vi at vi har kun en avdød, siden det er kun det vi støtter på gammelt regelverk)
=> Håndterer beregninger på gammelt regelverk i utledning av tt-grunnlag

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
Fjerner SB før flytt, da status 'ny' ikke fører til fjerning av SB
=> Fjerne SB før flytting, så vi ikke beholder SB når status blir NY

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktService.kt, apps/etterlatte-statistikk/src/main/kotlin/statistikk/clients/BehandlingKlient.kt, apps/etterlatte-statistikk/src/main/kotlin/statistikk/service/StatistikkService.kt
Hvis det ikke ligger inne noen avdød i persongalleriet vil oppdateringen av aktivitetsplikt til statistikk feile (behind the scenes). Hvis dette skal være et vedtak, og vurderingene som blir gjort av saksbehandler på aktivitet ikke gjøres etter at persongalleriet er korrigert, så vil ikke aktivitetspliktdataene sendes på nytt.
Dette løses ved at statistikk henter dto for alle OMS-vedtak, og dermed sikrer at vi har riktig informasjon om oppfyllelsen av aktivitetsplikt også når det glipper.
Feil før en sak er vedtatt er litt mer chill på logging, siden det uansett skal fikses i statistikk der det logges feil hvis vi ikke finner riktig dødsdato på innvilgede saker.
=> EY-4377 Har litt ekstra håndtering for aktivitetspliktDto-sending

.github/dependabot.yml
Draft fordi det er noko feil med nyaste versjon av lisenssjekkaren
=> Samlar lisenssjekk- og swagger-ui-avhengnadane med resten i dependabot-konfigen

apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt, apps/etterlatte-beregning/src/main/kotlin/klienter/BehandlingKlient.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BarnepensjonSammendrag.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/OmstillingsstoenadSammendrag.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/flereAvdoede/BeregningsMetodeRadForAvdoed.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/institusjonsopphold/InstitusjonsoppholdBeregningsgrunnlagSkjema.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/institusjonsopphold/InstitusjonsoppholdBeregningsgrunnlagTable.tsx
Når beregningsgrunnlag oppdateres, settes status til forrige status for behandlingen som er TRYGDETID_OPPDATERT. Dette for å unngå at det er mulig å gjøre endringer i beregningsgrunnlag, for så å gå til beregning via stegviseren uten å kjøre beregning på nytt.
Denne erstatter https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5701 pga langt branchnavn.
=> EY-4359: Endrer status til TRYGDETID_OPPDATERT ved endringer av beregningsgrunnlag

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NotatRepository.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NotatRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NotatService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NyNotatService.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/BehandlingSidemeny.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/NotatPanel.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/DokumentInfoDetail.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/notat/NotatRedigeringModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/notat.ts
Notat opprettes med referanse til behandlingen, men henter alle som er tilknyttet saken. Mulig det blir filtrert litt på sikt. Avventer eventuelle tilbakemeldinger fra saksbehandlere.
Notater vil vises under "Dokumenter"-fanen på en behandling. Journalførte notater vil kun bli vist som journalpost.
=> EY-4330 Notat i behandling

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningService.kt, apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt, apps/etterlatte-beregning/src/main/kotlin/klienter/BehandlingKlient.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/BeregningServiceTest.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/overstyrGrunnlagsBeregning/OverstyrBeregningsgrunnlagPeriodeSkjema.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/overstyrGrunnlagsBeregning/OverstyrtBeregningsgrunnlagTable.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/overstyrGrunnlagsBeregning/SkruAvOverstyrtBeregningModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/overstyrGrunnlagsBeregning/SkruPaaOverstyrtBeregning.tsx
Når overstyrt beregning oppdateres, settes status til forrige status for behandlingen som er TRYGDETID_OPPDATERT. Dette for å unngå at det er mulig å gjøre endringer i overstyrt beregning, for så å gå til beregning via stegviseren uten å kjøre beregning på nytt.
=> EY-4359: Setter TRYGDETID_OPPDATERT ved endring på overstyrt beregning

apps/etterlatte-behandling/src/main/resources/db/migration/V158__kommer_barnet_til_gode.sql
I EY-2349 splitta vi alt i fjor sommar denne informasjonen ut i ein eigen tabell. Tanken var heile tida å fjerne kolonna frå behandling, men vi ville gi det nokre veker først for å sjå at alt framleis fungerte. Det gjorde det, så no er det på tide å rydde opp.
I EY-2349 migrerte vi eksisterande data ut i den nye tabellen, så det som ligg i kolonna i behandling er ikkje lenger i bruk eller nyttig
=> EY-2476: Rydd bort kommer barnet til gode frå behandlingstabellen.

apps/etterlatte-saksbehandling-ui/server/package.json, apps/etterlatte-saksbehandling-ui/server/yarn.lock
path-to-regexp-biblioteket har, i versjonar brukt i Express < 4.20, ei sårbarheit. Ved å oppgradere Express, blir vi med det samme kvitt denne CVE-en
Samme fiks for søknadsdialogane: https://github.com/navikt/pensjon-etterlatte/pull/1461
=> Oppgraderer Express, for å rette CVE transitivt

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/klage/KlageServiceImplTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/klage/sidemeny/KlageSidemeny.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/klage/sidemeny/RedigerMottattDato.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/klage.ts, libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/Klage.kt, libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/klage/StatistikkKlage.kt
Kun når klagen er redigerbar -- for å kunne selv fikse på feil i registrering etc.
Det logges og registreres en hendelse i databasen når dette gjøres, for å ha sporbarhet på endringen.
Etter at "Rediger klagedato" er trykket på
=> EY-4396 Gir saksbehandler mulighet til å endre klagedato

apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt
Dersom sb ikke har tilgang til enhet får de en sykt vag feilmelding, noe som medfører at vi får masse spørsmål om hvorfor noe ikke fungerer. Ved å endre feilmeldingen de får vil det (forhåpentligvis) spare oss for unødvendig debugging. 
Ser slik ut i prod p.t.
=> Forbedre feilmeld til sb ved manglende tilgang til enhet (403)

apps/etterlatte-oppdater-behandling/src/main/kotlin/Application.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/OmregningFeiletRiver.kt, apps/etterlatte-oppdater-behandling/src/test/kotlin/regulering/OmregningFeiletRiverTest.kt
Det er ikkje forventa, skal i prinsippet ikkje skje, og når det skjer bør vi som oftast følgje det opp.
Døper med det samme om klassa, for denne bør vera lik for alle typar omregningar
=> Viss omregning feilar, bør vi logge det som error, ikkje info

apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt
- Legger til opphørsdato i avkortingsgrunnlag som kopieres
- Ved nytt avkortingsgrunnlag, vil eksisterende periode endre tom-dato fra opphørsdato - 1 til virkningstidspunkt - 1
=> EY-4414: Opphør mangler dersom dette er satt i en revurdering av OMS

apps/etterlatte-behandling/src/main/resources/db/prod/V160__slette_duplikate_mangler_soeknad_oppgaver.sql
Det finnes 42 oppgaver for `SOEKNAD_MANGLER`, hvorav 35 av de er duplikater som ikke skulle vært opprettet. 
Dette fjerner de som er feilaktig opprettet.
=> FAGSYSTEM-346194 Slette duplikatoppgaver for SOEKNAD_MANGLER

apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/DelvilkaarRepository.kt, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRepository.kt, apps/etterlatte-vilkaarsvurdering/src/main/resources/db/migration/V25__endre_schema.sql
Endrer skjema til å matche det som er definert i https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/5723
slik at vi kan overføre data i gcp buckets uten større problemer med flyway scriptene som er definert i vilkårsvurdering sin tabell.
=> Endre skjema i vilkårsvurdering før migrering av database

libs/etterlatte-ktor/src/main/kotlin/initialisering/EmbeddedServerConfig.kt
Frå lokalt (Running er der vi sett true i dag, Setting ready er den nye):
=> No sett vi readiness litt for tidleg, så vi kan heller vente litt

apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
Se fagsak: https://jira.adeo.no/browse/FAGSYSTEM-344020?filter=-1
I det tilfelle hvor forrigeGrunnlag er null (pga overstyrt beregning) er det heller ingen avvik, vi kan derfor returnere at det ikke er avvik på soeskenjustering, institusjonsopphold ettersom vi ikke har noe å sammenligne med
=> FAGSYSTEM-344020  rette feil når forrigeGrunnlag er null pga overstyrt beregnet

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/barnepensjon/FamilieforholdBarnepensjon.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/Virkningstidspunkt.tsx
Hvis det var to avdøde, så ville virk bli begrenset til en av dødsdatoene. Sørger nå for at det er den tidligste avdøde som brukes.
=> EY-4430: Begrenser valgbare virkningstidspunkt til å være etter det første dødsfallet. Før ble det brukt et vilkårlig dødsfall.

apps/etterlatte-beregning/.nais/dev.yaml, apps/etterlatte-brev-api/.nais/dev.yaml, apps/etterlatte-grunnlag/.nais/dev.yaml, apps/etterlatte-statistikk/.nais/dev.yaml, apps/etterlatte-tidshendelser/.nais/dev.yaml, apps/etterlatte-trygdetid/.nais/dev.yaml, apps/etterlatte-utbetaling/.nais/dev.yaml, apps/etterlatte-vedtaksvurdering/.nais/dev.yaml, apps/etterlatte-vilkaarsvurdering/.nais/dev.yaml
GCP sier `Underprovisioned resource` for disse instansene fordi de bruker for mer minne enn sqlinstansen vi spesifisierer.
=> Bumpe til 1GB minne for db i dev

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/VedtaksbrevService.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
Sikrer at saksbehandler får feilmelding i tilfeller hvor PDF-en ikke er ferdig generert og lagret når de forsøker å attestere (ferdigstille).
=> Gi sb feilmelding når PDF ikke er ferdig generert ved ferdigstilling

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
Skrur tilbake deler av 44303d3f3cf40011d198ce9191d78b3e188f7a5e 
Siden ny søknad ikke lenger avbryter automatisk kan denne koden forbli inntil vi anser den unødvendig.
=> EY-3270 Legge tilbake avbryt behandling (delvis)

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperRedigerbartUtfallVedtak.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EtterlatteBrev.kt
Vi får en del feil med `Required value was null.` pga manglende brevutfall. Endrer til `UgyldigForespoerselException` slik at dette ikke kommer opp i loggene våre. Så lenge bruker får en beskrivende melding her, vet de hva som må gjøres.
=> Bedre feilmelding ved manglende brevutfall

apps/etterlatte-behandling/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/vilkaarsvurdering/service/VilkaarsvurderingService.kt
Gjelder feil i prodlogger hvor vi ikke får ut hva som faktisk feiler pga manglende stacktrace.
Burde nok skrives om til å bruke ForespoerselException eller tilsvarende, men nå må prodissue løses.
=> Legger på stacktrace ved BehandlingstilstandException

apps/etterlatte-saksbehandling-ui/server/src/middleware/getOboToken.ts
Basert på et par feil som oppstod i prod forrige uke, så endres feilhåndteringen slik at feil catches og logges fremfor å sende feil videre til default error-handler. Dette gjør at stacktrace blir riktig logget i stedet for å bli splittet over mange logg-entries.
=> Fikser feilhåndtering ved uthenting av obo-token

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationBuilder.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevoppretter.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/JournalfoerBrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/PDFGenerator.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/oversendelsebrev/OversendelseBrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtaksbrev/VedtaksbrevRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtaksbrev/VedtaksbrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/VedtaksbrevUnderkjentRiver.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/DistribuerBrevRiverTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiverTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/rivers/VedtaksbrevUnderkjentRiverTest.kt
Liten rydding ifm at jeg ser på brev-api
Brevoppretter bør være generell og ikke ha kode for vedtaksbrev imo, flytter det til vedtaksbrevService
=> Forbedring brev-api vedtaksbrev

apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/notat/NyNotatServiceTest.kt
Burde på sikt lage et bedre system for å ha 1-1 på dataobjektet som leses av pdfgen.
=> FAGSYSTEM-347262 Sikre at JsonNode for pdfgen er korrekt

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/Behandling.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/generellbehandling/GenerellBehandling.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/klage/Klagebehandling.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrev.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/BehandleJournalfoeringOppgave.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/Tilbakekrevingsbehandling.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/statusbar/Statusbar.tsx
Dagens løsning gjør at det kan være diff i statusbar mellom `Behandling` og de andre sidene som bruker den. 
Et eksempel på noe som kan skje er at bruker dør. Dette vil vises med en tag på _alle_ sider, med unntak av behandling. 
Denne endringen gjør følgende: 
- Sikrer at `StatusBar` viser det samme på _alle_ sider. 
- Fjerner unødvendig kode. 
Avklart OK med fag!
=> Sikre at statusbar ALLTID har sanntidsdata fra PDL

apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/LastOppBrev.tsx
Fikser error: 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'size')
```
Kom dersom saksbehandler valgte fil, trykket "velg fil" igjen, og deretter avbrøt valget. Target var i det tilfellet udefinert, noe som medførte "kræsj". 
----- 
Slang også på en liten knapp for å tilbakestille opplastingen.
=> Sjekke om fil er null & støtte tilbakestilling

apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktAvdoedService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktBarnService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/mellomAttenOgTjueVedReformtidspunkt/BehandleDoedshendelseKontrollpunktService.kt
Dette er ikke nødvendig for denne jobben siden dette hendte bakover i tid og personene er over 18 år.
=> EY-4478: Fjerner kontrollsjekk av samtidig dødsfall for utsendelse mellom 18 og 20 år

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx
I stedet for å kaste en Error og logge til backend, som også tar ned visningen av beregningskomponenten uten videre.
=> Viser en feilmelding til saksbehandler om at noe ikke kan beregnes

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/Avbrutt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oppsummering.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/oppsummering/oversikt.tsx
Saksbehandler på oppgaven ble helt feil på oversikt.tsx da en avbrytt behandling ikke har en oppgave under behandling 🤠  + at den hadde mye annet ræl avbrutt ikke bryr seg om derfor egen komponent
=> Egen visning for avbrutt behandling i sidemenyen

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallVisning.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.ts
Når man sammenligner med === undefined (eller !== undefined) for å se om en verdi er der så blir det uheldige resultater om verdien er null, siden den da er forskjellig fra undefined, men har fremdeles ikke en gyldig verdi for visning.
=> Mer korrekt sjekk for om felter i brevutfall har verdi

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevoppretter.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtaksbrev/VedtaksbrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/rivers/OpprettJournalfoerOgDistribuerRiver.kt
Flyten blir feil med denne. Ved å fjerne den sjekkes mottakeren _etter_ at brevet er opprettet, men _før_ det ferdigstilles. 
Hvis det ikke kan ferdigstilles vil det bli opprettet en manuell oppgave til saksbehandler.
=> Mottaker skal valideres før ferdigstilling, ikke opprettelse

apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingService.kt
I stedet for en "En feil har skjedd" med 500-kode gir vi nå en tilpasset feil, som også unngår logging til prod-alerts.
=> Bedre feilmelding til saksbehandler i generell behandling

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/TilleggsinformasjonOppgaveModal.tsx
Gjør det mulig for saksbehandler å behandle oppgaver av type **tilleggsinformasjon** (bruker sender søknad mens behandling av forrige søknad pågår).
=> EY-4473 Støtte behandling av oppgavetype tilleggsinformasjon

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx
P.t. får ikke saksbehandler beskjed dersom lagring av metode feiler. Så det ser ut som de lagrer ok, mens det i realiteten bare feiler.
=> Vise feilmelding hvis lagring av beregningsgrunnlag feiler

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt
Dersom saksbehandler ikke velger å kopiere forrige behandling blir ikke gyldighetsresultat tatt med videre. Det blir som en følge av dette `null` og gjør at behandlingen stopper opp. 
https://jira.adeo.no/browse/FAGSYSTEM-348427
=> FAGSYSTEM-348427 Sikre at GyldighetsResultat er initiert

apps/etterlatte-behandling/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/vilkaarsvurdering/service/VilkaarsvurderingService.kt, apps/etterlatte-behandling/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutesTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vilkaarsvurdering.tsx
Bruker `UgyldigForespoerselException` i stedet for `IllegalStateException` som forenkler feilhåndteringen og melding til saksbehandler.
=> Forenkle feil til saksbehandler på vilkårsvurdering

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDaoMedEndringssporing.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveFristGaarUtJobService.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt, apps/etterlatte-behandling/src/main/resources/db/migration/V166__rydde_oppgaver_som_ikke_har_status_attestering.sql, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveFristGaarUtJobServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
Endrer på måten jobben setter status på. Tok også en endring på selve service-signaturen siden det var stress å mocke feltene forståelig i testen av ta av vent-jobben.
Det kommer et ryddescript som skal fikse opp i oppgavene som har mismatch med attestering og under behandling.
=> Ta oppgaver av vent-jobben endret i noen tilfeller til ugyldig status

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt, apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx
Saker hvor søknad er sendt inn før vi ber om inntekt neste år i søknadsskjema og som ikke blir innvilga i tide til varselbrev vil mange inntekt neste år uten at bruker vet at det skal oppgis.
Saksbehandler er nødt til å innhente dette manuelt men for å sikre at dette skjer gjør vi utfylling av inntekt neste år obligatorisk.
Siden dette er bare relevant i tiden fra og med varselbrev blir sendt ut ønsker vi å styre valideringen med brytere.
=> Avkorting inntekt neste år obligatorisk

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokarkiv/Journalpost.kt
Viser seg at det er helt lovlig å lagre journalpost _uten_ disse verdiene. Fjerner derfor sperren slik at vi ikke får feil i loggene i tilfeller hvor saksbehandler forsøker å hente journalposter av typen FAGSAK hvor id eller system mangler.
=> Ikke kaste feil hvis sakid eller -system mangler

.github/dependabot.yml
Legge til auto-merge av Dependabot PR for patch
```
Patch Versions:
Dependabot will automatically update to the latest available patch version within the current minor version range.
For example, if your current version is 1.2.3, Dependabot will update to the latest patch version like 1.2.4 but won’t upgrade to 1.3.0.
```
Tenker vi starter der, så kan vi evnt. se videre på auto-merge av minor versjoner etterpå
=> Enable auto-merge for patch PR fra Dependabot

.gitignore
Dersom man får kotlin-relaterte feil i IntelliJ vil det bli generert opp en mappe med errorlogg tilknyttet feilen. Legger til ignore for å unngå at det havner i kodebasen.
=> gitignore .kotlin-mappe som blir generert ved feil

apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/ArkiverHendelseModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/Hendelser.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/NyHendelseExpandableRow.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
- Fikse bug som gjorde at hendelser ikke lastet når man ble lenket direkte til siden.
- Endre fra "Begrunnelse" til "Kommentar" for at det skal være likt på tvers av alle oppgaver i løsningen. 
- Fikse filtrering på arkiverte hendelser (den viste tidligere de aktive også).
- Opprydding i type. Endret til enum. 
- Bruke `selected` på tabellraden for å tydeliggjøre hvilken som er valgt (ved redirect).
=> EY-4537 Fikse bug + opprydding i hendelsesbildet

apps/etterlatte-beregning/src/main/kotlin/avkorting/Avkorting.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRegelkjoring.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt, apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-beregning/src/main/kotlin/klienter/GrunnlagKlient.kt, apps/etterlatte-beregning/src/main/resources/db/migration/V52__innvilga_maander_til_grunnlag_og_fom_aarsopgjoer.sql, apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRegelkjoringTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRepositoryTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingValiderTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/BeregnAvkortingMedToInntektsTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/BeregnAvkortingTest.kt, apps/etterlatte-grunnlag/src/main/kotlin/Application.kt, apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/aldersovergang/AldersovergangDao.kt, apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/aldersovergang/AldersovergangRoutes.kt, apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/aldersovergang/AldersovergangService.kt, apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/aldersovergang/AldersovergangServiceTest.kt, apps/etterlatte-grunnlag/src/test/kotlin/grunnlag/aldersovergang/AldersovergangTest.kt
- Antall innvilga måneder flyttes tilbake til avkortingsgrunnlag
- nytt felt 'fom' på årsoppgjør for å enkelt kunne vite første fom i året - til nå blitt utledet av aarsoppgjoer.innvilga_maaneder
- Setter oppørFom til avkorting basert på måned bruker har aldersovergang ved å hente info fra Grunnlag
=> Tilpasse Avkorting for Aldersovergang

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/DokumentRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/Model.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/dokument/SafService.kt, apps/etterlatte-brev-api/src/main/resources/graphql/dokumentoversiktBruker.graphql, apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/DokumentFilter.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/Dokumentliste.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/DokumentlisteLiten.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/dokument.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/components/Sidebar.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Journalpost.ts
OBS: Dokumentoversikten laster 50 journalposter av gangen, så denne vil på de fleste saker være skjult i dev/prod. Satt 10 lokalt for å illustrere hvordan det blir.
=> EY-3570 Støtte paginering på journalposter

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/omstillingsstoenad/Person.tsx
Fjerner denne: 
```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
```
=> Fikser HTML-advarsel som fyller konsolloggen unødvendig

apps/etterlatte-behandling/src/main/resources/db/migration/V168__fjerner_tabell_mellom_atten_og_tjue_ved_reformtidspunkt.sql
Tabellen ble brukt midlertidig ved opprettelse av dødshendelser som trigget brev til personer mellom 18 og 20 på reformtidspunkt. Dataene er nå tilgjengelig i `doedshendelse`-tabellen, og vi har ikke lenger behov for å ha denne tabellen liggende.
=> EY-4505: Fjerner tabell brukt ved opprettelse av dødshendelser for personer mellom 18 og 20

apps/etterlatte-brev-kafka/src/main/kotlin/no/nav/etterlatte/klienter/BrevapiKlient.kt, apps/etterlatte-brev-kafka/src/main/kotlin/no/nav/etterlatte/rivers/DistribuerBrevRiver.kt, apps/etterlatte-brev-kafka/src/main/kotlin/no/nav/etterlatte/rivers/JournalfoerVedtaksbrevRiver.kt
bare videresender sakid fra 
```
internal class JournalfoerVedtaksbrevRiver(
private val rapidsConnection: RapidsConnection,
private val brevapiKlient: BrevapiKlient,
) : ListenerMedLogging() {
private val logger = LoggerFactory.getLogger(JournalfoerVedtaksbrevRiver::class.java)
init {
initialiserRiver(rapidsConnection, VedtakKafkaHendelseHendelseType.ATTESTERT) {
validate { it.requireKey("vedtak") }
validate { it.requireKey("vedtak.id") }
validate { it.requireKey("vedtak.behandlingId") }
validate { it.requireKey("vedtak.sak") }
validate { it.requireKey("vedtak.sak.id") }
```
=> EY-4499 Fiks sakid problematikk for distribuer brev

.github/workflows/app-etterlatte-brev-kafka.yaml
Vi må definere paths både på push main og pull request i yaml-en, elles vil denne appen byggje på kvar einaste push til main
=> Hindre unødige deploys av brev-kafka

apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/EndreEnhet.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Enhet.ts
Informerer bruker i forkant at de ikke har tilgang til enheten de endrer til, og forbedrer navigeringen i etterkant
Hvis bruker ikke har tilgang til enhet, før de endrer enhet:
Hvis bruker ikke har tilgang til enhet, etter de endret:
Hvis bruker *har* tilgang til enhet, etter de endret:
=> Forbedrer info til bruker ved endring av enhet

apps/etterlatte-brev-api/src/main/resources/db/prod/V23__oppdater_hendelse_ferdigstill.sql
Siden brev-kafka var nede så ble en behandling attestert før underkjent hendelsen ble kjørt som førte til at brev hendelsen fikk status oppdatert
=> Fiks brev i crashloop prod

apps/etterlatte-api/build.gradle.kts, apps/etterlatte-behandling/build.gradle.kts, apps/etterlatte-beregning/build.gradle.kts, apps/etterlatte-brev-api/build.gradle.kts, apps/etterlatte-gyldig-soeknad/build.gradle.kts, apps/etterlatte-hendelser-joark/build.gradle.kts, apps/etterlatte-hendelser-pdl/build.gradle.kts, apps/etterlatte-hendelser-samordning/build.gradle.kts, apps/etterlatte-pdltjenester/build.gradle.kts, apps/etterlatte-trygdetid/build.gradle.kts, apps/etterlatte-vedtaksvurdering-kafka/build.gradle.kts, apps/etterlatte-vilkaarsvurdering-kafka/build.gradle.kts, apps/etterlatte-vilkaarsvurdering/build.gradle.kts, libs/etterlatte-ktor/build.gradle.kts
Gå over til å eksponere implementation i libs ktor som `api` ikke implementation og fjerne fra apper som bruker libben.
Går gjennom flere i neste iterasjon, blir brått så mye å teste :D
=> Unngå dobbeldefinisjon av moduler fra ktor rest module

apps/etterlatte-behandling/src/main/resources/db/prod/V172__grante_servicebruker.sql, apps/etterlatte-vilkaarsvurdering/src/main/resources/db/migration/V31__grante_servicebruker.sql
vi har manuelt lagt inn for dev for å teste + at dev allerede er migrert.
Obs til later så må vi huske å ta ned podder, ta backup av databaser og være klar til å deploy versjon som bruker vilkårsvurderingsdata i tabellene i etterlatte-behandling.
=> EY-4499 Grante servicebruker i prod tilgang til migrering

apps/etterlatte-saksbehandling-ui/client/src/App.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/OppgaveVurderingRoute.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/VurderAktivitetspliktOppgave.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/brev/VurderingInfoBrev.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/sidemeny/AktivitetspliktSidemeny.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/stegmeny/AktivitetspliktNavLenke.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/stegmeny/AktivitetspliktStegmeny.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/VurderAktivitet.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/aktivitetsplikt.ts
Denne siden skal ta over for modalen der vurderingen gjøres i dag, og skal også ta med de nye vurderingene som gjøres for 12 mnd-kravet
Denne endringen bygger opp skjelettet og har en feature-toggle (`aktivitetsplikt.ny-vurdering`) for om den brukes.
=> EY-4583 Egen behandlingsflyt vurdering aktivitet

apps/etterlatte-brev-api/.nais/dev.yaml, apps/etterlatte-brev-api/.nais/prod.yaml
Ser ingen umiddelbar grunn til at brev-api ikke kan ha flere instanser oppe å kjøre nå som den er pure rest app.
=> Ha min 2 og max 4 brev-api apper oppe å kjøre brev-api

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EtterlatteBrev.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/EtterlatteBrevTrygdetidTest.kt
Hvis trygdetid-ident er ukjent_avdoed, behandlingen er uten avdøde og trygdetiden er overstyrt så tillater vi at avdødes navn settes til "ukjent avdød". Det skal ikke bli brukt i brevet. Vi trenger bare at det ikke kastes exception.
=> EY-4553: Henter navn = ukjent avdød i brev-api

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt, apps/etterlatte-brev-api/src/main/resources/db/migration/V24__status_utgaatt.sql, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/db/BrevRepositoryIntegrationTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/BrevOversikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/BrevStatusTag.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/handlinger/BrevUtgaar.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/handlinger/SlettBrev.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Brev.ts, libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/Brev.kt
Grunnet historiske problemer med brevløsningen har vi en del brev som er i limbo... Mange av disse brevene er såpass gamle at det ikke lenger er aktuelt å sende de. Brev som har status **FERDIGSTILT** eller **JOURNALFOERT**, og er mer enn 1 uke gammelt vil være mulig å markere som **UTGÅTT**. Dette gjør det mulig for saksbehandler å få gamle brev som har feilet ut av ordinær saksbehandlingsflyt.
=> EY-4580 Markere brev som utgått

apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/BeregningService.kt, apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/OmregningHendelserBeregningRiver.kt, apps/etterlatte-beregning-kafka/src/test/kotlin/no/nav/etterlatte/beregningkafka/OmregningHendelserBeregningRiverTest.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/VedtakAttestertRiver.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/behandlingsslistemappere.ts, libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/sak/KjoeringRequest.kt
Pr nå så er verifikasjonen med toleransegrenser og forrige / gjeldende beregning veldig tilpasset regulering som kun må forholde seg til en periode (for og etter ny G). Ved omregning feks fra 1. virk, vil det potensielt bli en lang tidslinje med mange perioder og det gir ikke samme mening å verifisere beløp her på en gitt dato. 
I denne PR'en gjøres det endringer slik at det kun er regulering som gjør verifikasjonene som er lagt inn. Videre er det tenkt å se på muligheten for å verifisere omregning med feks simulering.
=> EY-4513: Gjør verifikasjon av omregning kun ved regulering

apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-behandling/src/main/kotlin/Application.kt, apps/etterlatte-beregning/src/main/kotlin/Application.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-egne-ansatte-lytter/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-klage/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-pdltjenester/src/main/kotlin/Application.kt, apps/etterlatte-statistikk/src/main/kotlin/Application.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/Application.kt, apps/etterlatte-trygdetid/src/main/kotlin/Application.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/Application.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/config/ApplicationContext.kt, apps/etterlatte-vilkaarsvurdering/src/main/kotlin/Application.kt, libs/etterlatte-ktor/src/main/kotlin/HealthRoute.kt, libs/etterlatte-ktor/src/main/kotlin/initialisering/EmbeddedServerConfig.kt, libs/etterlatte-ktor/src/main/kotlin/initialisering/ReadinessProbe.kt, libs/etterlatte-ktor/src/test/kotlin/RestModuleTest.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/InitRogR.kt, libs/saksbehandling-common/src/main/kotlin/ShutdownHook.kt, libs/saksbehandling-common/src/main/kotlin/logging/LogUtils.kt
Endringen i isReady-endepunktene våre bør fjerne `Et endepunkt returnerte 503 Service Unavailable. Maskerer som 500: ` fra error-logging, ved at vi heller håndterer det som en standard ForespoerselException med status = 503. Tenker å teste deploy på denne i dev for å sjekke at vi ikke brekker noe når vi returnerer en faktisk response-body med 503'en når vi ikke er klar, men kan i utgangspunktet ikke se at det er et problem.
Tar også å fjerner shutdown-logging for sikkerlogg, da den i alle fall et tilfelle ser ut til å ha forårsaket en "Uncaught exception in thread main: Shutdown in progress"-feil. Vi trenger ikke at sikkerlogg logger at appen går ned uansett, det er en ganske sporbar greie i vanlige logger, og hvis den kan forårsake spammy logging ved enkelte deploys er det mer bry enn …
=> Minske error-logging når noe faktisk ikke er error

libs/etterlatte-ktor/src/main/kotlin/initialisering/EmbeddedServerConfig.kt
Hindrer disse fra å komme i error logger. Se tilsvarende eksempel https://kotlinlang.org/docs/cancellation-and-timeouts.html#timeout
https://logs.adeo.no/app/discover#/?_g=(time:(from:'2024-10-17T07:04:26.575Z',to:'2024-10-17T07:19:26.575Z'))&_a=(columns:!(level,message,envclass,application,pod),dataSource:(dataViewId:'96e648c0-980a-11e9-830a-e17bbd64b4db',type:dataView),filters:!(),hideChart:!f,interval:auto,query:(language:lucene,query:'namespace:etterlatte%20AND%20envclass:p%20AND%20level:Error'),sort:!(!('@timestamp',desc)))
=> Svelg redeploy exceptions

apps/etterlatte-behandling/src/main/kotlin/Application.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/omregning/OmregningService.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/kotlin/inntektsjustering/AarligInntektsjusteringJobbService.kt, apps/etterlatte-behandling/src/main/kotlin/inntektsjustering/AarligInntektsjusteringRoute.kt, apps/etterlatte-behandling/src/test/java/inntektsjustering/AarligInntektsjusteringJobbServiceTest.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/BehandlingService.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/inntektsjustering/InntektsjusteringJobbRiver.kt, apps/etterlatte-oppdater-behandling/src/test/kotlin/InntektsjusteringJobbRiverTest.kt, apps/etterlatte-testdata/src/main/resources/templates/egendefinert/ny-melding.hbs, libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/inntektsjustering/AarligInntektsjusteringRequest.kt, libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/OmregningHendelseType.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/RapidEvents.kt
- Endrer eksisterende River tiltenkt varselbrev til å omregne
- Flytter logikk fra River til behandling
- Legger på TODOS for mangler som skal utbedres i egne PR
=> Årlig Inntektsjustering jobb

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/Behandling.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/BehandlingRoutes.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/NavLenke.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/StegMeny/stegmeny.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/attesteringEllerUnderkjenning.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagBarnepensjon.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/BeregningsgrunnlagOmstillingsstoenad.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/overstyrGrunnlagsBeregning/OverstyrBeregningGrunnlag.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/Varselbrev.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/NesteOgTilbake.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/Start.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/handlinger/Tilbake.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidVisning.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/VilkaarsvurderingKnapper.tsx
1. Per i dag sjekker vi om routes er gyldige på 2 forskjellige steder og måter, samler de to og skriver om slik at vi kun har en route liste med egenskaper vi trenger kontra 2 og x antall forskjellige måter å sjonglere disse på.
2.  https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/6052/commits/455371c593a1ab30b674a07beba765b6cf0478fd
Tar for seg at vi sender behandlingroute data og funksjoner nedover i en context i stedet for å newe opp overalt da det kan få utilsiktede konsekvenser...
=> Konsolidere routesjekking i stegmeny og behandlingroutes

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRegelkjoring.kt, apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonService.kt, apps/etterlatte-beregning/src/test/kotlin/sanksjon/SanksjonServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx
Unngår å kopiere sanksjoner hver gang vi beregner, hvis vi allerede har gjort det.
Gir også bedre feilmeldinger når noe rart har skjedd med sanksjonsgrunnlaget som fører til at man ikke får lastet f.eks. avkorting, slik at saksbehandler kan rydde opp selv, eller det er en feiltype som vi ikke forventer og vi logger ut i prod-loggene.
=> EY-4615 fix oppretting av ekstra sanksjoner

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakEtterbetaling.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakEtterbetalingTest.kt
Når det gjøres et vedtak som er opphør, så vil beløp være `null` og dette feiler ved beregning av etterbetaling. 
Tenker kanskje denne sjekken uansett burde byttes ut med simulering, men nå må vi få det opp å gå i prod.
=> Fikser problem med beregning av etterbetaling ved opphør

apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/soeknad/OpprettSoeknad.kt, apps/etterlatte-testdata/src/main/resources/templates/soeknad/ny-soeknad.hbs
Gjør det mulig å opprette søknad og behandling på et bestemt steg, på en eksisterende familie. 
Har også gjort feltene `nøkkel` og `barn` valgfrie, samt lagt til støtte for kommaseparert barneliste.
=> Støtte opprettelse av behandling til steg på familie

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
Trygdetid går i loop hvis man har en avdød på en tidligere familiepleier sak.
=> Sjekk om soeker mangler trygdetid hvis det er tidligere familiepleier

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/klienter/SamordningsKlient.kt
Saker som ikke for overstyre samordning pga følgende melding
```
Text: "{"message":"Message with id = 25758215 has already been answered or time limit is exceeded.","exceptionType":"ALLEREDE_REGISTRERT_ELLER_UTENFOR_FRIST"}" 
```
De står derfor fast med status TIL_SAMORDNING og får ikke utbetaling
=> EY-4640 hotfix for saker som står fast TIL_SAMORDNING

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BlockTilSlateKonverterer.kt
Hadde en litt irriterende bug som legger inn komma når flere objekter i en liste slås sammen
=> EY-4555: Fjerner komma i liste ved konvertering til Slate

apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/Trygdetid.kt, apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidTest.kt
I koden så vil trygdetidsgrunnlagene sorteres, men siden elementer aksesseres direkte med `this` lenger nede i funksjonen, så vil ikke dette være den samme listen som er sortert. Dette fører til at saksbehandler får feil som nevnt i https://jira.adeo.no/browse/FAGSYSTEM-352841.
=> FAGSYSTEM-352841: Bruker sortert trygdetidsgrunnlag ved normalisering og poengår

apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/DokumentModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/DokumentRad.tsx
Har fått ønske fra flere saksbehandlere om å støtte åpning av journalpost i ny fane på **dokumentoversikten**. 
I sidemenyen på f.eks. en behandling åpnes alle dokumenter alltid i ny fane. På dokumentoversikten på personsiden åpnes de alltid i modal. Dette gjør det tungvint for dem siden de da ofte jobber med dokumentet side-om-side ved en behandling. 
Har derfor kjapt lagt til støtte for å åpne i ny fane. Skiller nå på `Vis` og `Åpne` journalpost.
=> Støtte åpning av journalpost i ny fane

apps/etterlatte-behandling/docker-compose.yml, apps/etterlatte-beregning/docker-compose.yml, apps/etterlatte-brev-api/docker-compose.yml, apps/etterlatte-grunnlag/docker-compose.yml, apps/etterlatte-hendelser-samordning/docker-compose.yml, apps/etterlatte-migrering/docker-compose.yml, apps/etterlatte-testdata/docker-compose.yml, apps/etterlatte-tidshendelser/docker-compose.yml, apps/etterlatte-tilbakekreving/docker-compose.yml, apps/etterlatte-trygdetid/docker-compose.yml, apps/etterlatte-utbetaling/docker-compose.yml, apps/etterlatte-vedtaksvurdering/docker-compose.yml
Får advarsel hver gang vi kjører docker compose lokalt
```
the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
```
=> fjerne attributt som ikke lenger er i bruk

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt
Verifisert opp mot uttrekk fra SAM om at disse skulle ha blitt sendt melding på, og kan kjøres til utbetaling
=> Legger til gjenværende saker som mangler samordningsmeldinger

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperRedigerbartUtfallVedtak.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadAvslag.kt
Tidligere familiepleier ble sendt til hoveddel når det skulle blitt sendt til redigerbart utfall
=> EY-4685: Avslag tidligere familiepleier

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevoppretter.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/JournalfoerBrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/Brevdistribuerer.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/oversendelsebrev/OversendelseBrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/pdf/PDFGenerator.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/pdf/PDFService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtaksbrev/VedtaksbrevService.kt, apps/etterlatte-brev-api/src/main/resources/db/migration/V27__lagre_bruker_paa_hendelse.sql, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevRouteTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevdistribuererTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/JournalfoerBrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/db/BrevRepositoryIntegrationTest.kt
Gjør det mulig å se _hvem_ som har gjort endringer i brev. Oppdateringer, ferdigstilling, journalføring, osv.
=> EY-4684 Lagre saksbehandler ident på hendelse i brev

apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/behandlingsslistemappere.ts
Stemmer ikke alltid at ANNEN er med brev. Dette er noe vi hadde tidligere når dette var to ulike årsaker.
=> Fjerner (med brev) for ANNEN revurderingsårsak

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottakerPanel.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/RedigerMottakerModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts
Gjør det enkelt å sette kopimottaker som hovedmottaker (og motsatt).
=> EY-4676 Støtte endring av mottakertype

apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/BrevModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/BrevOversikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/handlinger/BrevUtgaar.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/handlinger/SlettBrev.tsx
Ny knapp **Åpne** for å åpne i ny fane. Knappen **Vis** vil åpne en modal. 
Har også gjort litt generelle forbedringer på visning av knappene.
=> EY-4484 Ny knapp for å åpne brev i ny lenke + opprydding

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/personer/Soesken.tsx
Tidligere sjekk for å finne ut om to personer var hel/halvsøsken fungerte ikke da den kun så på gjenlevende. Denne endringen gjør at dette også blir riktig ved to avdøde / manglende gjenlevende
=> EY-4588: Bruker foreldre i stedet for gjenlevende for å sjekke om personer er søsken

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktOppgaveService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/aktivitetsplikt/AktivitetspliktOppgaveServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/VurderAktivitet.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktVurdering12MndOversikt.tsx, libs/etterlatte-tidshendelser-model/src/main/kotlin/no/nav/etterlatte/libs/tidshendelser/Jobbtype.kt
Validerer også at du faktisk har en vurdering fra 12 måneder med de
=> Justerer litt på teksten i aktivitetsplikt-oppgave

apps/etterlatte-behandling/src/main/kotlin/behandling/vedtaksbehandling/VedtaksbehandlingDao.kt
På grunn av at sjekken ikke tar høyde for tilstanden "formkrav ikke oppfylt" gir den feil svar tilbake på om vedtaket i klagen kan endres.
Legger også på litt logging for vedtaksbehandling-resultatet, så det er mulig å se i loggen hvorfor noe er svart ut slik det er svart ut
=> EY-4729 - Åpner for opprettelse av avvist klage-brev ved formkrav ikke oppfylt

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperRedigerbartUtfallVedtak.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonRevurdering.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
Utbetalingsavsnittet blir redigerbart så flere parametere må sendes til brevbakeren for dette. Endringer i pensjonsbrev her: https://github.com/navikt/pensjonsbrev/pull/1047
=> EY-4625: Endrer rekkefølge på avsnitt revurdering BP

.husky/pre-commit
Fjerner denne advarselen:
```
husky - DEPRECATED
Please remove the following two lines from .husky/pre-commit:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.
```
=> fikse advarsel fra husky

apps/etterlatte-behandling/src/main/kotlin/common/klienter/PdlTjenesterKlient.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktBarnService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt, apps/etterlatte-behandling/src/main/kotlin/inntektsjustering/AarligInntektsjusteringJobbService.kt, apps/etterlatte-behandling/src/test/kotlin/common/klienter/PdlTjenesterKlientTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktBarnServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/inntektsjustering/AarligInntektsjusteringJobbServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt
Renamer også funksjonen i PdlKlient til noe mer sensible for henting med kun en saktype
=> OMS-mottaker må hentes som gjenlevende

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingsstatusRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/inntektsjustering/AarligInntektsjusteringJobbService.kt, apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingDaoReguleringTest.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/BehandlingService.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/inntektsjustering/InntektsjusteringJobbRiver.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/Batchkjoerer.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/FinnSakerTilReguleringRiver.kt, apps/etterlatte-oppdater-behandling/src/main/kotlin/regulering/ReguleringsforespoerselRiver.kt, apps/etterlatte-oppdater-behandling/src/test/kotlin/InntektsjusteringJobbRiverTest.kt, apps/etterlatte-oppdater-behandling/src/test/kotlin/regulering/ReguleringsforespoerselRiverTest.kt, libs/saksbehandling-common/src/main/kotlin/sak/Sak.kt
Gjør det vesentlig enklere å hente åpne behandlinger (EY-4563).
=> Kun sende sakIder siden resten ikke blir brukt

apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/HendelseBeskrivelse.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/utils.ts, apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
Får inn litt info om hendelsen når saksbehandler viser den.
=> EY-4704: Forbedrer visning av hendelsesoppgave

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/grunnlag/GrunnlagVersjonValidering.kt
Her får bruker en god feilmelding som sier hva som må fikses. Tenker det holder med warn i loggene våre her. 
Brukers feilmelding:  `Ulik versjon av grunnlag brukt i vilkårsvurdering og beregning. Gå tilbake til søknadsoversikten og trykk oppdater grunnlag, deretter må totalvurderingen i vilkårsvurderingen gjøres på nytt.`
=> Endrer log-level for ulik versjon av grunnlag til warn

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/ParallelleSannheterService.kt
Virker som samtlige med `PersonRolle.TILKNYTTET_BARN` mangler ident, så vi hopper over det
=> ikke logge error + filtrere på rolle

apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt
Unngår at vi printer `Mangler skrivetilgang til enhet null`
=> Forbedre feilmelding til saksbehandler

apps/etterlatte-behandling/src/main/kotlin/common/klienter/PdlTjenesterKlient.kt, apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt, apps/etterlatte-behandling/src/test/kotlin/egenansatt/EgenAnsattRouteTest.kt, apps/etterlatte-behandling/src/test/kotlin/egenansatt/EgenAnsattServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, apps/etterlatte-behandling/src/test/kotlin/sak/SakServiceTest.kt
- Henter alle identer tilknyttet person i PDL
- Henter så alle saker tilknyttet alle identer. 
- Hvis det finnes flere saker av samme type, kastes `InternfeilException`
Dette sikrer at det ikke opprettes flere saker på samme person, selv om ident er ulik.
=> EY-4562 Sjekker alle identer på person ved henting av sak

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/attestering/attestering/attesteringEllerUnderkjenning.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/BehandlingSidemeny.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/klage/sidemeny/KlageSidemeny.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/sidemeny/TilbakekrevingSidemeny.tsx
Det er pr nå ikke mulig å attestere tilbakekreving- og klagebehandlinger fordi det brukes en property som hentes fra stegmenyen i en vanlig behandling for å sjekke om disse er på siste side i stegmenyen. 
Flytter denne property'en ett nivå opp, slik at dette blir et parameter inn til komponenten `AttesteringEllerUnderkjenning` og setter inntil videre hardkodet til `true` for tilbakekreving og klage. Har laget en oppgave for å sjekke at man er på siste side i disse behandlingene også (https://jira.adeo.no/browse/EY-4780).
=> EY-4779: flytter validering attesteringsvalg

apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/utbetalinger/TilbakekrevingVurderingPerioderSkjema.tsx
Valideringen som var lagt inn gjorde at det ikke var mulig å lagre et halvferdig skjema. Dette skal være mulig for tilbakekreving da det kan være mange perioder og det kan ta litt tid før man får ferdigstillt alle periodene.
=> EY-4778: Tillater midlertidig lagring av skjema uten at resultat og skyld er satt

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt
Det oppstod en feil ved at det ble forsøkt sendt en hendelse til statistikk når det ikke ennå er opprettet en tilbakekrevingsbehandling. Dette gir ikke mening før kravgrunnlaget er mottatt og behandlingen er opprettet. Gjør derfor en sjekk om referansen er en UUID for å unngå at det feiler.
Fikser også en annen potensiell bug ved at det hentes ut tilbakekrevingsoppgaver basert på referanse, hvor det i stedet kan hentes basert på sakId som er et eget felt på oppgave.
Ref:
https://logs.adeo.no/app/discover#/?_g=(time:(from:now-24h%2Fh,to:now))&_a=(columns:!(level,message,envclass,application,pod),dataSource:(dataViewId:'96e648c0-980a-11e9-830a-e17bbd64b4db',type:dataView),filters:!(),hideChart:!f,interval:auto,query:(language:lucene,query:'x_correlation_id:8005b448-3afc-4ca5-b00e-7b2c05bd174 …
=> Sjekker om uuid er gyldig før hendelse for statistikk opprettes fra oppgave

apps/etterlatte-behandling/src/main/kotlin/inntektsjustering/AarligInntektsjusteringJobbService.kt
Når revurdering er opprettet fra oppgave (Årlig inntektsjustering), så kan det være vanskelig å se at revurdering er knytt til inntektsjustering 
Slik er det i dag:
Endre til dette:
=> Tydliggjøre at revurdering gjelder inntektsjustering

apps/etterlatte-oppdater-behandling/src/main/kotlin/TidshendelseService.kt
Referansen som ble brukt for å opprette disse oppgavene pekte på forrige iverksatte behandling. Dette gav ingen mening da denne behandlingen allerede er lukket. Behandlingen oppgaven egentlig omhandler har blitt avbrutt.
=> Gir ikke mening å sette referanse når opprettelse av behandling feilet

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/Virkningstidspunkt.tsx
Gjør det mulig å overstyre virkningstidspunkt når en sak er opphørt (bruker samme konsept som er brukt tidligere ved overstyring av første virk). 
Grunnen til at det er behov for dette er at vi nå har noen saker hvor det skal innvilges perioder før 2024, deretter blir det opphør pga aldersovergang 18 år (etter gammelt regelverk). Etter en stund blir personen 20 år og har rett på ytelsen igjen. Man ønsker da å revurdere etter et opphør, med et virkningstidspunkt en del senere en opphørstidspunktet.
=> FAGSYSTEM-357542: Tillatter å overstyre virk etter opphørt sak

apps/etterlatte-vedtaksvurdering/src/main/resources/db/migration/V34__oppdater_vedtak_i_feil_tilstand.sql
Gjør det mulig å fatte vedtaket på nytt og fortsette med attestering.
=> FAGSYSTEM-357977: Ruller tilbake satus i vedtak som feilet i videre flyt

apps/etterlatte-behandling/src/main/kotlin/behandling/domain/ManuellRevurdering.kt
Ved utlandsopphold vil saksbehandler også ha mulighet til å legge til trygdetid ved avslag.
=> Kan fatte vedtak ved status TRYGDETID_OPPDATERT ved avslag i revurdering

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveKlient.kt
Vi får ofte feil fra Gosys når det hentes oppgaver med tema `PEN`. Det finnes helt vanvittig mange oppgaver på dette temaet, så prøver derfor å redusere antall oppgaver vi henter i et forsøk på å redusere antall feil. 
Ideelt sett burde vi skrevet om Gosys-oppgavetabellen til å bruke Oppgave API-et sin paginering, men det krever en del mer innsats.
=> Redusere ant. gosysoppgaver som hentes fra 1000 til 500

apps/etterlatte-beregning/src/main/kotlin/avkorting/AarligInntektsjusteringService.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingReparerAarsoppgjoeret.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt, apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-beregning/src/main/kotlin/ytelseMedGrunnlag/BeregningOgAvkortingBrevService.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingReparerAarsoppgjoeretTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingRepositoryTest.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt
Varselbrevjobb har en egen metode for å opprette avkorting og har ikke videreført tidligere årsoppgjør som har medført at revurdering tilbake i tid feiler fordi årsoppgjør for tidligere år da mangler
=> Avkorting feil etter varselbrevjobb

apps/etterlatte-behandling/src/main/kotlin/behandling/domain/SamsvarMellomKildeOgGrunnlag.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/SamsvarHelper.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringshendelseServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/SamsvarHelperKtTest.kt, apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/ParallelleSannheterService.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/HendelseBeskrivelse.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/typer.tsx
Nytt forsøk. Samme PR som sist, men nå med tester og et par ekstra sjekker. 
Forenkler hendelser tilknyttet endret folkeregisteridentifikator. 
Dagens løsning medfører at **søker** får hendelser hvor det ser ut som andre familiemedlemmer har fått endret identifikator. 
Nå vil _kun_ sak(er) tilknyttet bruker med endret ident motta hendelser. 
Avklart med fag at endret ident ikke skal påvirke eventuelle ytelser som familiemedlemmer mottaker. 
Dersom et familiemedlem må gjennomføre en revurdering, vil det komme en advarsel i familiebildet, slik at saksbehandler kan korrigere.
=> EY-4777 Fikser hendelser for endret fnr

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingsstatusRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringsHendelseFilter.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagsendringsHendelseFilterTest.kt
Gjør funksjonsnavn i hendelsesfilteret litt mer forståelig: 
`ikkeRelevanteHendelserForOpphoertSak` til `erHendelseRelevant`
Og ikke gjøre duplikatsjekk på hendelse med mindre det faktisk er nødvendig. 
Pluss litt smått.
=> opprydding i diverse smårusk

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntektForm.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/OverstyrInnvilgaMaaneder.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts
Viser også 67 år som en begrunnelse hvis det er satt av systemet (som ikke kan velges manuelt av saksbehandler)
=> Fikser resetting av skjema ved fjerning av aldersovergang

apps/etterlatte-testdata/.nais/dev.yaml, apps/etterlatte-testdata/src/main/kotlin/Application.kt, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/Auth.kt, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/OpprettOgBehandle.kt, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/dolly/DollyFeature.kt, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/egendefinert/EgendefinertMeldingFeature.kt, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/index/IndexFeature.kt, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/soeknad/OpprettSoeknad.kt, apps/etterlatte-testdata/src/main/resources/templates/_fragments/header.hbs, apps/etterlatte-testdata/src/main/resources/templates/index.hbs
Bruker `allowAllUsers: true` for å gi alle tilgang, deretter en primitiv sjekk for å se om bruker har AD-gruppen til etterlatte utvikling. 
Gjør at brukere kun får se de routes som er ment for alle på index-siden. De kan fremdeles lete seg frem til de andre sidene og få de opp, men det er ikke noe stort problem. Endringen er bare for å unngå forvirring med _hva_ de skal bruke på sidene våre. 
Testet OK med Frida som ikke har forventet ad-gruppe.
=> Gi alle tilgang til spesifikke routes

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevKodeMapperVedtak.kt
Denne sjekken var før omskriving:
`check(listOf(VedtakType.INNVILGELSE, VedtakType.ENDRING).contains(request.vedtakType)) {
"Vedtaktype må være ${VedtakType.INNVILGELSE.name} eller ${VedtakType.ENDRING.name} var ${request.vedtakType}"
}
`
Endrer slik at logikken blir riktig her.
=> FAGSYSTEM-358848: Fikser sjekk som har blitt snudd ved omskriving

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerKlient.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/brevbaker/BrevbakerService.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt
Frå brevbaker-sida ønskjer vi like responsobjekt for etterlatte og PEN, pga kompleksitet på vår side. Legg til rette for det ved å bruke samme namn i responsobjekta
Obs: Avhengig av https://github.com/navikt/pensjonsbrev/pull/1081
=> Endre feltnamn responsobjekt frå brevbaker

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/Brevoppretter.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/adresse/AdresseService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/grunnlag/GrunnlagService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/oversendelsebrev/OversendelseBrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/pdf/PDFService.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/adresse/AdresseServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/BehandlingTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/behandling/GrunnlagmapperTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/db/BrevRepositoryIntegrationTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/KlageMottakerRequestTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/oversendelsebrev/OversendelseBrevServiceImplTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/varselbrev/VarselbrevTest.kt, apps/etterlatte-saksbehandling-ui/docker-compose.yml
Oppretter flere mottakere ved opprettelse av brev. 
Gjøres i tilfeller hvor det finnes verge, eller søker og innsender er to ulike personer. 
Vil også gjøre enhetstesting enklere.
=> EY-4677 Opprette alle mottakere automatisk

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/SettPaaVentModal.tsx
På sikt burde disse 2 api kallene være bakt inn i sett på vent, slik at vi ikke må sjekke hele tiden
=> Fiks feil i sett på vent

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/generellbehandling/GenerellBehandlingServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/ManuellRevurderingServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
Flytter funksjon for opprettelse av førstegangsbehandling fra `oppgave` til `behandling`.
=> Opprydding i opprettelse av oppgave (forarbeid EY-4597)

apps/etterlatte-api/.nais/dev-api.yaml, apps/etterlatte-api/.nais/prod-api.yaml, apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/behandling/sak/BehandlingSakRoutes.kt, apps/etterlatte-api/src/test/kotlin/no/nav/etterlatte/behandling/sak/BehandlingSakRoutesTest.kt
Det er kun våre saksbehandlere som skal se inntekt i a-reg. ingen systembruker håndtering er nødvendig
=> Kun tilgang med OBO for a-inntekt

apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/GrunnlagHelperKtTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/SamsvarHelperKtTest.kt, apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlModell.kt, apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/UtlandMapper.kt, apps/etterlatte-pdltjenester/src/main/resources/pdl/hentPerson.graphql, apps/etterlatte-pdltjenester/src/main/resources/pdl/hentPersonBolk.graphql, apps/etterlatte-pdltjenester/src/test/kotlin/pdl/mapper/UtlandMapperTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/personopplysninger/Innflytting.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Person.ts, libs/saksbehandling-common/src/main/kotlin/person/Person.kt
Legger også til gyldighetsdato og ajourholdsdato som brukes i pesys i dag.
Ta gjerne en ekstra titt på Utlandsmapper da mye er lånt fra pesys for at dato skal være lik i begge systemer.
=> EY-4808: Bruk angitt flyttedato for innflytting

.husky/pre-push
Endre fra `pre-commit` til `pre-push` for å redusere ventetid ved hver enkelt commit. Gjør arbeidsflyten lokalt vesentlig raskere.
=> Endre fra pre-commit til pre-push

apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/samordning/LoggingPlugins.kt
Legger det kun på for etterlatte-api men videresender ikke til våre apper, da må man se på "x_correlation_id"
=> Tracke kall fra pensjonselvbetjening mot etterlatte-api

apps/etterlatte-api/.nais/dev-api.yaml, apps/etterlatte-api/.nais/prod-api.yaml, apps/etterlatte-api/README.md, apps/etterlatte-api/src/main/kotlin/no/nav/etterlatte/samordning/vedtak/SamordningVedtakRoute.kt
Vi må støtte delegering av auth via maskinporten mot altinn som styrer ut mot TP leverandører managere som feks Aksio, de har p.t. ikke tilgang og trenger dette.
=> EY-4809 Nytt format på maskinporten scope + delegation source for altinn

apps/etterlatte-behandling/src/main/kotlin/sak/SakRoutes.kt, apps/etterlatte-behandling/src/test/kotlin/sak/SakRoutesTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/hendelser/OppdaterIdentModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/SakOversiktHeader.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/sak.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/statusbar/Statusbar.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/statusbar/usePerson.tsx, apps/etterlatte-saksbehandling-ui/client/src/store/Store.tsx, apps/etterlatte-saksbehandling-ui/client/src/store/reducers/PersonReducer.ts
- Reducer for å ha en state med "valgt person". Unngår unødvendig mye prop drilling
- Advarsel hvis allerede oppdatert ident
- Muliggjør oppdatering _uten_ hendelse
Viktig i tilfeller hvor vi ikke har fått en hendelse. Dette kan f.eks. skje dersom bruker søker med DNR, _etter_ de har fått FNR.
=> FAGSYSTEM-360070 Støtte oppdatering av ident UTEN hendelse

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlFeilLogger.kt
Henger sammen med: https://logs.adeo.no/app/r/s/eOvfU
Vil på sikt redusere unødvenige prodvarsler, men logges som `error` en liten stund til for å se data-objektet. 
Min teori er at sjekken på `result.data` er en smule misvisende, da det ikke er `data` som er null, men query-objektet. I dette tilfellet objektet under, dvs. `hentPerson`
Forventet respons i prod: 
```
"result": {
"data": {
"hentPerson": null       // eller tilsvarende 
},
"errors": [ ... liste med feil ... ]
}
```
=> Håndtere manglende tilgang bedre

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/components/HandlingerForOppgave.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/FilterRad.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/filtreringAvOppgaver/GosysFilterRad.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/BrevOppgaveModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/GeneriskOppgaveModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/InntektsopplysningModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/TilleggsinformasjonOppgaveModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/tildeling/VelgSaksbehandler.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/components/Sidebar.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/header/ReleaseAlerts.tsx
Fjerner 80% av alle wcag feil vi har. Er den del igjen, men det er en start hvertfall.
=> Aria hidden på ikoner som kun er for "syns" skyld

apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/overstyrGrunnlagsBeregning/OverstyrBeregningsgrunnlagExpandableRowContent.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregningsgrunnlag/overstyrGrunnlagsBeregning/OverstyrBeregningsgrunnlagPeriodeSkjema.tsx
Det var lagt inn 480 år trygdetid i overstyrt beregning. Dette brukes ikke til noe direkte i beregningen.
Legger inn en sperre mot flere år enn 40 også i overstyrt beregning.
=> FAGSYSTEM-360636: Ikke lov å legge til trygdetid > 40 år

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlFeilLogger.kt
Har fått bekreftet teorien min fra #6608 og fjerner derfor error-logging. Viktigst at saksbehandler får tilgangsfeilen ut i frontend.
Lager egen oppgave for å utbedre feilhåndtering i `pdltjenester`
=> Ikke logge error ved unauthorized mot pdl

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/sidemeny/SettPaaVentModal.tsx
Merknad er ikke nullable i backend. Dette sikrer at vi ikke får serde-feil. 
Eks. https://logs.adeo.no/app/r/s/bJyHT
=> Sikre at kommentar blir satt ved "på vent"

apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/klienter/TilbakekrevingskomponentenKlient.kt, apps/etterlatte-tilbakekreving/src/main/kotlin/tilbakekreving/kravgrunnlag/KravgrunnlagMapper.kt, apps/etterlatte-tilbakekreving/src/test/kotlin/tilbakekreving/klienter/TilbakekrevingskomponentenKlientTest.kt
Fjerner tidspunkter fra XMLGregorianCalendar ved å først konverte til norsk tidssone slik at datoene blir riktig, så fjerne tidspunktet slik at det kun er dato som gjenstår.
Skulle gjerne hatt bedre måter å gjøre dette på fordi det blir litt rotete, men ser ingen åpenbar enklere vei rundt problemet.
=> Setter norsk tidssone ved konvertering av XMLGregorianCalendar til localdate

apps/etterlatte-behandling/src/main/kotlin/kodeverk/KodeverkKlientImpl.kt, apps/etterlatte-behandling/src/main/kotlin/kodeverk/KodeverkService.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, apps/etterlatte-behandling/src/test/kotlin/kodeverk/KodeverkServiceTest.kt
Sikre at vi ikke henter ugyldige arkivtemaer. På den måten unngår vi unødvendige feil mot dokarkiv fordi saksbehandler velger feil tema (eks. OKO=Økonomi).
Eks:
https://logs.adeo.no/app/discover#/?_g=(time:(from:'2024-12-18T07:34:58.308Z',to:'2024-12-18T07:49:58.308Z'))&_a=(columns:!(level,message,envclass,application,pod),dataSource:(dataViewId:'96e648c0-980a-11e9-830a-e17bbd64b4db',type:dataView),filters:!(),interval:auto,query:(language:lucene,query:'namespace:etterlatte%20AND%20envclass:p%20AND%20level:Error'),sort:!(!('@timestamp',desc)))
=> Ikke hente ugyldige arkivtemaer

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
Dette gjør at vi ikke allerede har sendt flere hendelser på kafka (statistikk etc) dersom vedtaket mot tilbakekreving feiler.
Dette er en midlertidig fiks før vi flytter tilbakekrevingskallet over i vedtak for å sikre at man ikke får et attestert vedtak, men feilende vedtak mot tilbakekrevingskomponenten i etterkant.
=> Flytter kall til tilbakekreving før hendelser opprettes for å lettere kunne rulle tilbake

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/avtaler/TrygdeAvtaleRedigering.tsx
Tidligere så gav kommentaren inntrykk av at saksbehandler måtte overstyre beregningen i saken, noe som ikke er riktig.
=> Endrer kommentar slik at den blir riktigere ift hva sb må gjøre

apps/etterlatte-saksbehandling-ui/client/src/components/person/Person.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/lenker/usePersonLocationState.tsx
Skjer bare i tilfeller hvor saksbehandlere sender hverandre URL-en, kopierer til ny fane, eller modifiserer manuelt. 
Lager derfor bare en superenkelt fiks på det.
=> Bedre feilmelding hvis fnr er ugyldig/null

apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingStatusServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoDaoTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoRoutesTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoServiceTest.kt, libs/saksbehandling-common/src/main/kotlin/behandling/Brevutfall.kt
I dag har vi to objekter som er like. Faser ut det som er minst brukt slik at vi kun trenger å bruke ett
=> standardisere brevutfall objekt

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallSkjema.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallVisning.tsx
Fjerne felter for etterbetaling som skal fases ut. 
Forbedret også visningen for frivilligSkattetrekk - denne skal vises uavhengig av etterbetaling. Og løsningen i dag var duplisering av kode.
=> EY-4877 fjerne unødvendige felter for etterbetaling utfall i brev

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonRevurdering.kt
Avsnitt om etterbetaling mangler noe tekst pga etterbatling objektet er null. Enkleste løsning å sende med. Kan heller se på å bruke erEtterbetaling på sikt.
=> EY-4877 sende med etterbetaling til pensjonsbrev bp revurdering redigerbart utfall

apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/BehandlingInfoRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/behandlinginfo/Etterbetaling.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoDaoTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoRoutesTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/behandlinginfo/BehandlingInfoServiceTest.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevDataMapperFerdigstillingVedtak.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/Etterbetaling.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/EtterlatteBrev.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelse.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgelseForeldreloes.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonOmregnetNyttRegelverk.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonRevurdering.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgetDTOTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/Brevutfall.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brevutfall/BrevutfallSkjema.tsx, libs/etterlatte-behandling-model/src/main/kotlin/no/nav/etterlatte/libs/common/behandling/EtterbetalingDto.kt
Ettersom `kravIEtterbetaling` og `etterbetalingPerioderValgt` ikke lengre er i bruk tar vi en opprydding i etterbetaling for barnepensjon
- `frivilligSkattetrekk` har i en periode blitt dobbeltlagret (`brevutfall` og `etterbetalingDto`), vi fjerner den fra `etterbetalingDto` ettersom `frivilligSkattetrekk` kan oppstå uten etterbetaling
- `datoTom` og `datoFom` i `etterbetalingDto` er faktisk ikke i bruk, endrer fra `etterbetaling` til `erEtterbetaling`, ikke utenkelig at `datoTom` og `datoFom` fases ut på sikt?
!! Det er og diskutert at historisk visning av valg i brevutfall ikke er relevant da dette uansett kommer frem i det genererte brevet 
Denne henger sammen med endringer i pensjonsbrev https://github.com/navikt/pensjonsbrev/pull/1148
=> EY-4889 rydde opp 'Utfall i brev' - etterbetaling, brevutfall 

apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/VedtakKlientImpl.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingHendelserService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/tilbakekreving/TilbakekrevingServiceIntegrationTest.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakTilbakekrevingService.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/config/ApplicationContext.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakTilbakekrevingServiceTest.kt, libs/rapidsandrivers-extras/src/main/kotlin/rapidsandrivers/IkkeStandardiserteKeys.kt
Utsending av vedtaksbrev for tilbakekreving ble gjort fra vedtaksvurdering tidligere. Dette skjedde før vi gjorde endelig kall mot tilbakekrevingskomponenten. Problemet her, er at sistnevnte kall kan feile (som vi har erfart), og da er brevet allerede på vei ut. 
Flytter nå trigging av hendelsen som journalfører og sender ut brevet til behandling, slik at vi kan sende vedtaket til tilbakekrevingskomponenten først, se at dette går fint for så å sende ut brevet.
=> EY-4879: Flytter trigging av hendelse for utsending av brev til behandling for tilbakekreving

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidManueltOverstyrt.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/trygdetid.ts, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidRoutes.kt, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt, apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidServiceIntegrationTest.kt
I noen tilfeller så har saksbehandler opprettet trygdetid med ukjent avdød (altså overstyrt trygdetid). Men ønsker senere å endre til vanlig trygdetid etter å ha oppdatert grunnlaget. Denne endringen gjør det mulig å gjøre dette ved å tilby en knapp for å opprette trygdetid på nytt. Denne vil overskrive eksisterende.
Se også porten-sak: https://jira.adeo.no/browse/FAGSYSTEM-362610?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D
=> EY-4892: Kunne endre fra overstyrt til vanlig trygdetid

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/utils/oppgaveSortering.ts
I stedet for å se på et annet datofelt når det er opprettet vi vil sortere på. Løser dette med å tilpasse sorteringsfunksjonen til å se på enten frist eller opprettet, avhengig av hva man ønsker
=> Fix: Sorteringen på dato for oppgaver sorterte alltid på frist

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt, apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-beregning/src/test/kotlin/TestHelper.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/AvkortingServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntektForm.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/Beregne.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BeregneBP.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BeregneOMS.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/avkorting.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/api/behandling.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts
- Deler Beregne.tsx opp i to egne for BP og OMS (er så mye logikk kun relevant for OMS)
- Sjekk om status avkorting hentes fra backend fordi det ikke er trygt å anta at status vil være avkorting i frontend
- Permanent håndtering av inntekt inntekt to år (ikke toggle eller hardkodet 2024)
Generelt vanskelig å få gode løsninger for disse tingene når beregningssiden er slik som nå. Tre steg på en side (beregning,avkorting og brevutfall) hvor beregning og avkorting har egen status men brevutfall ikke.
Det harmonerer ikke helt med "steg/status"-logikken behandlingsløpet legger opp til.
=> Refaktorer avkorting

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlFeilLogger.kt
```
java.lang.Exception: null
at no.nav.etterlatte.pdl.PdlFeilLoggerKt.loggDelvisReturnerteData(PdlFeilLogger.kt:31)
at no.nav.etterlatte.pdl.PdlKlient.hentPerson(PdlKlient.kt:49)
at no.nav.etterlatte.pdl.PdlKlient$hentPerson$1.invokeSuspend(PdlKlient.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at io.opentelemetry.javaagent.instrumentation.kotlinxcoroutines.RunnableWrapper.lambda$stopPropagation$0(RunnableWrapper.java:16)
at io.opentelemetry.javaagent.instrumentation.kotlinxcoroutines.RunnableWrapper.lambda$stopPropagation$0(RunnableWrapper.java:16)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at …
```
=> Kall til Exception fungerer ikke

.github/workflows/.test.yaml, .github/workflows/app-etterlatte-saksbehandling-ui.yaml
Sikrer at det er samme flyt og navn slik at kravet for å merge endring gir mer mening. 
Ser slik ut i workflow. Har samme navn på begge flytene (backend og frontend) for å matche `test / Verify pull request`
=> Felles workflow for frontend og backend (Verify pull request)

apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingService.kt, apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutesTest.kt, apps/etterlatte-trygdetid/.nais/dev.yaml, apps/etterlatte-trygdetid/.nais/prod.yaml, apps/etterlatte-trygdetid/build.gradle.kts, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/config/ApplicationContext.kt, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/klienter/VedtaksvurderingKlient.kt, apps/etterlatte-trygdetid/src/main/resources/application.conf, apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidServiceIntegrationTest.kt, apps/etterlatte-trygdetid/src/test/kotlin/no/nav/etterlatte/trygdetid/TrygdetidServiceTest.kt, apps/etterlatte-vedtaksvurdering/.nais/dev.yaml, apps/etterlatte-vedtaksvurdering/.nais/prod.yaml
Siden vi ikke kopierer med behandlingsgrunnlag (trygdetidsgrunnlag, beregningsgrunnlag, avkortingsgrunnlag) i opphør, er vi avhengig av å hente denne informasjonen fra siste vedtak som ikke er opphør. Dette var gjort riktig i avkorting, mens denne PR'en også gjør det på tilsvarende måte i beregningsgrunnlag og trygdetid.
=> EY-4794: Revurdering etter opphør gir riktig grunnlag for trygdetid og beregning

apps/etterlatte-brev-api/.nais/dev.yaml, apps/etterlatte-brev-api/.nais/prod.yaml
Vi får åtvaring i nais-konsollet vårt om at "Traffic from [etterlatte-brev-api](https://console.nav.cloud.nais.io/team/etterlatte/prod-gcp/app/etterlatte-brev-api) in namespace etterlatte (prod-gcp) is allowed by access policy, but [etterlatte-brev-api](https://console.nav.cloud.nais.io/team/etterlatte/prod-gcp/app/etterlatte-brev-api) does not have an outbound rule for pensjon-brevbaker." (og tilsvarande for dev)
Trur ikkje det er nokon grunn til at dokker bør kalle oss via ingress heller enn service discovery, men bør jo sjølvsagt teste i dev før eventuell merge.
=> Går over frå å bruke URL til å bruke outbound for brevbaker, som jo også køyrer på gcp

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/BrevOversikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrevHandlingerPanel.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/handlinger/SlettBrev.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Brev.ts
Det blir feil i aktivitetspliktsoppfølgingen om sb redigerer eller sletter brevet fra dens behandling, hotfix som fjerner muligheten i frontend.
=> FAGSYSTEM-363686 Hindre brev aksjoner på brev i aktivitetspliktflyten

apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingService.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/config/ApplicationContext.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtakBehandlingServiceTest.kt
Tidligere måtte man revurdere fra opphør-tidspunkt for å fjerne et opphør (med litt usynlig logikk i vedtaksvurdering). 
Nå som revurderinger kopierer med opphør fra og med, kan man i revurderingen velge om opphøret skal fjernes direkte i revurderingsoversikten. Vedtaksvurdering trenger ikke da å gjøre noe logikk her annet enn å sjekke konsistens.
=> Fjerner workaround for å fjerne opphørFom i revurdering da dette kan gjøres direkte nå

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/vilkaarsvurdering/Vurdering.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/vilkaarsvurdering.ts
Alle vilkår må fylles ut, så det skal ikke være behov for å slette vurderinger fra vilkårsvurdering. Fjerner derfor knappen for å unngå feil i vilkårsvurdering.
=> Fjern slett knapp på vilkår i vilkårsvurdering

apps/etterlatte-saksbehandling-ui/client/src/components/klage/sidemeny/KlageSidemeny.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/EndeligVurdering.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/InitiellVurdering.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/KlageVurderingFelles.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/components/KlageInnstilling.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/klage/vurdering/components/KlageOmgjoering.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/NyttBrevModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/oppretteklage/OppsummeringKlagebehandling.tsx
Diverse enkle småfikser og justeringer i klage-frontend
* Når ble vedtaken mottatt - skriveleif
* Gul alert, ta bort ved første steg (fra journalføringsflyt)
* I blå alert: Legg til kanskje - Du må kanskje sende brev til klager / eller presisere teksten 
* ønske om mellomlagring/ha lagreknapp
* Tekstboksene for smale 
* Se innstillingsbrevet og se blankett til KA, ha øye ikon/forhåndsvis 
* Intern kommentar, ha mer luft og større overskrift, nå flyter de sammen.
* Endre fra blankett, til "se innstillingsbrev til KA" 
* I høyresiden, bold headings begge steder, ser rart ut. Gjør brødtekst til regular.
* I alert skift fra av ka til "i klageinntans)
=> EY-4932 Fiksinger klage

apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/RevurderingService.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt, apps/etterlatte-beregning/src/main/kotlin/beregning/BeregningRepository.kt, apps/etterlatte-beregning/src/main/kotlin/sanksjon/SanksjonService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationContext.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/distribusjon/DistribusjonService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/beregning/BeregningService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonBeregning.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NotatRepository.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/notat/NotatRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/oversendelsebrev/OversendelseBrevService.kt, apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/gyldigsoeknad/PersongalleriMapper.kt, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/egendefinert/EgendefinertMeldingFeature.kt, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt, apps/etterlatte-vedtaksvurdering-kafka/src/main/kotlin/no/nav/etterlatte/regulering/AppBuilder.kt, apps/etterlatte-vilkaarsvurdering-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/AppBuilder.kt, libs/etterlatte-kafka/src/main/kotlin/kafka/JsonMessage.kt, libs/saksbehandling-common/src/testFixtures/kotlin/etterlatte/pdl/PersonTestData.kt
Bruker `krevIkkeNull` for å sikre at vi får error i loggene, tilsvarende hva `checkNotNull` har gjort til nå. 
Så kan vi filtrere ut det som bare er støy fortløpende.
=> EY-4738 Fjerner siste rest av check/require

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnOverstyrBeregningService.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnOverstyrServiceTest.kt
Regelverk ble ikke satt i overstyrt beregning. Dette medførte ikke problemer da dette også blir utledet i utbetaling, men ønsker egentlig at utbetaling skal få inn dette parameteret uten å ha noen fallback hvis det er `null`. Fin start å få det riktig ved alle tilfeller fra beregning / vedtak.
=> EY-4564: Legger til manglende regelverk i overstyrt beregning

apps/etterlatte-behandling/src/main/kotlin/behandling/aktivitetsplikt/AktivitetspliktRoute.kt, apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/unntak/LagreUnntakForm.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktVurdering.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/unntak/RedigerbarUnntakBehandling.tsx, apps/etterlatte-saksbehandling-ui/client/src/store/reducers/AktivitetspliktBehandlingReducer.ts
Skissene viser ikke hva som skjer ved nei så må bare improvisere her.
Spørsmålet her er hvordan vise frem varig unntak lagret, en custom sjekk som gjør at vanlig visning ikke inntreffer slik
at vi ikke viser vanlig listevisning men kun at det er valgt varig unntak?
edit:
Har håndtert dette ved litt ekstra state og egen visning hvis varig unntak.
=> Har aktivitetsplikt JANEI

apps/etterlatte-grunnlag/src/main/kotlin/grunnlag/rivers/GrunnlagHendelserRiver.kt, apps/etterlatte-gyldig-soeknad/src/main/kotlin/no/nav/etterlatte/gyldigsoeknad/NySoeknadRiver.kt, apps/etterlatte-opplysninger-fra-soeknad/src/main/kotlin/no/nav/etterlatte/opplysningerfrasoknad/StartUthentingFraSoeknadRiver.kt, apps/etterlatte-opplysninger-fra-soeknad/src/test/resources/melding.json, apps/etterlatte-testdata/src/main/kotlin/no/nav/etterlatte/testdata/features/soeknad/SoeknadMapper.kt, libs/saksbehandling-common/src/main/kotlin/event/SoeknadInnsendt.kt
- `GrunnlagHendelseRiver` har kun aktivt eventname. Bruker det direkte. 
- Fjerner `@adressebeskyttelse` siden det ikke lenger er i bruk
- Bruke constants for nøkler
=> Fjerne mer ubrukt kode fra rivers (EY-4942)

apps/etterlatte-saksbehandling-ui/client/src/shared/api/apiClient.ts
Uten dette vil frontenden prøve å logge noe selvom serveren ikke er klar og gå i evig loop.
Prøv å kjør opp frontend lokalt også drepe serveren deretter gjør noe i frontend så får du replikert oppførselen.
=> Ikke prøv å logg noe hvis serveren ikke vil ta i mot connections

apps/etterlatte-utbetaling/src/main/kotlin/no/nav/etterlatte/utbetaling/iverksetting/utbetaling/Utbetaling.kt
Ser også på å gjøre en endring for å splitte bruken av klassifikasjonskode for utbetaling og simulering da disse stadig er tilbakevendende. Vi har ikke så stort behov for typing ved simulering slik det er lagt inn i koden nå.
=> Legger til manglende klassekode for bidragsforskudd

libs/etterlatte-vilkaarsvurdering-model/src/main/kotlin/vilkaarsvurdering/VilkaarType.kt
Markerer hvilke vilkår som er aktuelle for kopiering ved kopi av vilkårsvurdering i søskensaker. Se kommentar i jira: https://jira.adeo.no/browse/EY-4635.
Har en utestående avklaring på om unntaksvilkårene også kan være aktuelle å kopiere dersom disse omhandler avdøde spesifikt.
=> EY-4938: Markerer vilkår aktuelle for kopiering

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/virkningstidspunkt/Virkningstidspunkt.tsx
Forslag til advarsel hvis saksbehandler prøver å sette virk uten at det er registrert dødsdato. 
Tar gjerne tips til forbedring av tekst.
=> Vis advarsel om at dødsdato ikke er registrert ved setting av virk

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/trygdetidPerioder/TrygdetidPerioder.tsx, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
Nuller ut beskrivelse av trygdetid hvis den er automatisk og endres
Fjerner litt unødvendig nøsting trygdetidperioder
=> EY-4956 Oppdater kommentar framtidig tt

apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/vurdering/unntak/LagreUnntakForm.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/header/HeaderBanner.tsx
Det manglet mellomrom mellom avbryt/lagre og tekstfeltet over
Diven til juletreet var fortsatt tilstede selv om julen er over. Spacing rundt Gjenny er nå riktig igjen.
=> Miniendringer i ui

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/RedigerbartBrev.tsx
Så det å vise knappen når vi ikke støtter det blir misvisende
=> Kun vedtaksbrev støtter tilbakestilling

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/Aktivitetsplikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/aktivitetsplikt/AktivitetspliktVurdering.tsx
Fikser logikken som gjør at saksbehandler kan gå videre hvis de har valgt varig unntak for bruker. Dette gjør også at hvis saksbehandler sletter en vurdering, så må de fylle inn aktivitetsplikt for å kunne gå videre.
=> La bruker gå videre hvis de har varig unntak

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/RedigerbartBrev.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/vedlegg/VedleggInfo.tsx
Ikke alltid lett å huske på å fjerne hjelpetekst fra brev, legger derfor til infoboks
- En hjelpetekst dukker opp i fanen for vedlegget hvis det er definert. 
Henger sammen med endring i pensjonsbrev https://github.com/navikt/pensjonsbrev/pull/1225
=> EY-4824 vise hjelpetekst ved spesifikke vedlegg

apps/etterlatte-beregning/src/main/kotlin/beregning/BeregnOverstyrBeregningService.kt, apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/BeregnOverstyrServiceTest.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt, libs/etterlatte-beregning-model/src/main/kotlin/OverstyrBeregningsGrunnlag.kt
Kopierer også inn grunnlaget fra forrige iverksatte behandling i revurderinger, hvis det finnes.
=> EY-4680 Sjekker konsistens med forrige overstyrt grunnlag

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingDao.kt, apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/utbetalinger/TilbakekrevingVurderingPerioderRadAndreKlassetyper.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/utbetalinger/TilbakekrevingVurderingPerioderSkjema.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/tilbakekreving/utbetalinger/TilbakekrevingVurderingPerioderVisning.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Tilbakekreving.ts, libs/etterlatte-tilbakekreving-model/src/main/kotlin/Tilbakekreving.kt
For at saksbehandler skal få et bedre overblikk over tilbakekrevingsperiodene, er det ønsket å også kunne se andre klassetyper slik som feilkonto og skattetrekk. Legger på dette (som readonly) i tilbakekrevingsvisningen.
=> EY-4961: Vise andre klassetyper enn YTEL i tilbakekreving

apps/etterlatte-behandling/src/main/kotlin/common/klienter/PesysKlient.kt, apps/etterlatte-behandling/src/test/kotlin/common/klienter/PesysKlientImplTest.kt
Et steg på veien i å rydde opp i datobruken i PEN.
Endepunktet er fra før av tatt i bruk av selvbetjeningsapper i Pensjon. https://nav-it.slack.com/archives/CB8B2R4G6/p1738325495454769?thread_ts=1738247587.380599&cid=CB8B2R4G6
=> Svitsjet til nytt PEN-endepunkt for Sakssammendrag med enklere datoformat

apps/etterlatte-behandling/src/main/kotlin/vilkaarsvurdering/service/VilkaarsvurderingService.kt, apps/etterlatte-behandling/src/main/kotlin/vilkaarsvurdering/vilkaar/OmstillingstoenadVilkaar.kt, apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt, apps/etterlatte-behandling/src/test/kotlin/vilkaarsvurdering/VilkaarsvurderingServiceTest.kt
Fjerner vilkåret med følgende ordlyd fra førstegangssøknad for OMS:
`Hvis en etterlatt som er innvilget omstillingsstønad etter § 17-5 tredje ledd (hadde rettigheter utover 3-5 år på grunn av lav inntekt siste fem år før dødsfall) inngår skilsmisse innen to år, får vedkommende rett til omstillingsstønad igjen.`
Dette gir kun mening i en revurdering. Når en revurdering opprettes vil dette vilkåret nå legges til. Saksbehandler slipper dermed å behandle dette i førstegangsbehandling.
=> EY-4947: Fjerner urelevant vilkår fra OMS førstegangsbehandling

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtaksbrev/VedtaksbrevService.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottakerWrapper.tsx
Funksjonen `ferdigstill` i `BrevService` brukes kun fra frontend, så det holder å kaste `UgyldigForespoerselException`
=> Feilmelding til saksbehandler + fjerne error logg

apps/etterlatte-behandling/src/main/kotlin/Application.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/AvbryterFeilopprettedeRevurderingJob.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/resources/db/migration/V229__avbryt_feil_opprettede_aktivitetspliktoppgaver.sql
Det ble opprettet aktivitetspliktrevurderinger for 12-månederskravet for feil måneder i starten av februar. Disse skal avbrytes.
Siden revurderinger er noe vi har sendt til statistikken er det best å avbryte de via service-laget for å få riktig håndtering. 
Aktivitetspliktoppgavene kan bare avbrytes med en oppdatering i databasen.
=> Avbryter ekstra feilopprettede aktivitetspliktoppgaver

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/ApplicationContext.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/BrevdataFacade.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottakerWrapper.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/api/brev.ts, libs/etterlatte-ktor/src/main/kotlin/route/RouteUtils.kt
TODO: teste rollback her, er sikkert ikke som intransaction i behandling.. -> flyttet om på rekkefølgen for å oppnå litt bedre handling
motivasjon: få nye mottakere om sb oppdaterer grunnlaget riktig
=> EY-5031 Tilbakestille mottakere fra oppdatert grunnlag

apps/etterlatte-saksbehandling-ui/client/src/components/person/journalfoeringsoppgave/journalpost/EndreAvsenderMottaker.tsx
Det ser ut som Dolly ikke setter idType helt, så feiler å oppdatere journalpost. Setter den til FNR ettersom det er de vi bruker
=> Sette idType til FNR i avsnederMottaker

apps/etterlatte-brev-api/src/main/resources/graphql/journalpost.graphql
AvsenderMottaker har type, men den blir aldri etterspurt i graphql
=> hente type i graphql spørring journalpost

apps/etterlatte-testdata-behandler/.nais/dev.yaml, apps/etterlatte-testdata-behandler/src/main/kotlin/no/nav/etterlatte/testdata/AppBuilder.kt, apps/etterlatte-testdata-behandler/src/main/resources/application.conf
Gå mot identisk route som nå er i `etterlatte-behandling`
Avhenger av https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/7046
=> EY-4942 Koble testdata-behandler til grunnlag via behandling

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingFactory.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/klage/KlageService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/BehandlingFactoryTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/ManuellRevurderingServiceTest.kt
Reell frist for disse oppgavene er avhengig av når Nav har mottatt søknad / klage, og ikke når vi har registrert behandlingen i vårt system. Setter i stedet fristen ut i fra søknad/klage mottatt.
=> EY-5025 Setter frist på førstegangsbehandlinger / klager ut i fra mottatt dato

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
* har fått det med seg så foreslår jeg at jobben bare kjører sjeldent i dev så vi slipper alle error loggene på den
evt bare kjøre om natta i dev?
=> Siden dødsmeldinger kommer kjempelenge før pdl og parallelklienter

apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/test/kotlin/VerdikjedeTest.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/ManuellRevurderingServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/integration/BehandlingIntegrationTest.kt
Gjør noen justeringer for å gjøre det enklere å bytte til ekte dao i hvert av miljøene. Dette medfører at testene nå kjører med reell dao i stedet for mock.
=> EY-4942: Justerer bruk av proxy for grunnlag

apps/etterlatte-behandling-kafka/build.gradle.kts, apps/etterlatte-behandling-kafka/src/main/kotlin/no/nav/etterlatte/AppBuilder.kt, apps/etterlatte-behandling-kafka/src/main/kotlin/no/nav/etterlatte/Application.kt, apps/etterlatte-behandling-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRiver.kt, apps/etterlatte-behandling-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingService.kt, apps/etterlatte-behandling-kafka/src/main/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingTidshendelseRiver.kt, apps/etterlatte-behandling-kafka/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingRiverTest.kt, apps/etterlatte-behandling-kafka/src/test/kotlin/no/nav/etterlatte/vilkaarsvurdering/VilkaarsvurderingTidshendelseRiverTest.kt
Flytter rivere fra `etterlatte-vilkaarsvurdering-kafka` til `etterlatte-behandling-kafka` da vilkårsvurdering nå er en del av behandling.
=> EY-5008: Flytte rivere for vilkårsvurdering til behandling-kafka

apps/etterlatte-behandling/src/main/resources/db/prod/V234__dropp_indekser_foer_merge_grunnlag.sql
* Da det tar kjempelang tid å kjøre migreringen med de på.
* De må legges på senere da dataen er i behandling, ikke i kjøringen
=> Dropp indekser for grunnlag i prod i behandling(ingen data der enda)

apps/etterlatte-behandling/src/main/resources/db/dev/V241__lag_servicerolledev.sql
rollen fantes allikevel?
`Caused by: org.postgresql.util.PSQLException: ERROR: role "cloudsqliamserviceaccount" already exists`
selvom den ikke får deploya uten.
=> Rollen fantes allikevel dev

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/familieforhold/RedigerFamilieforholdModal.tsx
Nå kan man lagre etter en oppdatering av grunnlag før siden refreshes som vil vise feil state potensielt. 
Ingen grunn til å støtte lagring 1 sek før siden oppdateres
=> Ikke kunne lagre på nytt før siden har blitt refreshet

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BeregneBP.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BeregneOMS.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/SimulerUtbetaling.tsx
Legger på simulering ved opphør av ytelse. Dette er nyttig i saker hvor det opphøres tilbake i tid, og dette medfører feilutbetaling. Da er det ønskelig for saksbehandler å se beløp.
=> FAGSYSTEM-371156: Legger på simulering ved opphør

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/ViderefoertOpphoerTest.kt
Dersom det er valgt ja ved videreført opphør, må det finnes en dato.
=> EY-5058: Dato må være satt ved videreført opphør

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/Trygdetid.tsx
Slik vistes det før (merk at det er samme behandling men i dev og den er innvilget):
=> Viser ikke kopiering av TT hvis behandling ikke kan endres

apps/etterlatte-behandling/src/main/resources/db/prod/V244__avbryt_oppgave_feil_opphoer.sql
Det ble ikke lagt til opphør fra og med dato i saken, denne gikk derfor helt til 21 år og fikk automatisk opprettet en oppgave på det tidspunktet. Denne er ikke lenger nødvendig da det er gjort et manuelt opphør ved 20 år i etterkant.
=> FAGSYSTEM-371156: Avbryter ikke relevant oppgave for alderovergang 21 år

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/trygdetid/TrygdetidIAnnenBehandlingMedSammeAvdoede.tsx
Må også kjøre effekt når trygdetider oppdateres. Dette vil typisk være tilfelle når man oppretter trygdetid første gang man går inn på trygdetidssteget.
=> FAGSYSTEM-372317: Fikser visning av "kopier trygdetid" komponent

apps/etterlatte-tidshendelser/src/main/resources/db/prod/V23__ekstra_kjoering_av_aktivitetsplikt.sql
Oppgavene som ideelt burde blitt kjørt i januar ble hoppet over når vi fikset behandlingsmåneden-avvikene i tidshendelser
=> Lager infobrevoppgaver som mangler i produksjon

apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/domain/Behandling.kt
Siden dette er et "separat" spor fra den innvilgede ytelsen er den ikke relevant i filtreringen på hva som er siste iverksatte behandling i saken
=> Ikke ta med avslag ny soeknad i liste over siste iverksatte

apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/brev/AktivitetspliktBrev.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/aktivitetsplikt/brev/FerdigstillBrevModal.tsx
Backend håndterer dette fint (verifisert i dev), men vi viser ikke knappen til saksbehandler hvis brevet allerede er distribuert. 
Viser også en melding om at brevet allerede er distribuert hvis det er det når oppgaven ferdigstilles
=> FAGSYSTEM-372626 Kan ferdigstille oppgave også hvis brev er ferdigstilt

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/sigrun/SkatteoppgjoerHendelserDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/sigrun/SkatteoppgjoerHendelserService.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/resources/db/migration/V250__opprette_tabell_skatteoppgjoer_hendelser_kjoeringer.sql, apps/etterlatte-behandling/src/test/kotlin/behandling/etteroppgjoer/sigrun/SkatteoppgjoerHendelseDaoTest.kt
Deloppgave
Opprette tabell som holder styr på sekvensnummer som brukes for å hente skatteoppgjoer hendelser. 
```
antallHendelser = hvor mangen hendelser vi ønsker
antallBehandlet = hvor mangen vi har sjekket opp mot hvem som skal ha etteroppgjør
antallRelevante = hvor mangen som det er opprettet forbehandling for 
```
=> EY-5093 opprette tabell for skatteoppgjoer hendelser kjoering

apps/etterlatte-utbetaling/src/main/resources/db/migration/V19__patch_sluttbehandling_utland.sql
NBNB: greit å ta en backup av basen før denne kjøres, og dobbeltsjekke den i dev en gang med transaksjon og verifisere at det blir rett
=> Oppdaterer vedtak som har gammel enumverdi lagret

apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/ManuellRevurderingService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlag/GrunnlagService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/ManuellRevurderingServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlag/GrunnlagServiceTest.kt
Går tilbake til å hente persongalleriet brukt i forrige iverksatte behandling ved revurdering.
Dette ble endret i forbindelse med å innføre støtte for å endre ident i sak. For å fortsatt støtte dette konseptet, gjøres det nå en uthenting av siste gjeldende ident på søker i persongalleriet slik at dersom dette har blitt endret siden forrige behandling, så vil det også bli oppdatert i ny behandling. 
Dette burde løse problemer som vi har sett i det siste slik som:
https://jira.adeo.no/browse/FAGSYSTEM-373275
Må testes litt for å verifisere.
=> EY-5099: endring ved uthenting av persongalleri i revurdering

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
Nå som vi har avklart at TREK med klassekode BPSKSKAT er forventet for barnepensjon, legger vi dette til som en kjent type.
=> Legger til TREK som kjent klassetype i tilbakekrevingvarsel

apps/etterlatte-behandling/src/main/kotlin/Application.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/VedtakKlientImpl.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepository.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRoute.kt, apps/etterlatte-vedtaksvurdering/src/main/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingService.kt, apps/etterlatte-vedtaksvurdering/src/test/kotlin/no/nav/etterlatte/vedtaksvurdering/VedtaksvurderingRepositoryTest.kt, libs/etterlatte-ktor/src/main/kotlin/token/BrukerTokenInfo.kt
Alle saker med en utbetalingsperiode for inntektsaar skal ha etteroppgjør
Oppretter etteroppgjør og setter status til `VENTER_PAA_SKATTEOPPGJOER`
=> EY-5086 opprette etteroppgjør for saker som skal ha det for inntektsaar

apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDao.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveDaoMedEndringssporing.kt, apps/etterlatte-behandling/src/main/kotlin/oppgave/OppgaveService.kt, apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveDaoTest.kt, apps/etterlatte-behandling/src/test/kotlin/oppgave/OppgaveServiceTest.kt
Tidligere ville kun oppgaver som var markert som strengt fortrolig og strengt fortrolig utland vises hvis for vikafossen. Dette er litt uheldig da vi har hatt tilfeller hvor oppgaver har hatt denne enheten, men ikke hatt gradering og derfor ikke har vært synlig for saksbehandler. 
Det bør holde at saksbehandler har enhet Vikafossen for å kunne hente hvilke som helst oppgaver som ligger på denne enheten.
=> EY-5079: Viser alle oppgaver som har enhet Vikafossen, også de som ikke er gradert

apps/etterlatte-behandling/src/main/kotlin/Application.kt, apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt, apps/etterlatte-behandling/src/test/kotlin/VerdikjedeTest.kt, apps/etterlatte-behandling/src/test/kotlin/adressebeskyttelse/AdressebeskyttelseTest.kt, apps/etterlatte-pdltjenester/src/main/kotlin/pdl/PdlFeilLogger.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/aktivitet/AktivitetspliktSakoversikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/BrevOversikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/KnyttTilAnnenBruker.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/dokumenter/avvik/KnyttTilAnnenSak.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/notat/NotatOversikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/SakIkkeFunnet.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/Sakshistorikk.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/header/Search.tsx, libs/saksbehandling-common/src/main/kotlin/feilhaandtering/ForespoerselException.kt
- egen pr for spesialsøk på fnr
- egen pr for div fjerning av info i oppgavelisten blant annet fnr
Spørsmål:
Hvilke andre steder burde vi tenke på statuskode håndtering som kan bli påvirket av dette? Som feks pdl-tjenester var det litt tilfeldig at jeg fant.
=> Endre til å bruke 403 hvis man mangler tilgang

apps/etterlatte-behandling/src/main/kotlin/behandling/tilbakekreving/TilbakekrevingService.kt
Hvis ikke får vi ikke registrert relevant og riktig statistikk for tilbakekrevinger. En fiks på tidligere sendte data må vurderes separat.
=> Sender oppdatert tilbakekreving til statistikk

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerModel.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerBrevService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt
Henting av beregnet resultat ble kjørt ved henting av forbehandling. Dette feiler for nye forbehandlinger som ikke enda har beregnet etteroppgjøret
=> rette feil ved henting av forbehandling etteroppgjør

apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/AutomatiskRevurderingService.kt
Manglet `inTransaction` ved automatisk revurdering (alderovergang BP og OMS)
=> Legger til manglende inTransaction for automatisk revurdering

apps/etterlatte-behandling/src/main/kotlin/brev/BrevKlientImpl.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtaksbrev/VedtaksbrevRouteNy.kt
Endepunktet forventet `pathParam` og `queryParam`. Får feilmelding ved ferdigstilling av brev i prod pga manglende `queryParam`.
Endrer til å kun bruke `queryParam` da dette også er brukt i tilbakestilling etc
=> FAGSYSTEM-377893 rette feil ved ferdigstilling av strukturert brev

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerModel.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/revurdering/EtteroppgjoerRevurderingService.kt, apps/etterlatte-behandling/src/main/resources/db/migration/V263__legge_til_nytt_felt_etteroppgjoer_forbehandling.sql, apps/etterlatte-behandling/src/test/kotlin/behandling/etteroppgjoer/EtteroppgjoerForbehandlingDaoTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/Etteroppgjoeroversikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/oversiktOverEtteroppgjoer/fastsettFaktiskInntekt/FastsettFaktiskInntekt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/EtteroppgjoerForbehandlingListe.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Etteroppgjoer.ts
Ved oppretting av revurdering for etteroppgjør oppretter vi og en kopi av forbehandling. Dette for å ikke overskrive inntekter i den første forbehandlingen. Den nye forbehandlingen viser faktisk inntekt fra forrige forbehandling via `relatertForbehandlingId`
TODO
=> EY-5160 opprette kopi av forbehandling ved oppretting av revurdering

apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/BeregningsGrunnlagService.kt, apps/etterlatte-beregning/src/test/kotlin/beregning/grunnlag/BeregningsGrunnlagServiceTest.kt
Fjerner validering av søsken i beregning dersom virkningstidspunkt er etter reformtidspunkt. Søskenjustering er da ikke aktuelt.
=> FAGSYSTEM-374321: Sjekker kun søsken i beregning før 2024

apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/AppContext.kt, apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/JobbPoller.kt, apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/aarliginntektsjustering/AarligInntektsjusteringService.kt, apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/omregning/OmregningDao.kt, apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/omregning/Omregningskonfigurasjon.kt, apps/etterlatte-tidshendelser/src/main/kotlin/no/nav/etterlatte/tidshendelser/omregning/ReguleringService.kt, apps/etterlatte-tidshendelser/src/main/resources/db/migration/V25__endre_navn_reguleringskonfigurasjon.sql, apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/JobbPollerIntegrationTest.kt, apps/etterlatte-tidshendelser/src/test/kotlin/no/nav/etterlatte/tidshendelser/regulering/OmregningDaoTest.kt
Legger også til et frivillig felt for å kontrollere kjøring-id'en, som brukes i stedet for datoen for konfigurasjonen hvis den er satt.
=> Renamer reguleringskonfigurasjon til Omregningskonfigurasjon

apps/etterlatte-beregning/src/main/kotlin/avkorting/regler/EtteroppgjoerResultatBeregning.kt, apps/etterlatte-beregning/src/test/kotlin/avkorting/regler/EtteroppgjoerBeregningResultatTest.kt
Grenseverdier for tilbakekreving og etterbetaling var byttet om
=> EY-5183 rette bug beregneEtteroppgjoerResultat

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/ParallelleSannheterService.kt
Hvis vi får en tom liste fra PDL så vil vi feile på måten vi ser i produksjon nå.
=> Er mer fleksibel på respons med manglende folkeregisteridentifikator

apps/etterlatte-behandling/src/main/kotlin/common/klienter/PdlTjenesterKlient.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/DoedshendelseUtil.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/PersonFnrMedRelasjon.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktAvdoedService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktBarnService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktEktefelleService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktOMSService.kt, apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktService.kt, apps/etterlatte-behandling/src/test/kotlin/TestHelper.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseJobServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/DoedshendelseUtilTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktAvdoedServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktBarnServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktEktefelleServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktOMSServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/grunnlagsendring/doedshendelse/kontrollpunkt/DoedshendelseKontrollpunktServiceTest.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/ParallelleSannheterService.kt, apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonRoute.kt, apps/etterlatte-pdltjenester/src/main/kotlin/person/PersonService.kt, libs/etterlatte-pdl-model/src/main/kotlin/pdl/PersonDTO.kt
Siden vi ikke har garanterte opplysninger på alle feltene som ikke brukes men er påkrevde i PersonDTO henter vi i stedet ut en mindre modell som kan brukes til å avklare sjekkpunktene i en dødshendelse
=> Leser en mindre modell for dødhendelser

apps/etterlatte-behandling/src/main/kotlin/brev/BrevService.kt
Så denne når jeg leste igjennom kode, riktig oppførsel (som også er beskrevet) er å ikke kaste internException her
=> Kaster faktisk den opprinnelige responseexception, ikke parseexception

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntektTabell.tsx
- Fjerning av historikk knappen, viser bare alle uansett,
- Inntektsavkorting år `<Tag />` er grønn hvis året er 2024 og det er etteroppgjør revurdering
=> EY-5196 forbedring av inntektsavkorting

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/brev/EtteroppgjoerBrevModel.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingModel.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BeregningKlientImpl.kt, apps/etterlatte-behandling/src/test/kotlin/integration/EksterneKlienter.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRepository.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/AvkortingRoutes.kt, apps/etterlatte-beregning/src/main/kotlin/avkorting/etteroppgjoer/EtteroppgjoerService.kt, apps/etterlatte-beregning/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/fastsettFaktiskInntekt/FaktiskInntektSkjema.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/fastsettFaktiskInntekt/FaktiskInntektVisning.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/fastsettFaktiskInntekt/SumAvFaktiskInntekt.tsx, apps/etterlatte-saksbehandling-ui/client/src/shared/types/Etteroppgjoer.ts, libs/etterlatte-beregning-model/src/main/kotlin/BeregningDTO.kt, libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/model/oms/EtteroppgjoerBrevData.kt
- Sende med faktisk inntekt ved oppretting av brev, dette for å vise tabell over grunnlag i brev
- FaktiskInntekt vises i frontend som del av etteroppgjør, rydder opp endepunkt for å hente det ut
Se PR i pensjonsbrev
https://github.com/navikt/pensjonsbrev/pull/1502
=> EY-5212 sende med faktisk inntekt som grunnlag ved oppretting av brev

apps/etterlatte-behandling/src/main/kotlin/Application.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingDao.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingModel.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/EtteroppgjoerJobService.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/resources/db/migration/V266__legge_til_relatertb_behandling_id_forbehandling.sql, apps/etterlatte-behandling/src/main/resources/db/migration/V266__legge_til_siste_iverksatte_behandling_for_forbehandling.sql, apps/etterlatte-behandling/src/test/kotlin/behandling/etteroppgjoer/EtteroppgjoerForbehandlingDaoTest.kt
Tidligere brukte vi sisteIverksatteBehandling for å hente beregnetEtteroppgjoerResultat, problemet der er at hvis en forbehandling er ferdigstilt og vi har gjennomført en revurdering så finner vi ikke et resultat fordi sisteIverksattebehandling har endret seg. 
- Ender til å lagre relatertBehandlingId som brukes for å hente beregnetEtteroppgjoerResultat
NB! Dette vil bryte tidligere saker i Gjenny da relatertBehandlingId er påkrevd og forventet...
- Vi bør kanskje ha en sjekk som sjekker om sisteIverksatteBehandling har endret seg mens forbehandling er under behandling. Da vil relatertBehandlingId ikke peke på siste
=> EY-5215 lagre relatertBehandling ved opprettelse av forbehandling

apps/etterlatte-beregning/src/main/resources/db/migration/V63__patch_soeskenjustering_beregningsgrunnlag_periode.sql
En sak i produksjon skal innvilges langt tilbake i tid, og det er ingen søsken.
Når vi opprettet beregningsgrunnlaget i saken ble det lagt inn ingen søsken fra original virk,
som nå er utdatert. Dette er ikke mulig for saksbehandler å gjøre noe med, siden de ikke får opp valget
for søskenjustering.
=> FAGSYSTEM-381181 Patch grunnlag som har utdatert dato

apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/EtteroppgjoerResultatVisning.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/components/resultatAvForbehandling/BrevutfallAvForbehandling.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/revurdering/EtteroppgjoerRevurderingOversikt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/etteroppgjoer/revurdering/EtteroppgjoerRevurderingResultat.tsx
Ved beregning av fastsatt inntekt skal vi vise resultat av etteroppgjøret på lik linje som i forbehandling. 
Det kommer potensielt flere endringer her og skiller seg ut fra forbehandling
=> EY-5200 vise resultat av etteroppgjøret for revurdering

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntektForm.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/OverstyrInnvilgaMaaneder.tsx
Sender med skjemaelementer som props i stedet -- siden context rundt var magisk fjernet og vi kun brukte den contexten dette stedet er det mer naturlig å sende med props i stedet
=> Fikser overstyr innvilgede måneder

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/brev/EtteroppgjoerBrevModel.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/brev/EtteroppgjoerForbehandlingBrevService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/brev/EtteroppgjoerRevurderingBrevService.kt, apps/etterlatte-behandling/src/main/kotlin/brev/BrevKlientImpl.kt, apps/etterlatte-behandling/src/main/kotlin/brev/TilbakekrevingBrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevRoute.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/InnholdTilRedigerbartBrevHenter.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/RedigerbartVedleggHenter.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/FeilutbetalingUtils.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/InnholdMedVedlegg.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonBeregning.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonOpphoer.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonRevurdering.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadInnvilgelse.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadOpphoer.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/oms/OmstillingsstoenadRevurdering.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtaksbrev/StrukturertBrevService.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/VedtaksbrevServiceTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/db/BrevRepositoryIntegrationTest.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/model/bp/BarnepensjonInnvilgetDTOTest.kt, libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/BrevData.kt, libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/EtterlatteBrevkode.kt, libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/model/oms/EtteroppgjoerBrevData.kt, libs/etterlatte-brev-model/src/main/kotlin/no/nav/etterlatte/brev/model/tilbakekreving/TilbakekrevingBrevData.kt
Se endring i pensjonsbrev også -> https://github.com/navikt/pensjonsbrev/pull/1522
- legge til støtte for innhold for vedlegg i strukturert brev
=> EY-4934 fritekst i beregningvedlegg etteroppgjør

apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/Avkorting.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntekt.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/AvkortingInntektForm.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/avkorting/OverstyrInnvilgaMaaneder.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BeregneEtteroppgjoerOMS.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/beregne/BeregneOMS.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/behandling/felles/utils.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/api/avkorting.ts, apps/etterlatte-saksbehandling-ui/client/src/shared/types/IAvkorting.ts, apps/etterlatte-saksbehandling-ui/client/src/utils/formatering/dato.ts
Endrer på AvkortingInntektForm til å heller ta imot en liste av inntekter som skal lagres / redigeres, i stedet for å duplisere komponenten. På denne måten får vi sendt alle inntektene over riktig slik at man kan legge inn alle inntektene med en gang før man prøver å beregne avkortingen, slik at man ikke er hindret hvis beregning har knekkpunkt i flere årsoppgjør
=> EY-5219 Støtter lagring av flere inntekter i samme gang i avkorting

apps/etterlatte-behandling/src/main/kotlin/behandling/revurdering/ManuellRevurderingService.kt, apps/etterlatte-behandling/src/test/kotlin/behandling/revurdering/ManuellRevurderingServiceTest.kt
Slik at vi ikke får unødvendig støy i prodloggene og saksbehandler får bedre informasjon om hvorfor noe går galt
=> Kaster riktige exceptions i revurderingservice

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/BrevService.kt, apps/etterlatte-brev-api/src/test/kotlin/no/nav/etterlatte/brev/BrevServiceTest.kt, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/BrevMottakerPanel.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/brev/mottaker/RedigerMottakerModal.tsx, apps/etterlatte-trygdetid/src/main/kotlin/trygdetid/TrygdetidService.kt
Det er tilfeller hvor mottaker med utenlandsadresser har blitt lagret med postnummer / sted. Saksbehandler har ingen enkel måte å rette opp i det.
- Vise postnummer / sted for alle type adresse
- Validere adresse ved lagring for å fange opp feil adresse
=> FAGSYSTEM-386582 validere mottaker adresse ved lagring

apps/etterlatte-behandling/src/main/kotlin/behandling/generellbehandling/GenerellBehandlingService.kt
Kravpakke for sak hentes ut og vises i frontend når man gjør en sluttbehandling, så feilmeldingen er viktig å få vist til saksbehandler. Dette er også en feilmelding som ikke trenger alarm i prod, siden dette er som følge av saksbehandlingen i saken
=> Bedre exception for kravpakke med feil status

apps/etterlatte-pdltjenester/src/main/kotlin/pdl/mapper/ParallelleSannheterService.kt
Fikser en potensiell regresjon hvis det første vergemålet i listen er historisk vergemål, men bruker har fremdeles aktivt vergemål.
=> Henter ut vergemål for statuslinjen mer stabilt hvis det er flere vergemål

apps/etterlatte-behandling/src/main/kotlin/oppgaveGosys/GosysOppgaveRoute.kt, apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/GosysOppgaveModal.tsx, apps/etterlatte-saksbehandling-ui/client/src/components/person/sakOgBehandling/ForenkletGosysOppgaverTable.tsx
Handlinger for gosys oppgave blir ikke synlig før siden lastes på nytt. Endrer så vi oppdatere oppgave tildeling med en gang slik at handlingene blir synlig.
=> Oppdatere oppgave tildeling 

apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/hentinformasjon/beregning/BeregningKlient.kt
Dette pga feil ved generering av PDF i brev-api: Henting av beregning for behandling med behandlingId=* feilet. Forrige iverksatte behandling har ikke nødvendigvis noen beregning.
=> Slutter å kaste exception når henting av beregning gir 404.

apps/etterlatte-brev-api/.nais/dev.yaml, apps/etterlatte-brev-api/.nais/prod.yaml
* Fra saf-scope til dokdistfordeling-scope for dokdistfordeling integrasjonen
> Vi gjør endringer på autentisering i dokdistfordeling, for å sørge for at autentisering med EntraID er implementert som tiltenkt. Pr i dag kalles distribuerJournalpost med EntraID tokens scopet mot SAF, hvor dokdistfordeling proxyer dette tokenet videre i kall til SAF. Vi ønsker på sikt å endre dette til av dokdistfordeling kun kan kalles med tokens som er scopet mot seg selv. Steg 1 av denne endringen innføres nå, hvor dokdistfordeling i en overgangsperiode vil akseptere tokens med enten saf- eller dokdistfordeling-scope. Dette innebærer at konsumenter ikke trenger å gjøre noe umiddelbart, men på sikt (helst så snart som mulig) må endre scope for tokenet de kaller dokdistfordeling med. Vi kommer til å bistå …
=> Oppdaterer scope for dokdistfordeling

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/EtteroppgjoerSvarfristUtloeptModal.tsx
Opprett revurdering tar ikke inn forbehandlingId da endepunktet allerede henter siste ferdigstilte forbehandling. 
Må diskutere senere hvorvidt vi skal bruker oppgave.referanse eller alltid ta utgangspunkt i siste ferdigstilte forbehandling, det kan være en corner-case hvor det ikke er snakk om samme forbehandling.
=> Rette byggefeil for etteroppgjoer svarfrist utloept modal

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerRoutes.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/brev/EtteroppgjoerForbehandlingBrevService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingModel.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/forbehandling/EtteroppgjoerForbehandlingService.kt, apps/etterlatte-behandling/src/main/kotlin/behandling/jobs/etteroppgjoer/EtteroppgjoerSvarfristUtloeptJobService.kt, apps/etterlatte-behandling/src/main/kotlin/brev/BrevService.kt, apps/etterlatte-behandling/src/main/kotlin/config/ApplicationContext.kt, apps/etterlatte-behandling/src/main/kotlin/tilgangsstyring/Tilgangsstyring.kt, libs/etterlatte-ktor/src/main/kotlin/route/RouteUtils.kt
Validering ved ferdigstille brev slår ut ettersom forbehandling ikke er under behandling. Valideringen er overflødig og kan fjernes
=> Rette feil ved ferdigstille brev etteroppgjør forbehandling

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/EtteroppgjoerOppgaveService.kt
Vi skal opprette oppgave for ny forbehandling hvis revurdering for etteroppgjøret avsluttes pga endring er til ugunst for bruker. 
I dag feiler det pga vi allerede har en oppgave under behandling. Må derfor filtrere bort ikke relevante oppgaver
=> filtrere bort ikke relevante oppgaver

apps/etterlatte-saksbehandling-ui/client/src/components/oppgavebenk/oppgaveModal/EtteroppgjoerSvarfristUtloeptModal.tsx
Legger til HelpText i modal for svarfrist utløpt:
=> Legger til HelpText i modal for svarfrist utløpt

apps/etterlatte-behandling/src/main/kotlin/behandling/klienter/BrevApiKlient.kt
Er det ok? Ikke så kult for SB å vente over 10 sekunder (som er default), men...
=> Øker timeout på kall til ferdigstill-journalfoer-og-distribuer i brev-api

apps/etterlatte-behandling/src/main/kotlin/behandling/etteroppgjoer/brev/EtteroppgjoerForbehandlingBrevService.kt, apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/vedtaksbrev/StrukturertBrevService.kt
Når vi henter brev bruker vi språk som er satt i brev-api `innhold.spraak`.
Men oppdaget en liten feil hvor språk for vedlegg alltid er på NB selv om språk for brev er satt til EN, `grunnlag.mapSpraak()` samsvarer ikke med språk valgt for brev, endrer derfor til at vi forholder oss til språk i brev hvis det er satt
=> Bruke språk fra brev i brevRequest hvis det er satt 
